---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/complete-preparation-for-upgrade.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configurar y gestionar el cifrado de almacenamiento, gestionar las claves de autenticación y desactivar las relaciones de SnapMirror cuando se utiliza ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Completa la preparación para la actualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Conoce las licencias de ONTAP y cómo gestionar Storage Encryption usando Onboard Key Manager (OKM). Opcionalmente, pon en pausa las relaciones de SnapMirror.



== Conoce las licencias de ONTAP

Cada nodo del clúster debe tener su propio archivo de licencia de NetApp (NLF).

Si no dispone de un NLF, las funciones con licencia actualmente en el clúster están disponibles para la nueva controladora. Sin embargo, el uso de funciones sin licencia en la controladora puede provocar que no cumpla el contrato de licencia, por lo que debe instalar NLF en la nueva controladora una vez completada la actualización.

Consulta link:other-references.html["Referencias"] para enlazar al _NetApp Support Site_ donde puedes obtener tu NLF. Los NLF están disponibles en la sección _My Support_ en _Software licenses_. Si el sitio no tiene los NLF que necesitas, contacta a tu representante de ventas de NetApp.

Para obtener información detallada sobre las licencias de ONTAP, consulta link:other-references.html["Referencias"] para enlazar con la _Referencia de administración del sistema_.



== Gestione el cifrado del almacenamiento con el gestor de claves incorporado

Usa el Onboard Key Manager (OKM) para gestionar las claves de cifrado. Si tienes el OKM configurado, debes registrar la frase de contraseña y el material de copia de seguridad antes de comenzar la actualización.

.Pasos
. Registre la clave de acceso para todo el clúster.
+
Esta es la frase de acceso que se introdujo cuando se configuró o actualizó OKM con la CLI o la API REST.

. Verifica la frase de contraseña y la operación del key-manager:
+
`security key-manager onboard sync`

+
Cuando te lo pidan, introduce la frase de contraseña OKM para todo el clúster que registraste en el paso anterior.

. Verifica que cc-mode está activado revisando la salida del siguiente comando:
+
`security key-manager config show`

. Haz una copia de seguridad de la información del key-manager:
+
`security key-manager onboard show-backup`





== Opcionalmente, silencia las relaciones SnapMirror

Antes de continuar con el procedimiento, debe confirmar que todas las relaciones de SnapMirror se ponen en modo inactivo. Cuando una relación de SnapMirror se pone en modo inactivo, sigue en modo inactivo tras reinicios y recuperaciones tras fallos.

.Pasos
. Compruebe el estado de la relación de SnapMirror en el clúster de destino:
+
`snapmirror show`

+
[NOTE]
====
Si el estado es "transferencia", debe anular dichas transferencias:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
La anulación falla si la relación de SnapMirror no se encuentra en el estado "transfiriendo".

. Desactive todas las relaciones entre el clúster:
+
`snapmirror quiesce -destination-vserver *`



.El futuro
Después de preparar la actualización, link:relocate-non-root-aggr-and-nas-data-lifs-node1-node2.html["reubica los agregados que no son raíz y las LIF de datos NAS que pertenecen al nodo1 en el nodo2"].
