---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-asa150-affa150-fas2820-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Instale los módulos del sistema de reemplazo en node2 durante una actualización ARL de los modelos de controladora en el mismo chasis. 
---
= Instale el módulo del controlador ASA A150, AFF A150 o FAS2820 en node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Instale el módulo de controlador ASA A150, AFF A150 o FAS2820 que recibió para la actualización en node2. El nodo 2 es la controladora B, situada en el lado derecho del chasis, cuando se tienen en cuenta las controladoras de la parte posterior del sistema.

.Antes de empezar
* Si usted no está ya conectado a tierra, correctamente tierra usted mismo.
* Desconecte todos los cables, incluidos los cables de consola, gestión, almacenamiento SAS y red de datos, de la controladora que se está quitando.


.Pasos
. Alinee el extremo del módulo del controlador con el compartimiento B del chasis y, a continuación, empuje suavemente el módulo del controlador hasta la mitad dentro del sistema.
+

TIP: La bahía B está ubicada en el lado derecho del chasis.

+

WARNING: No inserte por completo el módulo de la controladora en el chasis hasta que se le indique hacerlo más adelante en el procedimiento.

. Conecte los puertos de consola y de gestión al módulo de controladora 2.
+

NOTE: Debido a que el chasis ya está encendido, el nodo 2 comienza a arrancar tan pronto como esté completamente encajado.  Para evitar que el nodo 2 arranque, conecte los cables de consola y administración antes de insertar completamente el módulo controlador.

. Empuje firmemente el módulo de la controladora en el chasis hasta que se ajuste al plano medio y esté totalmente asentado.
+
El pestillo de bloqueo se eleva cuando el módulo del controlador está completamente asentado.

+

NOTE: Para evitar dañar los conectores, no ejerza demasiada fuerza al deslizar el módulo del controlador en el chasis.

. Conecte la consola serial tan pronto como el módulo esté instalado y prepárese para interrumpir el AUTOBOOT del nodo2.
. Después de interrumpir EL ARRANQUE AUTOMÁTICO, el nodo 2 se detiene en el símbolo del sistema del CARGADOR. Si no interrumpe el AUTOARRANQUE a tiempo y node2 comienza el arranque, espere a que se le indique el prompt y pulse Ctrl-C para ir al menú de arranque. Cuando el nodo se detenga en el menú de arranque, utilice la opción `8` para reiniciar el nodo e interrumpir EL AUTOARRANQUE durante el reinicio.

