---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/manage-storage-encryption-using-okm.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configurar y gestionar el cifrado de almacenamiento, gestionar las claves de autenticación y desactivar las relaciones de SnapMirror cuando se utiliza ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Gestione el cifrado del almacenamiento con el gestor de claves incorporado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede utilizar Onboard Key Manager (OKM) para gestionar las claves de cifrado. Si tiene configurado OKM, debe registrar la frase de acceso y el material de copia de seguridad antes de iniciar la actualización.

.Pasos
. Registre la clave de acceso para todo el clúster.
+
Esta es la frase de acceso que se introdujo cuando se configuró o actualizó OKM con la CLI o la API REST.

. Verifica la frase de contraseña y la operación del key-manager:
+
`security key-manager onboard sync`

+
Cuando te lo pidan, introduce la frase de contraseña OKM para todo el clúster que registraste en el paso anterior.

. Verifica que cc-mode está activado revisando la salida del siguiente comando:
+
`security key-manager config show`

. Haz una copia de seguridad de la información del key-manager:
+
`security key-manager onboard show-backup`





== Desactivar las relaciones de SnapMirror (opcional)

Antes de continuar con el procedimiento, debe confirmar que todas las relaciones de SnapMirror se ponen en modo inactivo. Cuando una relación de SnapMirror se pone en modo inactivo, sigue en modo inactivo tras reinicios y recuperaciones tras fallos.

.Pasos
. Compruebe el estado de la relación de SnapMirror en el clúster de destino:
+
`snapmirror show`

+
[NOTE]
====
Si el estado es "transferencia", debe anular dichas transferencias:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
La anulación falla si la relación de SnapMirror no se encuentra en el estado "transfiriendo".

. Desactive todas las relaciones entre el clúster:
+
`snapmirror quiesce -destination-vserver *`


