---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Compruebe que los LIF de datos NAS de node2 en node1 se reubican de node1 a node2 cuando utiliza ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Vuelva a colocar los agregados que no son raíz y las LIF de datos NAS en el nodo 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Después de verificar la configuración de red en el nodo 2, debe reubicar los LIF de datos NAS propiedad del nodo 2 del nodo 1 al nodo 2 y confirmar que los LIF de SAN existen en el nodo 2.

.Acerca de esta tarea
Los LIF remotos manejan el tráfico a los LUN SAN durante el procedimiento de actualización. No es necesario mover los LIF de SAN por el estado del clúster o del servicio durante la actualización. Los LIF de SAN no se mueven a menos que sea necesario asignarlos a nuevos puertos.

Verifica que los LIF estén en buen estado y ubicados en los puertos correctos después de poner en línea el nodo 2.

.Pasos
. Reanude la operación de reubicación:
+
[source, cli]
----
system controller replace resume
----
+
El sistema ejecuta las siguientes tareas:

+
--
** Comprobación de quórum del clúster
** Comprobación del ID del sistema
** Comprobación de la versión de la imagen
** Comprobación de la plataforma de destino
** Comprobación de accesibilidad de red


--
+
El sistema pausa la operación en esta etapa de la verificación de accesibilidad de la red.

. Reanude la operación de reubicación:
+
[source, cli]
----
system controller replace resume
----
+
El sistema realiza las siguientes comprobaciones:

+
--
** Comprobación del estado del clúster
** Comprobación del estado de LIF de clúster


--
+
Después de realizar estas comprobaciones, el sistema reubica los agregados no raíz y las LIF de datos NAS en node2, que ahora se está ejecutando en la controladora de reemplazo.

+
La operación de reemplazo de la controladora se coloca en pausa una vez que se completa la reubicación de recursos.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
[source, cli]
----
system controller replace show-details
----
+
Si el procedimiento de reemplazo de la controladora está en pausa, compruebe y corrija el error, si corresponde, y luego emita `resume` para continuar la operación.

. Si es necesario, restaure y revierta los LIF desplazados o migre y modifique manualmente los LIF del nodo 2 que no pudieron reubicarse automáticamente en el nodo 2.
+
[role="tabbed-block"]
====
.Restaurar y revertir los LIF desplazados
--
.. Enumere todos los LIF desplazados:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Si hay alguna LIF desplazada, restaurar el nodo inicial a 2:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrar y modificar manualmente los LIF
--
.. Migre los LIF que no pudieron reubicarse automáticamente al nodo 2:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. Modifique el nodo de inicio y el puerto de inicio para los LIF migrados:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. Reanude la operación para solicitar que el sistema realice las comprobaciones previas necesarias:
+
[source, cli]
----
system controller replace resume
----
+
El sistema realiza las siguientes comprobaciones posteriores:

+
** Comprobación de quórum del clúster
** Comprobación del estado del clúster
** Comprobación de reconstrucción de los agregados
** Comprobación del estado del agregado
** Comprobación del estado del disco
** Comprobación del estado de LIF de clúster
** Comprobación del volumen



