---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-nas-lifs-node1-from-node2-to-upgraded-node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Compruebe que los LIF de datos de NAS node1 en node2 se reubican de node2 a node1 cuando utiliza ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Mueva node1 agregados no raíz y LIF de datos NAS de node2 al node1 actualizado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Después de verificar la configuración de red en node1 y antes de reubicar agregados de node2 a node1, debe verificar que los LIF de datos NAS que pertenecen a node1 y que están actualmente en node2 se reubiquen de node2 a node1. También debe comprobar que las LIF SAN existen en el nodo 1.

.Acerca de esta tarea
Las LIF remotas gestionan el tráfico a LUN DE SAN durante el procedimiento de actualización. No es necesario mover LIF DE SAN durante la actualización para el estado del clúster o del servicio. Los LIF SAN no se mueven a menos que tengan que asignarse a nuevos puertos. Después de conectar el nodo 1, debe comprobar que el estado de las LIF es bueno y que están ubicadas en los puertos correspondientes.

.Pasos
. Reanude la operación de reubicación:
+
`system controller replace resume`

+
El sistema ejecuta las siguientes tareas:

+
--
** Comprobación de quórum del clúster
** Comprobación del ID del sistema
** Comprobación de la versión de la imagen
** Comprobación de la plataforma de destino
** Comprobación de accesibilidad de red


--
+
La operación se detiene en esta fase de la comprobación de accesibilidad de red.

. Realice una comprobación de accesibilidad de la red:
+
`network port reachability show -node node1`

+
Confirme que todos los puertos conectados, incluidos el grupo de interfaces y los puertos de VLAN, muestran su estado como `OK`.

. Para las siguientes actualizaciones, debe reasignar los LIF de SAN FCP.
+
[cols="35,65"]
|===
| Sistema existente | Sistema de sustitución 


| AFF A250 | AFF A30 y AFF A50 


| AFF C250 | AFF C30 y AFF C60 


| AFF A800 | AFF A70 y AFF A90 


| AFF C800 | AFF C80 
|===
+
Para todas las demás actualizaciones del sistema, vaya a <<resume_relocation_step4,Paso 4>>.

+
.. Reasignar los LIF SAN FCP utilizados para el acceso a los datos FCP o FC-NVMe a los puertos iniciales correctos:
+
`network interface show -vserver <vserver_hosting_fcp_lifs>`

.. Para las LIF con el nodo actual como node1 actualizado y el puerto actual informa de «status oper» como «-» (debido a que el puerto existía en el nodo AFF A800 pero no existe en el nodo AFF A90), modifique el puerto actual antes de que pueda conectarse.
+
Compruebe que se ha establecido la conectividad física con el puerto de destino FC al que se debe mover la LIF de FC:

+
--
... Establezca el estado de LIF en «inactivo»:
+
`network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down`

... Modifique el puerto raíz de la LIF:
+
`network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>`

... Establezca el estado de LIF en «activo»:
+
`network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up`



--
+
Repita los subpasos a y b para cada LIF SAN FC que esté alojado en node1.



. [[resume_relocation_step4]]Reanudar la operación de reubicación:
+
`system controller replace resume`

+
El sistema realiza las siguientes comprobaciones:

+
--
** Comprobación del estado del clúster
** Comprobación del estado de LIF de clúster


--
+
Tras realizar estas comprobaciones, el sistema reubica los agregados no raíz y las LIF de datos NAS que pertenecen al nodo 1 nuevo.

+
La operación de reemplazo de la controladora se coloca en pausa una vez que se completa la reubicación de recursos.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
`system controller replace show-details`

+
Si el procedimiento de reemplazo de la controladora está en pausa, compruebe y corrija el error, si corresponde, y luego emita `resume` para continuar la operación.

. Si es necesario, restaure y devuelva los LIF desplazados. Enumerar las LIF desplazadas:
+
`cluster controller-replacement network displaced-interface show`

+
Si hay alguna LIF desplazada, restaurar el nodo raíz nuevamente al nodo 1:

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Reanude la operación para solicitar que el sistema realice las comprobaciones previas necesarias:
+
`system controller replace resume`

+
El sistema realiza las siguientes comprobaciones posteriores:

+
** Comprobación de quórum del clúster
** Comprobación del estado del clúster
** Comprobación de reconstrucción de los agregados
** Comprobación del estado del agregado
** Comprobación del estado del disco
** Comprobación del estado de LIF de clúster
** Comprobación del volumen



