---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/prepare-nodes-for-upgrade.html 
keywords: preparing, prepare, nodes, upgrade, stage 1, prechecks, old, system, chassis, disk, disks 
summary: Prepare los nodos y ejecute una serie de comprobaciones previas cuando utilice ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Prepare los nodos para la actualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El proceso de reemplazo de la controladora comienza con una serie de comprobaciones previas. También se recopila información sobre los nodos originales para usar más adelante del procedimiento y, si es necesario, determinar el tipo de unidades de cifrado automático que se están usando.



[[step-1-prepare-the-nodes]]
== Paso 1: preparar los nodos

Inicia el proceso de sustitución del controlador y ejecuta las comprobaciones previas. Si es necesario, determina el tipo de unidades de autocifrado que se están utilizando.

.Pasos
. Enumere la versión del firmware del Service Processor (SP) o de la controladora de gestión de la placa base (BMC) que se ejecuta en la controladora anterior:
+
[source, cli]
----
service-processor show
----
+
Compruebe que tiene una versión de firmware de SP o BMC compatible:

+
[cols="30,35,35"]
|===
| La controladora anterior | SP o BMC | Versión de firmware mínima 


| AFF A800 | BMC | 10,9 


| AFF A220 | BMC | 11.9P1 


| AFF A200 | SP | 5.11P1 


| C190 de AFF | BMC | 11.9P1 


| FAS2620 | SP | 5.11P1 


| FAS2720 | BMC | 11.9P1 
|===
. Para iniciar el proceso de sustitución de la controladora, introduzca el siguiente comando en el modo de privilegio avanzado de la línea de comandos de ONTAP:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
system controller replace start -nodes <node_names>
----
+
Ves una salida similar a la del siguiente ejemplo. La salida muestra la versión de ONTAP que se está ejecutando en tu clúster:

+
....
Warning:
1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedures.

Do you want to continue? {y|n}: y
....
. Selecciona `y`. Ves el siguiente resultado:
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
Durante la fase de comprobaciones previas, el sistema ejecuta la siguiente lista de comprobaciones en segundo plano.

+
[cols="35,65"]
|===
| Comprobación previa | Descripción 


| Comprobación del estado del clúster | Comprueba todos los nodos del clúster para confirmar que están en buen estado. 


| Comprobación del estado de reubicación de agregados | Comprueba si ya hay una reubicación de agregados en curso. Si hay otra reubicación de agregado en curso, la comprobación falla. 


| Comprobación del nombre del modelo | Comprueba si los modelos de controlador son compatibles con este procedimiento. Si los modelos no son compatibles, la tarea falla. 


| Comprobación de quórum de clúster | Comprueba que los nodos que se van a sustituir tengan quórum. Si los nodos no están en quórum, la tarea falla. 


| Comprobación de la versión de la imagen | Comprueba que los nodos que se están reemplazando ejecutan la misma versión de ONTAP. Si las versiones de imagen de ONTAP son diferentes, la tarea falla. Los nodos nuevos deben tener la misma versión de ONTAP 9.x instalada que la que está instalada en los nodos originales. Si los nuevos nodos tienen una versión diferente de ONTAP instalada, necesitas hacer netboot a los nuevos controladores después de instalarlos. Para instrucciones sobre cómo actualizar ONTAP, consulta link:other-references.html["Referencias"] para enlazar a _Upgrade ONTAP_. 


| Comprobación de estado de HA | Comprueba si los dos nodos que se van a reemplazar se encuentran en una configuración de parejas de alta disponibilidad (ha). Si no está habilitada la conmutación por error del almacenamiento para las controladoras, la tarea falla. 


| Comprobación del estado del agregado | Si los nodos que se van a sustituir tienen agregados propios para los que no son el propietario principal, la tarea fallará. Los nodos no deben tener ningún agregado que no sea local. 


| Comprobación del estado del disco | Si alguno de los nodos que se están sustituyendo tiene discos que faltan o han fallado, la tarea falla. Si falta algún disco, consulta link:other-references.html["Referencias"] para enlazar a _Disk and aggregate management with the CLI_, _Logical storage management with the CLI_ y _HA pair management_ para configurar el almacenamiento del par de HA. 


| Comprobación del estado de LIF de datos | Comprueba si alguno de los nodos que se van a sustituir tiene LIF de datos no locales. Los nodos no deben contener ninguna LIF de datos para la cual no sean el propietario principal. Si uno de los nodos contiene LIF de datos no locales, la tarea falla. 


| Estado de LIF del clúster | Comprueba si los LIF del clúster están activos para ambos nodos. Si las LIF del clúster están inadas, la tarea falla. 


| AutoSupport Comprobación de estado | Si no se configuran las notificaciones de AutoSupport, la tarea falla. Debe habilitar AutoSupport antes de iniciar el procedimiento de reemplazo de la controladora. 


| Comprobación del uso de CPU | Comprueba si el uso de CPU es superior al 50 % en el caso de cualquiera de los nodos que se van a sustituir. Si el uso de CPU es superior al 50 % durante un período de tiempo considerable, la tarea falla. 


| Comprobación de reconstrucción de agregados | Comprueba si la reconstrucción se está produciendo en algún agregado de datos. Si la reconstrucción del agregado está en curso, la tarea falla. 


| Comprobación de trabajo de afinidad de nodo | Comprueba si se están ejecutando trabajos de afinidad de nodos. Si se están ejecutando trabajos de afinidad de nodo, la comprobación falla. 
|===
. Una vez iniciada la operación de sustitución de las controladoras y que se completen las comprobaciones previas, la operación se coloca en pausa, lo que permite recopilar información de salida que se pueda necesitar más adelante en el proceso de actualización de las controladoras.
. Ejecute el siguiente conjunto de comandos según lo indicado por el procedimiento de reemplazo de la controladora en la consola del sistema.
+
Ejecute los comandos desde el puerto serie conectado a cada nodo, ejecute y guarde la salida de los comandos individualmente:

+
[source, cli]
----
vserver services name-service dns show
----
+
[source, cli]
----
network interface show -curr-node <local> -role cluster,intercluster,node-mgmt,cluster-mgmt,data
----
+
[source, cli]
----
network port show -node <local> -type physical
----
+
[source, cli]
----
service-processor show -node <local> -instance
----
+
[source, cli]
----
network fcp adapter show -node <local>
----
+
[source, cli]
----
network port ifgrp show -node <local>
----
+
[source, cli]
----
system node show -instance -node <local>
----
+
[source, cli]
----
run -node <local> sysconfig
----
+
[source, cli]
----
run -node local sysconfig -ac
----
+
[source, cli]
----
run -node local aggr status -r
----
+
[source, cli]
----
vol show -fields type
----
+
[source, cli]
----
run local aggr options <data_aggregate_name>
----
+
[source, cli]
----
vol show -fields type , space-guarantee
----
+
[source, cli]
----
storage aggregate show -node <local>
----
+
[source, cli]
----
volume show -node <local>
----
+
[source, cli]
----
storage array config show -switch <switch_name>
----
+
[source, cli]
----
system license show -owner <local>
----
+
[source, cli]
----
storage encryption disk show
----
+
[source, cli]
----
security key-manager onboard show-backup
----
+
[source, cli]
----
security key-manager external show
----
+
[source, cli]
----
security key-manager external show-status
----
+
[source, cli]
----
network port reachability show -detail -node <local>
----
+

NOTE: Si el cifrado de volúmenes de NetApp (NVE) o el cifrado de agregado de NetApp (NAE) con el gestor de claves integrado están en uso, mantenga la frase de acceso del gestor de claves preparada para completar el administrador de claves de nuevo a sincronizar más adelante en el procedimiento.

. Si su sistema utiliza unidades de autocifrado, consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Cómo saber si una unidad tiene la certificación FIPS"^] Para determinar el tipo de unidades de autocifrado que se están utilizando en la pareja de alta disponibilidad que se está actualizando. El software ONTAP admite dos tipos de unidades de autocifrado:
+
--
** Unidades SAS o NVMe con cifrado en almacenamiento de NetApp (NSE) certificado FIPS
** Unidades NVMe (SED) con autocifrado no FIPS


[NOTE]
====
No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad.

Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["Obtenga más información sobre las unidades de autocifrado compatibles"^].

--




[[step-2-correct-aggregate-ownership-if-an-arl-precheck-fails]]
== Paso 2: Corregir la propiedad del agregado si falla una comprobación previa de ARL

Si falla la comprobación del estado del agregado, debe devolver los agregados propiedad del nodo asociado al nodo propietario principal e iniciar de nuevo el proceso de comprobaciones previas.

.Pasos
. Devolver los agregados que actualmente pertenecen al nodo asociado al nodo propietario principal:
+
[source, cli]
----
storage aggregate relocation start -node <source_node> -destination <destination_node> -aggregate-list *
----
. Compruebe que ni el nodo 1 ni el nodo 2 siguen teniendo agregados cuyos propietarios son actualmente (pero no el propietario del hogar):
+
[source, cli]
----
storage aggregate show -nodes <node_name> -is-home false -fields owner-name, home-name, state
----
+
En el ejemplo siguiente se muestra el resultado del comando cuando un nodo es al mismo tiempo el propietario actual y el propietario principal de los agregados:

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----
. Reinicia el proceso de sustitución del controlador:
+
[source, cli]
----
system controller replace start -nodes <node_names>
----


.El futuro
Una vez preparados los nodos, link:complete-preparation-for-upgrade.html["completar la preparación para la actualización"].
