---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/restore-key-manager-config-node2.html 
keywords: restore key-manager, configuration, node1, nve, arl, volume, encryption 
summary: Si es necesario, restaure la configuración del gestor de claves en node2 si utiliza ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Restaure la configuración de gestor de claves en el nodo 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si utiliza el cifrado de agregados de NetApp (NAE) o el cifrado de volúmenes de NetApp (NVE) para cifrar volúmenes en el sistema que desea actualizar, la configuración de cifrado debe sincronizarse con los nodos nuevos. Si no vuelve a sincronizar el gestor de claves, cuando se reinstalan los agregados del nodo 2 actualizados al nodo 2 actualizado mediante ARL, pueden producirse fallos, ya que el nodo 2 no tiene las claves de cifrado requeridas para poner en línea volúmenes y agregados cifrados.

.Acerca de esta tarea
Para sincronizar la configuración de cifrado con los nuevos nodos, realice los siguientes pasos:

.Pasos
. Ejecute el siguiente comando en el nodo 2:
+
`security key-manager onboard sync`

. Compruebe que la clave SVM-KEK se restaure en "true" en el nodo 2 antes de reubicar los agregados de datos:
+
[listing]
----
::> security key-manager key query -node node2 -fields restored -key-type SVM-KEK
----
+
.Ejemplo
[listing]
----
::> security key-manager key query -node node2 -fields restored -key-type SVM-KEK

node     vserver   key-server   key-id                                  restored
-------- --------- -----------  --------------------------------------- --------
node2    svm1      ""           00000000000000000200000000000a008a81976 true
                                2190178f9350e071fbb90f00000000000000000
----

