---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/retire-node2.html 
keywords: retire, node2, retiring, node 
summary: Apague node2 y quítelo del rack o chasis cuando utilice ARL para actualizar los modelos de controladora en el mismo chasis. 
---
= Retire el nodo 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para retirar el nodo 2, apáguelo correctamente y luego retírelo del rack o chasis.

.Pasos
. Reanude la operación:
+
`system controller replace resume`

+
El nodo se detiene automáticamente.



.El futuro
Después de retirar el nodo2, elige uno de los siguientes procedimientos de sustitución del controlador según tu configuración de actualización:

* link:replace-node2-affa250-affc250.html["Sustituye el módulo controlador AFF A250 o AFF C250 del nodo2"]
* link:replace-node2-affa800-affc800.html["Sustituye el módulo controlador AFF A800 o AFF C800 del nodo2"]
* link:replace-node2-affa220-affa200-affc190-fas2620-fas2720.html["Sustituye el módulo de controlador del nodo2 AFF A220, AFF A200, AFF C190, FAS2620 o FAS2720"]
* link:replace-node2-aff700-fas900.html["Sustituye el controlador AFF A700 o FAS9000 de node2 y los módulos NVRAM"]

