---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación sobre actualización del hardware de ONTAP
    url: "/index.html"
  - title: Seleccione el procedimiento de actualización del hardware de la controladora
    url: "/choose_controller_upgrade_procedure.html"
  - section: upgrade-arl
  - section: upgrade
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
