---
settings:
  name: Upgrade controllers
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentación sobre las actualizaciones del sistema AFF y FAS
    url: "/index.html"
  - title: Seleccione el procedimiento de actualización del hardware de la controladora
    url: "/choose_controller_upgrade_procedure.html"
  - section: upgrade-arl
  - section: upgrade
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Notas de la versión de ONTAP
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - title: Seleccione el procedimiento de actualización del hardware de la controladora
      url: "/choose_controller_upgrade_procedure.html"
  - title: Actualice mediante la reubicación de agregados en sistemas que ejecutan
      ONTAP 9,8 y versiones posteriores
    links:
    - title: Utilice los comandos para sustituir la controladora del sistema para
        actualizar los modelos de controladora en el mismo chasis
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/
    - title: Utilizar comandos para «sustituir controlador del sistema» (en la mayoría
        de los sistemas)
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/
    - title: Utilizar comandos manuales
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/
  - title: Actualice mediante la reubicación de agregados en sistemas que ejecutan
      ONTAP 9,7 y versiones anteriores
    links:
    - title: Utilizar comandos de “sustitución del controlador del sistema” (en la
        mayoría de los sistemas)
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/
    - title: Utilizar comandos manuales
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/
  - title: Actualice moviendo almacenamiento o volúmenes
    links:
    - title: Actualice el hardware de la controladora
      url: "/upgrade/upgrade-decide-to-use-this-guide.html"
    - title: Actualice AFF A250 a AFF A400 mediante la conversión a una bandeja de
        unidades
      url: "/upgrade/upgrade_aff_a250_to_aff_a400_ndu_upgrade_workflow.html"
  - title: Actualizar los sistemas en una configuración MetroCluster
    links:
    - title: Seleccione el procedimiento de actualización de la configuración de MetroCluster
      url: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html
  - title: Más recursos
    links:
    - title: Documentación de los sistemas ONTAP
      url: https://docs.netapp.com/us-en/ontap-systems/index.html
    - title: Documentación de los switches ONTAP
      url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
    - title: Documentación sobre el software ONTAP
      url: https://docs.netapp.com/us-en/ontap/index.html
    - title: Hardware Universe de NetApp
      url: https://hwu.netapp.com/
    - title: Active IQ Config Advisor de NetApp
      url: https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor
    - title: Matriz de interoperabilidad de NetApp
      url: https://mysupport.netapp.com/matrix/#welcome
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/ONTAP-and-FAS/ct-p/fas-ontap-oncommand-and-related-plug-ins
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
