---
permalink: upgrade/convert-node2-to-drive-shelf.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Convierte node2 en un estante de unidades y conéctalo a node4 antes de reasignar las unidades de node2 a node4. 
---
= Convierta node2 en una bandeja de unidades y conéctela a node4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Convierte el nodo2 en un estante de unidades y conéctalo al nodo4 antes de reasignar las unidades del nodo2 al nodo4. El nodo1 y el nodo2 son los controladores dentro del estante de unidades.

.Pasos
. Desconecte todos los cables de red de node2.
. Quita el node2 del chasis AFF A150, AFF A220 o FAS2820.
. Inserte el módulo IOM12 o IOM12B en la bahía del nodo 2.
. Conecte el puerto SCSI conectado en serie (SAS) del nodo 4 a un puerto disponible en el módulo IOM12 o IOM12B.  Ver ellink:https://hwu.netapp.com["Hardware Universe"^] para verificar los puertos SAS de su sistema.
. Cree conexiones de clúster temporales conectando los puertos e0a y e0b del nodo 1 a cualquiera de los dos puertos 25 GbE del nodo 4.
+

NOTE: Si el nodo 4 solo admite conexiones de clúster de 10 GbE, debe tener cableado de 10 GbE para crear conexiones de clúster temporales.



.El futuro
link:reassign-node2-drives.html["Reasignar unidades de node2 a node4"]
