---
permalink: upgrade/convert-fas2820-node2-drive-shelf.html 
sidebar: sidebar 
keywords: fas8280, ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: 'Convierta el nodo 2 (FAS2820) en un estante de unidad DS212C y luego conéctelo al nodo 4.' 
---
= Convierte el nodo 2 de FAS2820 en un estante de unidades y conéctalo al nodo 4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Convierta el nodo 2 de FAS2820 en un estante de unidad DS212C.  Conéctese al nodo 4 antes de reasignar unidades del nodo 2 al nodo 4.  El nodo1 y el nodo2 son los controladores dentro del estante DS212C.

.Pasos
. Desconecte todos los cables de red de node2.
. Retire el nodo 2 del chasis FAS2820 .
. Inserte el módulo IOM12 o IOM12B en la bahía del nodo 2.
. Conecte el puerto SCSI conectado en serie (SAS) del nodo 4 a un puerto disponible en el módulo IOM12 o IOM12B.  Ver ellink:https://hwu.netapp.com["Hardware Universe"^] para verificar los puertos SAS de su sistema.
. Cree conexiones de clúster temporales conectando los puertos e0a y e0b del nodo 1 a cualquiera de los dos puertos 25 GbE del nodo 4.
+

NOTE: Si el nodo 4 solo admite conexiones de clúster de 10 GbE, debe tener cableado de 10 GbE para crear conexiones de clúster temporales.



.El futuro
link:reassign-fas2820-node2-drives.html["Reasignar unidades de node2 a node4"]
