---
permalink: upgrade/migrate-node2-lifs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs 
summary: 'Migra las interfaces lógicas (LIF) y los agregados de datos de node2 a node1 antes de convertir node2 en una estantería de unidades.' 
---
= Migre LIF y agregados de datos de node2 a node1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Migra las interfaces lógicas (LIFs) y los agregados de datos en AFF A150, AFF A220 o FAS2820 nodo2 a nodo1 antes de convertir nodo2 en una drive shelf.

.Antes de empezar
Compruebe que cumple los siguientes requisitos:

* Los controladores original y de sustitución tienen la misma versión de ONTAP y el mismo parche, cuando sea posible. Consulta la  https://hwu.netapp.com["Hardware Universe de NetApp"^] para ver las versiones de ONTAP compatibles.


[NOTE]
====
* Debe iniciar en red e instalar la versión de ONTAP en el nodo 3 y el nodo 4 para que coincida con la versión de ONTAP en los sistemas FAS2820 .  El nodo 3 y el nodo 4 son los controladores de reemplazo.
* Tanto la imagen de arranque principal como la de respaldo de los controladores node3 y node4 deben tener la misma versión de ONTAP .
* Debe borrar cualquier configuración residual del clúster en el nodo 3 y el nodo 4 realizando una `wipeconfig` desde el menú de arranque.


====
* Ambos controladores de reemplazo están en espera en el indicador LOADER.
* Todo el cableado necesario está disponible.


.Pasos
Realiza estos pasos en node1.

. Acceda al nivel de privilegio avanzado:
+
[source, cli]
----
set -privilege advanced
----
. Desactivar la conmutación automática al nodo de respaldo del almacenamiento:
+
[source, cli]
----
storage failover modify -node node1 -auto-giveback false
----
. Deshabilite la reversión automática de las LIF en ambos nodos del par de alta disponibilidad:
+
[source, cli]
----
network interface modify -lif * -auto-revert false
----
. Mostrar el estado de todas las LIF de red de datos:
+
[source, cli]
----
network interface show -role data
----
. Muestre el estado de las LIF de administración del clúster:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Migre todas las LIF de datos desde las máquinas virtuales de almacenamiento alojadas en node2:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node1> -destination-port <port_name>
----
+

NOTE: Este comando solo migra LIF que no sean SAN. No puede utilizarlo para migrar LIF iSCSI y FCP.

. Mostrar el estado de todas las LIF de datos en el clúster:
+
[source, cli]
----
network interface show -role data
----
. Si algún LIF está inactivo, establezca su estado administrativo en `up` ingresando el siguiente comando una vez para cada LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. Muestre el estado de todos los agregados de datos del clúster:
+
[source, cli]
----
storage aggregate show
----
. Mostrar elegibilidad de failover:
+
[source, cli]
----
storage failover show
----
. Migre los agregados de datos de node2 a node1:
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node2> -destination <node1>
----
. Muestre el estado de todos los agregados de datos del clúster:
+
[source, cli]
----
storage aggregate show
----
. Muestre el estado de todos los volúmenes de datos en el clúster:
+
[source, cli]
----
volume show
----
. Muestre la `ha` estado y propiedad de épsilon:
+
[source, cli]
----
cluster show
----
. Deshabilitar cluster ha:
+
[source, cli]
----
cluster ha modify -configured false
----
. Muestre la `ha` estado y propiedad de épsilon:
+
[source, cli]
----
cluster show
----
. Detener nodo 2:
+
[source, cli]
----
halt -node <node2> -inhibit-takeover true -ignore-quorum-warnings true
----


.El futuro
link:convert-node2-to-drive-shelf.html["Convierta node2 en una bandeja de unidades y conéctela a node4"]
