---
permalink: upgrade/migrate-fas2820-node4-lIfs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: 'Para completar la actualización, conecte FAS2820node3 al node4 y luego migre las interfaces lógicas de datos (LIF) y los agregados de datos del node4 al node3.' 
---
= Migrar LIF y agregados de datos del nodo 4 de FAS2820 al nodo 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para completar la actualización, conecte el nodo 3 de FAS2820 al nodo 4 y luego migre las interfaces lógicas de datos (LIF) y los agregados de datos del nodo 4 al nodo 3.

.Acerca de esta tarea
Realice los siguientes pasos en el nodo3.

.Pasos
. En el símbolo del sistema DEL CARGADOR DE node3, arranque el nodo en el menú de arranque:
+
[source, cli]
----
boot_ontap menu
----
. Seleccione opción `6 Update flash from backup config` restaurar el sistema de archivos /var a node3.
+
Esto sustituye la configuración basada en all-flash por el último backup en discos.

. Introduzca `y` para continuar.
. Permita que el nodo arranque como normal.
+
[NOTE]
====
El nodo se reinicia automáticamente para cargar la nueva copia del sistema de archivos /var.

El nodo informa de una advertencia de que hay una discrepancia de ID del sistema. Introduzca `y` Para anular el ID del sistema.

====
. Verifique que los puertos del clúster y de alta disponibilidad estén conectados entre el nodo 3 y el nodo 4.
. Mostrar el clúster y los puertos HA en el nodo 3 y el nodo 4:
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
. Modifique el dominio de retransmisión de clúster para incluir los puertos de clúster deseados:
+
[source, cli]
----
network port broadcast-domain remove-ports -broadcast-domain <broadcast_domain_name> -ports <port_names>
----
+
[source, cli]
----
network port broadcast-domain add-ports -broadcast-domain Cluster -ports <port_names>
----
+

NOTE: A partir de ONTAP 9,8, se podrían designar nuevos espacios IP y uno o más dominios de retransmisión para los puertos físicos existentes destinados a la conectividad del clúster.

. Modifique el espacio IP del clúster para incluir los puertos del clúster deseados y establezca la unidad de transmisión máxima en 9000 si aún no está configurada:
+
[source, cli]
----
network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster
----
. Muestre todas las LIF de red del clúster:
+
[source, cli]
----
network interface show -role cluster
----
. Migre todos los LIF de la red del clúster en ambos nodos a sus puertos de origen planificados:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node_name> -destination-port <port_name>
----
. Muestre todas las LIF de red del clúster:
+
[source, cli]
----
network interface show -role cluster
----
. Configure los puertos domésticos para los LIF de la red del clúster:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <port_name>
----
. Migrar todos los LIF de datos destinados al nodo 3 de vuelta al nodo 3:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node3> -destination-port <port_name>
----
. Mostrar todas las LIF de red de datos:
+
[source, cli]
----
network interface show -role data
----
. Configure el nodo local y el puerto local para todos los LIF de datos.  Si algún LIF está inactivo, establezca su estado administrativo en `up` ingresando el siguiente comando una vez para cada LIF:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -status-admin up
----
. Migre la LIF de administración del clúster:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node3> -destination-port <port_name>
----
. Muestre el estado de la LIF de gestión del clúster:
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. Muestre el estado de todos los agregados de datos del clúster:
+
[source, cli]
----
storage aggregate show
----
. Habilitar la alta disponibilidad del clúster en el clúster de dos nodos:
+
[source, cli]
----
cluster ha modify -configured true
----
. Habilitar y verificar la conmutación por error de almacenamiento para el nodo 3 y el nodo 4:
+
[source, cli]
----
storage failover modify -node <node3> -enabled true
----
+
[source, cli]
----
storage failover modify -node <node4> -enabled true
----
+
[source, cli]
----
storage failover show
----
. Migrar agregados de datos propiedad del nodo 4 que deberían ser propiedad del nodo 3:
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node4> -destination <node3>
----
. Muestre el estado de todos los agregados de datos del clúster:
+
[source, cli]
----
storage aggregate show
----
. Habilite la reversión automática de las LIF de red en los nodos:
+
[source, cli]
----
network interface modify -lif * -auto-revert true
----
. Habilitar la conmutación automática al nodo de respaldo de almacenamiento:
+
[source, cli]
----
storage failover modify -node * -auto-giveback true
----
. Mostrar el estado del clúster:
+
[source, cli]
----
cluster show
----
. Mostrar elegibilidad de failover:
+
[source, cli]
----
storage failover show
----
+

NOTE: En la salida del informe de clúster, es posible que un nodo posea incorrectamente agregados que pertenecen a otro nodo.  Si esto ocurre, realice una adquisición y devolución desde ambos lados del clúster.

. Muestre el estado de todos los agregados de datos del clúster:
+
[source, cli]
----
storage aggregate show
----

