---
permalink: upgrade/reassign-node1-drives.html 
sidebar: sidebar 
keywords: fas2820, aff a150, aff a220, ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: Después de convertir AFF A150, AFF A220 o FAS2820 nodo1 en una estantería de unidades y conectarlo a nodo3, reasignas las unidades que antes pertenecían a nodo1 a nodo3. 
---
= Reasignar unidades de node1 a node3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reasigna las unidades que estaban previamente asignadas a AFF A150, AFF A220 o FAS2820 node1 a node3.

.Pasos
Realiza estos pasos en node3.

. En el símbolo del SISTEMA DEL CARGADOR, arranque node3 en Modo de mantenimiento:
+
[source, cli]
----
boot_ontap maint
----
+
Aparece el mensaje del modo de mantenimiento.

. Mostrar todas las unidades asociadas:
+
[source, cli]
----
disk show -v
----
. Registre el valor del ID del sistema local; este es el ID del sistema del nodo3.  Registre también los ID del sistema del nodo1 y del nodo4 de la columna "PROPIETARIO".
. Reasignar todas las unidades de node1 a node3:
+
[role="tabbed-block"]
====
.Si está utilizando discos completos
--
Ejecute el siguiente comando:

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID>
----
--
.Si está utilizando discos particionados
--
Ejecute el siguiente comando:

[source, cli]
----
disk reassign -s <node1_system_ID> -d <node3_system_ID> -p <node4_system_ID>
----
--
====
. Verifique que todas las unidades reasignadas puedan verse en el nuevo ID de sistema:
+
[source, cli]
----
disk show -s <node3_system_ID>
----
+

CAUTION: Si las unidades no se pueden ver, *deténgase* y comuníquese con el soporte técnico para obtener ayuda.

. Salir del modo de mantenimiento:
+
[source, cli]
----
halt
----


.El futuro
link:migrate-node4-lifs-aggregates.html["Migre LIF y agregados de datos de node4 a node3"]
