---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: Debe reasignar los discos que pertenecen al nodo 1 y al nodo 2 respectivamente al nodo 3 y al nodo 4. 
---
= Conecte las bandejas de almacenamiento y reasigne la propiedad de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe reasignar los discos que pertenecen al nodo 1 y al nodo 2 respectivamente al nodo 3 y al nodo 4.

.Acerca de esta tarea
Es necesario realizar los pasos de esta sección, como nodo 3 y nodo 4, completar cada paso del nodo 3 y luego nodo 4 antes de pasar al siguiente paso.

.Pasos
. Conecte los cables de la bandeja de almacenamiento de las bandejas que se conectaron previamente a node1/node2 a node3/node4.
+

CAUTION: No debe conectar las nuevas bandejas a node3/node4 durante este procedimiento de actualización. Puede conectar nuevas bandejas al sistema de forma no disruptiva una vez completada la actualización de la controladora.

. Verifique el suministro de alimentación y la conectividad física de las bandejas.
. Desde el símbolo del sistema DEL CARGADOR de nodo 3, arranque en modo de mantenimiento:
+
`boot_ontap maint`

. Muestre el ID del sistema del nodo 3:
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
Registre el ID del sistema del nodo 3 para usar en el paso 4 a continuación.

. Reasignar los discos de repuesto del nodo 1, los discos que pertenecen al agregado raíz y cualquier agregado de datos:
+
`disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysID_`

+
--
** El parámetro `_node1_sysid_` Es el valor registrado en _Apagar los nodos originales_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Paso 5"].
** Especifique el parámetro `_-p partner_sysID_` solo cuando haya discos compartidos presentes.


[NOTE]
====
Cuando se reasignan discos de repuesto del nodo 2, discos que pertenecen al agregado raíz y cualquier agregado de datos, el comando es:

`disk reassign -s node2_sysid -d node4_sysid -p node3_sysID`

====
--
+
El sistema muestra un mensaje similar a lo siguiente:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Introduzca `y` para continuar.
+
El sistema muestra un mensaje similar a lo siguiente:

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. Introduzca `y` para continuar.
. Confirme que el agregado raíz del nodo 1 está establecido en `root` en el campo de opciones y que otros agregados están en línea:
+
`aggr status`

+
Debería ver una salida similar a la siguiente:

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. Salir del modo de mantenimiento:
+
`halt`


