---
permalink: upgrade/upgrade-create-aggregate-move-volumes.html 
sidebar: sidebar 
keywords: create, aggregate, node, store, volume, original, node, identify, aggregate, individually, create an aggregate and moving volumes to the new nodes 
summary: Cree al menos un agregado en cada uno de los nuevos nodos para almacenar los volúmenes que desea mover desde los nodos originales. Debe identificar un agregado para cada volumen y moverlo por separado. 
---
= Cree un agregado y mueva volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante una actualización del software ONTAP, se migran los datos al crear un agregado en los nodos nuevos y, luego, mover los volúmenes.

Si la configuración de almacenamiento incluye volúmenes SAN o volúmenes cifrados, también debe mover estos volúmenes:

* <<move_san_vols,Mueva volúmenes SAN>>
* <<Mueva volúmenes con el cifrado habilitado>>




== Cree un agregado y mueva volúmenes a los nuevos nodos

Cree al menos un agregado en cada uno de los nuevos nodos para almacenar los volúmenes que desea mover desde los nodos originales. Debe identificar un agregado para cada volumen y moverlo por separado.

.Antes de empezar
Se deben inicializar las relaciones de reflejo de protección de datos para poder mover un volumen.

https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["Busque el procedimiento de protección de datos necesario"^].


NOTE: Para cada máquina virtual de almacenamiento (SVM), NetApp recomienda mover todos los volúmenes no raíz del clúster antes de mover el volumen raíz, y realizar este procedimiento en una SVM a la vez.

.Pasos
. Cree al menos un agregado en cada nuevo nodo:
+
`storage aggregate create -aggregate _aggr_name_ -node _new_node_name_ -diskcount integer`

. Añada el agregado nuevo a la misma máquina virtual de almacenamiento (SVM) que el agregado del nodo original desde el que desea mover los volúmenes:
+
`vserver add-aggregates`

+
Tanto el nuevo agregado como el anterior desde el que se moverá el volumen tienen que estar en la misma SVM.

. Compruebe que el nuevo agregado se haya asignado ahora a la misma SVM que el agregado del nodo original:
+
`vserver show -vserversvm_name`

. Muestra información de los volúmenes que se desean mover de los nodos originales a los nuevos nodos:
+
`volume show -vserver _svm_name_ -node _original_node_name_`

+
Debe conservar el resultado del comando para poder consultarlo más adelante si se desea.

+
En el siguiente ejemplo, se muestran los volúmenes en la SVM "vs1" y el nodo "node0":

+
[listing]
----
cluster::> volume show -vserver vs1 -node node0
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs1       clone        aggr1        online     RW         40MB    37.87MB    5%
vs1       vol1         aggr1        online     RW         40MB    37.87MB    5%
vs1       vs1root      aggr1        online     RW         20MB    18.88MB    5%
3 entries were displayed.
----
. Determine un agregado al que puede mover un volumen determinado:
+
`volume move target-aggr show -vserver _svm_name_ -volume _vol_name_`

+
El siguiente ejemplo muestra que el volumen "user_max" de la SVM "vs2" se puede mover a cualquiera de los agregados mostrados:

+
[listing]
----
cluster::> volume move target-aggr show -vserver vs2 -volume user_max
Aggregate Name   Available Size  Storage Type
--------------   --------------  ------------
aggr2            467.9GB         FCAL
node12a_aggr3    10.34GB         FCAL
node12a_aggr2    10.36GB         FCAL
node12a_aggr1    10.36GB         FCAL
node12a_aggr4    10.36GB         FCAL
5 entries were displayed
----
. Ejecute una comprobación de validación en cada volumen que desee mover para verificar que se pueda mover al agregado especificado:
+
`volume move start -vserver _svm_name_ -volume _volume_name_ -destination-aggregate _destination_aggregate_name_ -perform-validation-only true`

. Mueva los volúmenes de uno en uno (nivel de privilegios avanzado):
+
`volume move start -vserver _svm_name_ -volume _vol_name_ -destination-aggregate _destination_aggr_name_ -cutover-window integer`

+
No se puede mover el volumen raíz del nodo (vol0). Se pueden mover otros volúmenes, incluidos los volúmenes raíz de SVM.

. Muestre el resultado de `volume move` operación para verificar que los volúmenes se han movido correctamente:
+
`volume move show -vserver _svm_name_ -volume _vol_name_`

. Si la `volume move` la operación no completa la fase final después de varios intentos, fuerza el movimiento para terminar:
+
`volume move trigger-cutover -vserver _svm_name_ -volume _vol_name_ -force true`

+
Al forzar la operación de movimiento de volúmenes para que finalice, se puede interrumpir el acceso de los clientes al volumen que se está moviendo.

. Compruebe que los volúmenes se hayan movido correctamente a la SVM especificada y se encuentren en el agregado correcto:
+
`volume show -vserver _svm_name_`





== Mueva volúmenes SAN

Para mover volúmenes SAN, siga los pasos que se indican en https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html["Mover hosts iSCSI de Linux de nodos FC de MetroCluster a nodos IP de MetroCluster"^]. Esto se aplica al movimiento de volúmenes SAN tanto en configuraciones de MetroCluster como no de MetroCluster.



== Mueva volúmenes con el cifrado habilitado

Para mover volúmenes con el cifrado de agregados habilitado, siga los pasos de https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["Habilite el cifrado en un volumen existente con el comando volume Move start"^].
