---
permalink: upgrade/upgrade_considerations_move_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, lif, original, node, unjoin, original, move san lifs 
summary: Solo necesita mover LIF SAN si está cambiando el contenido del clúster. 
---
= Consideraciones para mover LIF SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Solo debe mover las LIF SAN si va a cambiar el contenido del clúster, por ejemplo, agregando nodos al clúster o eliminando nodos del clúster. Cuando mueve una LIF, no tiene que volver a dividir en zonas la estructura de FC ni crear nuevas sesiones iSCSI entre los hosts conectados del clúster y la nueva interfaz de destino.

Puede mover un LIF DE SAN mediante el `network interface modify` comando. Para mover un LIF SAN, debe desconectar la LIF, mover el LIF a un puerto o nodo raíz diferente y, a continuación, volver a conectarlo en su nueva ubicación. El acceso asimétrico de Unidad lógica (ALUA, Asymmetric Logical Unit Access) proporciona rutas redundantes y selección automática de rutas como parte de cualquier solución SAN de ONTAP. Por lo tanto, cuando el LIF se desconecta para dicho movimiento, no se produce ninguna interrupción de I/O. El host simplemente reintenta y, a continuación, mueve I/o a otra LIF.

Durante los movimientos de LIF, puede realizar de forma no disruptiva las siguientes tareas:

* Sustituya un par de alta disponibilidad de un clúster por un par de alta disponibilidad actualizado de manera que los hosts que acceden a los datos de una LUN sean transparentes
* Actualizar una tarjeta de interfaz de destino
* Traslade los recursos de una máquina virtual de almacenamiento (SVM) de un conjunto de nodos de un clúster a otro conjunto de nodos del mismo clúster
* Cuando el servidor host está en línea, puede mover una LUN SAN a un nuevo par de alta disponibilidad sin interrumpir el acceso del servidor host a los datos de la LUN


Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["Movimiento de LIF SAN"^] De la documentación de _SAN Storage Management_.
