---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: Debe reasignar los discos que pertenecen al nodo 1 y al nodo 2 respectivamente al nodo 3 y al nodo 4. 
---
= Conecte las bandejas de almacenamiento y reasigne la propiedad de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe reasignar los discos que pertenecen al nodo 1 y al nodo 2 respectivamente al nodo 3 y al nodo 4.

.Acerca de esta tarea
Debes seguir los pasos de esta sección en node3 y node4. Completa cada paso en node3 y luego en node4 antes de pasar al siguiente paso.

[[reassign-spare-disks-step1]]
.Pasos
. Conecta los cables de las estanterías de almacenamiento que ya estaban montadas:
+
** Conecta los cables de node1 a node3
** Conecta los cables de node2 a node4.
+

CAUTION: No conectes nuevas unidades de almacenamiento a node3 o node4 durante este procedimiento de actualización. Puedes conectar nuevas unidades de almacenamiento al sistema sin interrumpir el servicio después de completar la actualización del controlador.



. Verifique el suministro de alimentación y la conectividad física de las bandejas.
. Desde el símbolo del sistema DEL CARGADOR de nodo 3, arranque en modo de mantenimiento:
+
`boot_ontap maint`

. Muestre el ID del sistema del nodo 3:
+
`disk show -v`

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
Anota el ID del sistema de node3 para utilizarlo en <<reassign-disks-and-aggregates,Paso 5>>.

. [[reassign-disks-and-aggregates]]Reasigna los discos y los agregados de datos:
+
[role="tabbed-block"]
====
.Reasignar a node3
--
Reasigna los discos de reserva de node1, los discos que pertenecen al agregado raíz y cualquier agregado de datos a node3:

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** El parámetro  `node1_sysid` es el valor que anotaste en _Apagado de los nodos originales_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Paso 5"].
** Especifica el parámetro  `-p <node4_sysid>` solo cuando haya discos compartidos.


--
.Reasignar a node4
--
Reasigna los discos de reserva del nodo2, los discos que pertenecen al agregado raíz y cualquier agregado de datos al nodo4:

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** El parámetro  `node2_sysid` es el valor que anotaste en _Apagado de los nodos originales_, link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["Paso 5"].
** Especifica el parámetro  `-p <node3_sysid>` solo cuando haya discos compartidos.


--
====
+
El sistema muestra un mensaje similar a lo siguiente:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. Introduzca `y` para continuar.
+
El sistema muestra un mensaje similar a lo siguiente:

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. Introduzca `y` para continuar.
. Confirme que el agregado raíz del nodo 1 está establecido en `root` en el campo de opciones y que otros agregados están en línea:
+
`aggr status`

+
Debería ver una salida similar a la siguiente:

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]Sal del modo de mantenimiento:
+
`halt`

. Repite <<reassign-spare-disks-step1,Paso 1>> a <<reassign-spare-disks-step9,Paso 9>> en node4.


.El futuro
Tras conectar las bandejas de almacenamiento y reasignar la propiedad de los discos, link:upgrade-restore-root-volume-config.html["restaurar la configuración del volumen raíz"].
