---
permalink: upgrade/upgrade-remove-original-nodes.html 
sidebar: sidebar 
keywords: volume, move, node, remove, original, cluster, configuration, disk, initialize, remove the original nodes from the cluster 
summary: Una vez que los volúmenes se hayan trasladado a los nuevos nodos, elimine los nodos originales del clúster. Cuando se elimina un nodo, se borra la configuración del nodo y se inicializan todos los discos. 
---
= Eliminar los nodos originales del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de mover los volúmenes de los nodos originales a los nuevos y mover o eliminar LIF de datos, se eliminan los nodos originales del clúster. Cuando se elimina un nodo, se borra la configuración del nodo y se inicializan todos los discos.

.Pasos
. [[disable-ha]]Deshabilitar la configuración de alta disponibilidad (HA) en los nodos originales:
+
[source, cli]
----
storage failover modify -node <original_node_name> -enabled false
----


. Cambia el nivel de privilegio a avanzado:
+
[source, cli]
----
set -privilege advanced
----
. Identifica el nodo en el clúster que tiene epsilon:
+
[source, cli]
----
cluster show
----
+
En el siguiente ejemplo, "nodo 0" actualmente tiene un valor épsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Si el nodo que estás eliminando mantiene epsilon:
+
.. Mueve el epsilon del nodo que estás eliminando:
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. Mueve épsilon a un nodo que no vas a eliminar:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Identificar el nodo maestro actual:
+
[source, cli]
----
cluster ring show
----
+
El nodo maestro es el nodo que contiene procesos como `mgmt`, `vldb`, `vifmgr`, `bcomd`, y `crs`.

. Si el nodo que estás eliminando es el nodo maestro actual, habilita otro nodo en el clúster para que sea elegido como nodo maestro:
+
.. Hacer que el nodo maestro actual no sea elegible para participar en el clúster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
El nodo se marca como no saludable hasta que se restablece la elegibilidad. Cuando el nodo maestro deja de ser elegible, uno de los nodos restantes es elegido por el quórum del clúster como el nuevo maestro.

+
[NOTE]
====
Si realizas este paso en el primer nodo de un par de HA, deberías marcar solo ese nodo como no apto. No modifiques el estado del compañero de HA.

Si el nodo asociado es seleccionado como el nuevo maestro, necesitas verificar si tiene epsilon antes de hacerlo inelegible. Si el nodo asociado tiene epsilon, necesitas mover epsilon a un nodo diferente que permanezca en el cluster antes de hacerlo inelegible. Haces esto cuando repites estos pasos para remover el nodo asociado.

====
.. Hacer que el nodo maestro anterior sea elegible nuevamente para participar en el clúster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Inicia sesión en la LIF de gestión del nodo remoto o en la LIF de gestión del clúster en un nodo que no vas a quitar del clúster.
. Elimina los nodos del clúster:
+
|===
| Para esta versión de ONTAP... | Se usa este comando... 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9.4 y posteriores
 a| 
Con nombre de nodo:

[source, cli]
----
cluster remove-node -node <node_name>
----
Con IP de nodo:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Si tiene un clúster de versiones mixtas y está eliminando el último nodo de versión inferior, utilice el `-skip-last-low-version-node-check` parámetro con estos comandos.

+
El sistema le informa lo siguiente:

+
** También debe eliminar el socio de conmutación por error del nodo del clúster.
** Después de eliminar el nodo y antes de que pueda volver a unirse a un clúster, debe utilizar la opción *(4) Limpiar configuración e inicializar todos los discos* del menú de arranque o la opción *(9) Configurar particionamiento avanzado de unidades* para borrar la configuración del nodo e inicializar todos los discos.
+
Se genera un mensaje de error si hay condiciones que se deben abordar antes de eliminar el nodo. Por ejemplo, el mensaje puede indicar que el nodo tiene recursos compartidos que debe eliminar o que el nodo está en una configuración de alta disponibilidad de clúster o de conmutación por error de almacenamiento que debe deshabilitar.

+
Si el nodo es el quorum master, el clúster perderá brevemente y luego volverá al quorum. Esta pérdida de quorum es temporal y no afecta ninguna operación de datos.



. Si un mensaje de error indica condiciones de error, aborde esas condiciones y vuelva a ejecutar el `cluster remove-node` o `cluster unjoin` dominio.
+
El nodo se reinicia automáticamente después de ser eliminado con éxito del cluster.

. Si está reutilizando el nodo, borre la configuración del nodo e inicialice todos los discos:
+
.. Durante el proceso de arranque, presione Ctrl-C para mostrar el menú de arranque cuando se le solicite.
.. Seleccione la opción del menú de arranque *(4) Limpiar configuración e inicializar todos los discos*.


. [[return-admin]]Vuelve al nivel de privilegio admin:
+
[source, cli]
----
set -privilege admin
----


. Repetir pasos <<disable-ha,1>> a <<return-admin,10>> para eliminar el socio de conmutación por error del clúster.
. Si el clúster solo tiene dos nodos restantes, configure la alta disponibilidad para el clúster de dos nodos:
+
[source, cli]
----
cluster ha modify -configured true
----


.El futuro
link:upgrade-complete-move-volumes.html["Completar la actualización de volúmenes de movimiento"]
