---
permalink: upgrade/upgrade-move-lifs-to-new-nodes.html 
sidebar: sidebar 
keywords: move, volume, original, node, migrate, non-san, lif, cluster-management, move non-san data lifs and cluster management lifs to the new nodeas 
summary: Después de mover los volúmenes desde los nodos originales, necesitará migrar las LIF de datos sin SAN y los LIF de gestión de clústeres desde los nodos originales hasta los nuevos nodos. 
---
= Mueva LIF de datos que no sean SAN y LIF de gestión de clúster a los nuevos nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de mover los volúmenes de los nodos originales, deberá migrar las LIF de datos sin SAN y las LIF de administración de clúster de los nodos originales a los nuevos nodos.

.Acerca de esta tarea
No se puede migrar una LIF que se usa para operaciones de descarga de copias con las API de VMware vStorage para la integración de cabinas (VAAI).

.Pasos
. Inicie sesión con la LIF de gestión de clúster y enumere todas las LIF de los nodos originales (lista separada por comas):
+
[source, cli]
----
network interface show -curr-node <list_of_original_node_names>
----
. Cambie los puertos de inicio de las LIF de datos no SAN de los nodos originales a los nodos nuevos:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <new_node_name> -home-port {<netport|ifgrp>}
----
. Realice una de las siguientes acciones:
+
[cols="1,2"]
|===
| Si desea migrar... | A continuación, introduzca... 


 a| 
Una LIF específica
 a| 
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <dest_node_name> -destination-port <dest_port_name>
----


 a| 
Todos los LIF de datos que no sean SAN y los LIF de administración de clúster
 a| 
[source, cli]
----
network interface migrate-all -node <node_name>
----
|===
+
El siguiente comando migra una LIF llamada "datalif1" de la SVM "vs0" al puerto "e0d" de "nodet 0b":

+
[source, cli]
----
cluster::> network interface migrate -vserver vs0 -lif datalif1 -destination-node node0b -destination-port e0d
----
+
El siguiente comando migra todas las LIF de datos y de administración de clúster del nodo (local) actual:

+
[source, cli]
----
cluster::> network interface migrate-all -node local
----
. Compruebe si el nodo de inicio de la LIF de gestión de clústeres está en uno de los nodos originales:
+
[source, cli]
----
network interface show -lif cluster_mgmt -fields home-node
----
. Si el nodo inicial del LIF de gestión del clúster está en uno de los nodos originales, realice los siguientes pasos:
+
.. Cambie el nodo de inicio del LIF de gestión del clúster a uno de los nuevos nodos:
+
[source, cli]
----
network interface modify -vserver <cluster_name> -lif cluster_mgmt -home-node <new_node_name> -home-port {<netport|ifgrp>}
----
.. Migre el LIF de gestión de clústeres a uno de los nuevos nodos:
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif cluster-mgmt -destination-node <new_node_name> -destination-port {<netport|ifgrp>}
----




.El futuro
link:upgrade_move_delete_recreate_san_lifs.html["Mover, eliminar o crear SAN LIF"]
