---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: En este contenido se describe cómo actualizar el hardware de la controladora de un sistema AFF o de un sistema FAS en un clúster moviendo almacenamiento o volúmenes. 
---
= Decidir si se actualizará el volumen o el almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En este contenido se describe cómo actualizar el hardware de la controladora de un sistema AFF, FAS o ASA en un clúster moviendo el almacenamiento o los volúmenes.

Utilice este procedimiento si desea actualizar el hardware de la controladora en las siguientes situaciones:

[NOTE]
====
* Cuando actualiza a un sistema introducido en ONTAP 9.15,1, ONTAP convierte la eficiencia de almacenamiento de los volúmenes existentes y aplica las nuevas funciones de eficiencia del almacenamiento que utilizan la funcionalidad de descarga de hardware. Se trata de un proceso automático en segundo plano, sin impacto visible en el rendimiento del sistema.
+
** Para sistemas AFF A70, AFF A90 o AFF A1K, ONTAP convierte la eficiencia del almacenamiento de todos los volúmenes Thin-Provisioning existentes, incluidos aquellos que no usan la eficiencia del almacenamiento.
** Para un sistema FAS70 y FAS90, ONTAP solo convierte la eficiencia del almacenamiento de los volúmenes existentes con Thin-Provisioning que tenían activada la eficiencia del almacenamiento antes de la actualización.
+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Obtenga más información sobre la eficiencia del almacenamiento"^].



* Los procedimientos de actualización de hardware se han simplificado en ONTAP 9.8 con la introducción de la función de colocación automática de puertos.


====
* Los nodos originales y los nuevos son compatibles y compatibles.
* Los nodos originales y nuevos ejecutan ONTAP 9,0 o una versión posterior. NetApp recomienda, siempre que sea posible, que tenga la misma versión de ONTAP que se ejecute en los nodos originales y en los nuevos.
+
Si la actualización de la controladora incluye versiones mixtas de ONTAP, consulte https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["Clústeres de ONTAP de versión mixta"^] si quiere más información.

* Se están reutilizando las direcciones IP, las máscaras de red y las puertas de enlace de los nodos originales en los nuevos nodos.
* Para actualizar el hardware de la controladora, mueva almacenamiento o mueva volúmenes.
* Está preparado para realizar un procedimiento disruptivo si va a actualizar moviendo almacenamiento.
+
La actualización mediante el movimiento de volúmenes es no disruptiva.

* Planea convertir un nodo de un modelo compatible a una bandeja de discos y, a continuación, conectar a los nuevos nodos.


Si desea actualizar una configuración de MetroCluster, consulte https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Actualice, actualice o expanda la configuración de MetroCluster"^].

.Información relacionada
* link:upgrade-considerations.html["Consideraciones que tener en cuenta para actualizar el hardware de la controladora"]
* link:../choose_controller_upgrade_procedure.html["Elija métodos para actualizar el hardware de la controladora"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["Dónde encontrar procedimientos para las tareas de mantenimiento de MetroCluster"^]
* https://hwu.netapp.com["Hardware Universe de NetApp"^]

