---
permalink: upgrade/upgrade_migrate_lIFs_aggregates_node4_node3.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: Prepare node3, conecte el nodo node3 al node4 y después migre las LIF y los agregados de datos en node4 a node3. 
---
= Migre LIF y agregados de datos de node4 a node3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para completar la actualización, conecte node3 a node4 y, a continuación, migre las interfaces lógicas de datos (LIF) y los agregados de datos en node4 a node3.

.Pasos
. En el símbolo del sistema DEL CARGADOR DE node3, arranque el nodo en el menú de arranque:
+
`boot_ontap menu`

. Seleccione opción `6 Update flash from backup config` restaurar el sistema de archivos /var a node3.
+
Esto sustituye la configuración basada en all-flash por el último backup en discos.

. Introduzca `y` para continuar.
. Permita que el nodo arranque como normal.
+
[NOTE]
====
El nodo se reinicia automáticamente para cargar la nueva copia del sistema de archivos /var.

El nodo informa de una advertencia de que hay una discrepancia de ID del sistema. Introduzca `y` Para anular el ID del sistema.

====
. Conecte node3 a node4:
+
.. Conecte los cables de alta disponibilidad multivía (MPHA) a la bandeja NS224 para garantizar la redundancia. Conecte el puerto node3 100GbE e0d al puerto NSM B e0b y conecte el puerto node4 100GbE e0d al puerto NSM A e0a.
.. Compruebe que los puertos de alta disponibilidad e0a y e0b están conectados entre los nodos.
.. Compruebe que los puertos E3A y E3b del clúster están conectados entre los nodos.


. Migrar los LIF de clúster:
+
`set -privilege advanced`

+
`network port show`

. Modifique el dominio de retransmisión de clúster para incluir los puertos de clúster deseados:
+
`network port broadcast-domain remove-ports -broadcast-domain _broadcast_domain_name_ -ports _port_names_`

+
`network port broadcast-domain add-ports -broadcast-domain Cluster -ports _port_names_`

+

NOTE: A partir de ONTAP 9,8, se podrían designar nuevos espacios IP y uno o más dominios de retransmisión para los puertos físicos existentes destinados a la conectividad del clúster.

. Modifique el espacio IP del clúster para incluir los puertos del clúster deseados y establezca la unidad de transmisión máxima en 9000 si aún no está configurada:
+
`network port modify -node _node_name_ -port _port_name_ -mtu 9000 -ipspace Cluster`

. Muestre todas las LIF de red del clúster:
+
`network interface show -role cluster`

. Migre todas las LIF de red de clúster en ambos nodos a sus puertos principales:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node_name_ -destination-port _port_name_`

. Muestre todas las LIF de red del clúster:
+
`network interface show -role cluster`

. Compruebe los puertos de inicio de las LIF de red de clúster:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -home-port _port_name_`

. Migre todos los LIF de datos a node3:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node_name_ -destination-port _port_name_`

. Mostrar todas las LIF de red de datos:
+
`network interface show -role data`

. Configure el nodo de inicio y el puerto de inicio para todas las LIF de datos. Si alguna LIF está inactiva, establezca el estado administrativo de las LIF en `up` Con el siguiente comando, una vez para cada LIF:
+
`network interface modify -vserver _vserver_name_ -lif lif_name -home-node _node_name_ -home-port _port_name_ -status-admin up`

. Migre la LIF de administración del clúster:
+
`network interface migrate -vserver _vserver_name_ -lif cluster_mgmt -destination-node _node3_ -destination-port _port_name_`

. Muestre el estado de la LIF de gestión del clúster:
+
`network interface show cluster_mgmt`

. Muestre el estado de todos los agregados de datos del clúster:
+
`storage aggregate show`

. Habilitar el par de alta disponibilidad, la conmutación por error del almacenamiento y la restauración automática:
+
`cluster ha modify -configured true`

. Migrar agregados de datos propiedad de node4 a node3:
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node4_ -destination _node3_`

. Muestre el estado de todos los agregados de datos del clúster:
+
`storage aggregate show`

. Habilite la reversión automática de las LIF de red en los nodos:
+
`network interface modify -lif * -auto-revert true`

. Habilitar la conmutación automática al nodo de respaldo de almacenamiento:
+
`storage failover modify -node * -auto-giveback true`

. Mostrar el estado del clúster:
+
`cluster show`

. Mostrar elegibilidad de failover:
+
`storage failover show`

+

NOTE: En la salida del informe de clúster, es posible que un nodo pertenezca de forma incorrecta agregados que pertenecen a otro nodo. En este caso, normalice llevando a cabo una toma de control y una restauración por ambos lados del clúster.

. Muestre el estado de todos los agregados de datos del clúster:
+
`storage aggregate show`


