---
permalink: upgrade/upgrade_migrate_lifs_aggregates_node2_to_node1.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs 
summary: 'Migrar las interfaces lógicas (LIF) y los agregados de datos del node2 a node1.' 
---
= Migre LIF y agregados de datos de node2 a node1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de convertir AFF A250 node2 en una bandeja de unidades, deberá migrar las interfaces lógicas (LIF) y los agregados de datos en node2 a node1.

.Antes de empezar
Compruebe que cumple los siguientes requisitos:

* Las controladoras AFF A250 y AFF A400 ejecutan la misma versión y versión de revisión de ONTAP.
+
[NOTE]
====
** Debe reiniciar e instalar la versión de ONTAP en cada AFF A400 que sea idéntico a la versión que se ejecuta en AFF A250.
** Tanto la imagen de inicio principal como la de backup de cada AFF A400 deben tener la misma versión de ONTAP.
** Si los clústeres de AFF A400 se configuraron previamente, debe borrar cualquier configuración de clúster residual ejecutando un `wipeconfig` desde el menú de arranque.


====
* Ambas controladoras AFF A400 están en espera en el aviso del CARGADOR.
* Dispone de todos los cables adecuados a mano.


.Acerca de esta tarea
Los siguientes pasos se realizan en AFF A250 node1.

.Pasos
. Acceda al nivel de privilegio avanzado:
+
`set -privilege advanced`

. Desactivar la conmutación automática al nodo de respaldo del almacenamiento:
+
`storage failover modify -node _node1_ -auto-giveback false`

. Deshabilite la reversión automática de las LIF en ambos nodos del par de alta disponibilidad:
+
`network interface modify -lif * -auto-revert false`

. Mostrar el estado de todas las LIF de red de datos:
+
`network interface show -role data`

. Muestre el estado de las LIF de administración del clúster:
+
`network interface show -role cluster_mgmt`

. Migre todas las LIF de datos desde las máquinas virtuales de almacenamiento alojadas en node2:
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node1_ -destination-port _port_name_`

+

NOTE: Este comando solo migra LIF que no sean SAN. No puede utilizarlo para migrar LIF iSCSI y FCP.

. Mostrar el estado de todas las LIF de datos en el clúster:
+
`network interface show -role data`

. Si alguna LIF está inactiva, establezca el estado administrativo de las LIF en `up` Con el siguiente comando, una vez para cada LIF:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin up`

. Muestre el estado de todos los agregados de datos del clúster:
+
`storage aggregate show`

. Mostrar elegibilidad de failover:
+
`storage failover show`

. Migre los agregados de datos de node2 a node1:
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node2_ -destination _node1_`

. Muestre el estado de todos los agregados de datos del clúster:
+
`storage aggregate show`

. Muestre el estado de todos los volúmenes de datos en el clúster:
+
`volume show`

. Muestre la `ha` estado y propiedad de épsilon:
+
`cluster show`

. Desactivar `cluster ha`:
+
`cluster ha modify -configured false`

. Muestre la `ha` estado y propiedad de épsilon:
+
`cluster show`

. Detener nodo 2:
+
`halt -node _node2_ -inhibit-takeover true -ignore-quorum-warnings true`



.El futuro
link:upgrade_convert_node2_drive_shelf_connect_node4.html["Convierta node2 en una bandeja de unidades y conéctela a node4"]
