---
permalink: upgrade/upgrade_reassign_drives_node2_to_node4.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: Conecte físicamente node2 a node4 antes de reasignar unidades de node2 a node4. 
---
= Reasignar unidades de node2 a node4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de convertir AFF A250 node2 a una bandeja de unidades NS224 y conectarse a AFF A400 node4, debe reasignar las unidades que anteriormente pertenecían a node2 a node4.

.Antes de empezar
Compruebe que tanto node3 como node4 están en espera en el aviso del CARGADOR.

.Acerca de esta tarea
Realice los siguientes pasos en node4.

.Pasos
. En el símbolo del SISTEMA DEL CARGADOR, arranque node4 en Modo de mantenimiento:
+
`boot_ontap maint`

. Muestra el estado de las interfaces de 100GbE:
+
`storage port show`

. Establezca las interfaces de 100GbE a los puertos de almacenamiento:
+
`storage port modify -p e0c -m storage`

+
`storage port modify -p e0d -m storage`

. Compruebe que el modo cambia a las interfaces 100GbE:
+
`storage port show`

+
Se debe mostrar una salida como la del siguiente ejemplo:

+
[listing]
----
*> storage port modify -p e0c -m storage
Nov 10 16:27:23 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0c to storage mode.

Nov 10 16:27:29 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8885.

*> storage port modify -p e0d -m storage
Nov 10 16:27:34 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0d to storage mode.

Nov 10 16:27:38 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8886.

*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e0c  ENET storage 100 Gb/s    enabled  online  30
e0d  ENET storage 100 Gb/s    enabled  offline 30
----
. Mostrar todas las unidades asociadas:
+
`disk show -v`

. Registre el valor de ID del sistema local; éste es el ID del sistema node4. Registre también los ID del sistema de node1 y node2 de la columna de PROPIETARIO.
. Reasignar todas las unidades de node2 a node4:
+
`disk reassign -s _node2_system_ID_ -d _node4_system_ID_ -p _node1_system_ID_`

. Verifique que todas las unidades reasignadas puedan verse en el nuevo ID de sistema:
+
`disk show -s _node4_System_ID_`

+

NOTE: Si las unidades no se pueden ver, *STOP* y póngase en contacto con el soporte técnico para obtener ayuda.

. Compruebe que el agregado raíz de node2 se ha notificado en la salida y que el agregado está en línea:
+
`aggr status`

. Salga del modo de mantenimiento:
+
`halt`



.El futuro
link:upgrade_migrate_aggregates_epsilon_lifs_node1_to_node4.html["Migre agregados de datos, épsilon y LIF en node1 a node4"]
