---
permalink: upgrade/upgrade_reassign_drives_node1_to_node3.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node3, node1, reassign, drives 
summary: Conecte físicamente node1 a node3 antes de reasignar unidades de node1 a node3 
---
= Reasignar unidades de node1 a node3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de convertir AFF A250 node1 a una bandeja de unidades NS224 y conectarse a AFF A400 node3, debe reasignar las unidades que anteriormente pertenecían a node1 a node3.

.Pasos
. En el símbolo del SISTEMA DEL CARGADOR, arranque node3 en Modo de mantenimiento:
+
`boot_ontap maint`

. Muestra el estado de las interfaces de 100GbE:
+
`storage port show`

. Establezca las interfaces de 100GbE a los puertos de almacenamiento:
+
`storage port modify -p e0c -m storage`

+
`storage port modify -p e0d -m storage`

. Compruebe que el modo cambia a las interfaces 100GbE:
+
`storage port show`

+
Se debe mostrar una salida como la del siguiente ejemplo:

+
[listing]
----
*> storage port modify -p e0c -m storage
Nov 10 16:27:23 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0c to storage mode.

Nov 10 16:27:29 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8885.

*> storage port modify -p e0d -m storage
Nov 10 16:27:34 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0d to storage mode.

Nov 10 16:27:38 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8886.

*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e0c  ENET storage 100 Gb/s    enabled  online  30
e0d  ENET storage 100 Gb/s    enabled  offline 30
----
. Mostrar todas las unidades asociadas:
+
`disk show -v`

. Registre el valor de ID del sistema local; éste es el ID del sistema node3. Registre también los ID del sistema de node1 y node2 de la columna de PROPIETARIO.
. Reasignar todas las unidades de node1 a node3:
+
`disk reassign -s _node1_system_ID_ -d _node3_system_ID_ -p _node4_system_ID_`

. Verifique que todas las unidades reasignadas puedan verse en el nuevo ID de sistema:
+
`disk show -s _node3_system_ID_`

+

NOTE: Si las unidades no se pueden ver, *STOP* y póngase en contacto con el soporte técnico para obtener ayuda.

. Salir del modo de mantenimiento:
+
`halt`



.El futuro
link:upgrade_migrate_lIFs_aggregates_node4_node3.html["Migre LIF y agregados de datos de node4 a node3"]
