---
permalink: upgrade/upgrade-delete-san-lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lid, original, node, unjoin, original, delete san lifs from the original nodes 
summary: Si el clúster está en un entorno SAN, debe eliminar cualquier LIF SAN de los nodos originales antes de desunir los nodos originales del clúster. 
---
= Elimine ya no es necesario realizar LIF DE SAN desde los nodos originales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el clúster se encuentra en un entorno SAN, debe eliminar cualquier LIF DE SAN que ya no necesite desde los nodos originales antes de poder anular la unión de los nodos originales del clúster.

.Pasos
. Si tiene iniciadores de iSCSI, complete los pasos siguientes:
+
.. Muestre una lista de iniciadores activos conectados actualmente a una SVM en los nodos originales, una vez por cada una de las LIF anteriores: +
`iscsi connection show -vserver _Vserver_name_ -lif _old_lif_`
+
En el siguiente ejemplo, se muestra el resultado del comando con un iniciador activo conectado a SVM vs1:

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. Si algún iniciador sigue registrando en un nodo original, cierre la sesión de las sesiones del equipo host.


. Muestre la lista del conjunto de puertos para determinar si alguna LIF iSCSI o FC de los nodos originales pertenece a un conjunto de puertos:
+
`lun portset show`

+
En el siguiente ejemplo, se muestra el resultado de `lun portset show` comando:

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. Si alguno de los iSCSIs o LIF FC de un nodo original es miembro de un conjunto de puertos, elimínelos del conjunto de puertos:
+
`lun portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _lif_name_`

. Elimine las LIF en los nodos originales:
+
`network interface delete -vserver _vserver_name_ -lif _lif_name_`


