---
permalink: upgrade/upgrade-optional-move-internal-storage.html 
sidebar: sidebar 
keywords: node, support, model, internal, sata, drive, ssd, moving, move, upgrading, upgrade, convert, move internal storage or convert the system to a drive shelf 
summary: Si el nodo original es uno de los modelos admitidos, puede mover sus unidades SATA, SSD o SAS internas a una bandeja de unidades conectada a los nodos nuevos durante el proceso de actualización mediante la transferencia de almacenamiento. También puede convertir el sistema a una bandeja de unidades y adjuntarlo a los nuevos nodos. 
---
= Descripción general
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si el nodo original es uno de los modelos admitidos, puede mover sus unidades SATA, SSD o SAS internas a una bandeja de unidades conectada a los nodos nuevos durante el proceso de actualización mediante la transferencia de almacenamiento. También puede convertir el sistema a una bandeja de unidades y adjuntarlo a los nuevos nodos.

.Acerca de esta tarea
Solo puede mover unidades o bandejas de unidades dentro del mismo clúster.

.Opciones
* link:upgrade-move-internal-drives.html["Mueva unidades internas de un nodo original"]
+
Si el nodo original es uno de los modelos admitidos, durante el proceso de actualización moviendo almacenamiento puede mover las unidades SATA, SSD o SAS internas del nodo a una bandeja de unidades conectada al nodo nuevo del mismo clúster.

* link:upgrade-convert-node-to-shelf.html["Convertir un nodo original en una bandeja de unidades"]
+
Si el nodo original es uno de los modelos admitidos, durante el proceso de actualización moviendo almacenamiento puede convertir el nodo a una bandeja de unidades y, a continuación, arlo a los nuevos nodos del mismo clúster.


