---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configure y gestione el cifrado de almacenamiento, gestione las claves de autenticación y desactive las relaciones de SnapMirror cuando actualice las controladoras que ejecutan ONTAP 9.15.1 o una versión posterior mediante `system controller replace` el comando.' 
---
= Completa la preparación para la actualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Conoce las licencias de ONTAP y cómo gestionar Storage Encryption usando Onboard Key Manager (OKM). Opcionalmente, pon en pausa las relaciones de SnapMirror.



== Conoce las licencias de ONTAP

Si quiere información detallada sobre las licencias de ONTAP, consulte https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gestión de licencias"^].


NOTE: El uso de funciones sin licencia en la controladora puede provocar que no cumpla el contrato de licencia.



== Gestione el cifrado del almacenamiento con el gestor de claves incorporado

Usa el Onboard Key Manager (OKM) para gestionar las claves de cifrado. Si tienes el OKM configurado, debes registrar la frase de contraseña y el material de copia de seguridad antes de comenzar la actualización.

.Pasos
. Registre la clave de acceso para todo el clúster.
+
Esta es la frase de acceso que se introdujo cuando se configuró o actualizó OKM con la CLI o la API REST.

. Verifica la frase de contraseña y la operación del key-manager:
+
`security key-manager onboard sync`

+
Cuando te lo pidan, introduce la frase de contraseña OKM para todo el clúster que registraste en el paso anterior.

. Verifica que cc-mode está activado revisando la salida del siguiente comando:
+
`security key-manager config show`

. Haz una copia de seguridad de la información del key-manager:
+
`security key-manager onboard show-backup`





== Opcionalmente, silencia las relaciones SnapMirror

Antes de continuar con el procedimiento, debe confirmar que todas las relaciones de SnapMirror se ponen en modo inactivo. Cuando una relación de SnapMirror se pone en modo inactivo, sigue en modo inactivo tras reinicios y recuperaciones tras fallos.

.Pasos
. Compruebe el estado de la relación de SnapMirror en el clúster de destino:
+
`snapmirror show`

+
[NOTE]
====
Si el estado es "transferencia", debe anular dichas transferencias:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
La anulación falla si la relación de SnapMirror no se encuentra en el estado "transfiriendo".

. Desactive todas las relaciones entre el clúster:
+
`snapmirror quiesce -destination-vserver *`



.El futuro
Después de preparar la actualización, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["reubica los agregados que no son raíz y las LIF de datos NAS que pertenecen al nodo1 en el nodo2"].
