---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Decida si desea utilizar ARL para actualizar las controladoras que ejecutan ONTAP 9.15.1 o posterior mediante `system controller replace` comandos.' 
---
= Decida si desea utilizar el procedimiento de reubicación de agregados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este procedimiento se describe cómo actualizar las controladoras de almacenamiento en una pareja de alta disponibilidad con nuevas controladoras a la vez que se conservan los datos y los discos existentes. Se trata de un procedimiento complejo que sólo deben ser utilizados por administradores con experiencia.



== Actualizaciones compatibles de ARL

Puede actualizar una pareja de nodos en las siguientes circunstancias:

* Utiliza ONTAP 9.15.1 o posterior.
* No quiere añadir las nuevas controladoras como una nueva pareja de alta disponibilidad al clúster y migrar los datos mediante el procedimiento de movimiento de volúmenes.
* Tiene experiencia en la administración de ONTAP y está cómodo con los riesgos de trabajar en el modo de privilegios de diagnóstico.



NOTE: Puede usar el cifrado de almacenamiento de NetApp (NSE), el cifrado de volúmenes de NetApp (NVE) y el cifrado de agregados de NetApp (NAE) con este procedimiento.

[[sys_commands_9151_supported_systems]]La siguiente tabla muestra la matriz de modelo admitida para la actualización del controlador.

|===
| Controladora existente | Controladora de reemplazo | Compatible empezando con ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220 y AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| FAS8200, FAS8300, FAS8700 Y FAS9000 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ Para actualizar a un AFF A20, primero debe convertir un AFF A150 o AFF A220 en una bandeja DS224C intercambiando el módulo del controlador por un módulo IOM12. Consulte link:../upgrade/upgrade-convert-node-to-shelf.html["Convertir un nodo original en una bandeja de unidades"].

^2^ AFF A20, AFF A50, AFF A70 y AFF A90 son sistemas integrados con dos controladoras en una configuración de alta disponibilidad y discos incorporados en un único chasis:

* Si va a actualizar a un AFF A20, AFF A70 o AFF A90 con unidades internas, debe eliminar la propiedad de esas unidades internas antes de la actualización. Una vez completada la actualización, puede asignar las unidades internas a los nodos AFF A20, AFF A70 o AFF A90 y usarlas para crear agregados de datos. No es necesario migrar agregados de datos ni raíz a unidades internas.
* Si actualiza a un AFF A20, AFF A70 o AFF A90 sin unidades internas, no es necesario asignar unidades internas después de completar la actualización.


Si la combinación del modelo de actualización de la controladora no se encuentra en la tabla anterior, póngase en contacto con el soporte técnico.



== ARL no admite actualizaciones

No puede realizar actualizaciones mediante ARL en las siguientes circunstancias:

* Está realizando una de las siguientes actualizaciones:
+
|===
| Controladora existente | Controladora de reemplazo 


| AFF A250 | AFF A50 y AFF A30 


| AFF A800 | AFF A70 y AFF A90 


| AFF C250 | AFF C30 y AFF C60 


| AFF C800 | AFF C80 
|===
+
Para realizar una actualización de una lista en la tabla anterior, consulte link:other_references.html["Referencias"] el enlace a comandos _Utilizar «system controller replace» para actualizar los modelos de controladora en el mismo chasis_.

* Va a actualizar un sistema V-Series o un sistema de almacenamiento de virtualización de FlexArray a través de una cabina externa para almacenamiento back-end. Póngase en contacto con el soporte técnico para obtener opciones para actualizar un sistema V-Series o FlexArray.
* Va a actualizar una configuración IP o FC MetroCluster. Para actualizar una configuración de MetroCluster, consulte link:other_references.html["Referencias"] para vincular a la documentación _Actualización y ampliación de MetroCluster_.


Si prefiere un método diferente de actualización del hardware de la controladora y desea realizar movimientos de volúmenes, consulte link:other_references.html["Referencias"] Para enlazar con _Upgrade moviendo volúmenes o Storage_.

.Información relacionada
Consulte link:other_references.html["Referencias"] Para establecer un enlace al centro de documentación de _ONTAP 9_, donde puede acceder a la documentación de producto de ONTAP 9.
