---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'Decide si quieres usar ARL para actualizar a los controladores introducidos en ONTAP 9.15.1 o versiones posteriores usando los comandos  `system controller replace`.' 
---
= Decidir si se utilizará este procedimiento de reubicación agregada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varios métodos de reubicación agregada (ARL) para actualizar el hardware de los controladores. Este procedimiento de ARL describe cómo actualizar un par de controladores de alta disponibilidad (HA) en sistemas de almacenamiento AFF y FAS a controladores introducidos en ONTAP 9.15.1 o versiones posteriores, conservando al mismo tiempo los discos existentes y los datos almacenados en los discos. Este es un procedimiento complejo que solo deberían usar administradores de ONTAP con experiencia.

Para ayudarlo a decidir si este procedimiento ARL es adecuado para la actualización del hardware de su controlador, debe revisar todas las siguientes circunstancias para actualizaciones compatibles y no compatibles.



[[supported-upgrades-for-this-arl-procedure]]
== Actualizaciones compatibles con este procedimiento de ARL

Puede utilizar este procedimiento ARL para actualizar un par de nodos en las siguientes circunstancias:

* Utiliza ONTAP 9.15.1 o posterior.
* No quiere añadir las nuevas controladoras como una nueva pareja de alta disponibilidad al clúster y migrar los datos mediante el procedimiento de movimiento de volúmenes.
* Tiene experiencia en la administración de ONTAP y está cómodo con los riesgos de trabajar en el modo de privilegios de diagnóstico.
* Su combinación de actualización de hardware aparece en la <<sys_commands_9151_supported_systems,matriz de modelo soportada>> .



NOTE: Puede usar el cifrado de almacenamiento de NetApp (NSE), el cifrado de volúmenes de NetApp (NVE) y el cifrado de agregados de NetApp (NAE) con este procedimiento.



[[upgrades-not-supported-for-this-arl-procedure]]
== Actualizaciones no compatibles con este procedimiento de ARL

No puede utilizar este procedimiento ARL para actualizar un par de nodos en las siguientes circunstancias:

* Está realizando una de las siguientes actualizaciones:
+
|===
| Controladora existente | Controladora de reemplazo 


| AFF A250 | AFF A50 y AFF A30 


| AFF A800 | AFF A70 y AFF A90 


| AFF C250 | AFF C30 y AFF C60 


| AFF C800 | AFF C80 
|===
+
Para realizar una actualización de las indicadas en la tabla anterior, consulta link:other-references.html["Referencias"] para acceder a _Usa los comandos "system controller replace" para actualizar modelos de controladora en el mismo chasis_.

* Estás actualizando una configuración de FC o IP de MetroCluster. Para actualizar una configuración de MetroCluster, consulta link:other-references.html["Referencias"] para acceder a la documentación sobre la actualización y ampliación de _MetroCluster_.




[[supported-system-upgrade-combinations]]
[[sys_commands_9151_supported_systems]]
== Combinaciones de actualización del sistema admitidas

La siguiente tabla muestra las combinaciones de actualización de controlador compatibles con ARL para sistemas AFF y FAS introducidos en ONTAP 9.15.1 o posterior. Si su combinación de actualización de controlador no aparece en la lista, contacte con el soporte técnico.

|===
| Controladora existente | Controladora de reemplazo | Compatible empezando con ONTAP... 


| AFF A400 | AFF A50 ^2^ | 9.16.1 


| AFF A300 | AFF A50 ^2^ | 9.16.1 


| AFF A220 y AFF A150 | AFF A20 ^2^ | 9.16.1 ^1^ 


| AFF C400 | AFF C60, AFF C80 | 9.16.1 


| FAS8200, FAS8300, FAS9000 | FAS70, FAS90, FAS50 | 9.15.1P3 para FAS70, FAS90 9.16.1P2 para FAS50 


| FAS8700 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70 ^2^ , AFF A90 ^2^, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 ^2^, AFF A1K | 9.15.1 
|===
^1^ Para actualizar a un AFF A20, primero debe convertir un AFF A150 o AFF A220 en una bandeja DS224C intercambiando el módulo del controlador por un módulo IOM12. Consulte link:../upgrade/upgrade-convert-node-to-shelf.html["Convertir un nodo original en una bandeja de unidades"].

^2^ AFF A20, AFF A50, AFF A70 y AFF A90 son sistemas integrados con dos controladoras en una configuración de alta disponibilidad y discos incorporados en un único chasis:

* Si va a actualizar a un AFF A20, AFF A50, AFF A70 o AFF A90 con unidades internas, debe eliminar la propiedad de dichas unidades internas antes de la actualización. Después de completar la actualización, puede asignar las unidades internas a los nodos AFF A20, AFF A50, AFF A70 o AFF A90 y usarlos para crear agregados de datos. No es necesario migrar agregados de datos ni raíz a unidades internas.
* Si actualiza a un AFF A20, AFF A50, AFF A70 o AFF A90 sin unidades internas, no es necesario asignar unidades internas después de completar la actualización.




[[choose-a-different-hardware-upgrade-procedure]]
== Elija un procedimiento de actualización de hardware diferente

* link:../upgrade-arl/index.html["Revise los métodos ARL alternativos disponibles para actualizar el hardware del controlador"].
* Si prefieres un método diferente para actualizar el hardware del controlador y estás dispuesto a realizar movimientos de volúmenes, consulta link:other-references.html["Referencias"] para enlazar con _Actualización moviendo volúmenes o almacenamiento_.


.Información relacionada
Consulta link:other-references.html["Referencias"] para acceder a la _Documentación de ONTAP 9_.

.El futuro
Tras decidir utilizar este procedimiento ARL, link:required_tools_and_documentation.html["conoce las herramientas y la documentación necesarias"].
