---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Comprueba si puedes actualizar a los controladores introducidos en ONTAP 9.15.1 o versiones posteriores mediante los comandos  `system controller replace`.' 
---
= Directrices para actualizar controladoras con ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para saber si puedes usar ARL para actualizar a un par de controladoras introducidas en ONTAP 9.15.1 o versiones posteriores, depende de la plataforma y la configuración tanto de las controladoras originales como de las de reemplazo.



[[supported-upgrades-for-arl]]
== Actualizaciones compatibles de ARL

Antes de actualizar un par de nodos mediante este procedimiento ARL, revise los siguientes requisitos para asegurarse de que la configuración es compatible:

* Compruebe que ARL se puede realizar en los controladores originales y de sustitución.
* Comprueba el tamaño de todos los agregados definidos y el número de discos que admite el sistema original. Luego compara los tamaños de los agregados y el número de discos admitidos con el tamaño del agregado y el número de discos admitidos por el nuevo sistema. Consulta link:other-references.html["Referencias"] para ir a _Hardware Universe_, donde está disponible esta información. El tamaño del agregado y el número de discos admitidos por el nuevo sistema deben ser iguales o mayores que el tamaño del agregado y el número de discos admitidos por el sistema original.
* Comprueba en las reglas de mezcla del clúster si los nuevos nodos pueden integrarse en el clúster junto con los nodos existentes cuando se sustituya el controlador original. Para obtener más información sobre las reglas de mezcla del clúster, consulta link:other-references.html["Referencias"] para acceder a _Hardware Universe_.
* Migre y vuelva a alojar los LIF de clúster a dos puertos de clúster por nodo si tiene un sistema, como un AFF 700, con la siguiente configuración:
* Más de dos puertos de clúster por nodo
* Una tarjeta de interconexión de clúster en slot4 en modo de partición para crear los puertos E4A, e4b, e4c y e4d, y los puertos E4E, e4f, e4g y e4h
+

NOTE: Si se realiza una actualización de la controladora con más de dos puertos de clúster por nodo, es posible que falten LIF de clúster en la nueva controladora después de la actualización.

+
Para obtener más información, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["Cómo eliminar LIF de clúster no deseadas o innecesarias"^].



La actualización de la controladora mediante ARL es compatible en sistemas configurados con volúmenes de SnapLock Enterprise y SnapLock Compliance.



[[two-node-switchless-clusters]]
== Clústeres de dos nodos sin switches

Si va a actualizar nodos en un clúster sin switches de dos nodos, puede dejar los nodos en el clúster sin switches mientras realiza la actualización. No es necesario convertirlos en un clúster con switches.



[[upgrades-not-supported-for-arl]]
== ARL no admite actualizaciones

No es posible actualizar controladoras de reemplazo que no admiten las bandejas de discos conectadas a las controladoras originales.

Consulta link:other-references.html["Referencias"] para enlazar con _Hardware Universe_ y ver información sobre la compatibilidad de discos.

Si deseas actualizar los controladores de nivel básico con unidades internas, consulta link:other-references.html["Referencias"] para acceder al enlace _Actualización mediante el traslado de volúmenes o almacenamiento_ y ve al procedimiento _Actualización de un par de nodos que ejecutan Clustered Data ONTAP mediante el traslado de volúmenes_.



[[troubleshoot]]
== Solucionar problemas

Si surge algún problema al actualizar los controladores, consultelink:aggregate_relocation_failures.html["Solucionar problemas"] Para obtener más información y posibles soluciones.

Si no encuentra ninguna solución al problema que encontró, póngase en contacto con el soporte técnico.

.El futuro
Después de revisar las directrices para actualizar los controladores con ARL, link:overview_of_the_arl_upgrade.html["conoce la secuencia de actualización de la ARL"].
