---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 'Puede actualizar el hardware de la controladora que ejecuta ONTAP 9.15.1 o posterior mediante `system controller replace` comandos, reubicar la propiedad de agregados no raíz.' 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este procedimiento describe cómo actualizar el hardware de la controladora mediante la reubicación de agregados (ARL) para las siguientes configuraciones del sistema:

[cols="40,20,40"]
|===
| Método | Versión de ONTAP | Sistemas compatibles 


| Uso `system controller replace` comandos | 9.15.1 o posterior | link:decide_to_use_the_aggregate_relocation_guide.html#sys_commands_9151_supported_systems["Enlace a la matriz de sistemas admitidos"] 
|===

NOTE: No puede utilizar este procedimiento para actualizar una configuración de IP o FC de MetroCluster. Para actualizar una configuración de MetroCluster, consulte link:other_references.html["Referencias"] para vincular a la documentación _Actualización y ampliación de MetroCluster_.

Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo y, de este modo, reubicar la propiedad de agregados que no son raíz. Puede migrar agregados varias veces de nodo a nodo para confirmar que al menos un nodo está sirviendo datos desde los agregados a través del procedimiento de actualización. También puede migrar las interfaces lógicas de datos (LIF) y asignar los puertos de red de la nueva controladora a los grupos de interfaces a medida que continúa.

.Terminología utilizada en esta información
En esta información, los nodos originales reciben el nombre de "nodo 1" y "nodo 2", mientras que los nuevos se denominan "nodo 3" y "nodo 4". Durante el procedimiento descrito, el nodo 1 se reemplaza por nodo 3, y el nodo 2 se reemplaza por nodo 4.

Los términos "1", "2", "nodo 3" y "nodo 4" solo se usan para distinguir entre los nodos originales y los nuevos. Cuando siga el procedimiento, deberá sustituir los nombres reales de los nodos originales y los nuevos. Sin embargo, en realidad los nombres de los nodos no cambian: El nodo 3 tiene el nombre 1-nodo y el nodo 4 tiene el nombre 2 después de actualizar el hardware de la controladora.

.Información importante:
* Este procedimiento es complejo y asume que tiene habilidades avanzadas de administración de ONTAP. Usted también debe leer y entender el link:guidelines_for_upgrading_controllers_with_arl.html["Directrices para actualizar controladoras con ARL"] y la link:overview_of_the_arl_upgrade.html["Descripción general de la actualización de ARL"] secciones antes de comenzar la actualización.
* En este procedimiento se asume que el hardware de la controladora de reemplazo es nuevo y no se ha usado. En este procedimiento no se incluyen los pasos necesarios para preparar las controladoras usadas con `wipeconfig` el comando. Debe ponerse en contacto con el soporte técnico si se utilizó previamente el hardware de la controladora de reemplazo.
* Puede usar este procedimiento para actualizar el hardware de la controladora en clústeres con más de dos nodos; sin embargo, debe realizar el procedimiento por separado para cada pareja de alta disponibilidad (ha) del clúster.
* Cuando actualiza a un sistema introducido en ONTAP 9.15.1 o posterior, ONTAP convierte la eficiencia de almacenamiento de los volúmenes existentes y aplica las nuevas funciones de eficiencia del almacenamiento que utilizan la funcionalidad de descarga de hardware. Se trata de un proceso automático en segundo plano, sin impacto visible en el rendimiento del sistema.
+
** Para los sistemas AFF A20, AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60 y AFF C80, ONTAP convierte la eficiencia del almacenamiento de todos los volúmenes Thin Provisioning existentes, incluidos los que no utilizan la eficiencia del almacenamiento.
** Para un sistema FAS70 y FAS90, ONTAP solo convierte la eficiencia del almacenamiento de los volúmenes existentes con Thin-Provisioning que tenían activada la eficiencia del almacenamiento antes de la actualización.


+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["Obtenga más información sobre la eficiencia del almacenamiento"^].

* Los sistemas AFF A20, AFF A50, AFF A70, AFF A90, AFF A1K, FAS70 y FAS90 comparten puertos de red de 100GbE GbE para conexiones de clúster y de alta disponibilidad. Estos sistemas pueden admitir conexiones de clúster 10GbE o 25GbE a switches de clúster heredados; sin embargo, NetApp recomienda actualizar a las velocidades de clúster de 100GbE GbE cuando los switches 10GbE y 25GbE ya no sean necesarios. Para obtener más información, consulte los siguientes artículos de la base de conocimientos:
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Cómo configurar los puertos de clúster 10G o 25G en una nueva configuración de clúster"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Cómo convertir los puertos de clúster 10G o 25G existentes a puertos de clúster 40G o 100g"^]


--
+
El sistema AFF A20 comparte puertos de red 10GbE y 25GbE para las conexiones clúster y de alta disponibilidad. Estas son las únicas conexiones de clúster de puertos de red que admite un sistema AFF A20.

+
Si no puede vincular los puertos de clúster e0a o e0b del nodo existente a los puertos de clúster del nodo nuevo, consulte link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["ID de error de NetApp Bugs Online CONTAP-166978"^].


