---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: 'Preparar los nodos y ejecutar una serie de comprobaciones previas al actualizar las controladoras con ONTAP 9.15.1 o una versión posterior mediante `system controller replace` comandos.' 
---
= Prepare los nodos para la actualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El proceso de reemplazo de la controladora comienza con una serie de comprobaciones previas. También se recopila información sobre los nodos originales para usar más adelante del procedimiento y, si es necesario, determinar el tipo de unidades de cifrado automático que se están usando.

.Pasos
. Inicie el proceso de sustitución de la controladora con el siguiente comando en la línea de comandos de ONTAP:
+
`system controller replace start -nodes <node_names>`

+

NOTE: Solo puede ejecutar el comando system controller replace start en el nivel de privilegio avanzado: `set -privilege advanced`

+
Verá un resultado similar al siguiente ejemplo. La salida muestra la versión de ONTAP que se ejecuta en el clúster:

+
....
Warning: 1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedure.
Do you want to continue? {y|n}: y
....
. Pulse `y`, verá la siguiente salida:
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
El sistema ejecuta las siguientes comprobaciones previas; registre la salida de cada comprobación previa para utilizarla más adelante en el procedimiento:

+
[cols="35,65"]
|===
| Comprobación previa | Descripción 


| Comprobación del estado del clúster | Comprueba todos los nodos del clúster para confirmar que están en buen estado. 


| Comprobación del estado de reubicación de agregados | Comprueba si ya hay una reubicación de agregados en curso. Si hay otra reubicación de agregado en curso, la comprobación falla. 


| Comprobación del nombre del modelo | Comprueba si los modelos de controlador son compatibles con este procedimiento. Si los modelos no son compatibles, la tarea falla. 


| Comprobación de quórum de clúster | Comprueba que los nodos que se van a sustituir tengan quórum. Si los nodos no están en quórum, la tarea falla. 


| Comprobación de la versión de la imagen | Comprueba que los nodos que se reemplazan ejecuten la misma versión de ONTAP. Si las versiones de la imagen ONTAP son diferentes, la tarea fallará. Los nodos nuevos deben tener la misma versión de ONTAP 9.x instalada en ellos que se haya instalado en los nodos originales. Si los nodos nuevos tienen instalada una versión diferente de ONTAP, debe reiniciar el sistema las controladoras nuevas después de instalarlas. Para obtener instrucciones sobre cómo actualizar ONTAP, consulte link:other_references.html["Referencias"] Para enlazar a _Upgrade ONTAP_. 


| Comprobación de estado de HA | Comprueba si los dos nodos que se van a reemplazar se encuentran en una configuración de parejas de alta disponibilidad. Si no está habilitada la conmutación por error del almacenamiento para las controladoras, la tarea falla. 


| Comprobación del estado del agregado | Si los nodos que se van a sustituir tienen agregados propios para los que no son el propietario principal, la tarea fallará. Los nodos no deben tener ningún agregado que no sea local. 


| Comprobación del estado del disco | Si alguno de los nodos que se van a reemplazar tiene discos ausentes o con errores, la tarea falla. Si falta algún disco, consulte link:other_references.html["Referencias"]el enlace a _Disk and Aggregate management con CLI_, _Logical storage management con CLI_ y _HA pair management_ para configurar el almacenamiento para la pareja de alta disponibilidad. 


| Comprobación del estado de LIF de datos | Comprueba si alguno de los nodos que se van a reemplazar tiene LIF de datos no locales. Los nodos no deben contener ninguna LIF de datos para la cual no sean el propietario principal. Si uno de los nodos contiene LIF de datos no locales, la tarea falla. 


| Estado de LIF del clúster | Comprueba si los LIF del clúster están activos para ambos nodos. Si las LIF del clúster están inadas, la tarea falla. 


| Comprobación del estado de ASUP | Si no se configuran las notificaciones de ASUP, la tarea falla. Debe habilitar ASUP antes de iniciar el procedimiento de reemplazo de controladora. 


| Comprobación del uso de CPU | Comprueba si el uso de CPU es superior al 50 % en el caso de cualquiera de los nodos que se van a sustituir. Si el uso de CPU es superior al 50 % durante un período de tiempo considerable, la tarea falla. 


| Comprobación de reconstrucción de agregados | Comprueba si la reconstrucción se está produciendo en algún agregado de datos. Si la reconstrucción del agregado está en curso, la tarea falla. 


| Comprobación de trabajo de afinidad de nodo | Comprueba si se están ejecutando trabajos de afinidad de nodos. Si se están ejecutando trabajos de afinidad de nodo, la comprobación falla. 
|===
. Una vez iniciada la operación de sustitución de la controladora y que se completen las comprobaciones previas, la operación se coloca en pausa para recoger información de resultado que se pueda necesitar más adelante al configurar el nodo 3.
+
[NOTE]
====
Antes de iniciar la actualización, migra y vuelve a alojar los LIF de clúster en dos puertos de clúster por nodo si tiene un sistema, como un AFF 700, con la siguiente configuración:

** Más de dos puertos de clúster por nodo
** Una tarjeta de interconexión de clúster en slot4 en modo de partición para crear los puertos E4A, e4b, e4c y e4d, y los puertos E4E, e4f, e4g y e4h


Si se realiza una actualización de la controladora con más de dos puertos de clúster por nodo, es posible que falten LIF de clúster en la nueva controladora después de la actualización.

Para obtener más información, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["Cómo eliminar LIF de clúster no deseadas o innecesarias"^].

====
. Ejecute el siguiente conjunto de comandos según lo indicado por el procedimiento de reemplazo de la controladora en la consola del sistema.
+
Desde el puerto serie conectado a cada nodo, ejecute y guarde el resultado de los siguientes comandos de forma individual:

+
** `vserver services name-service dns show`
** `network interface show -curr-node <local> -role <cluster,intercluster,node-mgmt,cluster-mgmt,data>`
** `network port show -node <local> -type physical`
** `service-processor show -node <local> -instance`
** `network fcp adapter show -node <local>`
** `network port ifgrp show -node <local>`
** `system node show -instance -node <local>`
** `run -node <local> sysconfig`
** `storage aggregate show -r`
** `storage aggregate show -node <local>`
** `volume show -node <local>`
** `system license show -owner <local>`
** `storage encryption disk show`
** `security key-manager onboard show-backup`
** `security key-manager external show`
** `security key-manager external show-status`
** `network port reachability show -detail -node <local>`


+

NOTE: Si se está utilizando el cifrado de volúmenes de NetApp (NVE) o el cifrado de agregado de NetApp (NAE) con el gestor de claves incorporado (OKM), mantenga la frase de acceso del administrador de claves preparada para completar el administrador de claves para resincronizar más adelante en el procedimiento.

. Si su sistema utiliza unidades de autocifrado, consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Cómo saber si una unidad tiene la certificación FIPS"^] Para determinar el tipo de unidades de autocifrado que se están utilizando en la pareja de alta disponibilidad que se está actualizando. El software ONTAP admite dos tipos de unidades de autocifrado:
+
--
** Unidades SAS o NVMe con cifrado en almacenamiento de NetApp (NSE) certificado FIPS
** Unidades NVMe (SED) con autocifrado no FIPS


https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["Obtenga más información sobre las unidades de autocifrado compatibles"^].

--




== Corrija la propiedad del agregado si fallan las comprobaciones previas de ARL

Si falla la comprobación del estado del agregado, debe devolver los agregados propiedad del nodo asociado al nodo propietario principal e iniciar de nuevo el proceso de comprobaciones previas.

.Pasos
. Devolver los agregados que actualmente pertenecen al nodo asociado al nodo propietario principal:
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. Compruebe que ni el nodo 1 ni el nodo 2 siguen teniendo agregados cuyos propietarios son actualmente (pero no el propietario del hogar):
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
En el ejemplo siguiente se muestra el resultado del comando cuando un nodo es al mismo tiempo el propietario actual y el propietario principal de los agregados:

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== Después de terminar

Debe reiniciar el proceso de sustitución de la controladora:

`system controller replace start -nodes _node_names_`



== Licencia

Si quiere información detallada sobre las licencias de ONTAP, consulte https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["Gestión de licencias"^].


NOTE: El uso de funciones sin licencia en la controladora puede provocar que no cumpla el contrato de licencia.
