---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/prepare_for_netboot.html 
keywords: preparing, netboot, ndac, ontap 
summary: 'Prepare el nodo 3 y el nodo 4 para reiniciar controladoras que ejecutan ONTAP 9.8 o una versión posterior mediante `system controller replace` comandos.' 
---
= Prepárese para el arranque desde el red
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Después de montar físicamente en rack los nodos 3 y 4 posteriormente en el procedimiento, es posible que deba volver a arrancar. El término "reiniciar el sistema" significa que se inicia desde una imagen ONTAP almacenada en un servidor remoto. Cuando se prepara para el arranque por red, se coloca una copia de la imagen de arranque de ONTAP 9 en un servidor web al que el sistema pueda acceder.

También puede utilizar la opción de arranque USB para realizar un arranque desde el sistema. Consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_boot_recovery_LOADER_command_for_installing_ONTAP_for_initial_setup_of_a_system["Cómo utilizar el comando boot_recovery LOADER para instalar ONTAP para la configuración inicial de un sistema"^].

.Antes de empezar
* Compruebe que puede acceder a un servidor HTTP con el sistema.
* Consulte link:other_references.html["Referencias"] Para crear un enlace al _sitio de soporte de NetApp_ y descargar los archivos del sistema necesarios para su plataforma y la versión correcta de ONTAP.


.Acerca de esta tarea
Debe reiniciar el sistema de las controladoras nuevas si no tienen la misma versión de ONTAP 9 instalada en ellas que se instala en las controladoras originales. Tras instalar cada controladora nueva, arranque el sistema desde la imagen de ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema.

.Pasos
. Acceda al sitio de soporte de NetApp para descargar los archivos utilizados para realizar el arranque desde el sistema.
. Descargue el software ONTAP adecuado de la sección de descarga de software del sitio de soporte de NetApp y almacene el `<ontap_version>_image.tgz` archivo en un directorio accesible a través de la web.
. Cambie al directorio accesible a la Web y compruebe que los archivos que necesita están disponibles.
+
La lista de directorios debe contener el siguiente archivo:
`<ontap_version>_image.tgz`

+

NOTE: No es necesario extraer el contenido del `<ontap_version>_image.tgz` archivo.

+
Utilizará la información de los directorios en link:install_boot_node3.html["Etapa 3"].


