---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/reboots_panics_or_power_cycles.html 
keywords: reboots, panics, power, cycles, node, crash 
summary: 'El sistema podría bloquearse: Reinicio, alarma o pasar por un ciclo de encendido y apagado: Durante diferentes etapas cuando se actualizan las controladoras que ejecutan ONTAP 9.15.1 o posterior con `system controller replace` comandos.' 
---
= Reinicios, pánicos o ciclos de alimentación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se puede bloquear el sistema: Reinicio, alarma o interrupción de un ciclo de encendido, durante las diferentes etapas de la actualización.

La solución a estos problemas depende de cuándo se produzcan.



== Se reinicia, produce un pánico o se enciende durante la fase de comprobación previa



=== Los nodos 1 o 2 se bloquean antes de la fase de comprobación previa con el par de alta disponibilidad, aún habilitado

Si el nodo 1 o el nodo 2 se bloquean antes de la fase de comprobación previa, aún no se han reubicado agregados y la configuración de pares de alta disponibilidad está habilitada.

.Acerca de esta tarea
La toma de control y la devolución pueden proceder con normalidad.

.Pasos
. Compruebe la consola para ver los mensajes de EMS que el sistema podría haber emitido y realice la acción correctiva recomendada.
. Continúe con el procedimiento de actualización de la pareja de nodos.




== Los reinicios, los pánicos o los ciclos de encendido y apagado durante la primera fase de la versión de recursos



=== El nodo 1 se bloquea durante la primera fase del lanzamiento de recursos con el par de alta disponibilidad todavía habilitado

Algunos o todos los agregados se han reubicado del nodo 1 al nodo 2 y el par de alta disponibilidad sigue estando habilitado. El nodo 2 toma el volumen raíz del nodo 1 y todos los agregados que no sean raíz en la ubicación.

.Acerca de esta tarea
La propiedad de los agregados que se reubicaron tiene el mismo aspecto que la propiedad de los agregados no raíz que se tomaron el control porque el propietario de la casa no ha cambiado.

Cuando el nodo 1 entra en el `waiting for giveback` estado, el nodo 2 devuelve todos los agregados del nodo 1 que no son raíz.

.Pasos
. Después de arrancar el nodo 1, todos los agregados que no son raíz del nodo 1 se han movido de nuevo al nodo 1. Debe ejecutar una reubicación manual de agregados de los nodos 1 a 2:
`storage aggregate relocation start -node node1 -destination node2 -aggregate -list * -ndocontroller-upgrade true`
. Continúe con el procedimiento de actualización de la pareja de nodos.




=== El nodo 1 se bloquea durante la primera fase de lanzamiento de recursos mientras se deshabilita el par de alta disponibilidad

El nodo 2 no toma el relevo, pero intenta servir datos en todos los agregados que no son raíz.

.Pasos
. Coloque el nodo 1.
. Continúe con el procedimiento de actualización de la pareja de nodos.




=== Se produce un error en el nodo 2 durante la primera fase de lanzamiento de recursos con el par de alta disponibilidad, de todos modos habilitado

El nodo 1 ha reubicado algunos de sus agregados, o todos ellos, al nodo 2. La pareja de alta disponibilidad está habilitada.

.Acerca de esta tarea
El nodo 1 asume todos los agregados del nodo 2, así como todos sus propios agregados, que se habían reubicado en el nodo 2. Cuando el nodo 2 arranca, la reubicación de agregados se completa automáticamente.

.Pasos
. Sube el 2.
. Continúe con el procedimiento de actualización de la pareja de nodos.




=== El nodo 2 se bloquea en la primera fase de lanzamiento de recursos y después de que se deshabilita el par de alta disponibilidad

El nodo 1 no toma el control.

.Pasos
. Sube el 2.
+
Se produce una interrupción del servicio del cliente en todos los agregados, mientras que el nodo 2 arranca.

. Continúe con el resto del procedimiento de actualización de la pareja de nodos.




== Reinicia, produce un pánico o ciclos de encendido durante la primera fase de verificación



=== El nodo 2 se bloquea en la primera fase de verificación con el par de alta disponibilidad deshabilitado

El nodo 3 no retoma después de un bloqueo del nodo 2, ya que la pareja de alta disponibilidad ya está deshabilitada.

.Pasos
. Sube el 2.
+
Se produce una interrupción del servicio del cliente en todos los agregados, mientras que el nodo 2 arranca.

. Continúe con el procedimiento de actualización de la pareja de nodos.




=== El nodo 3 se bloquea durante la primera fase de verificación con la pareja de alta disponibilidad deshabilitada

El nodo 2 no toma el relevo, pero intenta servir datos en todos los agregados que no son raíz.

.Pasos
. Traiga el nodo 3.
. Continúe con el procedimiento de actualización de la pareja de nodos.




== Reinicios, pánicos o ciclos de alimentación durante la primera fase de recuperación de recursos



=== El nodo 2 se bloquea durante la primera fase de recuperación de recursos durante la reubicación de agregados

El nodo 2 ha reubicado algunos o todos sus agregados del nodo 1 al nodo 3. El nodo 3 proporciona datos de agregados que se reubicaron. El par de alta disponibilidad está deshabilitado y, por lo tanto, no hay toma de control.

.Acerca de esta tarea
Hay una interrupción del cliente para los agregados que no se han reubicado. Cuando el nodo de arranque del nodo 2, los agregados del nodo 1 se reubican en nodo 3.

.Pasos
. Sube el 2.
. Continúe con el procedimiento de actualización de la pareja de nodos.




=== El nodo 3 se bloquea durante la primera fase de recuperación de recursos durante la reubicación de agregados

Si el nodo 3 se bloquea mientras el nodo 2 se reubica los agregados en el nodo 3, la tarea continúa después de que se arranca el nodo 3.

.Acerca de esta tarea
El nodo 2 sigue sirviendo agregados restantes, pero los agregados que ya se reubicaron en nodo 3 se encuentran en una interrupción de cliente, mientras que el nodo 3 se inicia.

.Pasos
. Traiga el nodo 3.
. Continúe con la actualización de la controladora.




== Reinicios, pánicos o ciclos de alimentación durante la fase posterior a la comprobación



=== El nodo 2 o 3 se bloquea durante la fase de comprobación posterior

El par de alta disponibilidad está deshabilitado, por lo que no se toma el control. Hay una interrupción del cliente para los agregados que pertenecen al nodo que se reinició.

.Pasos
. Suba el nodo.
. Continúe con el procedimiento de actualización de la pareja de nodos.




== Reinicios, pánicos o ciclos de encendido durante la segunda fase de lanzamiento de recursos



=== El nodo 3 se bloquea durante la segunda fase de versión de recursos

Si el nodo 3 se bloquea mientras el nodo 2 está reubicando agregados, la tarea continuará después de que se arranque el nodo 3.

.Acerca de esta tarea
El nodo 2 sigue sirviendo agregados restantes, pero los agregados que ya se reubicaron en los agregados de nodo 3 y los propios de nodo 3 se encuentran en situación de interrupción del servicio del cliente, mientras que el nodo 3 se inicia.

.Pasos
. Traiga el nodo 3.
. Continúe con el procedimiento de actualización de la controladora.




=== El nodo 2 se bloquea durante la segunda fase de publicación de recursos

Si el nodo 2 se bloquea durante la reubicación de agregados, el nodo 2 no se retoma.

.Acerca de esta tarea
El nodo 3 sigue sirviendo los agregados que se reubicaron, pero los agregados propiedad del nodo 2 encuentran las interrupciones de servicio del cliente.

.Pasos
. Sube el 2.
. Continúe con el procedimiento de actualización de la controladora.




== Reinicia, produce un pánico o ciclos de encendido durante la segunda fase de verificación



=== El nodo 3 se bloquea durante la segunda fase de verificación

Si el nodo 3 se bloquea durante esta fase, la toma de control no se produce porque la pareja de alta disponibilidad ya está deshabilitada.

.Acerca de esta tarea
Hay una interrupción del servicio del cliente de todos los agregados hasta que se reinicia el nodo 3.

.Pasos
. Traiga el nodo 3.
. Continúe con el procedimiento de actualización de la pareja de nodos.




=== Node4 se bloquea durante la segunda fase de verificación

Si el nodo 4 se bloquea durante esta fase, la toma de control no se produce. El nodo 3 proporciona datos de los agregados.

.Acerca de esta tarea
Existe una interrupción del servicio de los agregados que no son raíz que ya se removieron hasta reinicios de nodo 4.

.Pasos
. Traiga el nodo 4.
. Continúe con el procedimiento de actualización de la pareja de nodos.

