---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/relocate_failed_or_vetoed_aggr.html 
keywords: relocating, failed, vetoed, aggregates, relocation, operation 
summary: 'Reubicar manualmente agregados con errores o vetados al actualizar controladoras con ONTAP 9.15.1 o posterior mediante `system controller replace` comandos.' 
---
= Se han producido fallos en la reubicación o los agregados vetados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si alguno de los agregados no se puede reubicar o vetar, debe reubicar los agregados manualmente o, si es necesario, anular los vetos o las comprobaciones de destino.

.Acerca de esta tarea
La operación de reubicación se pondrá en pausa debido al error.

.Pasos
. Compruebe los registros del sistema de gestión de eventos (EMS) para determinar por qué no se ha podido reubicar o vetar el agregado.
. Reubicar agregados que fallen o vetados:
+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr_name_ -ndo-controller-upgrade true`

. Cuando se le solicite, introduzca `y`.
. Puede forzar la reubicación mediante uno de los siguientes métodos:
+
[cols="35,65"]
|===
| Opción | Descripción 


| Anulación de las comprobaciones de veto | Utilice el siguiente comando:
`storage aggregate relocation start -node node1 -destination node2 -aggregate-list _aggr_list_ -ndo-controller-upgrade true -override-vetoes true` 


| Sobreescribir comprobaciones de destino | Utilice el siguiente comando:
`storage aggregate relocation start -node node1 -destination node2 -aggregate-list _aggr_list_ -ndo-controller-upgrade true -override-vetoes true -override-destination-checks true` 
|===

