---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: 'Almacenar en zona intermedia la secuencia de proceso 6 para una actualización de ARL mediante `system controller replace` comandos en controladoras que ejecutan ONTAP 9.15.1 o posterior.' 
---
= Descripción general de la etapa 6
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 6, el usuario confirma que los nodos nuevos están configurados correctamente y, si los nodos nuevos tienen la función de cifrado habilitada, se configuran y se configuran el cifrado de almacenamiento o el cifrado de volúmenes de NetApp. También debe retirar los nodos antiguos y reanudar las operaciones de SnapMirror.

.Pasos
. link:manage-authentication-using-kmip-servers.html["Gestionar la autenticación mediante servidores KMIP"]
. link:ensure_new_controllers_are_set_up_correctly.html["Confirmar que las nuevas controladoras están configuradas correctamente"]
. link:set_up_storage_encryption_new_module.html["Configure Storage Encryption en el nuevo módulo de la controladora"]
. link:set_up_netapp_volume_encryption_new_module.html["Configure el cifrado de volúmenes de NetApp o el cifrado de agregados en el nuevo módulo de la controladora"]
. link:decommission_old_system.html["Retire el sistema antiguo"]
. link:resume_snapmirror_operations.html["Reanudar las operaciones de SnapMirror"]


[NOTE]
====
Los sistemas AFF A70, AFF A90, AFF A1K, FAS70 y FAS90 comparten puertos de red de 100GbE GbE para conexiones de clúster y de alta disponibilidad. Estos sistemas pueden admitir conexiones de clúster 10GbE o 25GbE a switches de clúster heredados; sin embargo, NetApp recomienda actualizar a las velocidades de clúster de 100GbE GbE cuando los switches 10GbE y 25GbE ya no sean necesarios. Para obtener más información, consulte los siguientes artículos de la base de conocimientos:

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Cómo configurar los puertos de clústeres 10G o 25G en una nueva configuración de clúster en AFF/ASA A1K, A90, A70, FAS90 y FAS70"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["Cómo convertir un clúster existente de puertos de clúster 10G o 25G a puertos de clúster 40G o 100g en un AFF/ASA A1K, FAS70, A70, FAS90, A90"^]


Si no puede vincular los puertos de clúster e0a o e0b del nodo existente a los puertos de clúster del nodo nuevo, consulte link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["ID de error de NetApp Bugs Online CONTAP-166978"^].

====