---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_2_index.html 
keywords: relocating, retiring, node1, lif, stage 2 
summary: 'Almacenar en zona intermedia la secuencia de proceso 2 para una actualización de ARL mediante `system controller replace` comandos en controladoras que ejecutan ONTAP 9.15.1 o posterior.' 
---
= Descripción general de la etapa 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 2, debe reubicar agregados no raíz y LIF de datos NAS al nodo 1 en el nodo 2. Este proceso está en gran medida automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Si es necesario, reubique los agregados que han fallado o que han vetado. También registra la información necesaria de node1, retira node1 y prepara netboot node3 y node4 más adelante en el procedimiento.

.Pasos
. link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["Reubique los agregados que no son raíz y los LIF de datos NAS que pertenecen al nodo 1 al nodo 2"]
. link:relocate_failed_or_vetoed_aggr.html["Se han producido fallos en la reubicación o los agregados vetados"]
. link:retire_node1.html["Retire el nodo 1"]
. link:prepare_for_netboot.html["Prepárese para el arranque desde el red"]

