---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_3_index.html 
keywords: installing, booting, node3, install, cluster, stage 3 
summary: 'Almacenar en zona intermedia la secuencia de proceso 3 para una actualización de ARL mediante `system controller replace` comandos en controladoras que ejecutan ONTAP 9.15.1 o posterior.' 
---
= Descripción general de la etapa 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 3, debe instalar y arrancar el nodo 3, compruebe que los puertos de gestión del nodo y del clúster del nodo 1 estén en línea en el nodo 3 y verifique la instalación del nodo 3. Si utiliza el cifrado de volúmenes de NetApp (NVE), debe restaurar la configuración del gestor de claves. También se deben reubicar los LIF de datos NAS del nodo 1 y los agregados no raíz del nodo 2 al nodo 3, y verificar que las LIF SAN existan en el nodo 3.

.Pasos
. link:install_boot_node3.html["Instale y arranque el nodo 3"]
. link:verify_node3_installation.html["Verifique la instalación del nodo 3"]
. link:restore_key-manager_configuration_node3.html["Restaure la configuración de gestor de claves en el nodo 3"]
. link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["Mueva agregados que no son raíz y LIF de datos NAS que pertenecen al nodo 1 del nodo 2 al nodo 3"]

