---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Almacenar en zona intermedia la secuencia de proceso 5 para una actualización de ARL mediante `system controller replace` comandos en controladoras que ejecutan ONTAP 9.15.1 o posterior.' 
---
= Descripción general de la etapa 5
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 5, debe instalar y arrancar el nodo 4, compruebe que los puertos de gestión del clúster y de los nodos del nodo 2 estén en línea en el nodo 4 y verifique la instalación del nodo 4. Si utiliza NVE, debe restaurar la configuración del gestor de claves. También se deben reubicar los LIF de datos NAS 2 y los agregados no raíz de nodo 3 a nodo 4, y verificar que las LIF SAN existan en el nodo 4.

.Pasos
. link:install_boot_node4.html["Instale y arranque el nodo 4"]
. link:verify_node4_installation.html["Verifique la instalación del nodo 4"]
. link:restore_key-manager_config_node4.html["Restaure la configuración de gestor de claves en el nodo 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Mueva agregados no raíz y LIF de datos NAS que pertenecen al nodo 2 desde el nodo 3 al nodo 4"]

