---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node3.html 
keywords: install, boot, node3 relocation, nodes, V-series, storage disks 
summary: 'Instale y arranque el nodo 3 e instale el software ONTAP cuando actualice controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Instale y arranque el nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe instalar el nodo 3 en el rack, transferir las conexiones del nodo 1 al nodo 3, al nodo de arranque 3 e instalar ONTAP. Después, debe reasignar cualquiera de los discos de repuesto del nodo 1, todos los discos que pertenezcan al volumen raíz y todos los agregados que no sean raíz que no se hayan reubicado al nodo 2 anteriormente en el proceso, como se explica en esta sección.

.Acerca de esta tarea
La operación de reubicación se detiene al principio de esta etapa. Este proceso está en gran medida automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Además, es necesario verificar que las LIF SAN se hayan movido correctamente al nodo 3.

Es necesario reiniciar el nodo 3 si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 1. Después de instalar el nodo 3, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema, siguiendo las instrucciones en link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

.Importante:
* Si va a actualizar un sistema V-Series conectado a cabinas de almacenamiento o un sistema con el software de virtualización de FlexArray conectado a cabinas de almacenamiento, debe completar <<auto_install3_step1,Paso 1>> por <<auto_install3_step21,Paso 21>>, luego salga de esta sección y siga las instrucciones de la link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] Secciones según sea necesario, introducir comandos en modo de mantenimiento. A continuación, debe volver a esta sección y reanudar con <<auto_install3_step23,Paso 23>>.
* Si va a actualizar un sistema con discos de almacenamiento, debe completar esta sección completa y, a continuación, ir a la link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] secciones, introducir comandos en el símbolo del sistema del clúster.


.Pasos
. [[auto_install3_step1]]Asegúrese de que dispone de espacio en rack para el nodo 3.
+
Si los nodos 1 y 2 están en un chasis separado, puede colocar el nodo 3 en la misma ubicación de rack que el nodo 1. Sin embargo, si el nodo 1 estaba en el mismo chasis con el nodo 2, debe poner el nodo 3 en su propio espacio de rack, preferiblemente cerca de la ubicación del nodo 1.

. [[auto_install3_step2]]instale el nodo 3 en el rack siguiendo las _instrucciones de instalación y configuración_ del modelo de nodo.
+

NOTE: Si va a actualizar a un sistema con ambos nodos del mismo chasis, instale el nodo 4 en el chasis y el nodo 3. Si no se hace, cuando se arranca el nodo 3, el nodo se comportará como si fuera en una configuración de doble chasis, y cuando se arranca el nodo 4, la interconexión entre los nodos no se iniciará.

. [[auto_install3_step3]]nodo de cable 3, moviendo las conexiones del nodo 1 al nodo 3.
+
Conecte los cables de las siguientes conexiones utilizando las _instrucciones de instalación y configuración_ o los requisitos y referencias_ de la instalación de la virtualización FlexArray para la plataforma node3, el documento de bandeja de discos correspondiente y _Gestión de alta disponibilidad_.

+
Consulte link:other_references.html["Referencias"] Para enlazar con _FlexArray Virtualization Installation requisitos y Reference_ y _High Availability Management_.

+
** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC
+

NOTE: Es posible que no sea necesario mover la tarjeta de interconexión o la conexión del cable de interconexión del clúster del nodo 1 al nodo 3, ya que la mayoría de los modelos de plataforma tienen un modelo de tarjeta de interconexión único. Para la configuración MetroCluster, es necesario mover las conexiones de cables FC-VI del nodo 1 al nodo 3. Si el host nuevo no tiene una tarjeta FC-VI, puede que necesite mover la tarjeta FC-VI.



. [[auto_install3_step4]]Active la alimentación del nodo 3 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al indicador de entorno de arranque.
+
Si va a actualizar a un sistema con ambos nodos del mismo chasis, el nodo 4 también se reinicia. Sin embargo, es posible ignorar el arranque de nodo 4 hasta más adelante.

+

NOTE: Cuando se arranca el nodo 3, es posible que se muestre el siguiente mensaje de advertencia:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]Si aparece el mensaje de advertencia en <<auto_install3_step4,Paso 4>>, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

WARNING: *Atención: No anular el retardo; si no se permite que la batería se cargue, se podrían producir pérdidas de datos.*

+

NOTE: Consulte link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].





. [[auto9597_istall3_step6]]Configure la conexión netboot eligiendo una de las siguientes acciones.
+

NOTE: Se deben utilizar el puerto e IP de gestión como conexión para reiniciar el sistema. No utilice una IP de LIF de datos ni una interrupción del servicio de datos mientras se realiza la actualización.

+
[cols="30,70"]
|===
| Si el protocolo de configuración dinámica de hosts (DHCP) es... | Realice lo siguiente... 


| Ejecutando | Configure la conexión automáticamente introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -auto` 


| No se está ejecutando  a| 
Configure manualmente la conexión introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Es la dirección IP del sistema de almacenamiento (obligatorio).
`_netmask_` es la máscara de red del sistema de almacenamiento (obligatoria).
`_gateway_` es la puerta de enlace del sistema de almacenamiento. (obligatorio).
`_dns_addr_` Es la dirección IP de un servidor de nombres en la red (opcional).
`_dns_domain_` Es el nombre de dominio del servicio de nombres de dominio (DNS). Si utiliza este parámetro opcional, no necesita un nombre de dominio completo en la URL del servidor para reiniciar el sistema; solo necesita el nombre de host del servidor.


NOTE: Es posible que sean necesarios otros parámetros para la interfaz. Introduzca `help ifconfig` en el símbolo del sistema del firmware para obtener detalles.

|===
. [[step7]]lleve a cabo netboot en el nodo 3:
+
[cols="30,70"]
|===
| Durante... | Realice lo siguiente... 


| Sistemas de la serie FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Todos los demás sistemas | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
La `<path_to_the_web-accessible_directory>` debería conducir al lugar en el que se ha descargado el `<ontap_version>_image.tgz` en la sección link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

+

NOTE: No interrumpa el arranque.

. [[paso8]]en el menú de inicio, seleccione la opción `(7) Install new software first`.
+
Esta opción del menú descarga e instala la nueva imagen de ONTAP en el dispositivo de arranque.

+
Ignore el siguiente mensaje:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota se aplica a las actualizaciones no disruptivas de ONTAP, no a las actualizaciones de controladoras.

+

NOTE: Utilice siempre netboot para actualizar el nodo nuevo a la imagen deseada. Si utiliza otro método para instalar la imagen en la nueva controladora, podría instalarse la imagen incorrecta. Este problema se aplica a todas las versiones de ONTAP. El procedimiento para reiniciar el sistema combinado con la opción `(7) Install new software` Limpia el soporte de arranque y coloca la misma versión ONTAP en ambas particiones de imagen.

. [[step9]]Si se le solicita continuar con el procedimiento, introduzca `y`, Y cuando se le solicite el paquete, escriba la dirección URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]]lleve a cabo los siguientes pasos para reiniciar el módulo del controlador:
+
.. Introduzca `n` para omitir la recuperación del backup cuando aparezca la siguiente solicitud:
+
`Do you want to restore the backup configuration now? {y|n}`

.. Introduzca `y` para reiniciar cuando vea el siguiente aviso:
+
`The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}`

+
El módulo del controlador se reinicia pero se detiene en el menú de inicio porque el dispositivo de arranque se ha reformateado y los datos de configuración deben restaurarse.



. [[step11]]Seleccione el modo de mantenimiento `5` desde el menú de inicio y entrar `y` cuando se le pida que continúe con el arranque.
. [[step12]]Compruebe que la controladora y el chasis están configurados como ha:
+
`ha-config show`

+
En el siguiente ejemplo, se muestra el resultado del `ha-config show` comando:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: El sistema graba en una PROM tanto si se encuentran en un par ha como en una configuración independiente. El estado debe ser el mismo en todos los componentes del sistema independiente o del par de alta disponibilidad.

. [[step13]]Si la controladora y el chasis no están configurados como ha, utilice los siguientes comandos para corregir la configuración:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si tiene una configuración MetroCluster, utilice los siguientes comandos para modificar la controladora y el chasis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[step14]]salir del modo de mantenimiento:
+
`halt`

+
Interrumpa el AUTOBOOT pulsando Ctrl-C en el prompt del entorno de arranque.

. [[step15]]en el nodo 2, compruebe la fecha, hora y zona horaria del sistema:
+
`date`

. [[step16]]en el nodo 3, compruebe la fecha utilizando el siguiente comando en el indicador de entorno de arranque:
+
`show date`

. [[step17]]Si es necesario, establezca la fecha en node3:
+
`set date _mm/dd/yyyy_`

. [[step18]]en el nodo 3, compruebe la hora utilizando el siguiente comando del símbolo del sistema del entorno de arranque:
+
`show time`

. [[step19]]Si es necesario, establezca la hora en node3:
+
`set time _hh:mm:ss_`

. [[step20]]en el cargador de arranque, configure el ID del sistema asociado en el nodo 3:
+
`setenv partner-sysid _node2_sysid_`

+
Para nodo 3, `partner-sysid` debe ser del nodo 2.

+
.. Guarde los ajustes:
+
`saveenv`



. [[auto_install3_step21]]Compruebe el `partner-sysid` para el nodo 3:
+
`printenv partner-sysid`

. [[step22]]realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si su sistema... | Descripción 


| Cuenta con discos y sin almacenamiento de gestión | Vaya a. <<auto_install3_step23,Paso 23>> 


| Es un sistema V-Series o un sistema con software de virtualización FlexArray conectado a cabinas de almacenamiento  a| 
.. Vaya a la sección link:set_fc_or_uta_uta2_config_on_node3.html["Configurar la configuración de FC o UTA/UTA2 en el nodo 3"] y completar las subsecciones de esta sección.
.. Vuelva a esta sección y complete los pasos restantes, empezando por <<auto_install3_step23,Paso 23>>.



IMPORTANT: Debe volver a configurar los puertos integrados de FC, los puertos CNA integrados y las tarjetas CNA antes de iniciar ONTAP en el sistema V-Series o con el software de virtualización FlexArray.

|===
. [[auto_install3_step23]]Añada los puertos iniciadores FC del nuevo nodo a las zonas del switch.
+
Si su sistema tiene UNA SAN de cinta, debe dividir en zonas para los iniciadores. Si es necesario, modifique los puertos internos al iniciador en la link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configurar puertos FC en el nodo 3"]. Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener más instrucciones sobre la división en zonas.

. [[step24]]Añada los puertos iniciadores FC a la cabina de almacenamiento como hosts nuevos, asignando las LUN de cabina a los nuevos hosts.
+
Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. [[step25]]modifique los valores de nombre de puerto WWPN en el host o los grupos de volúmenes asociados con las LUN de cabina en la cabina de almacenamiento.
+
La instalación de un módulo de controladora nuevo cambia los valores de WWPN asociados con cada puerto FC integrado.

. [[step26]]Si su configuración utiliza la división en zonas basada en switches, ajuste la división en zonas para reflejar los nuevos valores de WWPN.


. Si tiene unidades de cifrado de almacenamiento de NetApp (NSE) instaladas, siga estos pasos.
+

NOTE: Si aún no lo ha hecho anteriormente en el procedimiento, consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Cómo saber si una unidad tiene la certificación FIPS"^] para determinar el tipo de unidades de autocifrado que están en uso.

+
.. Configurado `bootarg.storageencryption.support` para `true` o. `false`:
+
[cols="35,65"]
|===
| Si están en uso las siguientes unidades... | Entonces… 


| Unidades NSE que cumplen con los requisitos de autocifrado de FIPS 140-2 de nivel 2 | `setenv bootarg.storageencryption.support *true*` 


| SED de NetApp no con FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad. Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.

====
.. Póngase en contacto con el soporte de NetApp para obtener ayuda para restaurar la información sobre la gestión de claves incorporada.


. Nodo de arranque en el menú de arranque:
+
`boot_ontap menu`

+
Si no dispone de una configuración FC o UTA/UTA2, lleve a cabo link:set_fc_or_uta_uta2_config_node4.html#auto_check_4_step15["Comprobar y configurar los puertos UTA/UTA2 en el nodo 4, paso 15"] de modo que el nodo 4 puede reconocer los discos del nodo 2.

. [[auto9597_istall3_step29]]para una configuración MetroCluster, sistemas y sistemas V-Series con software de virtualización FlexArray conectado a matrices de almacenamiento, vaya a. link:set_fc_or_uta_uta2_config_on_node3.html#auto9597_check_node3_step15["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3, paso 15"].

