---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: 'Instale y arranque el nodo 4 e instale el software ONTAP cuando actualice controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Instale y arranque el nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe instalar el nodo 4 en el rack, transferir las conexiones 2 al nodo 4, el nodo de arranque 4 e instalar ONTAP. Luego, debe reasignar todos los discos de repuesto en el nodo 2, todos los discos que pertenezcan al volumen raíz y todos los agregados que no sean raíz que no se hayan reubicado en nodo 3 anteriormente en el proceso, como se explica en esta sección.

.Acerca de esta tarea
La operación de reubicación se detiene al principio de esta etapa. Este proceso está prácticamente automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Además, debe verificar que las LIF de datos NAS se hayan movido correctamente al nodo 4.

Es necesario reiniciar el nodo 4 si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 2. Después de instalar el nodo 4, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema, siguiendo las instrucciones en link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

[IMPORTANT]
====
* Para actualizar un controlador AFF A800 o AFF C800 , debe asegurarse de que todas las unidades en el chasis estén firmemente asentadas contra el plano medio antes de quitar el nodo 2. Para obtener más información, consulte link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Sustituya los módulos del controlador AFF A800 o AFF C800"].
* Si está actualizando un sistema con discos de almacenamiento, debe completar toda esta sección y luego continuar. link:set_fc_or_uta_uta2_config_node4.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 4"] , ingresando comandos en el indicador del clúster.


====
.Pasos
. [[auto_install4_step1]]Asegúrese de que el nodo 4 tenga suficiente espacio en rack.
+
Si el nodo 4 se encuentra en un chasis separado del nodo 2, es posible colocar el nodo 4 en la misma ubicación que el nodo 3. Si el nodo 2 y el nodo 4 están en el mismo chasis, el nodo 4 ya se encuentra en la ubicación de rack adecuada.

. Instale el nodo 4 en el rack, siguiendo las instrucciones de _Installation and Setup_ para el modelo de nodo.
. Cablee el nodo 4, mueva las conexiones del nodo 2 al nodo 4.
+
Conecte las siguientes conexiones utilizando las _Instrucciones de instalación y configuración_ para la plataforma node4, el documento de estante de discos apropiado y la documentación de _Administración de pares HA_.

+
Referirse alink:other_references.html["Referencias"] para vincular a la _gestión de pares HA_.

+
** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC
+

NOTE: Es posible que no sea necesario mover la conexión de cable de la tarjeta de interconexión/tarjeta FC-VI del nodo 2 al nodo 4, ya que la mayoría de los modelos de plataforma tienen modelos de tarjeta de interconexión únicos. Para la configuración de MetroCluster, es necesario mover las conexiones de cables FC-VI del nodo 2 al nodo 4. Si el host nuevo no tiene una tarjeta FC-VI, puede que necesite mover la tarjeta FC-VI.



. Encienda el nodo 4 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al aviso del entorno de arranque.
+

NOTE: Cuando se arranca el nodo 4, es posible que se muestre el siguiente mensaje de advertencia:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. Si aparece el mensaje de advertencia en el paso 4, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

WARNING: *No anule el retraso; si no permite que la batería se cargue, podría perderse información.*

+

NOTE: Consulte link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].





. [[step6]]Configure la conexión netboot eligiendo una de las siguientes acciones.
+

NOTE: Se deben utilizar el puerto e IP de gestión como conexión para reiniciar el sistema. No utilice una IP de LIF de datos ni una interrupción del servicio de datos mientras se realiza la actualización.

+
[cols="30,70"]
|===
| Si el protocolo de configuración dinámica de hosts (DHCP) es... | Realice lo siguiente... 


| Ejecutando | Configure la conexión automáticamente introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -auto` 


| No se está ejecutando | Configure manualmente la conexión introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Es la dirección IP del sistema de almacenamiento (obligatorio).
`_netmask_` es la máscara de red del sistema de almacenamiento (obligatoria).
`_gateway_` es la puerta de enlace del sistema de almacenamiento (obligatorio).
`_dns_addr_` Es la dirección IP de un servidor de nombres en la red (opcional).
`_dns_domain_` Es el nombre de dominio del servicio de nombres de dominio (DNS). Si utiliza este parámetro opcional, no necesita un nombre de dominio completo en la URL del servidor para reiniciar el sistema; solo necesita el nombre de host del servidor. NOTA: Es posible que se necesiten otros parámetros para la interfaz. Introduzca `help ifconfig` en el símbolo del sistema del firmware para obtener detalles. 
|===
. Reiniciar el sistema en el nodo 4:
+
[cols="30,70"]
|===
| Durante... | Realice lo siguiente... 


| Sistemas de la serie FAS/AFF8000 | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| Todos los demás sistemas | `netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
La `<path_to_the_web-accessible_directory>` debería conducir al lugar en el que se ha descargado el `<ontap_version>_image.tgz` En el paso 1 de la sección link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

+

NOTE: No interrumpa el arranque.

. En el menú de inicio, seleccione opción `(7) Install new software first`.
+
Esta opción del menú descarga e instala la nueva imagen de ONTAP en el dispositivo de arranque.

+
Ignore el siguiente mensaje:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota se aplica a las actualizaciones no disruptivas de ONTAP, no a las actualizaciones de controladoras.

+

NOTE: Utilice siempre netboot para actualizar el nodo nuevo a la imagen deseada. Si utiliza otro método para instalar la imagen en la nueva controladora, podría instalarse la imagen incorrecta. Este problema se aplica a todas las versiones de ONTAP. El procedimiento para reiniciar el sistema combinado con la opción `(7) Install new software` Limpia el soporte de arranque y coloca la misma versión ONTAP en ambas particiones de imagen.

. Si se le solicita que continúe el procedimiento, introduzca `y`, Y cuando se le solicite el paquete, escriba la dirección URL:
+
`\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. Lleve a cabo los siguientes pasos para reiniciar el módulo del controlador:
+
.. Introduzca `n` para omitir la recuperación del backup cuando aparezca la siguiente solicitud:
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. Reinicie introduciendo `y` cuando vea el siguiente símbolo del sistema:
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
El módulo del controlador se reinicia pero se detiene en el menú de inicio porque el dispositivo de arranque se ha reformateado y los datos de configuración deben restaurarse.



. Seleccione el modo de mantenimiento `5` desde el menú de inicio y entrar `y` cuando se le pida que continúe con el arranque.
. Compruebe que la controladora y el chasis están configurados como ha:
+
`ha-config show`

+
En el siguiente ejemplo, se muestra el resultado del `ha-config show` comando:

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: El sistema graba en una PROM tanto si se encuentran en un par ha como en una configuración independiente. El estado debe ser el mismo en todos los componentes del sistema independiente o del par de alta disponibilidad.

. Si la controladora y el chasis no están configurados como alta disponibilidad, utilice los siguientes comandos para corregir la configuración:
+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si tiene una configuración MetroCluster, utilice los siguientes comandos para modificar la controladora y el chasis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. Salga del modo de mantenimiento:
+
`halt`

+
Interrumpa el AUTOBOOT pulsando Ctrl-C en el prompt del entorno de arranque.

. [[auto_install4_step15]]en el nodo 3, compruebe la fecha, la hora y la zona horaria del sistema:
+
`date`

. El nodo 4, compruebe la fecha mediante el siguiente comando en el símbolo del sistema del entorno de arranque:
+
`show date`

. Si es necesario, configure la fecha del nodo 4:
+
`set date _mm/dd/yyyy_`

. En el nodo 4, compruebe la hora mediante el siguiente comando en el símbolo del sistema del entorno de arranque:
+
`show time`

. Si es necesario, configure la hora del nodo 4:
+
`set time _hh:mm:ss_`

. En el cargador de arranque, establezca el ID del sistema del partner en el nodo 4:
+
`setenv partner-sysid _node3_sysid_`

+
Para el nodo 4, `partner-sysid` debe ser el del nodo 3.

+
Guarde los ajustes:

+
`saveenv`

. [[auto_install4_step21]] Compruebe el `partner-sysid` para el nodo 4:
+
`printenv partner-sysid`



. [[auto_install4_step22]]Si tiene unidades NetApp Storage Encryption (NSE) instaladas, realice los siguientes pasos:
+

NOTE: Si aún no lo ha hecho anteriormente en el procedimiento, consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Cómo saber si una unidad tiene la certificación FIPS"^] para determinar el tipo de unidades de autocifrado que están en uso.

+
.. Configurado `bootarg.storageencryption.support` para `true` o. `false`:
+
[cols="35,65"]
|===
| Si están en uso las siguientes unidades... | Entonces… 


| Unidades NSE que cumplen con los requisitos de autocifrado de FIPS 140-2 de nivel 2 | `setenv bootarg.storageencryption.support *true*` 


| SED de NetApp no con FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad. Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.

====
.. Póngase en contacto con el soporte de NetApp para obtener ayuda para restaurar la información sobre la gestión de claves incorporada.


. Inicie el nodo en el menú de arranque:
+
`boot_ontap menu`



.El futuro
* Si tiene un sistema con una configuración FC o UTA/UTA2,link:set_fc_or_uta_uta2_config_node4.html["Establecer la configuración FC o UTA/UTA2 en el nodo 4"] .
* Si no tiene una configuración FC o UTA/UTA2,link:reassign-node2-disks-to-node4.html#reassign-node2-node4-step1["Reasignar los discos del nodo 2 al nodo 4, Paso 1"] para que el nodo 4 pueda reconocer los discos del nodo 2.
* Si tiene una configuración MetroCluster ,link:set_fc_or_uta_uta2_config_node4.html["Establecer la configuración FC o UTA/UTA2 en el nodo 4"] para detectar los discos conectados al nodo.

