---
sidebar: sidebar 
permalink: upgrade-arl-auto/issues_in_multiple_stages_of_procedure.html 
keywords: issues, arise, multiple, stages, procedure 
summary: 'Información sobre problemas que pueden producirse al actualizar controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Problemas que pueden surgir en varias etapas del procedimiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Algunos problemas pueden ocurrir durante diferentes etapas del procedimiento.



== Resultado de comando "Storage Failover show" inesperado

Durante el procedimiento, si el nodo que aloja todos los agregados de datos produce una alarma o se reinicia por accidente, podría ver un resultado inesperado para el `storage failover show` comando antes y después del reinicio, la alarma o el ciclo de apagado y encendido.

.Acerca de esta tarea
Puede que aparezca un resultado inesperado en el `storage failover show` Orden en la etapa 2, etapa 3, etapa 4 o etapa 5.

El siguiente ejemplo muestra el resultado esperado del `storage failover show` comando si no hay reinicios o produce una alarma en el nodo que aloja todos los agregados de datos:

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     false     Unknown
node2    node1     false     Node owns partner aggregates as part of the non-disruptive head upgrade procedure. Takeover is not possible: Storage failover is disabled.
....
En el siguiente ejemplo, se muestra el resultado del `storage failover show` comando tras un reinicio o una alarma:

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     -         Unknown
node2    node1     false     Waiting for node1, Partial giveback, Takeover is not possible: Storage failover is disabled
....
Aunque el resultado dice que un nodo está en una devolución parcial y que la conmutación al respaldo del almacenamiento está deshabilitada, puede ignorar este mensaje.

.Pasos
No es necesario realizar ninguna acción; continúe con el procedimiento de actualización de la pareja de nodos.
