---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node1_node3.html 
keywords: map, port, node1, node3, settings, restore, cluster 
summary: 'Compruebe que los puertos físicos del nodo 1 se asignan correctamente al nodo 3 cuando se actualizan controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Asigne puertos del nodo 1 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Debe verificar que los puertos físicos del nodo 1 se asignen correctamente a los puertos físicos del nodo 3, lo que permitirá que el nodo 3 se comunique con otros nodos del clúster y con la red después de la actualización.

.Acerca de esta tarea
Consulte link:other_references.html["Referencias"] Para enlazar con _Hardware Universe_ y obtener información acerca de los puertos en los nuevos nodos. Utilizará la información más adelante en esta sección.

La configuración del puerto puede variar en función del modelo de los nodos. Debe hacer que la configuración de puertos y LIF en el nodo original sea compatible con el uso y la configuración planificados del nuevo nodo. Esto es así porque el nuevo nodo reproduce la misma configuración cuando arranca, lo que significa que cuando arranca el nodo 3, ONTAP intentará alojar LIF en los mismos puertos que se usaron en el nodo 1.

Por lo tanto, si los puertos físicos del nodo 1 no se asignan directamente a los puertos físicos del nodo 3, se necesitarán cambios de configuración del software para restaurar la conectividad de clúster, gestión y red después del arranque. Además, si los puertos del clúster del nodo 1 no se asignan directamente a los puertos del clúster del nodo 3, es posible que el nodo 3 no vuelva a unir automáticamente el quórum cuando se reinicia hasta que se cambie la configuración de software para alojar las LIF del clúster en los puertos físicos correctos.

.Pasos
. Registre toda la información de cableado del nodo 1 para el nodo 1, los puertos, los dominios de retransmisión y los espacios IP, en la tabla:
+
|===
| LUN | Puertos 1 nodo 1 | Espacios IP 1 | Dominios de retransmisión 1-1 | Puertos de nodo 3 | Espacios IP de nodo 3 | Dominios de retransmisión de nodo 3 


| Clúster 1 |  |  |  |  |  |  


| Clúster 2 |  |  |  |  |  |  


| Clúster 3 |  |  |  |  |  |  


| Clúster 4 |  |  |  |  |  |  


| Gestión de nodos |  |  |  |  |  |  


| Gestión de clústeres |  |  |  |  |  |  


| Datos 1 |  |  |  |  |  |  


| Datos 2 |  |  |  |  |  |  


| Datos 3 |  |  |  |  |  |  


| Datos 4 |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| Puerto de interconexión de clústeres |  |  |  |  |  |  
|===
. Registre toda la información de cableado de los nodos 3, los puertos, los dominios de retransmisión y los espacios IP de la tabla.
. Siga estos pasos para verificar si la configuración es un clúster sin switches de dos nodos:
+
.. Configure el nivel de privilegio en Advanced:
+
`cluster::> set -privilege advanced`

.. Compruebe si la configuración es un clúster sin switches de dos nodos:
+
`cluster::> network options switchless-cluster show`

+
[listing]
----
cluster::*> network options switchless-cluster show

Enable Switchless Cluster: false/true
----
+
El valor de la salida de este comando debe coincidir con el estado físico del sistema.

.. Volver al nivel de privilegio de administración:
+
[listing]
----
cluster::*> set -privilege admin

cluster::>
----


. Siga estos pasos para colocar el nodo 3 en el quórum:
+
.. Nodo de arranque 3. Consulte link:install_boot_node3.html["Instale y arranque el nodo 3"] para arrancar el nodo si aún no lo ha hecho.
.. Compruebe que los nuevos puertos del clúster se encuentran en el dominio de retransmisión del clúster:
+
`network port show -node _node_ -port _port_ -fields broadcast-domain`

+
En el siguiente ejemplo, se muestra que el puerto "e0a" está en el dominio del clúster del nodo 3:

+
[listing]
----
 cluster::> network port show -node _node3_ -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e0a  Cluster
----
.. Si los puertos del clúster no están en el dominio de retransmisión del clúster, añádalos con el siguiente comando:
+
`broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports _node:port_`

+
En este ejemplo, se añade el puerto de clúster "e1b" del nodo 3:

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
.. Añada los puertos correctos al dominio de retransmisión de clúster:
+
`network port modify -node -port -ipspace Cluster -mtu 9000`

+
En este ejemplo, se añade el puerto de clúster "e1b" del nodo 4:

+
[listing]
----
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000
----
.. Migre las LIF del clúster a los nuevos puertos, una vez por cada LIF:
+
`network interface migrate -vserver Cluster -lif _lif_name_ -source-node _node3_ -destination-node _node3_ -destination-port _port_name_`

.. Modifique el puerto de inicio de las LIF del clúster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Quite los puertos antiguos del dominio de retransmisión de clúster:
+
`network port broadcast-domain remove-ports`

+
El siguiente comando elimina el puerto "e0d" del nodo 3:

+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports node3:e0d`

.. Compruebe que el nodo 3 se haya Unido nuevamente al quórum:
+
`cluster show -node node3 -fields health`



. [[auto_map_3_step5]]ajuste los dominios de retransmisión que alojan las LIF del clúster y las LIF de gestión del nodo/clusterManagement. Confirme que cada dominio de retransmisión contiene los puertos correctos. No se puede mover un puerto entre dominios de retransmisión si aloja o pertenece a una LIF, de modo que podría necesitar migrar y modificar las LIF de la siguiente manera:
+
.. Mostrar el puerto de inicio de una LIF:
+
`network interface show -fields home-node,home-port`

.. Muestre el dominio de retransmisión que contiene este puerto:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Añada o quite puertos de los dominios de retransmisión:
+
`network port broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. Modificar el puerto de inicio de una LIF:
+
`network interface modify -vserver vserver -lif _lif_name_ –home-port _port_name_`



. Ajuste la pertenencia al dominio de retransmisión de los puertos de red utilizados para las LIF de interconexión de clústeres mediante los mismos comandos que se muestran en <<auto_map_3_step5,Paso 5>>.
. Ajuste cualquier otro dominio de retransmisión y migre los LIF de datos, si es necesario, mediante los mismos comandos que se muestran en <<auto_map_3_step5,Paso 5>>.
. Si hubiera algún puerto en el nodo 1 que ya no exista en el nodo 3, siga estos pasos para eliminarlos:
+
.. Acceda al nivel de privilegio avanzado en cualquiera de los nodos:
+
`set -privilege advanced`

.. Para eliminar los puertos:
+
`network port delete -node _node_name_ -port _port_name_`

.. Volver al nivel admin:
+
`set -privilege admin`



. Ajustar todos los grupos de recuperación tras fallos de LIF:
+
`network interface modify -failover-group _failover_group_ -failover-policy _failover_policy_`

+
El siguiente comando establece la directiva de conmutación por error en `broadcast-domain-wide` Y utiliza los puertos del grupo de conmutación por error "fg1" como destinos de conmutación por error para la LIF "data1" del nodo 3:

+
`network interface modify -vserver node3 -lif data1 failover-policy broadcast-domainwide -failover-group fg1`

+
Consulte link:other_references.html["Referencias"] Para establecer un vínculo a _Network Management_ o a los comandos _ONTAP 9: Manual Page Reference_ para obtener más información.

. Verifique los cambios en el nodo 3:
+
`network port show -node node3`

. Cada LIF de clúster debe estar escuchando en el puerto 7700. Compruebe que las LIF del clúster están escuchando en el puerto 7700:
+
`::> network connections listening show -vserver Cluster`

+
El resultado esperado de la escucha del puerto 7700 en los puertos del clúster tal y como se muestra en el siguiente ejemplo de un clúster de dos nodos:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. De ser necesario, para cada LIF de clúster que no esté escuchando en el puerto 7700, establezca el estado administrativo de la LIF en `down` y después `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Repita el paso 11 para verificar que el LIF del clúster ahora esté escuchando en el puerto 7700.


