---
sidebar: sidebar 
permalink: upgrade-arl-auto/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'Mueva los LIF de datos NAS 2 del nodo 3 del nodo 3 al nodo 4 cuando actualice las controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Mueva agregados no raíz y LIF de datos NAS que pertenecen al nodo 2 desde el nodo 3 al nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de verificar la instalación del nodo 4 y antes de reubicar agregados de nodo 3 al nodo 4, es necesario mover los LIF de datos NAS que pertenecen al nodo 2, que actualmente son del nodo 3 al nodo 4. También es necesario verificar que las LIF SAN existen en el nodo 4.

.Acerca de esta tarea
Las LIF remotas gestionan el tráfico a LUN DE SAN durante el procedimiento de actualización. No es necesario mover LIF DE SAN durante la actualización para el estado del clúster o del servicio. Los LIF SAN no se mueven a menos que tengan que asignarse a nuevos puertos. Verifique que las LIF estén en buen estado y ubicadas en puertos adecuados después de poner el nodo 4 en línea.

.Pasos
. Reanude la operación de reubicación:
+
`system controller replace resume`

+
El sistema ejecuta las siguientes tareas:

+
** Comprobación de quórum del clúster
** Comprobación del ID del sistema
** Comprobación de la versión de la imagen
** Comprobación de la plataforma de destino
** Comprobación de accesibilidad de red


+
La operación se detiene en esta fase de la comprobación de accesibilidad de red.

. Compruebe manualmente que la red y todas las VLAN, los grupos de interfaces y los dominios de retransmisión se han configurado correctamente.
. Reanude la operación de reubicación:
+
`system controller replace resume`

+
[listing]
----
To complete the "Network Reachability" phase, ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes assigning network ports to the correct broadcast domains,creating any required ifgrps and VLANs, and modifying the home-port parameter of network interfaces to the appropriate ports.Refer to the "Using aggregate relocation to upgrade controller hardware on a pair of nodes running ONTAP 9.x" documentation, Stages 3 and 5. Have all of these steps been manually completed? [y/n]
----
. Introduzca `y` para continuar.
. El sistema realiza las siguientes comprobaciones:
+
** Comprobación del estado del clúster
** Comprobación del estado de LIF de clúster


+
Después de ejecutar estas comprobaciones, el sistema reubica los agregados que no son raíz y los LIF de datos NAS que pertenecen al nodo 2 en la nueva controladora, el nodo 4. El sistema se detiene una vez que se completa la reubicación de recursos.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
`system controller replace show-details`

. Compruebe manualmente que los agregados que no son raíz y los LIF de datos NAS se han reubicado correctamente en el nodo 4.
+
Si alguno de los agregados no se puede reubicar o vetar, deberá reubicar los agregados manualmente o anular los vetos o las comprobaciones de destino, si fuera necesario. Consulte la sección link:relocate_failed_or_vetoed_aggr.html["Se han producido fallos en la reubicación o los agregados vetados"] si quiere más información.

. Confirme que las LIF DE SAN se encuentran en los puertos correctos del nodo 4. Para ello, realice los siguientes subpasos:
+
.. Introduzca el siguiente comando y examine su resultado:
+
`network interface show -data-protocol iscsi|fcp -home-node _node4_`

+
El sistema devuelve un resultado similar al siguiente ejemplo:

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
        Logical    Status     Network           Current Current Is
Vserver Interface  Admin/Oper Address/Mask      Node    Port    Home
------- ---------- ---------- ----------------- ------- ------- ---
vs0
        a0a        up/down    10.63.0.53/24     node3   a0a     true
        data1      up/up      10.63.0.50/18     node3   e0c     true
        rads1      up/up      10.63.0.51/18     node3   e1a     true
        rads2      up/down    10.63.0.52/24     node3   e1b     true
vs1
        lif1       up/up      172.17.176.120/24 node3   e0c     true
        lif2       up/up      172.17.176.121/24 node3   e1a     true
----
.. Si el nodo 4 tiene LIF SAN o grupos de LIF SAN que están en un puerto que no existen en el nodo 2 o que deben asignarse a un puerto diferente, mueva a un puerto adecuado del nodo 4 completando los siguientes subpasos:
+
... Establezca el estado de LIF en inactivo con la introducción del comando siguiente:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin down`

... Quite la LIF del conjunto de puertos:
+
`portset remove -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

... Escriba uno de los siguientes comandos:
+
**** Mueva un solo LIF introduciendo el comando siguiente:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -home-port _new_home_port_`

**** Mueva todos los LIF de un puerto único inexistente o incorrecto a un puerto nuevo introduciendo el comando siguiente:
+
`network interface modify {-home-port _port_on_node1_ -home-node _node1_ -role data} -home-port _new_home_port_on_node3_`

**** Vuelva a agregar las LIF al conjunto de puertos:
+
`portset add -vserver _vserver_name_ -portset _portset_name_ -port-name _port_name_`

+

NOTE: Debe confirmar que mueve LIF SAN a un puerto que tiene la misma velocidad de enlace que el puerto original.





.. Modifique el estado de todas las LIF a. `up` De modo que las LIF pueden aceptar y enviar tráfico del nodo introduciendo el comando siguiente:
+
`network interface modify -home-port _port_name_ -home-node _node4_ -lif data -statusadmin up`

.. Escriba el comando siguiente y examine su resultado para verificar que las LIF se han movido a los puertos correctos y que las LIF tienen el estado de `up` introduciendo el siguiente comando en cualquiera de los nodos y examinando el resultado:
+
`network interface show -home-node <node4> -role data`

.. Si alguna LIF está inactiva, establezca el estado administrativo de las LIF en `up` Con el siguiente comando, una vez para cada LIF:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -status-admin up`



. Reanude la operación para solicitar que el sistema realice las comprobaciones previas necesarias:
+
`system controller replace resume`

+
El sistema realiza las siguientes comprobaciones posteriores:

+
** Comprobación de quórum del clúster
** Comprobación del estado del clúster
** Comprobación de reconstrucción de los agregados
** Comprobación del estado del agregado
** Comprobación del estado del disco
** Comprobación del estado de LIF de clúster



