---
sidebar: sidebar 
permalink: upgrade-arl-auto/overview_of_the_arl_upgrade.html 
keywords: aggregate relocation, upgrade, process, overview, stages 
summary: 'Conozca cómo el procedimiento para actualizar controladoras que ejecutan ONTAP 9.5 a 9.7 con `system controller replace` los comandos funcionan.' 
---
= Descripción general de la actualización de ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de actualizar los nodos mediante ARL, debe comprender cómo funciona el procedimiento. En este contenido, el procedimiento se divide en varias etapas.



== Actualice el par de nodos

Para actualizar la pareja de nodos, debe preparar los nodos originales y realizar una serie de pasos en los nodos original y en los nuevos. A continuación, puede retirar los nodos originales.



== Información general sobre la secuencia de actualizaciones de ARL

Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo, una controladora cada vez, aprovechando la configuración de par de alta disponibilidad para reubicar la propiedad de agregados que no son raíz. Todos los agregados que no son raíz deben pasar por dos reubicaciones para llegar a su destino final, que es el nodo actualizado correcto.

Cada agregado tiene un propietario particular y un propietario actual. El propietario del hogar es el propietario real del agregado, y el propietario actual es el propietario temporal.

La siguiente tabla describe las tareas de alto nivel que realiza durante cada etapa y el estado de propiedad del agregado al final de la etapa. Los pasos detallados se proporcionan más adelante en el procedimiento:

[cols="25,75"]
|===
| Etapa | Pasos 


| link:stage_1_index.html["Etapa 1. Prepare la actualización"]  a| 
Durante la fase 1, realizará comprobaciones previas y, si fuera necesario, corrija la propiedad del agregado. Debe registrar cierta información si gestiona el cifrado del almacenamiento mediante el administrador de claves incorporado y puede optar por desactivar las relaciones de SnapMirror.

Propiedad del agregado al final de la fase 1:

* El nodo 1 es el propietario raíz y el propietario actual de los agregados del nodo 1.
* El nodo 2 es el propietario particular y el propietario actual de los agregados del nodo 2.




| link:stage_2_index.html["Fase 2. Reubicar y retirar el nodo 1"]  a| 
Durante la fase 2, debe reubicar agregados no raíz y LIF de datos NAS al nodo 1 en el nodo 2. Este proceso está en gran medida automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Si es necesario, reubique los agregados que han fallado o que han vetado. Debe registrar la información necesaria del nodo 1 para utilizarla más adelante en el procedimiento y, a continuación, retirar el nodo 1. También es posible preparar el modo de reiniciar el sistema de los nodos 3 y los nodos 4 más adelante en el procedimiento.

Propiedad del agregado al final de la fase 2:

* El nodo 2 es el propietario actual de los agregados del nodo 1.
* El nodo 2 es el propietario particular y el propietario actual de agregados del nodo 2.




| link:stage_3_index.html["Etapa 3. Instale y arranque el nodo 3"]  a| 
Durante la fase 3, debe instalar y arrancar el nodo 3, asignar los puertos de gestión del nodo y del clúster del nodo 1 al nodo 3 y verificar la instalación del nodo 3. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 3 y confirmar que el nodo 3 se ha Unido al quórum. También se deben reubicar los LIF de datos NAS del nodo 1 y los agregados no raíz del nodo 2 al nodo 3, y verificar que las LIF SAN existan en el nodo 3.

Propiedad agregada al final de la etapa 3:

* Node3 es el propietario raíz y el propietario actual de los agregados del nodo 1.
* El nodo 2 es el propietario particular y el propietario actual de agregados del nodo 2.




| link:stage_4_index.html["Etapa 4. Reubicar y retirar el 2"]  a| 
Durante la etapa 4, se deben reubicar los agregados no raíz 2 y las LIF de datos no SAN en el nodo 3. También puede registrar la información necesaria del nodo 2 y después retirar el nodo 2.

Propiedad agregada al final de la etapa 4:

* Node3 es el propietario raíz y el propietario actual de los agregados que originalmente pertenecían al nodo 1.
* El nodo 2 es el propietario en casa de los agregados 2.
* El nodo 3 es el propietario actual de agregados de 2 nodos.




| link:stage_5_index.html["Etapa 5. Instale y arranque el nodo 4"]  a| 
En la etapa 5, se deben instalar y arrancar los nodos 4, asignar los puertos de gestión del clúster y del nodo del nodo 2 al nodo 4 y verificar la instalación del nodo 4. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 4 y confirmar que el nodo 4 se ha Unido al quórum. También se pueden reubicar los LIF de datos NAS 2 y agregados no raíz de nodo 3 a nodo 4 y verificar las LIF SAN existentes en el nodo 4.

Propiedad agregada al final de la etapa 5:

* Nodo 3 es el propietario raíz y el propietario actual de los agregados que originalmente pertenecían al nodo 1.
* Node4 es el propietario nacional y el propietario actual de agregados que pertenecía originalmente al nodo 2.




| link:stage_6_index.html["Etapa 6. Complete la actualización"]  a| 
Durante la fase 6, el usuario confirma que los nodos nuevos están configurados correctamente y, si los nodos nuevos tienen la función de cifrado habilitada, se configuran y se configuran el cifrado de almacenamiento o el cifrado de volúmenes de NetApp. También debe retirar los nodos antiguos y reanudar las operaciones de SnapMirror.

|===