---
sidebar: sidebar 
permalink: upgrade-arl-auto/reassign-node1-disks-to-node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports 
summary: 'Configure los puertos FC integrados de nodo 3, los puertos UTA/UTA2 o la tarjeta UTA/UTA2 cuando actualice las controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Reasigne discos de node1 GB a node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe reasignar los discos que pertenecían a node1 a node3 antes de verificar la instalación de node3.

.Pasos
. [[reassign-node1-node3-step1]]Verifique que el nodo1 se haya detenido en el menú de arranque y reasigne los discos del nodo1 al nodo3:
+
`boot_after_controller_replacement`

+
Tras un breve retraso, se le pedirá que introduzca el nombre del nodo que se va a reemplazar. Si hay discos compartidos (también llamados Advanced Disk Partitioning (ADP) o discos con particiones), se le pedirá que introduzca el nombre del nodo del compañero de alta disponibilidad.

+
Estos mensajes pueden aparecer ocultos en los mensajes de la consola. Si no introduce un nombre de nodo o introduce un nombre incorrecto, se le pedirá que vuelva a introducir el nombre.

+
.Expanda el ejemplo de salida de consola
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
...
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
.
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 22/7
.
.
(boot_after_controller_replacement)   Boot after controller upgrade
(9a)                                  Unpartition all disks and remove their ownership information.
(9b)                                  Clean configuration and initialize node with partitioned disks.
(9c)                                  Clean configuration and initialize node with whole disks.
(9d)                                  Reboot the node.
(9e)                                  Return to main boot menu.

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? boot_after_controller_replacement
.
This will replace all flash-based configuration with the last backup to
disks. Are you sure you want to continue?: yes
.
.
Controller Replacement: Provide name of the node you would like to replace: <name of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node <node being replaced> disks.
Fetched sanown old_owner_sysid = 536953334 and calculated old sys id = 536953334
Partner sysid = 4294967295, owner sysid = 536953334
.
.
.
Terminated
<node reboots>
.
.
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
.
.
System rebooting...
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
Login:
...
----
====
. Si el sistema entra en un bucle de reinicio con el mensaje `no disks found` , esto se debe a que ha restablecido los puertos al modo de destino y, por lo tanto, no puede ver ningún disco.  Llevar a cabo<<auto_check3_step3,Paso 3>> a<<auto_check3_step8,Paso 8>> en el nodo3 para resolver este problema.
. [[auto_check3_step3]]Pulse Ctrl-C durante el ARRANQUE AUTOMÁTICO para detener el nodo en el indicador Loader>.
. [[step18]]En el aviso del CARGADOR, acceda al modo de mantenimiento:
+
`boot_ontap maint`

. [[paso 19]]en el modo de mantenimiento, muestre todos los puertos iniciadores previamente configurados que se encuentran ahora en modo de destino:
+
`ucadmin show`

+
Cambie los puertos de nuevo al modo iniciador:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. [[step20]]Compruebe que los puertos se han cambiado al modo de iniciador:
+
`ucadmin show`

. [[step21]]salir del modo de mantenimiento:
+
`halt`

+
[NOTE]
====
Si va a actualizar desde un sistema que admite discos externos a un sistema que también admite discos externos, vaya a <<auto_check3_step8,Paso 8>>.

Si va a actualizar desde un sistema que admite discos externos a un sistema que admita discos internos y externos, por ejemplo, un sistema AFF A800, vaya a <<auto_check3_step9,Paso 9>>.

====
. [[auto_check3_step8]]En el símbolo del SISTEMA DEL CARGADOR, arranque:
+
`boot_ontap menu`

+
Ahora, en el arranque, el nodo puede detectar todos los discos que se le habían asignado previamente y puede arrancar según se esperaba.

+
Cuando los nodos de clúster que desea reemplazar utilizan cifrado de volumen raíz, ONTAP no puede leer la información de los volúmenes desde los discos. Restaure las claves del volumen raíz:

+
.. Vuelva al menú de inicio especial:
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Seleccione *(10) establecer secretos de recuperación de Onboard Key Manager*
.. Introduzca `y` en el siguiente símbolo del sistema:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. En la solicitud de, introduzca la frase de contraseña del gestor de claves.
.. Introduzca los datos de copia de seguridad cuando se le solicite.
+

NOTE: Debe haber obtenido la clave de acceso y los datos de backup en la link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"] sección de este procedimiento.

.. Después de que el sistema se inicie de nuevo en el menú de inicio especial, ejecute la opción *(1) Inicio normal*
+

NOTE: Es posible que se encuentre un error en este momento. Si se produce un error, repita los subpasos de <<auto_check3_step8,Paso 8>> hasta que el sistema arranque normalmente.



. [[auto_check3_step9]]Si está actualizando desde un sistema con discos externos a un sistema que admite discos internos y externos (sistemas AFF A800 , por ejemplo), configure el agregado del nodo1 como el agregado raíz para confirmar que el nodo3 arranca desde el agregado raíz del nodo1.  Para configurar el agregado raíz, vaya al menú de arranque en el nodo 3 y seleccione la opción `5` para ingresar al modo de mantenimiento.
+

CAUTION: *Debe realizar los siguientes subpasos en el orden exacto que se muestra; de lo contrario, podría causar una interrupción o incluso pérdida de datos.*

+
El siguiente procedimiento establece el nodo 3 para arrancar desde el agregado raíz del nodo 1:

+
.. Entrar en el modo de mantenimiento:
+
`boot_ontap maint`

.. Compruebe la información de RAID, plex y suma de comprobación para el agregado 1-1:
+
`aggr status -r`

.. Compruebe el estado del agregado 1-1:
+
`aggr status`

.. Si es necesario, active el agregado de los nodos:
+
`aggr_online root_aggr_from___node1__`

.. Impida que el nodo 3 arranque desde su agregado raíz original:
+
`aggr offline _root_aggr_on_node3_`

.. Establezca el agregado raíz del nodo 1 como el nuevo agregado raíz del nodo 3:
+
`aggr options aggr_from___node1__ root`

.. Compruebe que el agregado raíz del nodo 3 esté sin conexión y que el agregado raíz de los discos extraídos del nodo 1 esté en línea y establecido en raíz:
+
`aggr status`

+

NOTE: Si no se pudo realizar el subpaso anterior, el nodo 3 se puede arrancar desde el agregado raíz interno, o bien es posible que el sistema asuma que existe una nueva configuración de clúster o que se le solicite identificar una.

+
El siguiente muestra un ejemplo de resultado del comando:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



