---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node4.html 
keywords: node4, interface group, VLANs, broadcast domains, re-create 
summary: 'Vuelva a crear las VLAN, los grupos de interfaces y los dominios de retransmisión en el nodo 4 cuando actualice las controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Vuelva a crear VLAN, grupos de interfaces y dominios de retransmisión en el nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una vez que se confirma que el nodo 4 funciona de quórum y que se puede comunicar con el nodo 3, es necesario volver a crear las VLAN del nodo 2, los grupos de interfaces y los dominios de retransmisión en el nodo 4. También es necesario añadir los puertos de nodo 3 a los dominios de retransmisión recientemente creados.

.Acerca de esta tarea
Para obtener más información sobre la creación y recreación de VLAN, grupos de interfaces y dominios de retransmisión, vaya a. link:other_references.html["Referencias"] Y enlace a _Network Management_.

.Pasos
. Vuelva a crear las VLAN en el nodo 4 mediante la información 2 registrada en el link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["Reubique los agregados que no son raíz y los LIF de datos NAS del nodo 2 al nodo 3"] sección:
+
`network port vlan create -node _node4_ -vlan _vlan-names_`

. Vuelva a crear los grupos de interfaces en nodo 4 con la información 2 registrada en el link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["Reubique los agregados que no son raíz y los LIF de datos NAS del nodo 2 al nodo 3"] sección:
+
`network port ifgrp create -node _node4_ -ifgrp _port_ifgrp_names_-distr-func`

. Vuelva a crear los dominios de retransmisión en el nodo 4 con la información 2 registrada en el link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["Reubique los agregados que no son raíz y los LIF de datos NAS del nodo 2 al nodo 3"] sección:
+
`network port broadcast-domain create -ipspace Default -broadcast-domain _broadcast_domain_names_ -mtu _mtu_size_ -ports _node_name:port_name,node_name:port_name_`

. Añada los puertos de nodo 4 a los dominios de retransmisión recientemente creados:
+
`network port broadcast-domain add-ports -broadcast-domain _broadcast_domain_names_ -ports _node_name:port_name,node_name:port_name_`


