---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_nas_data_lifs_node1_node2.html 
keywords: relocate, non-root, nonroot, aggregates, NAS, data, lifs, node1, node2 
summary: 'Mueva agregados que no son raíz y LIF de datos NAS del nodo 1 al nodo 2 y mueva los recursos del nodo 1 al nodo 3 cuando actualice las controladoras que ejecutan ONTAP 9.5 a 9.7 mediante los comandos "System Controller replace".' 
---
= Reubique los agregados que no son raíz y los LIF de datos NAS que pertenecen al nodo 1 al nodo 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de poder sustituir el nodo 1 por el nodo 3, debe mover los agregados que no son raíz y las LIF de datos NAS del nodo 1 al nodo 2 antes de mover, en última instancia, los recursos del nodo 1 al nodo 3.

.Antes de empezar
La operación ya debe estar en pausa cuando se inicia la tarea, por lo que se debe reanudar manualmente.

.Acerca de esta tarea
Las LIF remotas gestionan el tráfico a LUN DE SAN durante el procedimiento de actualización. No es necesario mover LIF DE SAN durante la actualización para el estado del clúster o del servicio. Debe verificar que las LIF están en buen estado y ubicadas en puertos adecuados después de poner el nodo 3 en línea.


NOTE: El propietario principal de los agregados y las LIF no está modificado; solo se modifica el propietario actual.

.Pasos
. Reanudar las operaciones de movimiento de LIF de datos NAS y reubicación de agregados:
+
`system controller replace resume`

+
Todos los agregados que no son raíz y los LIF de datos NAS están migrados del nodo 1 al nodo 2.

+
La operación se pone en pausa para permitir verificar si todos los agregados que no son raíz del nodo 1 y las LIF de datos que no son SAN se han migrado al nodo 2.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
`system controller replace show-details`

. Con la operación en pausa, verifique que todos los agregados que no son raíz estén en línea para su estado en el nodo 2:
+
`storage aggregate show -node <node2> -state online -root false`

+
En el ejemplo siguiente, los agregados no raíz en el nodo 2 están en línea:

+
[listing]
----
cluster::> storage aggregate show -node node2 -state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Si los agregados se encuentran sin conexión o en estado no externo en el nodo 2, deben estar en línea usando el siguiente comando en el nodo 2, una vez para cada agregado:

+
`storage aggregate online -aggregate <aggregate_name>`

. Verifique que todos los volúmenes estén en línea en el nodo 2 mediante el siguiente comando en el nodo 2 y examinar su salida:
+
`volume show -node <node2> -state offline`

+
Si alguno de los volúmenes está sin conexión en el nodo 2, debe volver a ponerlos en línea usando el siguiente comando en el nodo 2, una vez para cada volumen:

+
`volume online -vserver <vserver_name> -volume <volume_name>`

+
El  `vserver_name` El uso de este comando se encuentra en la salida del comando anterior.  `volume show` dominio.



. [[step5]]Si los puertos que actualmente alojan LIF de datos no existen en el nuevo hardware, elimínelos del dominio de retransmisión:
+
`network port broadcast-domain remove-ports`

. Si alguna LIF está inactiva, establezca el estado administrativo de las LIF en «up» introduciendo el comando siguiente, una vez para cada LIF:
+
`network interface modify -vserver _Vserver_name -lif _LIF_name_`
                          `-home-node _nodename_ -status-admin up`

. Si tiene configurados grupos de interfaces o VLAN, complete los siguientes subpasos:
+
.. Si todavía no los ha guardado, registre información de VLAN e ifgrp, de modo que pueda volver a crear las VLAN y los ifgrps en el nodo 3 una vez que se haya iniciado el nodo 3.
.. Quite las VLAN de los grupos de interfaces introduciendo el comando siguiente:
+
`network port vlan delete -node _nodename_ -port _ifgrp_ -vlan-id _VLAN_ID_`

+

NOTE: Siga la acción correctiva para resolver los errores que sugiere el comando vlan delete.

.. Introduzca el siguiente comando y examine su salida para ver si hay algún grupo de interfaces configurado en el nodo:
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
El sistema muestra información del grupo de interfaces del nodo, como se muestra en el ejemplo siguiente:

+
[listing]
----
cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                 Node: node1
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. Si hay algún grupo de interfaces configurado en el nodo, registre los nombres de esos grupos y los puertos asignados a ellos y, a continuación, elimine los puertos introduciendo el comando siguiente, una vez para cada puerto:
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




