---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_on_node3.html 
keywords: FC, UTA, UTA2, configure, node3, CNA adapters, onboard ports 
summary: 'Configure los puertos FC integrados de nodo 3, los puertos UTA/UTA2 o la tarjeta UTA/UTA2 cuando actualice las controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Establezca la configuración de FC o UTA/UTA2 en el nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si el nodo 3 tiene puertos FC integrados, puertos de adaptador de objetivo unificado (UTA/UTA2) integrados o una tarjeta UTA/UTA2, debe configurar los ajustes antes de completar el resto del procedimiento.

.Acerca de esta tarea
Es posible que tenga que completar la sección <<Configure los puertos FC en el nodo 3>>, la sección <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>, o ambas secciones.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para referirse a puertos y adaptadores de adaptador de red convergente (CNA). Sin embargo, la CLI utiliza el término CNA.

Si node3 no tiene puertos FC integrados, puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, y está actualizando un sistema con discos de almacenamiento, puede saltar a.link:reassign-node1-disks-to-node3.html["Reasigne discos de node1 GB a node3"]



== Configure los puertos FC en el nodo 3

Si el nodo 3 tiene puertos FC, ya sea integrados o en un adaptador FC complementario, debe establecer las configuraciones de los puertos en el nodo antes de ponerlo en servicio porque los puertos no están preconfigurados cuando se envían los sistemas.  Si no configura los puertos, podría experimentar una interrupción en el servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto FC del nodo 1 que haya guardado en la sección link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puede omitir esta sección si el sistema no tiene configuraciones de FC. Si su sistema tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe configurarlos en <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.

.Pasos
. Compare la configuración de FC en el nodo3 con la configuración que capturó anteriormente del nodo1.
. Realice una de las siguientes acciones para modificar los puertos FC en el nodo 3, según sea necesario:
+
En modo de mantenimiento (opción 5 en el menú de arranque):

+
** Para programar como puertos de destino:
+
`ucadmin modify -m fc -t target <adapter>`

+
Por ejemplo: `ucadmin modify -m fc -t target 2a`

** Para programar puertos iniciadores:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Por ejemplo: `ucadmin modify -m fc -t initator 2b`



. Verifique la nueva configuración utilizando el siguiente comando y examinando el resultado:
+
`ucadmin show`

. Detenga el nodo:
+
`halt`

. Arranque el sistema desde el símbolo del sistema del CARGADOR:
+
`boot_ontap menu`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Seleccione opción `5` desde el menú de arranque para el modo de mantenimiento.


. Ejecute una de las siguientes acciones:
+
** Si el nodo 3 tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, vaya a. <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.
** Si node3 no tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, vaya directamente <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>> y vaya a.link:reassign-node1-disks-to-node3.html["Reasigne discos de node1 GB a node3"]






== Comprobar y configurar los puertos UTA/UTA2 en el nodo 3

Si el nodo 3 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe comprobar la configuración de los puertos y es posible que los vuelva a configurar, según cómo desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Si desea utilizar un puerto adaptador de objetivo unificado (UTA/UTA2) para FC, primero debe verificar cómo se ha configurado el puerto.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Puedes utilizar el `ucadmin show` Comando para ver o verificar la configuración actual del puerto, como se muestra en el siguiente ejemplo de salida:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA2. El modo FC admite el iniciador FC y el destino FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y sea compatible con destinos FC.

Es posible que encuentre puertos UTA/UTA2 en un adaptador adicional o en la placa base del controlador, y que tengan las siguientes configuraciones, pero debería comprobar la configuración de los puertos UTA/UTA2 en el nodo3 y cambiarla, si es necesario:

* LAS tarjetas UTA/UTA2 solicitadas cuando se solicita la controladora se configuran antes del envío para tener la personalidad que solicita.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras se configuran antes del envío para que tengan la personalidad que solicita.
+

WARNING: Debe estar en modo de mantenimiento para configurar los puertos UTA/UTA2.  Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.



.Pasos
. Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. Verifique la configuración del puerto UTA/UTA2:
+
`ucadmin show`

+
Examine la salida y determine si los puertos UTA/UTA2 tienen la personalidad que desea.

+
La salida en el siguiente ejemplo muestra que el tipo de adaptador "1b" está cambiando a iniciador y que el modo de los adaptadores "2a" y "2b" está cambiando a "cna".  El modo CNA le permite utilizar la tarjeta como un adaptador de red.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si los puertos UTA/UTA2... | Entonces… 


| No tenga la personalidad que usted desea | Vaya a <<auto_check3_step4,Paso 4>>. 


| Tenga la personalidad que usted desea | Omita los pasos 4 a 8 y vaya a<<auto_check3_step9,Paso 9>> . 
|===
. [[auto_check3_step4]]Realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si va a configurar... | Entonces… 


| Puertos en una tarjeta UTA/UTA2 | Ir a<<auto_check3_step5,Paso 5>> 


| Puertos UTA/UTA2 integrados | Omite el paso 5 y ve a<<auto_check3_step6,Paso 6>> . 
|===
. [[auto_check3_step5]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está en línea, desconecte el puerto UTA/UTA2:
+
`storage disable adapter <adapter_name>`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[auto_check3_step6]]Si la configuración actual no coincide con el uso deseado, cambie la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` es el modo de personalidad, `fc` o. `cna`.
** `-t` Es el tipo FC4, `target` o. `initiator`.
+

NOTE: Debe utilizar el iniciador FC para unidades de cinta y configuraciones de MetroCluster .  Debe utilizar el destino FC para los clientes SAN.



. Coloque cualquier puerto de destino en línea ingresando el siguiente comando una vez para cada puerto:
+
`storage enable adapter <adapter_name>`

. Conecte el cable del puerto.


[[auto_check3_step9]]
. Salga del modo de mantenimiento:
+
`halt`

. Arranque el nodo en el menú de arranque ejecutando `boot_ontap menu` .


.El futuro
* Si está actualizando a un sistema AFF A800 , vaya alink:reassign-node1-disks-to-node3.html#auto_check3_step9["Reasigne los discos node1 a node3, paso 9"] .
* Para todas las demás actualizaciones del sistema, vaya alink:reassign-node1-disks-to-node3.html["Reasigne los discos node1 a node3, paso 1"] .

