---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_3_index.html 
keywords: stage 3, install node3, non-SAN data LIFs, non-root aggregates 
summary: 'Secuencia de procesos en la fase 3 de una actualización de ARL mediante `system controller replace` Comandos en controladoras que ejecutan ONTAP 9.5 a 9.7.' 
---
= Descripción general de la etapa 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Durante la fase 3, debe instalar y arrancar el nodo 3, asignar los puertos de gestión del nodo y del clúster del nodo 1 al nodo 3 y verificar la instalación del nodo 3. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 3 y confirmar que el nodo 3 se ha Unido al quórum. También se deben reubicar los LIF de datos NAS del nodo 1 y los agregados no raíz del nodo 2 al nodo 3, y verificar que las LIF SAN existan en el nodo 3.

.Pasos
. link:install_boot_node3.html["Instale y arranque el nodo 3"]
. link:set_fc_or_uta_uta2_config_on_node3.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 3"]
. link:map_ports_node1_node3.html["Asigne puertos del nodo 1 al nodo 3"]
. link:join_quorum_node_has_different_ports_stage3.html["Unirse al quórum cuando un nodo tiene un conjunto diferente de puertos de red"]
. link:verify_node3_installation.html["Verifique la instalación del nodo 3"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html["Mueva agregados que no son raíz y LIF de datos NAS que pertenecen al nodo 1 del nodo 2 al nodo 3"]

