---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_5_index.html 
keywords: install, boot, node4, node2, node-management,  stage 5 
summary: 'Secuencia de procesos en la fase 5 de una actualización de ARL mediante `system controller replace` Comandos en controladoras que ejecutan ONTAP 9.5 a 9.7.' 
---
= Etapa 5. Instale y arranque el nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En la etapa 5, se deben instalar y arrancar los nodos 4, asignar los puertos de gestión del clúster y del nodo del nodo 2 al nodo 4 y verificar la instalación del nodo 4. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 4 y confirmar que el nodo 4 se ha Unido al quórum. También se pueden reubicar los LIF de datos NAS 2 y agregados no raíz de nodo 3 a nodo 4 y verificar las LIF SAN existentes en el nodo 4.

.Pasos
. link:install_boot_node4.html["Instale y arranque el nodo 4"]
. link:set_fc_or_uta_uta2_config_node4.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 4"]
. link:map_ports_node2_node4.html["Asigne puertos del nodo 2 al nodo 4"]
. link:join_quorum_node_has_different_ports_stage5.html["Unir el quórum cuando un nodo tiene un conjunto diferente de puertos de red"]
. link:verify_node4_installation.html["Verifique la instalación del nodo 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Mueva agregados no raíz y LIF de datos NAS que pertenecen al nodo 2 desde el nodo 3 al nodo 4"]

