---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_health_of_metrocluster_config.html 
keywords: health, metrocluster, alerts 
summary: 'Compruebe el estado de la configuración de MetroCluster y el funcionamiento correcto cuando actualice controladoras que ejecutan ONTAP 9.5 a 9.7 mediante `system controller replace` comandos.' 
---
= Compruebe el estado de la configuración de MetroCluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de iniciar una actualización en una configuración de Fabric MetroCluster, debe comprobar el estado de la configuración de MetroCluster para verificar que la operación sea correcta.

.Pasos
. Compruebe que los componentes de MetroCluster están en buen estado:
+
`metrocluster check run`

+
[listing]
----
dpgqa-mcc-funct-8040-0403_siteA::*> metrocluster check run
----
+
La operación se ejecuta en segundo plano.

. Después del `metrocluster check run` la operación finaliza, vea los resultados:
+
`metrocluster check show`

+
Después de unos cinco minutos, se muestran los siguientes resultados:

+
[listing]
----
metrocluster_siteA::*> metrocluster check show
Last Checked On: 4/7/2019 21:15:05
Component            Result
---------------      -------
nodes                ok
lifs                 ok
config-replication   ok
aggregates           warning
clusters             ok
connections          not-applicable
volumes              ok
7 entries were displayed.
----
. Comprobar el estado de la operación de comprobación de MetroCluster en ejecución:
+
`metrocluster operation history show -job-id 38`

. Compruebe que no hay alertas de estado:
+
`system health alert show`


