= Licencia
:allow-uri-read: 




== Licencia

Cuando configura un clúster, el asistente de configuración le solicita que introduzca la clave de licencia base de clúster. Sin embargo, algunas funciones requieren licencias adicionales, que se emiten como _packages_ que incluyen una o más funciones. Cada nodo del clúster debe tener su propia clave para cada función que se usará en el clúster.

Si no tiene claves de licencia nuevas, las funciones con licencia actualmente en el clúster están disponibles para la nueva controladora. Sin embargo, el uso de funciones sin licencia en la controladora puede dejar de cumplir con el acuerdo de licencia, de modo que debe instalar la nueva clave o las claves de licencia para la nueva controladora una vez que se haya completado la actualización.

Consulte link:other_references.html["Referencias"] Para enlazar con el _sitio de soporte de NetApp_ donde puede obtener nuevas claves de licencia de 2 caracteres de ONTAP. Las claves están disponibles en la sección _My Support_ en _Software licences_. Si el sitio no tiene las claves de licencia que necesita, puede ponerse en contacto con su representante de ventas de NetApp.

Para obtener información detallada sobre las licencias, consulte link:other_references.html["Referencias"] Para vincular a _System Administration Reference_.
