= Comprobar y configurar los puertos UTA/UTA2 en el nodo 3
:allow-uri-read: 




== Comprobar y configurar los puertos UTA/UTA2 en el nodo 3

Si el nodo 3 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe comprobar la configuración de los puertos y es posible que los vuelva a configurar, según cómo desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Si desea utilizar un puerto adaptador de objetivo unificado (UTA/UTA2) para FC, primero debe verificar cómo se ha configurado el puerto.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Puedes utilizar el `ucadmin show` Comando para ver o verificar la configuración actual del puerto, como se muestra en el siguiente ejemplo de salida:

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA2. El modo FC admite el iniciador FC y el destino FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y sea compatible con destinos FC.

Es posible que encuentre puertos UTA/UTA2 en un adaptador adicional o en la placa base del controlador, y que tengan las siguientes configuraciones, pero debería comprobar la configuración de los puertos UTA/UTA2 en el nodo3 y cambiarla, si es necesario:

* LAS tarjetas UTA/UTA2 solicitadas cuando se solicita la controladora se configuran antes del envío para tener la personalidad que solicita.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras se configuran antes del envío para que tengan la personalidad que solicita.
+

WARNING: Debe estar en modo de mantenimiento para configurar los puertos UTA/UTA2.  Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.



.Pasos
. Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. Verifique la configuración del puerto UTA/UTA2:
+
`ucadmin show`

+
Examine la salida y determine si los puertos UTA/UTA2 tienen la personalidad que desea.

+
La salida en el siguiente ejemplo muestra que el tipo de adaptador "1b" está cambiando a iniciador y que el modo de los adaptadores "2a" y "2b" está cambiando a "cna".  El modo CNA le permite utilizar la tarjeta como un adaptador de red.

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. Realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si los puertos UTA/UTA2... | Entonces… 


| No tenga la personalidad que usted desea | Vaya a <<auto_check3_step4,Paso 4>>. 


| Tenga la personalidad que usted desea | Omita los pasos 4 a 8 y vaya a<<auto_check3_step9,Paso 9>> . 
|===
. [[auto_check3_step4]]Realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si va a configurar... | Entonces… 


| Puertos en una tarjeta UTA/UTA2 | Ir a<<auto_check3_step5,Paso 5>> 


| Puertos UTA/UTA2 integrados | Omite el paso 5 y ve a<<auto_check3_step6,Paso 6>> . 
|===
. [[auto_check3_step5]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está en línea, desconecte el puerto UTA/UTA2:
+
`storage disable adapter <adapter_name>`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[auto_check3_step6]]Si la configuración actual no coincide con el uso deseado, cambie la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` es el modo de personalidad, `fc` o. `cna`.
** `-t` Es el tipo FC4, `target` o. `initiator`.
+

NOTE: Debe utilizar el iniciador FC para unidades de cinta y configuraciones de MetroCluster .  Debe utilizar el destino FC para los clientes SAN.



. Coloque cualquier puerto de destino en línea ingresando el siguiente comando una vez para cada puerto:
+
`storage enable adapter <adapter_name>`

. Conecte el cable del puerto.

