= Gestione el cifrado del almacenamiento con el gestor de claves incorporado
:allow-uri-read: 




== Gestione el cifrado del almacenamiento con el gestor de claves incorporado

Usa el Onboard Key Manager (OKM) para gestionar las claves de cifrado. Si tienes el OKM configurado, debes registrar la frase de contraseña y el material de copia de seguridad antes de comenzar la actualización.

.Pasos
. Registre la clave de acceso para todo el clúster.
+
Esta es la frase de acceso que se introdujo cuando se configuró o actualizó OKM con la CLI o la API REST.

. Verifica la frase de contraseña y la operación del key-manager:
+
`security key-manager onboard sync`

+
Cuando te lo pidan, introduce la frase de contraseña OKM para todo el clúster que registraste en el paso anterior.

. Verifica que cc-mode está activado revisando la salida del siguiente comando:
+
`security key-manager config show`

. Haz una copia de seguridad de la información del key-manager:
+
`security key-manager onboard show-backup`


