= Configure los puertos FC en el nodo 3
:allow-uri-read: 




== Configure los puertos FC en el nodo 3

Si el nodo 3 tiene puertos FC, ya sea integrados o en un adaptador FC complementario, debe establecer las configuraciones de los puertos en el nodo antes de ponerlo en servicio porque los puertos no están preconfigurados cuando se envían los sistemas.  Si no configura los puertos, podría experimentar una interrupción en el servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto FC del nodo 1 que haya guardado en la sección link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puede omitir esta sección si el sistema no tiene configuraciones de FC. Si su sistema tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe configurarlos en <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.

.Pasos
. Compare la configuración de FC en el nodo3 con la configuración que capturó anteriormente del nodo1.
. Realice una de las siguientes acciones para modificar los puertos FC en el nodo 3, según sea necesario:
+
En modo de mantenimiento (opción 5 en el menú de arranque):

+
** Para programar como puertos de destino:
+
`ucadmin modify -m fc -t target <adapter>`

+
Por ejemplo: `ucadmin modify -m fc -t target 2a`

** Para programar puertos iniciadores:
+
`ucadmin modify -m fc -t initiator <adapter>`

+
Por ejemplo: `ucadmin modify -m fc -t initator 2b`



. Verifique la nueva configuración utilizando el siguiente comando y examinando el resultado:
+
`ucadmin show`

. Detenga el nodo:
+
`halt`

. Arranque el sistema desde el símbolo del sistema del CARGADOR:
+
`boot_ontap menu`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Seleccione opción `5` desde el menú de arranque para el modo de mantenimiento.

