= 
:allow-uri-read: 



NOTE: El propietario principal de los agregados y las LIF no está modificado; solo se modifica el propietario actual.

.Pasos
. Reanudar las operaciones de movimiento de LIF de datos NAS y reubicación de agregados:
+
`system controller replace resume`

+
Todos los agregados que no son raíz y los LIF de datos NAS están migrados del nodo 1 al nodo 2.

+
La operación se pone en pausa para permitir verificar si todos los agregados que no son raíz del nodo 1 y las LIF de datos que no son SAN se han migrado al nodo 2.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
`system controller replace show-details`

. Con la operación en pausa, verifique que todos los agregados que no son raíz estén en línea para su estado en el nodo 2:
+
`storage aggregate show -node <node2> -state online -root false`

+
En el ejemplo siguiente, los agregados no raíz en el nodo 2 están en línea:

+
[listing]
----
cluster::> storage aggregate show -node node2 -state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
Si los agregados se encuentran sin conexión o en estado no externo en el nodo 2, deben estar en línea usando el siguiente comando en el nodo 2, una vez para cada agregado:

+
`storage aggregate online -aggregate <aggregate_name>`

. Verifique que todos los volúmenes estén en línea en el nodo 2 mediante el siguiente comando en el nodo 2 y examinar su salida:
+
`volume show -node <node2> -state offline`

+
Si alguno de los volúmenes está sin conexión en el nodo 2, debe volver a ponerlos en línea usando el siguiente comando en el nodo 2, una vez para cada volumen:

+
`volume online -vserver <vserver_name> -volume <volume_name>`

+
El  `vserver_name` El uso de este comando se encuentra en la salida del comando anterior.  `volume show` dominio.


