= 
:allow-uri-read: 


. Añada los puertos de iniciador de FC a la cabina de almacenamiento como hosts nuevos y asigne los LUN de cabina a los hosts nuevos.
+
Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. Modifique los valores de nombre de puerto WWPN en el host o los grupos de volúmenes asociados con los LUN de cabina en la cabina de almacenamiento.
+
La instalación de un módulo de controladora nuevo cambia los valores de WWPN asociados con cada puerto FC integrado.

. Si su configuración utiliza la división en zonas basada en switches, ajuste la división en zonas para reflejar los nuevos valores de WWPN.
. [[step27]]ajuste el `bootarg.storageencryption.support` y.. `kmip.init.maxwait` variables para evitar un bucle de arranque después de cargar la configuración 2.
+
Si aún no lo ha hecho anteriormente en el procedimiento, consulte el artículo de la base de conocimientos https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["Cómo indicar que tengo unidades FIPS instaladas"^] para determinar el tipo de unidades de autocifrado que están en uso.

+
[cols="35,65"]
|===
| Si están en uso las siguientes unidades... | Entonces… 


| Unidades de cifrado en almacenamiento de NetApp (NSE) que cumplen con los requisitos de cifrado automático de nivel 2 de FIPS 140-2-2  a| 
** `setenv bootarg.storageencryption.support *true*`
** `setenv kmip.init.maxwait off`




| SED de NetApp no con FIPS  a| 
** `setenv bootarg.storageencryption.support *false*`
** `setenv kmip.init.maxwait off`


|===
+
[NOTE]
====
** No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad.
** Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.
** Si se produce una interrupción del suministro eléctrico después de configurar el `kmip.init.maxwait` variable a. `off`, póngase en contacto con el soporte técnico para obtener ayuda para evitar la posible pérdida de datos.
** Tan pronto como se complete la actualización de la controladora en el par de alta disponibilidad, debe anular la definición del `kmip.init.maxwait` variable. Consulte link:ensure_new_controllers_are_set_up_correctly.html["Confirmar que las nuevas controladoras están configuradas correctamente"].


====
. Nodo de arranque en el menú de arranque:
+
`boot_ontap menu`

+
Si no tiene una configuración FC o UTA/UTA2, ejecute link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15["Comprobar y configurar los puertos UTA/UTA2 en el nodo 4, paso 15"] de modo que el nodo 4 puede reconocer los discos del nodo 2.


