= Paso 1: Configurar puertos FC en nodo4
:allow-uri-read: 




== Paso 1: Configurar puertos FC en nodo4

Si el nodo 4 tiene puertos FC, ya sea integrados o en un adaptador FC complementario, debe establecer las configuraciones de los puertos en el nodo antes de ponerlo en servicio porque los puertos no están preconfigurados cuando se envían los sistemas.  Si no configura los puertos según lo requerido, podría experimentar una interrupción en el servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto de FC en el nodo 2 que haya guardado en la sección link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puedes omitir esta sección si tu sistema no tiene configuraciones FC. Si tu sistema tiene puertos UTA/UTA2 integrados o un adaptador UTA/UTA2, configúralos en <<check-config-uta-uta2-node4,Comprobar y configurar los puertos UTA/UTA2 en el nodo 4>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.

.Pasos
. Mostrar información sobre todos los adaptadores de red convergentes y FC en el sistema:
+
`system node hardware unified-connect show`

. Compare la configuración de FC del nodo 4 con la de los ajustes capturados anteriormente del nodo 1.
. Modifique los puertos FC en el nodo 4 según sea necesario:
+
** Para programar como puertos de destino:
+
`ucadmin modify -m fc -t target _adapter_`

+
Por ejemplo: `ucadmin modify -m fc -t target 2a`

** Para programar puertos iniciadores:
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` Es el tipo FC4: Objetivo o iniciador.

+
Por ejemplo: `ucadmin modify -m fc -t initator 2b`



. Detenga el nodo:
+
`halt`

. Arranque el sistema desde el símbolo del sistema del CARGADOR:
+
`boot_ontap menu`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Seleccione opción `5` desde el menú de arranque para el modo de mantenimiento.

