= 
:allow-uri-read: 


Debe instalar el nodo 3 en el rack, transferir las conexiones del nodo 1 al nodo 3, al nodo de arranque 3 e instalar ONTAP. Después, debe reasignar cualquiera de los discos de repuesto del nodo 1, todos los discos que pertenezcan al volumen raíz y todos los agregados que no sean raíz que no se hayan reubicado al nodo 2 anteriormente en el proceso, como se explica en esta sección.

.Acerca de esta tarea
La operación de reubicación se detiene al principio de esta etapa. Este proceso está en gran medida automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Además, es necesario verificar que las LIF SAN se hayan movido correctamente al nodo 3.

Es necesario reiniciar el nodo 3 si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 1. Después de instalar el nodo 3, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema, siguiendo las instrucciones en link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

[IMPORTANT]
====
* Para actualizar un controlador AFF A800 o AFF C800, debe asegurarse de que todas las unidades en el chasis estén firmemente asentadas contra el plano medio antes de quitar el nodo 1. Para obtener más información, consulte link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["Sustituya los módulos del controlador AFF A800 o AFF C800"].
* Si va a actualizar un sistema V-Series conectado a cabinas de almacenamiento o un sistema con el software de virtualización de FlexArray conectado a cabinas de almacenamiento, debe completar <<auto_install3_step1,Paso 1>> por <<auto_install3_step21,Paso 21>>, luego salga de esta sección y siga las instrucciones de la link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] Secciones según sea necesario, introducir comandos en modo de mantenimiento. A continuación, debe volver a esta sección y reanudar con <<auto_install3_step23,Paso 23>>.
* Si va a actualizar un sistema con discos de almacenamiento, debe completar esta sección completa y, a continuación, ir a la link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] secciones, introducir comandos en el símbolo del sistema del clúster.


====
.Pasos
. [[auto_install3_step1]]Asegúrese de que dispone de espacio en rack para el nodo 3.
+
Si los nodos 1 y 2 están en un chasis separado, puede colocar el nodo 3 en la misma ubicación de rack que el nodo 1. Sin embargo, si el nodo 1 estaba en el mismo chasis con el nodo 2, debe poner el nodo 3 en su propio espacio de rack, preferiblemente cerca de la ubicación del nodo 1.

. [[auto_install3_step2]]instale el nodo 3 en el rack siguiendo las _instrucciones de instalación y configuración_ del modelo de nodo.
+

NOTE: Si va a actualizar a un sistema con ambos nodos del mismo chasis, instale el nodo 4 en el chasis y el nodo 3. Si no lo hace, cuando inicie el nodo 3, el nodo se comportará como si estuviera en una configuración de chasis dual y cuando inicie el nodo 4, la interconexión entre los nodos no se activará.

. [[auto_install3_step3]]nodo de cable 3, moviendo las conexiones del nodo 1 al nodo 3.
+
Conecte los cables siguientes mediante las _Instrucciones de instalación y configuración_ o _Referencia y requisitos de instalación de virtualización de FlexArray_ de la plataforma node3, el documento de bandeja de discos correspondiente y _Gestión de pares de HA_.

+
Consulte link:other_references.html["Referencias"]el enlace para el enlace _FlexArray Virtualization Installation Requirements and Reference_ and _HA pair management_.

+
** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC
+

NOTE: Es posible que no sea necesario mover la tarjeta de interconexión o la conexión del cable de interconexión del clúster del nodo 1 al nodo 3, ya que la mayoría de los modelos de plataforma tienen un modelo de tarjeta de interconexión único. Para la configuración MetroCluster, es necesario mover las conexiones de cables FC-VI del nodo 1 al nodo 3. Si el host nuevo no tiene una tarjeta FC-VI, puede que necesite mover la tarjeta FC-VI.



. [[auto_install3_step4]]Active la alimentación del nodo 3 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al indicador de entorno de arranque.
+
Si va a actualizar a un sistema con ambos nodos del mismo chasis, el nodo 4 también se reinicia. Sin embargo, es posible ignorar el arranque de nodo 4 hasta más adelante.

+

NOTE: Cuando se arranca el nodo 3, es posible que se muestre el siguiente mensaje de advertencia:

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]Si aparece el mensaje de advertencia en <<auto_install3_step4,Paso 4>>, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

WARNING: *Atención: No anular el retardo; si no se permite que la batería se cargue, se podrían producir pérdidas de datos.*

+

NOTE: Consulte link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].




