= Comprobar y configurar los puertos UTA/UTA2 en el nodo 4
:allow-uri-read: 




== Comprobar y configurar los puertos UTA/UTA2 en el nodo 4

Si el nodo 4 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA 2, debe comprobar la configuración de los puertos y configurarlos, según cómo se desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA 2. El modo FC admite iniciador FC y objetivo FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y admite destino FC.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Los puertos UTA/UTA2 pueden estar en un adaptador o en la controladora con las siguientes configuraciones:

* Las tarjetas UTA/UTA2 solicitadas al mismo tiempo que la controladora están configuradas antes del envío para tener la personalidad solicitada.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras están configurados (antes del envío) para tener la personalidad solicitada.


Sin embargo, debe comprobar la configuración de los puertos UTA/UTA2 del nodo 4 y cambiarlo, si es necesario.


WARNING: Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.

.Pasos
. Compruebe cómo están configurados actualmente los puertos en el nodo 4:
+
`system node hardware unified-connect show`

+
El sistema muestra un resultado similar al siguiente ejemplo:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. Compruebe la configuración:
+
`ucadmin show`

+
Examine el resultado del `ucadmin show` Command y determine si los puertos UTA/UTA2 tienen la personalidad que desea.

+
La salida de los siguientes ejemplos muestra que el tipo FC4 del adaptador "1b" está cambiando a. `initiator` y que el modo de los adaptadores "2a" y "2b" está cambiando a. `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si los puertos CNA... | Entonces… 


| No tenga la personalidad que usted desea | Vaya a. <<auto_check_4_step5,Paso 5>>. 


| Tenga la personalidad que usted desea | Omita los pasos 5 a 9 y vaya a<<auto_check_4_step10,Paso 10>> . 
|===
. [[auto_check_4_step5]]realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si va a configurar... | Entonces… 


| Puertos en una tarjeta UTA/UTA2 | Ir a<<auto_check_4_step6,Paso 6>> 


| Puertos UTA/UTA2 integrados | Omite el paso 6 y ve a<<auto_check_4_step7,Paso 7>> . 
|===
. [[auto_check_4_step6]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está en línea, desconecte el puerto UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[auto_check_4_step7]]Si la configuración actual no coincide con el uso deseado, cambie la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` Es el modo personalidad, FC o 10 GbE UTA.
** `-t` Es el tipo FC4, `target` o. `initiator`.
+

NOTE: Debe utilizar el iniciador FC para unidades de cinta y configuraciones de MetroCluster .  Debe utilizar el destino FC para los clientes SAN.



. Coloque cualquier puerto de destino en línea ingresando el siguiente comando, una vez para cada puerto:
+
`storage enable adapter <adapter_name>`

. Conecte el cable del puerto.

