= Conoce las licencias de ONTAP
:allow-uri-read: 




[[learn-about-ontap-licensing]]
== Conoce las licencias de ONTAP

Algunas funciones requieren licencias, que se emiten como _packages_ que incluyen una o más funciones. Cada nodo del clúster debe tener su propia clave para cada función que se usará en el clúster.

Si no tiene claves de licencia nuevas, las funciones con licencia actualmente en el clúster están disponibles para la nueva controladora. Sin embargo, el uso de funciones sin licencia en la controladora puede dejar de cumplir con el acuerdo de licencia, de modo que debe instalar la nueva clave o las claves de licencia para la nueva controladora una vez que se haya completado la actualización.

Consulta link:other-references.html["Referencias"] para enlazar al _NetApp Support Site_, donde puedes obtener nuevas claves de licencia de 28 caracteres para ONTAP. Las claves están disponibles en la sección _My Support_ bajo _Software licenses_. Si el sitio no tiene las claves de licencia que necesitas, puedes contactar a tu representante de ventas de NetApp.

Para obtener información detallada sobre las licencias de ONTAP, consulta link:other-references.html["Referencias"] para enlazar con la _Referencia de administración del sistema_.
