= 
:allow-uri-read: 


Debe instalar el nodo 3 en el rack, transferir las conexiones del nodo 1 al nodo 3, al nodo de arranque 3 e instalar ONTAP. También debe reasignar cualquiera de los discos de repuesto del nodo 1, todos los discos que pertenezcan al volumen raíz y todos los agregados no raíz que no estén ubicados en el nodo 2 anteriormente.

.Acerca de esta tarea
Debe iniciar el nodo 3 mediante netboot si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 1. Después de instalar el nodo 3, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema. Consulte link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

Sin embargo, no es necesario iniciar el nodo 3 mediante netboot si tiene la misma versión o una posterior de ONTAP 9 que está instalada en el nodo 1.

[IMPORTANT]
====
* Para actualizar un controlador AFF A800 o AFF C800 , debe asegurarse de que todas las unidades en el chasis estén firmemente asentadas contra el plano medio antes de quitar el nodo 1. Para obtener más información, consulte link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Sustituya los módulos del controlador AFF A800 o AFF C800"].
* Si está actualizando un sistema con discos de almacenamiento, debe completar toda esta sección y luego ir a link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] , ingresando comandos en el indicador del clúster.


====
.Pasos
. [[man_install3_step1]]Asegúrese de que dispone de espacio en rack para el nodo 3.
+
Si los nodos 1 y 2 están en un chasis separado, puede colocar el nodo 3 en la misma ubicación de rack que el nodo 1. Sin embargo, si node1 estaba en el mismo chasis con node2, debe poner node3 en su propio espacio de rack, preferiblemente cerca de la ubicación de node1.

. [[step2]]instale el nodo 3 en el rack siguiendo las _instrucciones de instalación y configuración_ del modelo de nodo.
+

NOTE: Si está actualizando a un sistema con ambos nodos en el mismo chasis, instale el nodo 4 y el nodo 3 en el chasis. Si no instala ambos nodos en el mismo chasis, cuando inicia el nodo3, se comporta como si estuviera en una configuración de chasis dual y cuando inicia el nodo4, la interconexión entre los nodos no aparece.

. [[step3]]cable node3, moviendo las conexiones del nodo 1 al nodo 3.
+
Las siguientes referencias le ayudan a realizar las conexiones de cable adecuadas. Vaya a. link:other_references.html["Referencias"] para vincularlos.

+
** _Instrucciones de instalación y configuración_ para la plataforma node3
** El procedimiento de la bandeja de discos apropiado
** La documentación _HA pair management_


+
Conectar las siguientes conexiones:

+
** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC
+

NOTE: Es posible que no sea necesario mover la tarjeta de interconexión o la conexión del cable de interconexión del clúster del nodo 1 al nodo 3, ya que la mayoría de los modelos de plataforma tienen un modelo de tarjeta de interconexión único. Para la configuración de MetroCluster, se deben mover las conexiones de cables FC-VI de node1 a node3. Si el host nuevo no tiene una tarjeta FC-VI, puede que necesite mover la tarjeta FC-VI.



. [[man_install3_step4]]Active la alimentación del nodo 3 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al indicador de entorno de arranque.
+
Si va a actualizar a un sistema con ambos nodos del mismo chasis, el nodo 4 también se reinicia. Sin embargo, es posible ignorar el arranque de nodo 4 hasta más adelante.

+

NOTE: Cuando se arranca el nodo 3, es posible que se muestre el siguiente mensaje de advertencia:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]Si aparece el mensaje de advertencia en <<man_install3_step4,Paso 4>>, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

WARNING: *No anule el retraso; si no permite que la batería se cargue, podría perderse información.*



. En el indicador del modo de mantenimiento, ingrese el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema al que va a actualizar está en una... | Realice lo siguiente... 


| Configuración de chasis doble (con controladoras en diferentes chasis) | Vaya a <<man_install3_step8,Paso 8>>. 


| Configuración de chasis único (con controladoras en el mismo chasis)  a| 
.. Cambie el cable de la consola del nodo 3 al nodo 4.
.. Encienda el nodo 4 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al aviso del entorno de arranque.
+
La alimentación debe estar encendida si ambas controladoras están en el mismo chasis.

+

NOTE: Deje el nodo 4 en el aviso del entorno de arranque; regresará al nodo 4 en link:install_boot_node4.html["Instale y arranque el nodo 4"].

.. Si ve el mensaje de advertencia en <<man_install3_step4,Paso 4>>, siga las instrucciones de <<man_install3_step5,Paso 5>>
.. Vuelva a cambiar el cable de la consola del nodo 4 al nodo 3.
.. Vaya a <<man_install3_step8,Paso 8>>.


|===
. [[man_install3_step8]]Configurar el nodo 3 para ONTAP:
+
`set-defaults`


