= 
:allow-uri-read: 


. [[man_install3_step17]] Si la versión de ONTAP instalada en el nodo 3 es la misma o posterior que la versión de ONTAP 9 instalada en el nodo 1, enumerar y reasignar discos al nuevo nodo 3:
+
`boot_ontap`

+

WARNING: Si este nodo nuevo se ha usado alguna vez en cualquier otro clúster o pareja de alta disponibilidad, debe ejecutar `wipeconfig` antes de continuar. De no hacerlo, se pueden producir interrupciones del servicio o pérdida de datos. Póngase en contacto con el soporte técnico si la controladora de reemplazo se utilizó anteriormente, especialmente si las controladoras ejecutaban ONTAP en 7-Mode.

. Presione CTRL-C para mostrar el menú de arranque.
. [[man_install3_step19]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema que desea actualizar... | Realice lo siguiente... 


| _Not_ tiene la versión correcta o actual de ONTAP en el nodo 3 | Vaya a <<man_install3_step13,Paso 13>>. 


| Tiene la versión correcta o actual de ONTAP en el nodo 3 | Vaya a <<man_install3_step18,Paso 18>>. 
|===
. [[man_install3_step13]]Configure la conexión de arranque de red eligiendo una de las siguientes acciones.
+

NOTE: Se deben utilizar el puerto e IP de gestión como conexión para reiniciar el sistema. No utilice una IP de LIF de datos ni ninguna otra interrupción del servicio de datos mientras se realiza la actualización.

+
[cols="35,65"]
|===
| Si el protocolo de configuración dinámica de hosts (DHCP) es... | Realice lo siguiente... 


| Ejecutando | Configure la conexión automáticamente introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -auto` 


| No se está ejecutando  a| 
Configure manualmente la conexión introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Es la dirección IP del sistema de almacenamiento (obligatorio).
`_netmask_` es la máscara de red del sistema de almacenamiento (obligatoria).
`_gateway_` es la puerta de enlace del sistema de almacenamiento (obligatorio).
`_dns_addr_` Es la dirección IP de un servidor de nombres en la red (opcional).
`_dns_domain_` Es el nombre de dominio del servicio de nombres de dominio (DNS). Si utiliza este parámetro opcional, no necesita un nombre de dominio completo en la URL del servidor para reiniciar el sistema; solo necesita el nombre de host del servidor.


NOTE: Es posible que sean necesarios otros parámetros para la interfaz. Introduzca `help ifconfig` en el símbolo del sistema del firmware para obtener detalles.

|===
. Realizar arranque de red en el nodo3:
+
[cols="35,65"]
|===
| Durante... | Realice lo siguiente... 


| Sistemas de la serie FAS/AFF8000 | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| Todos los demás sistemas | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
La `<path_to_the_web-accessible_directory>` lleva al lugar en el que se ha descargado el `<ontap_version>_image.tgz` pulg link:prepare_for_netboot.html#man_netboot_Step1["Paso 1"] En la sección _Prepárese para netboot_.

+

NOTE: No interrumpa el arranque.

. Desde el menú de arranque, seleccione primero la opción *(7) Instalar nuevo software*.
+
Esta opción del menú descarga e instala la nueva imagen de ONTAP en el dispositivo de arranque.

+
Ignore el siguiente mensaje:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota se aplica a las actualizaciones no disruptivas de ONTAP, no a las actualizaciones de controladoras.

+

NOTE: Utilice siempre netboot para actualizar el nodo nuevo a la imagen deseada. Si utiliza otro método para instalar la imagen en la nueva controladora, es posible que se instale una imagen incorrecta. Este problema se aplica a todas las versiones de ONTAP. El procedimiento para reiniciar el sistema combinado con la opción `(7) Install new software` Limpia el soporte de arranque y coloca la misma versión ONTAP de ONTAP en ambas particiones de imagen.

. Si se le solicita que continúe con el procedimiento, ingrese `y` , y cuando se le solicite el paquete, ingrese la siguiente URL:
+
`\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. Complete los siguientes subpasos:
+
.. Introduzca `n` para omitir la recuperación del backup cuando aparezca la siguiente solicitud:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Reinicie introduciendo `y` cuando vea el siguiente símbolo del sistema:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
El módulo del controlador se reinicia pero se detiene en el menú de arranque porque se reformateó el dispositivo de arranque y es necesario restaurar los datos de configuración.



. [[man_install3_step18]]Seleccione *(5) Modo de mantenimiento de arranque* ingresando `5` , y luego entrar `y` cuando se le solicite continuar con el arranque.
. [[man_install3_step26]]antes de continuar, vaya a. link:set_fc_uta_uta2_config_node3.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 3"] Se deben realizar los cambios necesarios en los puertos FC o UTA/UTA2 del nodo.
+
Realice los cambios recomendados en esas secciones, reinicie el nodo y vaya al modo de mantenimiento.

. Encuentre el ID del sistema del nodo3:
+
`disk show -a`

+
El sistema muestra el ID del sistema del nodo e información acerca de sus discos, como se muestra en el ejemplo siguiente:

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: Puede que vea el mensaje `disk show: No disks match option -a.` tras introducir el comando. Este no es un mensaje de error para que pueda continuar con el procedimiento.

. [[man_install3_step21]]Reasigne los discos de repuesto del nodo 1, cualquier disco que pertenezca a la raíz y cualquier agregado que no sea raíz que no se haya reubicado anteriormente en el nodo 2.link:relocate_non_root_aggr_node1_node2.html["Cambie la ubicación de los agregados que no son raíz del nodo 1 al nodo 2"] .
+
Introduzca la forma adecuada del `disk reassign` comando basado en si su sistema tiene discos compartidos:

+

NOTE: Si ha compartido discos, agregados híbridos o ambos en el sistema, debe utilizar los correctos `disk reassign` desde la siguiente tabla.

+
[cols="35,65"]
|===
| Si el tipo de disco es... | Después, ejecute el comando... 


| Con discos compartidos | `disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysid_` 


| Sin discos compartidos | `disk reassign -s _node1_sysid_ -d _node3_sysid_` 
|===
+
Para la `_node1_sysid_` utilice la información capturada en link:record_node1_information.html["Registre la información del nodo 1"]. Para obtener el valor de `_node3_sysid_`, utilice la `sysconfig` comando.

+

NOTE: La `-p` la opción solo es necesaria en modo de mantenimiento cuando hay discos compartidos presentes.

+
La `disk reassign` el comando reasigna solo aquellos discos para los que `_node1_sysid_` es el propietario actual.

+
El sistema muestra el siguiente mensaje:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]]Introduzca `n`.
+
El sistema muestra el siguiente mensaje:

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]]Introduzca `y`
+
El sistema muestra el siguiente mensaje:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]]Introduzca `y`.
. [[man_install3_step32]]Si va a actualizar desde un sistema con discos externos a un sistema que admita discos internos y externos (sistemas AFF A800, por ejemplo), establezca el agregado 1-1 como raíz para confirmar que el nodo 3 arranque desde el agregado raíz del nodo 1.
+

WARNING: *Advertencia*: Debe realizar los siguientes subpasos en el orden exacto que se muestra; de lo contrario, podría causar una interrupción o incluso pérdida de datos.

+
El siguiente procedimiento establece el nodo 3 para arrancar desde el agregado raíz del nodo 1:

+
.. Compruebe la información de RAID, plex y suma de comprobación para el agregado 1-1:
+
`aggr status -r`

.. Compruebe el estado del agregado 1-1:
+
`aggr status`

.. Coloque el agregado del nodo 1 en línea, si es necesario:
+
`aggr_online _root_aggr_from_node1_`

.. Impida que el nodo 3 arranque desde su agregado raíz original:
`aggr offline _root_aggr_on_node3_`
.. Establezca el agregado raíz del nodo 1 como el nuevo agregado raíz del nodo 3:
+
`aggr options _aggr_from_node1_ root`

.. Compruebe que el agregado raíz del nodo 3 esté sin conexión y que el agregado raíz de los discos extraídos del nodo 1 esté en línea y establecido en raíz:
+
`aggr status`

+

NOTE: Si no se pudo realizar el subpaso anterior, el nodo 3 se puede arrancar desde el agregado raíz interno, o bien es posible que el sistema asuma que existe una nueva configuración de clúster o que se le solicite identificar una.

+
El siguiente muestra un ejemplo de resultado del comando:



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]]Compruebe que el controlador y el chasis están configurados como `ha`:
+
`ha-config show`

+
En el siguiente ejemplo se muestra el resultado del comando ha-config show:

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
Los sistemas graban en una ROM programable (PROM) tanto si se encuentran en un par ha como en una configuración independiente. El estado debe ser el mismo en todos los componentes del sistema independiente o del par de alta disponibilidad.

+
Si la controladora y el chasis no están configurados como "ha", utilice los siguientes comandos para corregir la configuración:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si tiene una configuración MetroCluster, utilice los siguientes comandos para modificar la controladora y el chasis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[man_install3_step34]]destruya los buzones del nodo 3:
+
`mailbox destroy local`

+
La consola muestra el siguiente mensaje:

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]]Introduzca `y` cuando el sistema le solicite que confirme que desea destruir los buzones locales.
. [[man_install3_step36]]salir del modo de mantenimiento:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. [[man_install3_step37]]en el nodo 2, compruebe la fecha, la hora y la zona horaria del sistema:
+
`date`

. [[man_install3_step38]]en el nodo 3, compruebe la fecha en el indicador de entorno de arranque:
+
`show date`

. [[man_install3_step39]]Si es necesario, establezca la fecha en node3:
+
`set date _mm/dd/yyyy_`

. [[man_install3_step40]]en el nodo 3, compruebe la hora en el indicador de entorno de arranque:
+
`show time`

. [[man_install3_step41]]Si es necesario, establezca la hora en node3:
+
`set time _hh:mm:ss_`

. [[man_install3_step42]]Verifique que el ID del sistema asociado esté configurado correctamente como se indica en<<man_install3_step21,Paso 21>> bajo el modificador -p:
+
`printenv partner-sysid`

. [[man_install3_step43]]Si es necesario, establezca el ID del sistema asociado en el nodo 3:
+
`setenv partner-sysid _node2_sysid_`

+
Guarde los ajustes:

+
`saveenv`

. [[man_install3_step44]]Acceda al menú de inicio en el indicador de entorno de arranque:
+
`boot_ontap menu`

. [[man_install3_step45]]en el menú de inicio, seleccione la opción *(6) Actualizar flash desde backup config* introduciendo `6` en el prompt de.
+
El sistema muestra el siguiente mensaje:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]]Introduzca `y` en el prompt de.
+
El arranque continúa con normalidad y el sistema le pide que confirme que el ID del sistema no coincide.

+

NOTE: El sistema puede reiniciarse dos veces antes de mostrar la advertencia de no coincidencia.

. [[man_install3_step47]]confirme la discrepancia como se muestra en el ejemplo siguiente:
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
Es posible que el nodo pase por una ronda de reinicio antes de arrancar normalmente.

. [[man_install3_step48]]Inicie sesión en el nodo 3.

