= Comprobar y configurar los puertos UTA/UTA2 en el nodo 4
:allow-uri-read: 




== Comprobar y configurar los puertos UTA/UTA2 en el nodo 4

Si el nodo 4 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA 2, debe comprobar la configuración de los puertos y configurarlos, según cómo se desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA 2. El modo FC admite el iniciador FC y el destino FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y admita el destino FC.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Los puertos UTA/UTA2 pueden estar en un adaptador o en la controladora con las siguientes configuraciones:

* Las tarjetas UTA/UTA2 solicitadas al mismo tiempo que la controladora están configuradas antes del envío para tener la personalidad solicitada.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras están configurados (antes del envío) para tener la personalidad solicitada.


Sin embargo, puede comprobar la configuración de los puertos UTA/UTA2 del nodo 4 y cambiarlo, si es necesario.


WARNING: Ingrese los comandos de esta sección en el indicador del clúster, a menos que se le indique que ingrese al modo de mantenimiento.  Si tiene un sistema MetroCluster FC, debe estar en modo de mantenimiento para configurar los puertos UTA/UTA2.

.Pasos
. Compruebe cómo están configurados actualmente los puertos en el nodo 4:
+
`system node hardware unified-connect show`

. Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. Examine el resultado del `system node hardware unified-connect show` o. `ucadmin show` Command y determine si los puertos UTA/UTA2 tienen la personalidad que desea.
. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si los puertos CNA... | Realice lo siguiente... 


| No tenga la personalidad que usted desea | Vaya a. <<man_check_4_Step5,Paso 5>>. 


| Tenga la personalidad que usted desea | Pase los pasos 5 a 12 y vaya a. <<man_check_4_Step13,Paso 13>>. 
|===
. [[man_check_4_Step5]]Si el sistema tiene discos de almacenamiento y está ejecutando Data ONTAP 8.3, inicie el nodo 4 e ingrese al modo de mantenimiento:
+
`boot_ontap maint`

. Verifique la configuración introduciendo el siguiente comando y examinando su resultado:
+
`ucadmin show`

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si va a configurar... | Realice lo siguiente... 


| En una tarjeta UTA/UTA 2 | Vaya a <<man_check_4_Step8,Paso 8>>. 


| Puertos UTA/UTA2 integrados | Omite el paso 8 y ve a<<man_check_4_Step9,Paso 9>> . 
|===
. [[man_check_4_Step8]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está en línea, desconecte el puerto UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[man_check_4_Step9]]Si la configuración actual no coincide con el uso deseado, ingrese el siguiente comando para cambiar la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Es el modo personalidad: FC o 10 GbE UTA.
** `-t` Es el tipo FC4: Objetivo o iniciador.


+

NOTE: Debe utilizar el iniciador FC para unidades de cinta y el destino FC para clientes SAN.

. Si el sistema tiene discos de almacenamiento, ingrese el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

+
.. Introduzca el siguiente comando:
+
`boot_ontap`



. Si el sistema tiene discos de almacenamiento, ingrese el siguiente comando:
+
`system node hardware unified-connect show`

+
La salida de los siguientes ejemplos muestra que el tipo FC4 del adaptador "1b" está cambiando a. `initiator` y que el modo de los adaptadores "2a" y "2b" está cambiando a. `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. Coloque los puertos de destino en línea introduciendo uno de los siguientes comandos, una vez por cada puerto:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[Man_check_4_step13]]Conecte el puerto.

