= 
:allow-uri-read: 


Antes de poder sustituir node2 con node4, debe enviar un mensaje de AutoSupport para node2 y, a continuación, reubicar los agregados no raíz que node2 posee a node3.


CAUTION: Durante este procedimiento, no reubique agregados de node3 a node2. Esto provoca que los agregados se desconecten y una interrupción de datos para los agregados que se reubican.

[[verify-partner-sys-id]]
.Pasos
. Compruebe que el ID del sistema asociado está definido correctamente en node3 :
+
.. Introduzca el nivel de privilegio avanzado:
+
`set -privilege advanced`

.. Mostrar el ID del sistema asociado en node3:
+
`ha interconnect config show -node <node3-node1>`

+
El sistema muestra un resultado similar al siguiente ejemplo:

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. Si el identificador del sistema asociado es incorrecto para node3:
+
.. Parada node3:
+
`halt`

.. En el aviso de Loader, defina el valor correcto de «sisid del partner».
+
El node3 “partner-sysid” es el ID del sistema de node2, que se puede encontrar en la `ha interconnect config show` salida en <<verify-partner-sys-id,Paso 1>>.

.. Guarde los ajustes:
+
`saveenv`

.. En el símbolo del sistema de Loader, arranque node3 en el menú de arranque:
+
`boot_ontap menu`

.. Inicie sesión en node3.


. Envíe un mensaje de AutoSupport a NetApp para node2:
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. Compruebe que se ha enviado el mensaje de AutoSupport:
+
`system node autosupport show -node <node2> -instance`

+
Los campos "último asunto enviado:" y "última vez enviado:" contienen el título del último mensaje que se envió y la hora en que se envió el mensaje.

. Reubicar los agregados no raíz:
+
.. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

.. Enumere los agregados que son propiedad de 2:
+
`storage aggregate show -owner-name <node2>`

.. Iniciar reubicación de agregado:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: El comando busca solo agregados que no son raíz.

.. Cuando se le solicite, introduzca `y`.
+
La reubicación se produce en segundo plano. La reubicación de un agregado puede tardar entre unos segundos y un par de minutos. El tiempo incluye tanto la interrupción del servicio como las partes que no son de la interrupción del servicio. El comando no reubica ningún agregado sin conexión ni restringido.

.. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



. Verificar el estado de reubicación del nodo 2:
+
`storage aggregate relocation show -node <node2>`

+
La salida muestra “Listo” para un agregado después de que se haya reubicado.

+

NOTE: Debe esperar hasta que todos los agregados de los que son propiedad del nodo 2 se hayan reubicado en el nodo 3 antes de continuar con el siguiente paso.

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si la reubicación de... | Realice lo siguiente... 


| Todos los agregados se han realizado correctamente | Vaya a <<man_relocate_2_3_step8,Paso 8>>. 


| Todos los agregados han fallado o se ha vetado  a| 
.. Mostrar un mensaje de estado detallado:
+
`storage aggregate show -instance`

+
También puede consultar los registros de EMS para ver la acción correctiva que es necesaria.

+

NOTE: La `event log show` comando muestra todos los errores que se han producido.

.. Realice la acción correctiva.
.. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

.. Reubicar agregados que fallen o vetados:
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. Cuando se le solicite, introduzca `y`.
.. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



Si es necesario, puede forzar la reubicación mediante uno de los siguientes métodos:

** Mediante la anulación de las comprobaciones de veto:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** Mediante la anulación de comprobaciones de destino:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Para obtener más información sobre los comandos de reubicación de agregados de almacenamiento, vaya a. link:other_references.html["Referencias"] Para establecer un vínculo a la gestión de discos y agregados con la CLI_ y los comandos _ONTAP 9: Manual Page Reference_.

|===
. [[man_relocate_2_3_step8]]Verifique que todos los agregados no raíz estén en línea en node3:
+
`storage aggregate show -node <node3> -state offline -root false`

+
Si alguno de los agregados se ha desconectado o se ha convertido en externo, debe conectarlos, una vez por cada agregado:

+
`storage aggregate online -aggregate <aggregate_name>`

. Verifique que todos los volúmenes estén en línea en el nodo 3:
+
`volume show -node <node3> -state offline`

+
Si alguno de los volúmenes se encuentra sin conexión en el nodo 3, es necesario conectarlos, una vez por cada volumen:

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. Compruebe que node2 no posee ningún agregado no raíz en línea:
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
El resultado del comando no debe mostrar agregados no raíz en línea, ya que todos los agregados en línea no raíz ya se han reubicado al nodo 3.


