= 
:allow-uri-read: 


Debe instalar el nodo 4 en el rack, transferir las conexiones 2 a nodo 4 y el nodo de arranque 4. También debe reasignar todos los repuestos de nodo 2, todos los discos que pertenezcan a raíz y todos los agregados que no sean raíz que no se hayan reubicado al nodo 3 anterior.

.Acerca de esta tarea
Debe iniciar el nodo 4 mediante netboot si no tiene la misma versión de ONTAP 9 instalada en el nodo 2. Después de instalar el nodo 4, arranque desde la imagen ONTAP 9 almacenada en el servidor web. Luego, puede descargar los archivos correctos al dispositivo de arranque para los siguientes arranques del sistema siguiendo las instrucciones de link:prepare_for_netboot.html["Prepárese para el arranque desde el red"] .

Sin embargo, no es necesario iniciar el nodo 4 desde la red si tiene la misma versión o una versión posterior de ONTAP 9 que está instalada en el nodo 2.

[IMPORTANT]
====
* Para actualizar un controlador AFF A800 o AFF C800 , debe asegurarse de que todas las unidades en el chasis estén firmemente asentadas contra el plano medio antes de quitar el nodo 2. Para obtener más información, consulte link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["Sustituya los módulos del controlador AFF A800 o AFF C800"].
* Si está actualizando un sistema con discos de almacenamiento, debe completar toda esta sección y luego continuar con la sección link:set_fc_uta_uta2_config_node4.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 4"] , ingresando comandos en el indicador del clúster.


====
.Pasos
. [[man_install4_Step1]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el nodo 4 estará en... | Realice lo siguiente... 


| Un chasis separado del nodo 3 | Vaya a. <<man_install4_Step2,Paso 2>>. 


| El mismo chasis con el nodo 3 | Evite los pasos 2 y 3 y vaya a. <<man_install4_Step4,Paso 4>>. 
|===
. [[man_install4_Step2]] Asegúrese de que el nodo 4 tenga suficiente espacio en rack.
+
Si el nodo 4 se encuentra en un chasis separado del nodo 3, es posible colocar el nodo 4 en la misma ubicación que el nodo 2. Si el nodo 3 y el nodo 4 se encuentran en el mismo chasis, el nodo 4 ya se encuentra en la ubicación de rack adecuada.

. Instale el nodo 4 en el rack, siguiendo las instrucciones de _Installation and Setup_ para el modelo de nodo.
. [[man_install4_Step4]]nodo de cable 4, moviendo las conexiones del nodo 2 al nodo 4.
+
Las siguientes referencias le ayudan a realizar las conexiones de cable adecuadas. Vaya a. link:other_references.html["Referencias"] para vincularlos.

+
** _Instrucciones de instalación y configuración_ para la plataforma node4
** El procedimiento de la bandeja de discos apropiado
** La documentación _HA pair management_
+
Conectar las siguientes conexiones:

** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC


+

NOTE: No es necesario mover la conexión de cable de la tarjeta de interconexión/FC_VI o de interconexión/FC_VI del nodo 2 al nodo 4, ya que la mayoría de los modelos de plataforma tienen modelos de tarjeta de interconexión únicos.

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el nodo 4 está en... | Realice lo siguiente... 


| El mismo chasis que el nodo 3 | Vaya a. <<man_install4_Step8,Paso 8>>. 


| Un chasis separado del nodo 3 | Vaya a. <<man_install4_Step6,Paso 6>>. 
|===
. [[MAN_install4_Step6]]Encienda la alimentación a node4 y, a continuación, interrumpa el arranque pulsando Ctrl-C para acceder a la petición de datos del entorno de inicio.
+

NOTE: Cuando se arranca el nodo 4, es posible que se muestre el siguiente mensaje:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]Si aparece el mensaje de advertencia en el paso 6, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

WARNING: *No anule el retraso.  Si no se permite que la batería se cargue, podría producirse una pérdida de datos.*



. [[man_install4_Step8]]En el indicador del modo de mantenimiento, ingrese el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. Configure el nodo 4 para ONTAP:
+
`set-defaults`


