= Comprobar y configurar los puertos UTA/UTA2 en el nodo 4
:allow-uri-read: 




== Comprobar y configurar los puertos UTA/UTA2 en el nodo 4

Si el nodo 4 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA 2, debe comprobar la configuración de los puertos y configurarlos, según cómo se desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA 2. El modo FC admite el iniciador FC y el destino FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y admita el destino FC.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Los puertos UTA/UTA2 pueden estar en un adaptador o en la controladora con las siguientes configuraciones:

* Las tarjetas UTA/UTA2 solicitadas al mismo tiempo que la controladora están configuradas antes del envío para tener la personalidad solicitada.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras están configurados (antes del envío) para tener la personalidad solicitada.


Sin embargo, puede comprobar la configuración de los puertos UTA/UTA2 del nodo 4 y cambiarlo, si es necesario.

*Atención*: Si el sistema tiene discos de almacenamiento, debe introducir los comandos de esta sección en el indicador del clúster a menos que se le indique entrar en modo de mantenimiento. Si tiene un sistema FC de MetroCluster, un sistema V-Series o un sistema con software de virtualización FlexArray conectado a cabinas de almacenamiento, debe estar en modo de mantenimiento para configurar puertos UTA/UTA2.

.Pasos
. Compruebe cómo se configuran los puertos actualmente mediante uno de los siguientes comandos del nodo 4:
+
[cols="35,65"]
|===
| Si el sistema... | Entonces… 


| Tiene discos de almacenamiento | `system node hardware unified-connect show` 


| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a las cabinas de almacenamiento | `ucadmin show` 
|===
+
El sistema muestra un resultado similar al siguiente ejemplo:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. Examine el resultado del `system node hardware unified-connect show` o. `ucadmin show` Command y determine si los puertos UTA/UTA2 tienen la personalidad que desea.
. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si los puertos CNA... | Realice lo siguiente... 


| No tenga la personalidad que usted desea | Vaya a. <<man_check_4_Step5,Paso 5>>. 


| Tenga la personalidad que usted desea | Pase los pasos 5 a 12 y vaya a. <<man_check_4_Step13,Paso 13>>. 
|===
. [[Man_check_4_Step5]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema... | Realice lo siguiente... 


| Tiene discos de almacenamiento y ejecuta Data ONTAP 8.3 | Arrancar el nodo 4 e introducir modo de mantenimiento:
`boot_ontap maint` 


| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a las cabinas de almacenamiento | Vaya a. <<man_check_4_Step6,Paso 6>>. Ya debe estar en modo de mantenimiento. 
|===
. [[Man_check_4_Step6]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si va a configurar... | Realice lo siguiente... 


| En una tarjeta UTA/UTA 2 | Vaya a. <<man_check_4_Step7,Paso 7>>. 


| Puertos UTA/UTA2 integrados | Vaya al paso 7 y vaya a. <<man_check_4_Step8,Paso 8>>. 
|===
. [[man_check_4_Step7]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está conectado, tenga el puerto UTA/UTA2 desconectado:
+
`storage disable adapter _adapter_name_`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[Man_check_4_Step8]]Si la configuración actual no coincide con el uso deseado, introduzca el siguiente comando para cambiar la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` Es el modo personalidad: FC o 10 GbE UTA.
** `-t` Es el tipo FC4: Objetivo o iniciador.


+

NOTE: Se debe usar iniciador FC para las unidades de cinta y los sistemas de virtualización FlexArray. Debe usar el destino FC para los clientes SAN.

. Verifique la configuración introduciendo el siguiente comando y examinando su resultado:
+
`ucadmin show`

. Ejecute una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema... | Realice lo siguiente... 


| Tiene discos de almacenamiento  a| 
.. Introduzca el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

.. Introduzca el siguiente comando:
+
`boot_ontap`





| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a cabinas de almacenamiento y funciona con Data ONTAP 8.3 | Reinicie al modo de mantenimiento:
`boot_ontap maint` 
|===
. Compruebe la configuración:
+
[cols="35,65"]
|===
| Si el sistema... | Realice lo siguiente... 


| Tiene discos de almacenamiento | Introduzca el siguiente comando:
`system node hardware unified-connect show` 


| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a las cabinas de almacenamiento | Introduzca el siguiente comando:
`ucadmin show` 
|===
+
La salida de los siguientes ejemplos muestra que el tipo FC4 del adaptador "1b" está cambiando a. `initiator` y que el modo de los adaptadores "2a" y "2b" está cambiando a. `cna`.

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----
. Coloque los puertos de destino en línea introduciendo uno de los siguientes comandos, una vez por cada puerto:
+
[cols="35,65"]
|===
| Si el sistema... | Realice lo siguiente... 


| Tiene discos de almacenamiento | `network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up` 


| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a las cabinas de almacenamiento | `fcp config _adapter_name_ up` 
|===
. [[Man_check_4_step13]]Conecte el puerto.
. Ejecute una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema... | Realice lo siguiente... 


| Tiene discos de almacenamiento | Vaya a. link:map_ports_node2_node4.html["Asigne puertos del nodo 2 al nodo 4"]. 


| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a las cabinas de almacenamiento | Vuelva a la sección _Install and boot node4_ y reanude la sección en link:install_boot_node4.html#man_install4_Step9["Paso 9"]. 
|===

