= Configure los puertos FC en el nodo 4
:allow-uri-read: 




== Configure los puertos FC en el nodo 4

Si el nodo 4 tiene puertos FC, ya sea integrados o de un adaptador de FC, se deben establecer configuraciones de puertos en el nodo antes de llevarlo al servicio, ya que los puertos no están preconfigurados. Si no se configuran los puertos, es posible que experimente una interrupción del servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto de FC en el nodo 2 que haya guardado en la sección link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puede omitir esta sección si el sistema no tiene configuraciones de FC. Si su sistema tiene puertos UTA/UTA2 integrados o un adaptador UTA/UTA2, debe configurarlos en <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 4>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador del clúster.

.Pasos
. Mostrar información sobre todos los adaptadores de red convergentes y FC en el sistema:
+
`system node hardware unified-connect show`

. Compare la configuración de FC de los nodos nuevos con la configuración que ha capturado anteriormente del nodo original.
. Modifique los puertos FC en el nodo 4 según sea necesario:
+
** Para programar puertos de destino:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Para programar puertos iniciadores:
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type` Es el tipo, destino o iniciador de FC4.



. Verifique la nueva configuración ingresando el siguiente comando y examinando el resultado:
+
`system node unified-connect show`

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si la configuración de FC predeterminada en los nodos nuevos es... | Entonces… 


| Igual que los que ha capturado en los nodos originales | Vaya a <<man_config_4_Step9,Paso 9>>. 


| Es diferente de la que ha capturado en los nodos originales | Vaya a <<man_config_4_Step6,Step6>>. 
|===
. [[man_config_4_Step6]]Salir del modo de mantenimiento:
+
`halt`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Arranque el nodo 4 ingresando el siguiente comando en el indicador del entorno de arranque:
+
`boot_ontap`

. [[man_config_4_Step9]]Realice una de las siguientes acciones:
+
** Vaya a. <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 4>> Si el nodo 4 tiene una tarjeta UTA/UTA 2 o puertos UTA/UTA2 integrados.
** Omita la sección y vaya a. link:map_ports_node2_node4.html["Asigne puertos del nodo 2 al nodo 4"] Si el nodo 4 no tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados.



