= 
:allow-uri-read: 


Debe instalar el nodo 4 en el rack, transferir las conexiones 2 a nodo 4 y el nodo de arranque 4. También debe reasignar todos los repuestos de nodo 2, todos los discos que pertenezcan a raíz y todos los agregados que no sean raíz que no se hayan reubicado al nodo 3 anterior.

.Acerca de esta tarea
Debe reiniciar el nodo 4 si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 2. Después de instalar el nodo 4, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema siguiendo las instrucciones en link:prepare_for_netboot.html["Prepárese para el arranque desde el red"]

Sin embargo, no es necesario que netboot node4 si tiene la misma versión o posterior de ONTAP 9 que está instalada en node2.

*Información importante:*

* Si va a actualizar un sistema V-Series o un sistema con software de virtualización FlexArray conectado a cabinas de almacenamiento, debe completar <<man_install4_Step1,Paso 1>> por <<man_install4_Step7,Paso 7>>, deje esta sección en <<man_install4_Step8,Paso 8>> y siga las instrucciones de link:set_fc_uta_uta2_config_node4.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 4"] Según sea necesario, introduzca los comandos en modo de mantenimiento. A continuación, debe volver a esta sección y reanudar el procedimiento en <<man_install4_Step9,Paso 9>>.
* Sin embargo, si va a actualizar un sistema con discos de almacenamiento, debe completar toda esta sección y luego continuar con la sección link:set_fc_uta_uta2_config_node4.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 4"], introduciendo comandos en el símbolo del sistema del clúster.


.Pasos
. [[man_install4_Step1]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el nodo 4 estará en... | Realice lo siguiente... 


| Un chasis separado del nodo 3 | Vaya a. <<man_install4_Step2,Paso 2>>. 


| El mismo chasis con el nodo 3 | Evite los pasos 2 y 3 y vaya a. <<man_install4_Step4,Paso 4>>. 
|===
. [[man_install4_Step2]] Asegúrese de que el nodo 4 tenga suficiente espacio en rack.
+
Si el nodo 4 se encuentra en un chasis separado del nodo 3, es posible colocar el nodo 4 en la misma ubicación que el nodo 2. Si el nodo 3 y el nodo 4 se encuentran en el mismo chasis, el nodo 4 ya se encuentra en la ubicación de rack adecuada.

. Instale el nodo 4 en el rack, siguiendo las instrucciones de _Installation and Setup_ para el modelo de nodo.
. [[man_install4_Step4]]nodo de cable 4, moviendo las conexiones del nodo 2 al nodo 4.
+
Las siguientes referencias le ayudan a realizar las conexiones de cable adecuadas. Vaya a. link:other_references.html["Referencias"] para vincularlos.

+
** _Instrucciones de instalación y configuración_ o _FlexArray requisitos de instalación y referencia_ para la plataforma node4
** El procedimiento de la bandeja de discos apropiado
** La documentación _HA pair management_
+
Conectar las siguientes conexiones:

** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC


+

NOTE: No es necesario mover la conexión de cable de la tarjeta de interconexión/FC_VI o de interconexión/FC_VI del nodo 2 al nodo 4, ya que la mayoría de los modelos de plataforma tienen modelos de tarjeta de interconexión únicos.

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el nodo 4 está en... | Realice lo siguiente... 


| El mismo chasis que el nodo 3 | Vaya a. <<man_install4_Step8,Paso 8>>. 


| Un chasis separado del nodo 3 | Vaya a. <<man_install4_Step6,Paso 6>>. 
|===
. [[MAN_install4_Step6]]Encienda la alimentación a node4 y, a continuación, interrumpa el arranque pulsando Ctrl-C para acceder a la petición de datos del entorno de inicio.
+

NOTE: Cuando se arranca el nodo 4, es posible que se muestre el siguiente mensaje:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7]]Si aparece el mensaje de advertencia en el paso 6, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

WARNING: *Advertencia: No anule el retraso. Si no se permite la carga de la batería, se podrían producir pérdidas de datos.*



. [[man_install4_Step8]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si su sistema... | Realice lo siguiente... 


| Cuenta con discos y sin almacenamiento de gestión | Pase los pasos 9 a 14 y vaya a. <<man_install4_Step15,Paso 15>>. 


| Es un sistema V-Series o tiene software de virtualización FlexArray y se conecta a las cabinas de almacenamiento  a| 
.. Vaya a la sección _set la configuración de FC o UTA/UTA2 en el nodo 4_ y complete las secciones link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["Configure los puertos FC en el nodo 4"] y.. link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["Comprobar y configurar los puertos UTA/UTA2 en el nodo 4"], según corresponda a su sistema.
.. Vuelva a esta sección y complete los pasos restantes, empezando por <<man_install4_Step9,Paso 9>>.



IMPORTANT: Debe reconfigurar los puertos FC internos, los puertos UTA/UTA2 internos y las tarjetas UTA/UTA2 antes de arrancar ONTAP en el sistema V-Series.

|===
. [[man_install4_Step9]]Añada los puertos iniciadores FC del nuevo nodo a las zonas del switch.
+
Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. Añada los puertos de iniciador de FC a la cabina de almacenamiento como hosts nuevos y asigne los LUN de cabina a los hosts nuevos.
+
Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. Modifique los valores de nombre de puerto WWPN en el host o los grupos de volúmenes asociados con los LUN de cabina en la cabina de almacenamiento.
+
La instalación de un módulo de controladora nuevo cambia los valores de WWPN asociados con cada puerto FC integrado.

. Si su configuración utiliza la división en zonas basada en switches, ajuste la división en zonas para reflejar los nuevos valores de WWPN.
. Verifique que los LUN de cabina ahora sean visibles para el nodo 4. Para ello, introduzca el siguiente comando y examine su resultado:
+
`sysconfig -v`

+
El sistema muestra todas las LUN de cabina que son visibles para cada uno de los puertos iniciadores FC. Si los LUN de cabina no son visibles, no se pueden reasignar los discos del nodo 2 al nodo 4 más adelante en esta sección.

. Pulse Ctrl-C para mostrar el menú de arranque y seleccione Modo de mantenimiento.
. [[man_install4_Step15]]en el símbolo del sistema del modo de mantenimiento, introduzca el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. Configure el nodo 4 para ONTAP:
+
`set-defaults`


