= 
:allow-uri-read: 


Debe instalar el nodo 3 en el rack, transferir las conexiones del nodo 1 al nodo 3, al nodo de arranque 3 e instalar ONTAP. También debe reasignar cualquiera de los discos de repuesto del nodo 1, todos los discos que pertenezcan al volumen raíz y todos los agregados no raíz que no estén ubicados en el nodo 2 anteriormente.

.Acerca de esta tarea
Debe reiniciar el nodo 3 si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 1. Después de instalar el nodo 3, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema. Consulte link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

Sin embargo, no es necesario reiniciar el nodo 3 si tiene la misma versión o una posterior de ONTAP 9 que está instalada en el nodo 1.

[IMPORTANT]
====
Si va a actualizar un sistema V-Series conectado a cabinas de almacenamiento o un sistema con el software de virtualización de FlexArray conectado a cabinas de almacenamiento, debe completar <<man_install3_step1,Paso 1>> por <<man_install3_step5,Paso 5>>, deje esta sección en <<man_install3_step6,Paso 6>> y siga las instrucciones de link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] según sea necesario, introduzca los comandos en modo de mantenimiento. A continuación, debe volver a esta sección y reanudar con <<man_install3_step7,Paso 7>>.

Sin embargo, si va a actualizar un sistema con discos de almacenamiento, debe completar toda esta sección y, a continuación, vaya a. link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"], introduciendo comandos en el símbolo del sistema del clúster.

====
.Pasos
. [[man_install3_step1]]Asegúrese de que dispone de espacio en rack para el nodo 3.
+
Si los nodos 1 y 2 están en un chasis separado, puede colocar el nodo 3 en la misma ubicación de rack que el nodo 1. Sin embargo, si node1 estaba en el mismo chasis con node2, debe poner node3 en su propio espacio de rack, preferiblemente cerca de la ubicación de node1.

. [[step2]]instale el nodo 3 en el rack siguiendo las _instrucciones de instalación y configuración_ del modelo de nodo.
+

NOTE: Si va a actualizar a un sistema con ambos nodos del mismo chasis, instale el nodo 4 en el chasis y el nodo 3. Si no se hace, cuando se arranca el nodo 3, el nodo se comportará como si fuera en una configuración de doble chasis, y cuando se arranca el nodo 4, la interconexión entre los nodos no se iniciará.

. [[step3]]cable node3, moviendo las conexiones del nodo 1 al nodo 3.
+
Las siguientes referencias le ayudan a realizar las conexiones de cable adecuadas. Vaya a. link:other_references.html["Referencias"] para vincularlos.

+
** _Instrucciones de instalación y configuración_ o _requisitos de instalación y referencia_ de la virtualización FlexArray para la plataforma node3
** El procedimiento de la bandeja de discos apropiado
** La documentación _High Availability Management_


+
Conectar las siguientes conexiones:

+
** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC
+

NOTE: Es posible que no sea necesario mover la tarjeta de interconexión o la conexión del cable de interconexión del clúster del nodo 1 al nodo 3, ya que la mayoría de los modelos de plataforma tienen un modelo de tarjeta de interconexión único. Para la configuración de MetroCluster, se deben mover las conexiones de cables FC-VI de node1 a node3. Si el host nuevo no tiene una tarjeta FC-VI, puede que necesite mover la tarjeta FC-VI.



. [[man_install3_step4]]Active la alimentación del nodo 3 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al indicador de entorno de arranque.
+
Si va a actualizar a un sistema con ambos nodos del mismo chasis, el nodo 4 también se reinicia. Sin embargo, es posible ignorar el arranque de nodo 4 hasta más adelante.

+

NOTE: Cuando se arranca el nodo 3, es posible que se muestre el siguiente mensaje de advertencia:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]Si aparece el mensaje de advertencia en <<man_install3_step4,Paso 4>>, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

NOTE: *Atención*: No anule el retardo; si no se permite que la batería se cargue, podría producirse una pérdida de datos.



. [[man_install3_step6]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si su sistema... | Realice lo siguiente... 


| Cuenta con discos y sin almacenamiento de gestión | Pase los pasos 7 a 12 y vaya a. <<man_install3_step13,Paso 13>>. 


| Es un sistema V-Series o un sistema con software de virtualización FlexArray conectado a cabinas de almacenamiento  a| 
.. Vaya a. link:set_fc_uta_uta2_config_node3.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 3"] y completar las subsecciones link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_uta_uta2_config_node3.html#check-and-configure-UTAUTA2-ports-on-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"], según corresponda a su sistema.
.. Vuelva a esta sección y complete los pasos restantes, empezando por <<man_install3_step7,Paso 7>>.



IMPORTANT: Debe volver a configurar los puertos integrados de FC, los puertos CNA integrados y las tarjetas CNA antes de iniciar ONTAP en el sistema V-Series o con el software de virtualización FlexArray.

|===
. [[man_install3_step7]]Añada los puertos iniciadores FC del nuevo nodo a las zonas del switch.
+
Si su sistema tiene UNA SAN de cinta, debe dividir en zonas para los iniciadores. Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. [[man_install3_step8]]Añada los puertos de iniciador de FC a la cabina de almacenamiento como hosts nuevos, asignando las LUN de la cabina a los nuevos hosts.
+
Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. [[man_install3_step9]] modifique los valores de nombre de puerto WWPN en el host o los grupos de volúmenes asociados con los LUN de cabina en la cabina de almacenamiento.
+
La instalación de un módulo de controladora nuevo cambia los valores de WWPN asociados con cada puerto FC integrado.

. [[man_install3_step10]]Si la configuración usa la división en zonas basada en switches, ajuste la división en zonas para reflejar los nuevos valores de WWPN.
. [[man_install3_step11]]Compruebe que los LUN de la cabina ahora sean visibles para el nodo 3:
+
`sysconfig -v`

+
El sistema muestra todas las LUN de la cabina visibles para cada uno de los puertos iniciadores FC. Si los LUN de cabina no están visibles, no podrá reasignar discos del nodo 1 al nodo 3 más adelante en esta sección.

. [[man_install3_step12]]Pulse Ctrl-C para mostrar el menú de inicio y seleccionar el modo de mantenimiento.
. [[man_install3_step13]]en el símbolo del sistema del modo de mantenimiento, introduzca el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. [[man_install3_step14]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema al que va a actualizar está en una... | Realice lo siguiente... 


| Configuración de chasis doble (con controladoras en diferentes chasis) | Vaya a. <<man_install3_step15,Paso 15>>. 


| Configuración de chasis único (con controladoras en el mismo chasis)  a| 
.. Cambie el cable de la consola del nodo 3 al nodo 4.
.. Encienda el nodo 4 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al aviso del entorno de arranque.
+
La alimentación debe estar encendida si ambas controladoras están en el mismo chasis.

+

NOTE: Deje el nodo 4 en el aviso del entorno de arranque; regresará al nodo 4 en link:install_boot_node4.html["Instale y arranque el nodo 4"].

.. Si ve el mensaje de advertencia en <<man_install3_step4,Paso 4>>, siga las instrucciones de <<man_install3_step5,Paso 5>>
.. Vuelva a cambiar el cable de la consola del nodo 4 al nodo 3.
.. Vaya a. <<man_install3_step15,Paso 15>>.


|===
. [[man_install3_step15]]Configurar nodo 3 para ONTAP:
+
`set-defaults`


