= Configure los puertos FC en el nodo 3
:allow-uri-read: 




== Configure los puertos FC en el nodo 3

Si el nodo 3 tiene puertos FC, ya sea integrados o en un adaptador FC complementario, debe establecer las configuraciones de los puertos en el nodo antes de ponerlo en servicio porque los puertos no están preconfigurados cuando se envían los sistemas.  Si no configura los puertos, podría experimentar una interrupción en el servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto FC del nodo 1 donde haya guardado link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puede omitir esta sección si el sistema no tiene configuraciones de FC. Si su sistema tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe configurarlos en <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador del clúster.

.Pasos
. Muestra información sobre todos los adaptadores de red convergentes y FC en el sistema.
+
`system node hardware unified-connect show`

. Compare la configuración FC del nodo3 con la configuración que capturó anteriormente del nodo1.
. [[man_config_3_step3]]Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si la configuración de FC predeterminada en los nodos nuevos es... | Realice lo siguiente... 


| Igual que los que capturó en el nodo 1 | Vaya a <<man_config_3_step9,Paso 9>>. 


| Diferente de las que capturó en el nodo 1 | Vaya a <<man_config_3_step4,Paso 4>>. 
|===
. [[man_config_3_step4]]Modifique los puertos FC en el nodo 3 según sea necesario ingresando uno de los siguientes comandos:
+
** Para programar puertos de destino:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Para programar puertos iniciadores:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` Es el tipo FC4: Objetivo o iniciador.



. Verifique la nueva configuración ingresando el siguiente comando y examinando el resultado:
+
`system node hardware unified-connect show`

. Salir del modo de mantenimiento:
+
`halt`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Arranque el nodo 3 en el indicador del entorno de arranque:
+
`boot_ontap`

. [[man_config_3_step9]]Realice una de las siguientes acciones:
+
** Si el nodo 3 tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, vaya a. <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.
** Si el nodo 3 no tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, omita <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>> y vaya a. link:map_ports_node1_node3.html["Asigne puertos del nodo 1 al nodo 3"].



