---
sidebar: sidebar 
permalink: upgrade-arl-manual/install_boot_node3.html 
keywords: install, boot, node3, rack, transfer connections, v-series, flexarray, storage disks 
summary: Instale y arranque el nodo 3 e instale el software ONTAP durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.7 o una versión anterior. 
---
= Instale y arranque el nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe instalar el nodo 3 en el rack, transferir las conexiones del nodo 1 al nodo 3, al nodo de arranque 3 e instalar ONTAP. También debe reasignar cualquiera de los discos de repuesto del nodo 1, todos los discos que pertenezcan al volumen raíz y todos los agregados no raíz que no estén ubicados en el nodo 2 anteriormente.

.Acerca de esta tarea
Debe iniciar el nodo 3 mediante netboot si no tiene la misma versión de ONTAP 9 que está instalada en el nodo 1. Después de instalar el nodo 3, arranque desde la imagen ONTAP 9 almacenada en el servidor web. A continuación, puede descargar los archivos correctos en el dispositivo multimedia de arranque para posteriores arranques del sistema. Consulte link:prepare_for_netboot.html["Prepárese para el arranque desde el red"].

Sin embargo, no es necesario iniciar el nodo 3 mediante netboot si tiene la misma versión o una posterior de ONTAP 9 que está instalada en el nodo 1.

[IMPORTANT]
====
* Para actualizar un controlador AFF A800 o AFF C800, debe asegurarse de que todas las unidades en el chasis estén firmemente asentadas contra el plano medio antes de quitar el nodo 1. Para obtener más información, consulte link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["Sustituya los módulos del controlador AFF A800 o AFF C800"].
* Si va a actualizar un sistema V-Series conectado a cabinas de almacenamiento o un sistema con el software de virtualización de FlexArray conectado a cabinas de almacenamiento, debe completar <<man_install3_step1,Paso 1>> por <<man_install3_step5,Paso 5>>, deje esta sección en <<man_install3_step6,Paso 6>> y siga las instrucciones de link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] según sea necesario, introduzca los comandos en modo de mantenimiento. A continuación, debe volver a esta sección y reanudar con <<man_install3_step7,Paso 7>>.
* Si está actualizando un sistema con discos de almacenamiento, debe completar toda esta sección y luego ir a link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"] , ingresando comandos en el indicador del clúster.


====
.Pasos
. [[man_install3_step1]]Asegúrese de que dispone de espacio en rack para el nodo 3.
+
Si los nodos 1 y 2 están en un chasis separado, puede colocar el nodo 3 en la misma ubicación de rack que el nodo 1. Sin embargo, si node1 estaba en el mismo chasis con node2, debe poner node3 en su propio espacio de rack, preferiblemente cerca de la ubicación de node1.

. [[step2]]instale el nodo 3 en el rack siguiendo las _instrucciones de instalación y configuración_ del modelo de nodo.
+

NOTE: Si va a actualizar a un sistema con ambos nodos del mismo chasis, instale el nodo 4 en el chasis y el nodo 3. Si no se hace, cuando se arranca el nodo 3, el nodo se comportará como si fuera en una configuración de doble chasis, y cuando se arranca el nodo 4, la interconexión entre los nodos no se iniciará.

. [[step3]]cable node3, moviendo las conexiones del nodo 1 al nodo 3.
+
Las siguientes referencias le ayudan a realizar las conexiones de cable adecuadas. Vaya a. link:other_references.html["Referencias"] para vincularlos.

+
** _Instrucciones de instalación y configuración_ o _requisitos de instalación y referencia_ de la virtualización FlexArray para la plataforma node3
** El procedimiento de la bandeja de discos apropiado
** La documentación _HA pair management_


+
Conectar las siguientes conexiones:

+
** Consola (puerto de gestión remota)
** Puertos del clúster
** Puertos de datos
** Puertos de gestión de clústeres y nodos
** Reducida
** Configuraciones SAN: Puertos Ethernet iSCSI y switch FC
+

NOTE: Es posible que no sea necesario mover la tarjeta de interconexión o la conexión del cable de interconexión del clúster del nodo 1 al nodo 3, ya que la mayoría de los modelos de plataforma tienen un modelo de tarjeta de interconexión único. Para la configuración de MetroCluster, se deben mover las conexiones de cables FC-VI de node1 a node3. Si el host nuevo no tiene una tarjeta FC-VI, puede que necesite mover la tarjeta FC-VI.



. [[man_install3_step4]]Active la alimentación del nodo 3 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al indicador de entorno de arranque.
+
Si va a actualizar a un sistema con ambos nodos del mismo chasis, el nodo 4 también se reinicia. Sin embargo, es posible ignorar el arranque de nodo 4 hasta más adelante.

+

NOTE: Cuando se arranca el nodo 3, es posible que se muestre el siguiente mensaje de advertencia:

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]]Si aparece el mensaje de advertencia en <<man_install3_step4,Paso 4>>, realice las siguientes acciones:
+
.. Compruebe todos los mensajes de la consola que puedan indicar un problema distinto a una batería NVRAM baja y, si es necesario, realice las acciones correctivas necesarias.
.. Deje que la batería se cargue y finalice el proceso de arranque.
+

NOTE: *Atención*: No anule el retardo; si no se permite que la batería se cargue, podría producirse una pérdida de datos.



. [[man_install3_step6]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si su sistema... | Realice lo siguiente... 


| Cuenta con discos y sin almacenamiento de gestión | Pase los pasos 7 a 12 y vaya a. <<man_install3_step13,Paso 13>>. 


| Es un sistema V-Series o un sistema con software de virtualización FlexArray conectado a cabinas de almacenamiento  a| 
.. Vaya a. link:set_fc_uta_uta2_config_node3.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 3"] y completar las subsecciones link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["Configure los puertos FC en el nodo 3"] y.. link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["Comprobar y configurar los puertos UTA/UTA2 en el nodo 3"], según corresponda a su sistema.
.. Vuelva a esta sección y complete los pasos restantes, empezando por <<man_install3_step7,Paso 7>>.



IMPORTANT: Debe volver a configurar los puertos integrados de FC, los puertos CNA integrados y las tarjetas CNA antes de iniciar ONTAP en el sistema V-Series o con el software de virtualización FlexArray.

|===
. [[man_install3_step7]]Añada los puertos iniciadores FC del nuevo nodo a las zonas del switch.
+
Si su sistema tiene UNA SAN de cinta, debe dividir en zonas para los iniciadores. Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. [[man_install3_step8]]Añada los puertos de iniciador de FC a la cabina de almacenamiento como hosts nuevos, asignando las LUN de la cabina a los nuevos hosts.
+
Consulte la documentación de la cabina de almacenamiento y la división en zonas para obtener instrucciones.

. [[man_install3_step9]] modifique los valores de nombre de puerto WWPN en el host o los grupos de volúmenes asociados con los LUN de cabina en la cabina de almacenamiento.
+
La instalación de un módulo de controladora nuevo cambia los valores de WWPN asociados con cada puerto FC integrado.

. [[man_install3_step10]]Si la configuración usa la división en zonas basada en switches, ajuste la división en zonas para reflejar los nuevos valores de WWPN.
. [[man_install3_step11]]Compruebe que los LUN de la cabina ahora sean visibles para el nodo 3:
+
`sysconfig -v`

+
El sistema muestra todas las LUN de la cabina visibles para cada uno de los puertos iniciadores FC. Si los LUN de cabina no están visibles, no podrá reasignar discos del nodo 1 al nodo 3 más adelante en esta sección.

. [[man_install3_step12]]Pulse Ctrl-C para mostrar el menú de inicio y seleccionar el modo de mantenimiento.
. [[man_install3_step13]]en el símbolo del sistema del modo de mantenimiento, introduzca el siguiente comando:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. [[man_install3_step14]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema al que va a actualizar está en una... | Realice lo siguiente... 


| Configuración de chasis doble (con controladoras en diferentes chasis) | Vaya a. <<man_install3_step15,Paso 15>>. 


| Configuración de chasis único (con controladoras en el mismo chasis)  a| 
.. Cambie el cable de la consola del nodo 3 al nodo 4.
.. Encienda el nodo 4 y, a continuación, interrumpa el proceso de arranque pulsando Ctrl-C en el terminal de la consola para acceder al aviso del entorno de arranque.
+
La alimentación debe estar encendida si ambas controladoras están en el mismo chasis.

+

NOTE: Deje el nodo 4 en el aviso del entorno de arranque; regresará al nodo 4 en link:install_boot_node4.html["Instale y arranque el nodo 4"].

.. Si ve el mensaje de advertencia en <<man_install3_step4,Paso 4>>, siga las instrucciones de <<man_install3_step5,Paso 5>>
.. Vuelva a cambiar el cable de la consola del nodo 4 al nodo 3.
.. Vaya a. <<man_install3_step15,Paso 15>>.


|===
. [[man_install3_step15]]Configurar nodo 3 para ONTAP:
+
`set-defaults`

. [[man_install3_step16]]Si tiene unidades NetApp Storage Encryption (NSE) instaladas, realice los siguientes pasos:
+

NOTE: Si aún no lo ha hecho anteriormente en el procedimiento, consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Cómo saber si una unidad tiene la certificación FIPS"^] para determinar el tipo de unidades de autocifrado que están en uso.

+
.. Configurado `bootarg.storageencryption.support` para `true` o. `false`:
+
[cols="35,65"]
|===
| Si están en uso las siguientes unidades... | Entonces… 


| Unidades NSE que cumplen con los requisitos de autocifrado de FIPS 140-2 de nivel 2 | `setenv bootarg.storageencryption.support *true*` 


| SED de NetApp no con FIPS | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad.

Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.

====
.. Póngase en contacto con el soporte de NetApp para obtener ayuda para restaurar la información sobre la gestión de claves incorporada.


. [[man_install3_step17]] Si la versión de ONTAP instalada en el nodo 3 es la misma o posterior que la versión de ONTAP 9 instalada en el nodo 1, enumerar y reasignar discos al nuevo nodo 3:
+
`boot_ontap`

+

WARNING: Si este nodo nuevo se ha usado alguna vez en cualquier otro clúster o pareja de alta disponibilidad, debe ejecutar `wipeconfig` antes de continuar. De no hacerlo, se pueden producir interrupciones del servicio o pérdida de datos. Póngase en contacto con el soporte técnico si la controladora de reemplazo se utilizó anteriormente, especialmente si las controladoras ejecutaban ONTAP en 7-Mode.

. [[man_install3_step18]]Pulse CTRL-C para mostrar el menú de inicio.
. [[man_install3_step19]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si el sistema que desea actualizar... | Realice lo siguiente... 


| _Not_ tiene la versión correcta o actual de ONTAP en el nodo 3 | Vaya a. <<man_install3_step20,Paso 20>>. 


| Tiene la versión correcta o actual de ONTAP en el nodo 3 | Vaya a. <<man_install3_step25,Paso 25>>. 
|===
. [[man_install3_step20]]Configure la conexión netboot eligiendo una de las siguientes acciones.
+

NOTE: Se deben utilizar el puerto e IP de gestión como conexión para reiniciar el sistema. No utilice una IP de LIF de datos ni ninguna otra interrupción del servicio de datos mientras se realiza la actualización.

+
[cols="35,65"]
|===
| Si el protocolo de configuración dinámica de hosts (DHCP) es... | Realice lo siguiente... 


| Ejecutando | Configure la conexión automáticamente introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -auto` 


| No se está ejecutando  a| 
Configure manualmente la conexión introduciendo el siguiente comando en el símbolo del sistema del entorno de arranque:
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` Es la dirección IP del sistema de almacenamiento (obligatorio).
`_netmask_` es la máscara de red del sistema de almacenamiento (obligatoria).
`_gateway_` es la puerta de enlace del sistema de almacenamiento (obligatorio).
`_dns_addr_` Es la dirección IP de un servidor de nombres en la red (opcional).
`_dns_domain_` Es el nombre de dominio del servicio de nombres de dominio (DNS). Si utiliza este parámetro opcional, no necesita un nombre de dominio completo en la URL del servidor para reiniciar el sistema; solo necesita el nombre de host del servidor.


NOTE: Es posible que sean necesarios otros parámetros para la interfaz. Introduzca `help ifconfig` en el símbolo del sistema del firmware para obtener detalles.

|===
. [[man_install3_step21]]lleve a cabo netboot en el nodo 3:
+
[cols="35,65"]
|===
| Durante... | Realice lo siguiente... 


| Sistemas de la serie FAS/AFF8000 | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| Todos los demás sistemas | `netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
La `<path_to_the_web-accessible_directory>` lleva al lugar en el que se ha descargado el `<ontap_version>_image.tgz` pulg link:prepare_for_netboot.html#man_netboot_Step1["Paso 1"] En la sección _Prepárese para netboot_.

+

NOTE: No interrumpa el arranque.

. [[man_install3_step22]]en el menú de inicio, seleccione la opción *(7) instale primero el nuevo software*.
+
Esta opción del menú descarga e instala la nueva imagen de ONTAP en el dispositivo de arranque.

+
Ignore el siguiente mensaje:

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
La nota se aplica a las actualizaciones no disruptivas de ONTAP, no a las actualizaciones de controladoras.

+

NOTE: Utilice siempre netboot para actualizar el nodo nuevo a la imagen deseada. Si utiliza otro método para instalar la imagen en la nueva controladora, es posible que se instale una imagen incorrecta. Este problema se aplica a todas las versiones de ONTAP. El procedimiento para reiniciar el sistema combinado con la opción `(7) Install new software` Limpia el soporte de arranque y coloca la misma versión ONTAP de ONTAP en ambas particiones de imagen.

. [[man_install3_step23]]Si se le solicita que continúe el procedimiento, introduzca `y`, Y cuando se le solicite el paquete, escriba la siguiente dirección URL:
+
`\http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. [[man_install3_step24]]lleve a cabo los siguientes subpasos:
+
.. Introduzca `n` para omitir la recuperación del backup cuando aparezca la siguiente solicitud:
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. Reinicie introduciendo `y` cuando vea el siguiente símbolo del sistema:
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
El módulo del controlador se reinicia pero se detiene en el menú de arranque porque se reformateó el dispositivo de arranque y es necesario restaurar los datos de configuración.



. [[man_install3_step25]]Seleccione *(5) modo de mantenimiento boot* introduciendo `5`y, a continuación, introduzca `y` cuando se le solicite continuar con el arranque.
. [[man_install3_step26]]antes de continuar, vaya a. link:set_fc_uta_uta2_config_node3.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 3"] Se deben realizar los cambios necesarios en los puertos FC o UTA/UTA2 del nodo.
+
Realice los cambios recomendados en esas secciones, reinicie el nodo y vaya al modo de mantenimiento.

. [[man_install3_step27]]Busque el ID del sistema del nodo 3:
+
`disk show -a`

+
El sistema muestra el ID del sistema del nodo e información acerca de sus discos, como se muestra en el ejemplo siguiente:

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: Puede que vea el mensaje `disk show: No disks match option -a.` tras introducir el comando. Este no es un mensaje de error para que pueda continuar con el procedimiento.

. [[man_install3_step28]]reasignar repuestos del nodo 1, cualquier disco que pertenezca a la raíz y cualquier agregado que no fuera de raíz que no se haya reubicado en el nodo 2 anteriormente en link:relocate_non_root_aggr_node1_node2.html["Cambie la ubicación de los agregados que no son raíz del nodo 1 al nodo 2"].
+
Introduzca la forma adecuada del `disk reassign` comando basado en si su sistema tiene discos compartidos:

+

NOTE: Si ha compartido discos, agregados híbridos o ambos en el sistema, debe utilizar los correctos `disk reassign` desde la siguiente tabla.

+
[cols="35,65"]
|===
| Si el tipo de disco es... | Después, ejecute el comando... 


| Con discos compartidos | `disk reassign -s _node1_sysid_ -d _node3_sysid_ -p _node2_sysid_` 


| Sin discos compartidos | `disk reassign -s _node1_sysid_ -d _node3_sysid_` 
|===
+
Para la `_node1_sysid_` utilice la información capturada en link:record_node1_information.html["Registre la información del nodo 1"]. Para obtener el valor de `_node3_sysid_`, utilice la `sysconfig` comando.

+

NOTE: La `-p` la opción solo es necesaria en modo de mantenimiento cuando hay discos compartidos presentes.

+
La `disk reassign` el comando reasigna solo aquellos discos para los que `_node1_sysid_` es el propietario actual.

+
El sistema muestra el siguiente mensaje:

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]]Introduzca `n`.
+
El sistema muestra el siguiente mensaje:

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]]Introduzca `y`
+
El sistema muestra el siguiente mensaje:

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step31]]Introduzca `y`.
. [[man_install3_step32]]Si va a actualizar desde un sistema con discos externos a un sistema que admita discos internos y externos (sistemas AFF A800, por ejemplo), establezca el agregado 1-1 como raíz para confirmar que el nodo 3 arranque desde el agregado raíz del nodo 1.
+

WARNING: *Advertencia*: Debe realizar los siguientes subpasos en el orden exacto que se muestra; de lo contrario, podría causar una interrupción o incluso pérdida de datos.

+
El siguiente procedimiento establece el nodo 3 para arrancar desde el agregado raíz del nodo 1:

+
.. Compruebe la información de RAID, plex y suma de comprobación para el agregado 1-1:
+
`aggr status -r`

.. Compruebe el estado del agregado 1-1:
+
`aggr status`

.. Coloque el agregado del nodo 1 en línea, si es necesario:
+
`aggr_online _root_aggr_from_node1_`

.. Impida que el nodo 3 arranque desde su agregado raíz original:
`aggr offline _root_aggr_on_node3_`
.. Establezca el agregado raíz del nodo 1 como el nuevo agregado raíz del nodo 3:
+
`aggr options _aggr_from_node1_ root`

.. Compruebe que el agregado raíz del nodo 3 esté sin conexión y que el agregado raíz de los discos extraídos del nodo 1 esté en línea y establecido en raíz:
+
`aggr status`

+

NOTE: Si no se pudo realizar el subpaso anterior, el nodo 3 se puede arrancar desde el agregado raíz interno, o bien es posible que el sistema asuma que existe una nueva configuración de clúster o que se le solicite identificar una.

+
El siguiente muestra un ejemplo de resultado del comando:



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]]Compruebe que el controlador y el chasis están configurados como `ha`:
+
`ha-config show`

+
En el siguiente ejemplo se muestra el resultado del comando ha-config show:

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
Los sistemas graban en una ROM programable (PROM) tanto si se encuentran en un par ha como en una configuración independiente. El estado debe ser el mismo en todos los componentes del sistema independiente o del par de alta disponibilidad.

+
Si la controladora y el chasis no están configurados como "ha", utilice los siguientes comandos para corregir la configuración:

+
`ha-config modify controller ha`

+
`ha-config modify chassis ha`

+
Si tiene una configuración MetroCluster, utilice los siguientes comandos para modificar la controladora y el chasis:

+
`ha-config modify controller mcc`

+
`ha-config modify chassis mcc`

. [[man_install3_step34]]destruya los buzones del nodo 3:
+
`mailbox destroy local`

+
La consola muestra el siguiente mensaje:

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]]Introduzca `y` cuando el sistema le solicite que confirme que desea destruir los buzones locales.
. [[man_install3_step36]]salir del modo de mantenimiento:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. [[man_install3_step37]]en el nodo 2, compruebe la fecha, la hora y la zona horaria del sistema:
+
`date`

. [[man_install3_step38]]en el nodo 3, compruebe la fecha en el indicador de entorno de arranque:
+
`show date`

. [[man_install3_step39]]Si es necesario, establezca la fecha en node3:
+
`set date _mm/dd/yyyy_`

. [[man_install3_step40]]en el nodo 3, compruebe la hora en el indicador de entorno de arranque:
+
`show time`

. [[man_install3_step41]]Si es necesario, establezca la hora en node3:
+
`set time _hh:mm:ss_`

. [[man_install3_step42]]Compruebe que el ID del sistema asociado esté configurado correctamente como se indica en la <<man_install3_step28,Paso 28>> interruptor de debajo de -p:
+
`printenv partner-sysid`

. [[man_install3_step43]]Si es necesario, establezca el ID del sistema asociado en el nodo 3:
+
`setenv partner-sysid _node2_sysid_`

+
Guarde los ajustes:

+
`saveenv`

. [[man_install3_step44]]Acceda al menú de inicio en el indicador de entorno de arranque:
+
`boot_ontap menu`

. [[man_install3_step45]]en el menú de inicio, seleccione la opción *(6) Actualizar flash desde backup config* introduciendo `6` en el prompt de.
+
El sistema muestra el siguiente mensaje:

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]]Introduzca `y` en el prompt de.
+
El arranque continúa con normalidad y el sistema le pide que confirme que el ID del sistema no coincide.

+

NOTE: El sistema puede reiniciarse dos veces antes de mostrar la advertencia de no coincidencia.

. [[man_install3_step47]]confirme la discrepancia como se muestra en el ejemplo siguiente:
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
Es posible que el nodo pase por una ronda de reinicio antes de arrancar normalmente.

. [[man_install3_step48]]Inicie sesión en el nodo 3.

