---
sidebar: sidebar 
permalink: upgrade-arl-manual/map_ports_node2_node4.html 
keywords: map, node2, node4, physical ports, cluster, network, connectivity 
summary: Verifique que los puertos físicos en 2 se asignen correctamente al nodo 4 durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.7 o una versión anterior. 
---
= Asigne puertos del nodo 2 al nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que los puertos físicos del nodo 2 se asignen correctamente a los puertos físicos del nodo 4, lo que permitirá que el nodo 4 se comunique con otros nodos del clúster y con la red después de la actualización.

.Antes de empezar
Para acceder a esta información, ya debe tener información sobre los puertos en los nodos nuevos. Consulte link:other_references.html["Referencias"] Para enlazar con _Hardware Universe_. La información se utiliza más adelante en esta sección.

La configuración de software del nodo 4 debe coincidir con la conectividad física del nodo 4, y se debe restaurar la conectividad IP antes de continuar con la actualización.

.Acerca de esta tarea
La configuración del puerto puede variar en función del modelo de los nodos. Debe hacer que el puerto y la configuración de LIF del nodo original sean compatibles con lo que planifique la configuración del nodo nuevo. Esto es así porque el nuevo nodo reproduce la misma configuración cuando arranca, lo que significa que cuando arranca el nodo 4, Data ONTAP intentará host LIF en los mismos puertos que se usaron en el nodo 2.

Por lo tanto, si los puertos físicos del nodo 2 no se asignan directamente a los puertos físicos del nodo 4, se necesitarán cambios de configuración del software para restaurar la conectividad de clúster, gestión y red después del arranque. Además, si los puertos del clúster en el nodo 2 no se asignan directamente a los puertos del clúster del nodo 4, es posible que el nodo 4 no vuelva a unir automáticamente el quórum cuando se reinicia hasta que se realice un cambio de configuración de software para alojar las LIF del clúster en los puertos físicos correctos.

.Pasos
. Registre toda la información de cableado del nodo 2 para el nodo 2, los puertos, los dominios de retransmisión y los espacios IP en esta tabla:
+
[cols="7*"]
|===
| LUN | 2 puertos | Espacios IP 2 | Dominios de retransmisión 2 | Puertos Node4 | Espacios IP Node4 | Dominios de retransmisión Node4 


| Clúster 1 |  |  |  |  |  |  


| Clúster 2 |  |  |  |  |  |  


| Clúster 3 |  |  |  |  |  |  


| Clúster 4 |  |  |  |  |  |  


| Clúster 5 |  |  |  |  |  |  


| Clúster 6 |  |  |  |  |  |  


| Gestión de nodos |  |  |  |  |  |  


| Gestión de clústeres |  |  |  |  |  |  


| Datos 1 |  |  |  |  |  |  


| Datos 2 |  |  |  |  |  |  


| Datos 3 |  |  |  |  |  |  


| Datos 4 |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| Puerto de interconexión de clústeres |  |  |  |  |  |  
|===
+
Consulte la sección "grabación de información 2" para conocer los pasos necesarios para obtener esta información.

. Registre toda la información de cableado de los nodos 4, los puertos, los dominios de retransmisión y los espacios IP en la tabla anterior con el mismo procedimiento de link:record_node2_information.html["Grabar información del nodo 2"] para conocer los pasos para obtener esta información.
. Siga estos pasos para verificar si la configuración es un clúster sin switches de dos nodos:
+
.. Configure el nivel de privilegio en Advanced:
.. Compruebe si la configuración es un clúster sin switches de dos nodos:
+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster: false/true
----
+
El valor de este comando debe coincidir con el estado físico del sistema.

.. Volver al nivel de privilegio de administración:
+
[listing]
----
cluster::*> set -privilege admin
cluster::>
----


. Para obtener el quórum del nodo 4, siga estos pasos:
+
.. Nodo de arranque 4. Consulte link:install_boot_node4.html["Instale y arranque el nodo 4"] para arrancar el nodo si aún no lo ha hecho.
.. Compruebe que los nuevos puertos del clúster se encuentran en el dominio de retransmisión del clúster:
+
`network port show -node _node_ -port _port_ -fields broadcast-domain`En el siguiente ejemplo, se muestra que el puerto "e0a" es en el dominio del clúster del nodo 4:

+
[listing]
----
cluster::> network port show -node node4 -port e0a -fields broadcast-domain

node       port broadcast-domain
---------- ---- ----------------
node4      e1a  Cluster
----
.. Si los puertos del clúster no están en el dominio de retransmisión del clúster, añádalos con el siguiente comando:
+
`broadcast-domain add-ports -ipspace Cluster -broadcast-domain Cluster -ports _node:port_`

.. Añada los puertos correctos al dominio de retransmisión de clúster:
+
`network port modify -node -port -ipspace Cluster -mtu 9000`

+
En este ejemplo, se añade el puerto de clúster "e1b" del nodo 4:

+
`network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000`

+

NOTE: Para una configuración MetroCluster, es posible que no pueda cambiar el dominio de retransmisión de un puerto porque está asociado a un puerto que aloja la LIF de una SVM sincronizada en destino y ver errores similares, pero sin limitarse a ellos, a los siguientes:

+
[listing]
----
command failed: This operation is not permitted on a Vserver that is configured as the destination of a MetroCluster Vserver relationship.
----
+
Escriba el siguiente comando desde la SVM sincronizada en origen correspondiente en el sitio remoto para reasignar la LIF sincronizada en destino a un puerto adecuado:

+
`metrocluster vserver resync -vserver _vserver_name_`

.. Migre las LIF del clúster a los nuevos puertos, una vez por cada LIF:
+
`network interface migrate -vserver Cluster -lif _lif_name_ -source-node node4 - destination-node node4 -destination-port _port_name_`

.. Modifique el puerto de inicio de las LIF del clúster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Quite los puertos antiguos del dominio de retransmisión de clúster:
+
`network port broadcast-domain remove-ports`

+
Este comando elimina el puerto "e0d" del nodo 4:
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports node4:e0d`

.. Verifique que el nodo 4 se haya reUnido al quórum:
+
`cluster show -node node4 -fields health`



. [[man_map_2_step5]]ajuste los dominios de retransmisión que alojan las LIF del clúster y las LIF de gestión del nodo/administración del clúster. Confirme que cada dominio de retransmisión contiene los puertos correctos. No se puede mover un puerto entre dominios de retransmisión si aloja o pertenece a una LIF para que deba migrar y modificar las LIF como se muestra en los siguientes pasos:
+
.. Mostrar el puerto de inicio de una LIF:
+
`network interface show -fields home-node,home-port`

.. Muestre el dominio de retransmisión que contiene este puerto:
+
`network port broadcast-domain show -ports _node_name:port_name_`

.. Añada o quite puertos de los dominios de retransmisión:
+
`network port broadcast-domain add-ports`

+
`network port broadcast-domain remove-ports`

.. Modificar el puerto de inicio de una LIF:
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ –home-port _port_name_`



. Ajuste los dominios de retransmisión entre clústeres y migre las LIF entre clústeres, si es necesario, mediante los mismos comandos que se muestran en <<man_map_2_step5,Paso 5>>.
. Ajuste cualquier otro dominio de retransmisión y migre los LIF de datos, si es necesario, mediante los mismos comandos que se muestran en <<man_map_2_step5,Paso 5>>.
. Si hubiera algún puerto en el nodo 2 que ya no exista en el nodo 4, siga estos pasos para eliminarlos:
+
.. Acceda al nivel de privilegio avanzado en cualquiera de los nodos:
+
`set -privilege advanced`

.. Para eliminar los puertos:
+
`network port delete -node _node_name_ -port _port_name_`

.. Volver al nivel admin:
+
`set -privilege admin`



. Ajustar todos los grupos de recuperación tras fallos de LIF:
`network interface modify -failover-group _failover_group_ -failover-policy _failover_policy_`
+
El siguiente comando establece la directiva de conmutación por error en `broadcast-domain-wide` y utiliza los puertos del grupo de recuperación tras fallos `fg1` Como destinos de conmutación por error para LIF `data1` encendido `node4`:

+
`network interface modify -vserver node4 -lif data1 failover-policy broadcast-domain-wide -failover-group fg1`

+
Para obtener más información, consulte link:other_references.html["Referencias"] Para establecer un vínculo con _Network Management_ o los comandos _ONTAP 9: Manual Page Reference_, y vaya a _Configuración de la configuración de la conmutación por error en una LIF_.

. Verifique los cambios en el nodo 4:
+
`network port show -node node4`

. Cada LIF de clúster debe estar escuchando en el puerto 7700. Compruebe que las LIF del clúster están escuchando en el puerto 7700:
+
`::> network connections listening show -vserver Cluster`

+
El resultado esperado de la escucha del puerto 7700 en los puertos del clúster tal y como se muestra en el siguiente ejemplo de un clúster de dos nodos:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. Para cada LIF de clúster que no esté escuchando en el puerto 7700, establezca el estado administrativo de la LIF en `down` y después `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Repita el paso 11 para verificar que el LIF del clúster ahora esté escuchando en el puerto 7700.


