---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node1_node2.html 
keywords: node1, node3, nas, lifs, cluster, san 
summary: Mueva los LIF de datos de NAS del nodo 1 al nodo 2 si tiene un clúster de dos nodos o a un tercer nodo si el clúster tiene más de dos nodos, durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.7 o una versión anterior. 
---
= Mueva LIF de datos NAS que pertenezcan al nodo 1 al nodo 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de poder reemplazar el nodo 1 por nodo 3, debe mover las LIF de datos NAS que pertenecen al nodo 1 al nodo 2 si tiene un clúster de dos nodos, o a un tercer nodo si el clúster tiene más de dos nodos. El método que utilice dependerá de si el clúster está configurado para NAS o SAN.

.Acerca de esta tarea
Las LIF remotas gestionan el tráfico a LUN DE SAN durante el procedimiento de actualización. No es necesario mover LIF DE SAN durante la actualización para el estado del clúster o del servicio. Debe verificar que las LIF están en buen estado y ubicadas en puertos adecuados después de poner el nodo 3 en línea.

.Pasos
. Enumere todas las LIF de datos NAS alojadas en el nodo 1 introduciendo el comando siguiente y capturando el resultado:
+
`network interface show -data-protocol nfs|cifs -curr-node _node1_`

+
El sistema muestra las LIF de datos NAS en el nodo 1, como se muestra en el ejemplo siguiente:

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. Realice una de las siguientes acciones:
+
[cols="40,60"]
|===
| Si el nodo 1... | Realice lo siguiente... 


| Tiene configurados grupos de interfaces de VLAN | Vaya a. <<man_move_lif_1_2_step3,Paso 3>>. 


| No tiene grupos de interfaces ni VLAN configuradas | Vaya al paso 3 y vaya a. <<man_move_lif_1_2_step4,Paso 4>>. 
|===
+
Utilice la `network port vlan show` Comando para ver información sobre los puertos de red conectados a VLAN y, a su vez, utilice el `network port ifgrp show` comando para mostrar información sobre los grupos de interfaces del puerto.

. [[man_Move_lif_1_2_step3]]realice los siguientes pasos para migrar cualquier LIF de datos NAS alojada en los grupos de interfaces y VLAN del nodo 1:
+
.. [[man_move_lif_1_2_substepa]]migre las LIF alojadas en cualquier grupo de interfaces y las VLAN del nodo 1 a un puerto del nodo 2 que pueda alojar LIF en la misma red que las de los grupos de interfaces introduciendo el comando siguiente, una vez para cada LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _LIF_name_ -destination-node _node2_ –destination-port _netport|ifgrp_`

.. Modifique el puerto de inicio y el nodo de inicio de las LIF y VLAN en <<man_move_lif_1_2_substepa,Subpaso a>> En el puerto y el nodo que actualmente alojan las LIF, escriba el comando siguiente, una vez para cada LIF:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-node _node2_ - home-port _netport|ifgrp_`



. [[Man_Move_lif_1_2_step4]]realice una de las siguientes acciones:
+
[cols="20,80"]
|===
| Si el clúster está configurado para... | Realice lo siguiente... 


| NAS | Completo <<man_move_lif_1_2_step5,Paso 5>> por <<man_move_lif_1_2_step8,Paso 8>>. 


| SAN | Desactive todos los LIF SAN del nodo para desactivarlos durante la actualización:
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node_to_upgrade_ -home-port _netport|ifgrp_ -status-admin down` 
|===
. [[man_Move_lif_1_2_step5]]migre las LIF de datos NAS del nodo 1 al nodo 2 introduciendo el comando siguiente, una vez para cada LIF de datos:
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination-node _node2_ -destination-port _data_port_`

. [[step6]]Introduzca el comando siguiente y examine su resultado para verificar que las LIF se han movido a los puertos correctos y que las LIF tienen el estado up introduciendo el comando siguiente en cualquier nodo y examinando el resultado:
+
`network interface show -curr-node _node2_ -data-protocol nfs|cifs`

. [[step7]]Introduzca el siguiente comando para modificar el nodo de inicio de las LIF migradas:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _node2_ -home-port _port_name_`

. [[Man_Move_lif_1_2_step8]]Compruebe si la LIF está utilizando el puerto como puerto principal o actual. Si el puerto no es de origen o puerto actual, vaya a. <<man_move_lif_1_2_step9,Paso 9>>:
+
`network interface show -home-node _node2_ -home-port _port_name_`

+
`network interface show -curr-node _node_name_ -curr-port _port_name_`

. [[man_Move_lif_1_2_step9]]Si las LIF están utilizando el puerto como puerto de inicio o puerto actual, modifique la LIF para que utilice un puerto diferente:
+
`network interface migrate -vserver _Vserver-name_ -lif _LIF_name_ -destination–node _node_name_ -destination-port _port_name_`

+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home–node _node_name_ -home-port _port_name_`

. [[step10]]Si los puertos que actualmente alojan LIF de datos no van a existir en el nuevo hardware, elimínelos del dominio de difusión ahora:
+
`network port broadcast-domain remove-ports -ipspace Default -broadcast-domain Default -ports _node:port_`

. [[paso 11]]Si alguna LIF está inactiva, establezca el estado administrativo de las LIF en "up" introduciendo el comando siguiente, una vez para cada LIF:
+
`network interface modify -vserver _Vserver-name_ -lif _LIF_name_ -home-node _nodename_ -status-admin up`

+

NOTE: Para las configuraciones de MetroCluster, es posible que no pueda cambiar el dominio de retransmisión de un puerto porque está asociado a un puerto que aloja la LIF de una máquina virtual de almacenamiento (SVM) de destino. Escriba el comando siguiente desde la SVM de origen correspondiente en el sitio remoto para reasignar la LIF de destino a un puerto apropiado:
`metrocluster vserver resync -vserver _Vserver_name_`

. [[step12]]Introduzca el siguiente comando y examine su salida para verificar que no quedan LIF de datos en el nodo 1:
+
`network interface show -curr-node _node1_ -role data`

. [[step13]]Si tiene grupos de interfaces o VLAN configurados, realice los siguientes subpasos:
+
.. Quite las VLAN de los grupos de interfaces introduciendo el comando siguiente:
+
`network port vlan delete -node _nodename_ -port _ifgrp_name_ -vlan-id _VLAN_ID_`

.. Introduzca el siguiente comando y examine su salida para ver si hay algún grupo de interfaces configurado en el nodo:
+
`network port ifgrp show -node _nodename_ -ifgrp _ifgrp_name_ -instance`

+
El sistema muestra información del grupo de interfaces del nodo, como se muestra en el ejemplo siguiente:

+
[listing]
----
  cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                   Node: node1
   Interface Group Name: a0a
  Distribution Function: ip
          Create Policy: multimode_lacp
            MAC Address: 02:a0:98:17:dc:d4
     Port Participation: partial
          Network Ports: e2c, e2d
               Up Ports: e2c
             Down Ports: e2d
----
.. Si hay algún grupo de interfaces configurado en el nodo, registre los nombres de esos grupos y los puertos asignados a ellos y, a continuación, elimine los puertos introduciendo el comando siguiente, una vez para cada puerto:
+
`network port ifgrp remove-port -node _nodename_ -ifgrp _ifgrp_name_ -port _netport_`




