---
sidebar: sidebar 
permalink: upgrade-arl-manual/relocate_non_root_aggr_node2_node3.html 
keywords: node2, node3, node2, aggregates, autosupport 
summary: Envíe un mensaje de AutoSupport para el nodo 2 y reubique los agregados que no son raíz del nodo 3 durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.7 o una versión anterior. 
---
= Reubique los agregados que no son raíz del nodo 2 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de poder sustituir node2 con node4, debe enviar un mensaje de AutoSupport para node2 y, a continuación, reubicar los agregados no raíz que node2 posee a node3.

[[sysconfig-a-command]]
.Pasos
. Compruebe que el ID del sistema asociado está configurado correctamente en node2 y node3:
+
** `system node run -node _node2_ -command sysconfig -a`
** `system node run -node _node3_ -command sysconfig -a`
+
El sistema muestra un resultado similar al siguiente ejemplo:

+
[listing, subs="+quotes"]
----
NetApp Release 9.16.1: Mon Feb 10 07:55:45 EST 2025
System ID: _system-ID_; *partner ID: _partner-system-ID_*
System Serial Number: _system-serial-number_
System Rev: A0
System Storage Configuration: Mixed-Path HA
----
+
Si el ID de socio es incorrecto para node2 o node3:

+
... Reinicie el nodo con el valor incorrecto.
... Vuelva a ejecutar los comandos de <<sysconfig-a-command,Paso 1>>y confirme que el identificador de partner ha cambiado al valor correcto.




. Envíe un mensaje de AutoSupport a NetApp para node2:
+
`system node autosupport invoke -node _node2_ -type all -message "Upgrading _node2_ from _platform_old_ to _platform_new_"`

. Compruebe que se ha enviado el mensaje de AutoSupport:
+
`system node autosupport show -node _node2_ -instance`

+
Los campos "último asunto enviado:" y "última vez enviado:" contienen el título del último mensaje que se envió y la hora en que se envió el mensaje.

. Reubicar los agregados no raíz:
+
.. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

.. Enumere los agregados que son propiedad de 2:
+
`storage aggregate show -owner-name _node2_`

.. Iniciar reubicación de agregado:
+
`storage aggregate relocation start -node _node2_ -destination _node3_ -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: El comando busca solo agregados que no son raíz.

.. Cuando se le solicite, introduzca `y`.
+
La reubicación se produce en segundo plano. La reubicación de un agregado puede tardar entre unos segundos y un par de minutos. El tiempo incluye tanto la interrupción del servicio como las partes que no son de la interrupción del servicio. El comando no reubica ningún agregado sin conexión ni restringido.

.. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



. Verificar el estado de reubicación del nodo 2:
+
`storage aggregate relocation show -node _node2_`

+
La salida muestra “Listo” para un agregado después de que se haya reubicado.

+

NOTE: Debe esperar hasta que todos los agregados de los que son propiedad del nodo 2 se hayan reubicado en el nodo 3 antes de continuar con el siguiente paso.

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si la reubicación de... | Realice lo siguiente... 


| Todos los agregados se han realizado correctamente | Vaya a <<man_relocate_2_3_step7,Paso 7>>. 


| Todos los agregados han fallado o se ha vetado  a| 
.. Mostrar un mensaje de estado detallado:
+
`storage aggregate show -instance`

+
También puede consultar los registros de EMS para ver la acción correctiva que es necesaria.

+

NOTE: La `event log show` comando muestra todos los errores que se han producido.

.. Realice la acción correctiva.
.. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

.. Reubicar agregados que fallen o vetados:
+
`storage aggregate relocation start -node _node2_ -destination _node3_ -aggregate-list * -ndo-controllerupgrade true`

.. Cuando se le solicite, introduzca `y`.
.. Vuelva al nivel de privilegio de administrador:
+
`set -privilege admin`



Si es necesario, puede forzar la reubicación mediante uno de los siguientes métodos:

** Mediante la anulación de las comprobaciones de veto:
+
`storage aggregate relocation start -override-vetoes true -ndo-controller-upgrade`

** Mediante la anulación de comprobaciones de destino:
+
`storage aggregate relocation start -override-destination-checks true -ndocontroller-upgrade`



Para obtener más información sobre los comandos de reubicación de agregados de almacenamiento, vaya a. link:other_references.html["Referencias"] Para establecer un vínculo a la gestión de discos y agregados con la CLI_ y los comandos _ONTAP 9: Manual Page Reference_.

|===
. [[man_relocate_2_3_step7]]Verifique que todos los agregados no raíz estén en línea en node3:
+
`storage aggregate show -node _node3_ -state offline -root false`

+
Si alguno de los agregados se ha desconectado o se ha convertido en externo, debe conectarlos, una vez por cada agregado:

+
`storage aggregate online -aggregate _aggr_name_`

. Verifique que todos los volúmenes estén en línea en el nodo 3:
+
`volume show -node _node3_ -state offline`

+
Si alguno de los volúmenes se encuentra sin conexión en el nodo 3, es necesario conectarlos, una vez por cada volumen:

+
`volume online -vserver _Vserver-name_ -volume _volume-name_`

. Compruebe que node2 no posee ningún agregado no raíz en línea:
+
`storage aggregate show -owner-name _node2_ -ha-policy sfo -state online`

+
El resultado del comando no debe mostrar agregados no raíz en línea, ya que todos los agregados en línea no raíz ya se han reubicado al nodo 3.


