---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: Si es necesario, configure el nuevo módulo de la controladora para NVE o NAE durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.7 o una versión anterior. 
---
= Configure el cifrado de volúmenes de NetApp o el cifrado de agregados en el nuevo módulo de la controladora
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si la controladora reemplazada o el partner de alta disponibilidad (ha) de la nueva controladora utilizan el cifrado de volúmenes de NetApp (NVE) o el cifrado de agregados de NetApp (NAE), debe configurar el nuevo módulo de controladoras para NVE o NAE.

.Acerca de esta tarea
Este procedimiento incluye los pasos que se realizan en el nuevo módulo del controlador. Debe introducir el comando en el nodo correcto.

.Pasos
. Compruebe que los servidores de gestión de claves aún estén disponibles, su estado y la información de la clave de autenticación:
+
[cols="35,65"]
|===
| Para esta versión de ONTAP… | Se usa este comando... 


| ONTAP 9.6 o 9.7 | `security key-manager key query -node node` 


| ONTAP 9.5 o anterior | `security key-manager key show` 
|===
. Añada los servidores de gestión de claves que se enumeran en el paso anterior a la lista del servidor de gestión de claves de la nueva controladora:
+
.. Añada el servidor de gestión de claves mediante el siguiente comando:
+
`security key-manager -add _key_management_server_ip_address_`

.. Repita el paso anterior para cada servidor de gestión de claves enumerado. Puede vincular hasta cuatro servidores de gestión de claves.
.. Compruebe que los servidores de gestión de claves se han añadido correctamente mediante el siguiente comando:
+
`security key-manager show`



. En el nuevo módulo de controlador, ejecute el asistente de configuración de gestión de claves para configurar e instalar los servidores de gestión de claves.
+
Debe instalar los mismos servidores de gestión de claves que se instalan en el módulo de controladora existente.

+
.. Inicie el asistente de configuración del servidor de gestión de claves en el nuevo nodo mediante el siguiente comando:
+
`security key-manager setup -node _new_controller_name_`

.. Complete los pasos del asistente para configurar los servidores de gestión de claves.


. Restaure las claves de autenticación de todos los servidores de gestión de claves vinculados al nodo nuevo.
+
** Autenticación de restauración para External Key Manager (EKD):
+
`security key-manager external restore`

+
Este comando necesita la clave de acceso del gestor de claves incorporado (OKM)

** Restaurar la autenticación de OKM:
+
[cols="35,65"]
|===
| Para esta versión de ONTAP… | Se usa este comando... 


| El resto de las versiones de ONTAP | `security key-manager onboard sync` 


| ONTAP 9.5 | `security key-manager setup -node _node_name_` 
|===




.Después de terminar
Compruebe si alguno de los volúmenes se desconectó debido a que no existían claves de autenticación o porque no se pudo acceder a los servidores de gestión de claves externos. Vuelva a conectar esos volúmenes en línea mediante el siguiente comando:

`volume online`
