---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_3_index.html 
keywords: relocate, retire, node1, steps, stage 3 
summary: Fase 3 secuencia de procesos para una actualización manual de ARL en controladoras que ejecutan ONTAP 9.7 o una versión anterior. 
---
= Etapa 3. Instale y arranque el nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 3, debe instalar y arrancar el nodo 3, asignar los puertos de gestión del clúster y del nodo del nodo 1 al nodo 3, verificar la instalación del nodo 3 y mover las LIF de datos y LAS LIF DE SAN que pertenecen al nodo 1 del nodo 2 al nodo 3. También se pueden reubicar todos los agregados del nodo 2 al nodo 3 y mover las LIF de datos y las LIF DE SAN propiedad del nodo 2 al nodo 3.

.Pasos
. link:install_boot_node3.html["Instale y arranque el nodo 3"]
. link:set_fc_uta_uta2_config_node3.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 3"]
. link:map_ports_node1_node3.html["Asigne puertos del nodo 1 al nodo 3"]
. link:verify_node3_installation.html["Verifique la instalación del nodo 3"]
. link:move_nas_lifs_node1_from_node2_node3_verify_san_lifs_node3.html["Mueva LIF de datos NAS que pertenecen al nodo 2 al nodo 3 y verifique las LIF DE SAN del nodo 3"]
. link:relocate_non_root_aggr_node2_node3.html["Reubique los agregados que no son raíz del nodo 2 al nodo 3"]
. link:move_nas_lifs_node2_node3.html["Mueva LIF de datos NAS que sean del nodo 2 al nodo 3"]

