---
sidebar: sidebar 
permalink: upgrade-arl-manual/stage_6_index.html 
keywords: stage 6, complete, upgrade, set up, setup, controller, storage encryption, netapp encryption, decommission, resume snapmirror 
summary: Fase 6 secuencia de procesos para una actualización manual de ARL en controladoras que ejecutan ONTAP 9.7 o una versión anterior. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 6, el usuario confirma que los nodos nuevos están configurados correctamente y, si los nodos nuevos tienen la función de cifrado habilitada, se configuran y se configuran el cifrado de almacenamiento o el cifrado de volúmenes de NetApp. También debe retirar los nodos antiguos y reanudar las operaciones de SnapMirror.

. link:manage_authentication_kmip.html["Gestionar la autenticación mediante servidores KMIP"]
. link:ensure_controllers_set_up_correctly.html["Confirmar que las nuevas controladoras están configuradas correctamente"]
. link:set_up_storage_encryption_new_controller.html["Configure Storage Encryption en el nuevo módulo de la controladora"]
. link:set_up_netapp_encryption_on_new_controller.html["Configure el cifrado de volúmenes de NetApp o el cifrado de agregados en el nuevo módulo de la controladora"]
. link:decommission_old_system.html["Retire el sistema antiguo"]
. link:resume_snapmirror_ops.html["Reanudar las operaciones de SnapMirror"]

