---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'Configure y gestione el cifrado de almacenamiento, gestione las claves de autenticación y ponga en modo inactivo las relaciones de SnapMirror cuando actualice las controladoras que ejecutan ONTAP 9.8 o una versión posterior mediante `system controller replace` comando.' 
---
= Completa la preparación para la actualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Conoce las licencias de ONTAP y cómo gestionar Storage Encryption usando Onboard Key Manager (OKM). Opcionalmente, pon en pausa las relaciones de SnapMirror.



== Conoce las licencias de ONTAP

Algunas funciones requieren licencias, que se emiten como _packages_ que incluyen una o más funciones. Cada nodo del clúster debe tener su propia clave para cada función que se usará en el clúster.

Si no tiene claves de licencia nuevas, las funciones con licencia actualmente en el clúster están disponibles para la nueva controladora. Sin embargo, el uso de funciones sin licencia en la controladora puede dejar de cumplir con el acuerdo de licencia, de modo que debe instalar la nueva clave o las claves de licencia para la nueva controladora una vez que se haya completado la actualización.

Consulte link:other_references.html["Referencias"] Para establecer un enlace al sitio de soporte de _NetApp_, donde puede obtener nuevas claves de licencia de 28 caracteres para ONTAP. Las claves están disponibles en la sección _My Support_ en _Software licences_. Si el sitio no tiene las claves de licencia que necesita, puede ponerse en contacto con su representante de ventas de NetApp.

Para obtener información detallada sobre las licencias de ONTAP, consulta link:other_references.html["Referencias"] para enlazar con la _Referencia de administración del sistema_.



== Gestione el cifrado del almacenamiento con el gestor de claves incorporado

Usa el Onboard Key Manager (OKM) para gestionar las claves de cifrado. Si tienes el OKM configurado, debes registrar la frase de contraseña y el material de copia de seguridad antes de comenzar la actualización.

.Pasos
. Registre la clave de acceso para todo el clúster.
+
Esta es la frase de acceso que se introdujo cuando se configuró o actualizó OKM con la CLI o la API REST.

. Verifica la frase de contraseña y la operación del key-manager:
+
`security key-manager onboard sync`

+
Cuando te lo pidan, introduce la frase de contraseña OKM para todo el clúster que registraste en el paso anterior.

. Verifica que cc-mode está activado revisando la salida del siguiente comando:
+
`security key-manager config show`

. Haz una copia de seguridad de la información del key-manager:
+
`security key-manager onboard show-backup`





== Opcionalmente, silencia las relaciones SnapMirror

Antes de continuar con el procedimiento, debe confirmar que todas las relaciones de SnapMirror se ponen en modo inactivo. Cuando una relación de SnapMirror se pone en modo inactivo, sigue en modo inactivo tras reinicios y recuperaciones tras fallos.

.Pasos
. Compruebe el estado de la relación de SnapMirror en el clúster de destino:
+
`snapmirror show`

+
[NOTE]
====
Si el estado es "transferencia", debe anular dichas transferencias:
`snapmirror abort -destination-vserver _vserver_name_`

====
+
La anulación falla si la relación de SnapMirror no se encuentra en el estado "transfiriendo".

. Desactive todas las relaciones entre el clúster:
+
`snapmirror quiesce -destination-vserver *`



.El futuro
Después de preparar la actualización, link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["reubica los agregados que no son raíz y las LIF de datos NAS que pertenecen al nodo1 en el nodo2"].
