---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'Comprender si puede actualizar controladoras que ejecutan ONTAP 9.8 o una versión posterior mediante `system controller replace` comandos.' 
---
= Directrices para actualizar controladoras con ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para comprender si puede usar ARL para actualizar un par de controladoras que ejecuten ONTAP 9.8 o una versión posterior dependerá de la plataforma y la configuración de las controladoras original y de reemplazo.



[[supported-upgrades-for-arl]]
== Actualizaciones compatibles de ARL

Cuando actualice un par de nodos con este procedimiento ARL para ONTAP 9.8 o una versión posterior, compruebe que la ARL pueda realizarse en las controladoras originales y de reemplazo.

Debes comprobar el tamaño de todos los agregados definidos y el número de discos que admite el sistema original. Luego, debes comparar los tamaños de los agregados y el número de discos admitidos con el tamaño del agregado y el número de discos que admite el nuevo sistema. Consulta link:other-references.html["Referencias"] para ir a _Hardware Universe_, donde está disponible esta información. El tamaño del agregado y el número de discos que admite el nuevo sistema deben ser iguales o superiores al tamaño del agregado y al número de discos que admite el sistema original.

Debes comprobar en las reglas de combinación del clúster si los nuevos nodos pueden integrarse en el clúster junto con los nodos existentes cuando se sustituya el controlador original. Para obtener más información sobre las reglas de combinación del clúster, consulta link:other-references.html["Referencias"] para acceder a _Hardware Universe_.


NOTE: Si vas a actualizar un sistema que admite unidades internas (por ejemplo, un FAS2700 o un AFF A250) pero que NO cuenta con unidades internas, consulta link:other-references.html["Referencias"] y usa el procedimiento en el contenido _Aggregate Relocation to Manually Upgrade Controller Hardware_ que sea correcto para tu versión de ONTAP.

Si tiene un sistema con más de dos puertos de clúster por nodo, como un sistema FAS8080 o AFF8080, antes de iniciar la actualización, debe migrar y volver a home los LIF del clúster a dos puertos de clúster por nodo. Si realiza la actualización de la controladora con más de dos puertos de clúster por nodo, es posible que falten LIF en el nuevo controlador después de la actualización

La actualización de la controladora mediante ARL es compatible en sistemas configurados con volúmenes de SnapLock Enterprise y SnapLock Compliance.



[[two-node-switchless-clusters]]
== Clústeres de dos nodos sin switches

Si va a actualizar nodos en un clúster sin switches de dos nodos, puede dejar los nodos en el clúster sin switches mientras realiza la actualización. No es necesario convertirlos en un clúster con switches.



[[upgrades-not-supported-for-arl]]
== ARL no admite actualizaciones

No se pueden realizar las siguientes actualizaciones:

* Para el reemplazo de controladoras que no admiten las bandejas de discos conectadas a las controladoras originales
+
Consulta link:other-references.html["Referencias"] para enlazar con _Hardware Universe_ y ver información sobre la compatibilidad de discos.

* A controladores básicos con unidades internas, por ejemplo: un FAS2750.
+
Si deseas actualizar los controladores de nivel básico con unidades internas, consulta link:other-references.html["Referencias"] para acceder al enlace _Actualización mediante el traslado de volúmenes o almacenamiento_ y ve al procedimiento _Actualización de un par de nodos que ejecutan Clustered Data ONTAP mediante el traslado de volúmenes_.





[[metrocluster-fc-configuration]]
== Configuración de FC de MetroCluster

En una configuración de MetroCluster FC, debe sustituir los nodos del sitio de recuperación ante desastres/conmutación al nodo de respaldo lo antes posible. No se admite la discrepancia en los modelos de controladoras dentro de un MetroCluster, ya que el error de coincidencia del modelo de controladora puede provocar que la operación de mirroring de recuperación ante desastres se desconecte. Utilice `-skip-metrocluster-check true` el comando para omitir las comprobaciones de MetroCluster cuando va a reemplazar nodos en el segundo sitio.



[[troubleshoot]]
== Solucionar problemas

Es posible que aparezca un error mientras se actualiza la pareja de nodos. El nodo podría bloquearse, es posible que los agregados no se reubiquen o que los LIF no migren. La causa del fallo y su solución dependen de cuándo se produjo el fallo durante el procedimiento de actualización.

Si ocurre algún problema, consulte el link:aggregate_relocation_failures.html["Solucionar problemas"] Sección al final del procedimiento para obtener más información y posibles soluciones. La información sobre las fallas que pueden ocurrir se enumera por fase del procedimiento en el link:overview_of_the_arl_upgrade.html["Secuencia de actualización de ARL"] .

Si no encuentra ninguna solución al problema que encontró, póngase en contacto con el soporte técnico.

.El futuro
Después de revisar las directrices para actualizar los controladores con ARL, link:verify_health_of_metrocluster_config.html["verificar la salud de la configuración de MetroCluster"].
