---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 'Puede actualizar el hardware de la controladora que ejecuta ONTAP 9.8 o una versión posterior mediante `system controller replace` comandos, reubicar la propiedad de agregados que no son raíz.' 
---
= Descripción general
:allow-uri-read: 


[role="lead lead"]
Este procedimiento describe cómo actualizar el hardware de la controladora mediante la reubicación de agregados (ARL) para las siguientes configuraciones del sistema:

[cols="40,20,40"]
|===
| Método | Versión de ONTAP | Sistemas compatibles 


| Uso `system controller replace` comandos | 9.8 o posterior | link:decide_to_use_the_aggregate_relocation_guide.html#sys_commands_98_supported_systems["Enlace a la matriz de sistemas admitidos"] 
|===
Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo y, de este modo, reubicar la propiedad de agregados que no son raíz. Puede migrar agregados varias veces de nodo a nodo para confirmar que al menos un nodo está sirviendo datos desde los agregados a través del procedimiento de actualización. También puede migrar las interfaces lógicas de datos (LIF) y asignar los puertos de red de la nueva controladora a los grupos de interfaces a medida que continúa.

.Terminología utilizada en esta información
En esta información, los nodos originales reciben el nombre de "nodo 1" y "nodo 2", mientras que los nuevos se denominan "nodo 3" y "nodo 4". Durante el procedimiento descrito, el nodo 1 se reemplaza por nodo 3, y el nodo 2 se reemplaza por nodo 4. Los términos "1", "2", "nodo 3" y "nodo 4" solo se usan para distinguir entre los nodos originales y los nuevos. Cuando siga el procedimiento, deberá sustituir los nombres reales de los nodos originales y los nuevos. Sin embargo, en realidad los nombres de los nodos no cambian: El nodo 3 tiene el nombre 1-nodo y el nodo 4 tiene el nombre 2 después de actualizar el hardware de la controladora.

A lo largo de esta información, el término "sistemas con software de virtualización FlexArray" hace referencia a los sistemas que pertenecen a estas nuevas plataformas. El término "sistema V-Series" hace referencia a los sistemas de hardware independientes que pueden conectarse a las cabinas de almacenamiento.

.Información importante:
* Este procedimiento es complejo y asume que tiene habilidades avanzadas de administración de ONTAP. Usted también debe leer y entender el link:guidelines_for_upgrading_controllers_with_arl.html["Directrices para actualizar controladoras con ARL"] y la link:overview_of_the_arl_upgrade.html["Descripción general de la actualización de ARL"] secciones antes de comenzar la actualización.
* En este procedimiento se asume que el hardware de la controladora de reemplazo es nuevo y no se ha usado. Los pasos necesarios para preparar las controladoras usadas con el `wipeconfig` el comando no se incluye en este procedimiento. Debe ponerse en contacto con el soporte técnico si se utilizó anteriormente el hardware de la controladora de reemplazo, especialmente si las controladoras ejecutaban Data ONTAP en 7- Mode.
* Puede utilizar ARL para realizar una actualización de controladoras simplificada y sin interrupciones a una nueva controladora que ejecute una versión de ONTAP posterior a la versión que se ejecuta en el clúster que está actualizando. Las combinaciones de versiones de ONTAP para controladoras antiguas y nuevas están determinadas por el modelo de cadencia de actualizaciones no disruptivas de software de ONTAP. Por ejemplo, si tiene una controladora que ejecuta ONTAP 9.8 y esa es la última versión compatible de esa controladora, puede actualizar a una nueva controladora que ejecute una versión de ONTAP posterior a ONTAP 9.8.
+
Este procedimiento de actualización se aplica principalmente a situaciones de actualización en las que el modelo de controladora que se está reemplazando no admite versiones posteriores de ONTAP y la nueva controladora no admite versiones anteriores de ONTAP.

* Puede usar este procedimiento para actualizar el hardware de la controladora en clústeres con más de dos nodos; sin embargo, debe realizar el procedimiento por separado para cada pareja de alta disponibilidad (ha) del clúster.
* Este procedimiento se aplica a sistemas FAS, sistemas V-Series, sistemas AFF y sistemas con software de virtualización FlexArray. Los sistemas FAS publicados después de ONTAP 9.5 pueden conectarse a las cabinas de almacenamiento si se instala la licencia necesaria. Para obtener más información sobre la cabina de almacenamiento y los modelos V-Series, consulte link:other_references.html["Referencias"] Para enlazar con _Hardware Universe_ y pasar a la matriz de compatibilidad de V-Series.
* Este procedimiento se aplica a sistemas que ejecutan configuración MetroCluster de NetApp de 4 nodos o superior. Dado que los sitios de configuración de MetroCluster pueden estar en dos ubicaciones físicamente diferentes, la actualización automatizada de la controladora debe realizarse individualmente en cada site de MetroCluster para lograr un par de alta disponibilidad.
* Para sistemas que no son MetroCluster, como clústeres de alta disponibilidad, la actualización de ARL es el único procedimiento compatible.
* Si actualiza desde un sistema AFF A320, puede usar el movimiento de volúmenes para actualizar el hardware de la controladora o ponerse en contacto con el soporte técnico. Consulte link:other_references.html["Referencias"] Para enlazar con _Upgrade moviendo volúmenes o Storage_.

