---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'Verifique que los LIF de datos NAS del nodo 2 que están en el nodo 3 se reubican de nodo 3 a nodo 4 cuando se actualizan controladoras que ejecutan ONTAP 9.8 o una versión posterior mediante `system controller replace` comandos.' 
---
= Mueva agregados no raíz y LIF de datos NAS que pertenecen al nodo 2 desde el nodo 3 al nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Después de verificar la configuración de red en el nodo 4, debe reubicar los LIF de datos NAS propiedad del nodo 2 del nodo 3 al nodo 4 y confirmar que los LIF de SAN existen en el nodo 4.

.Acerca de esta tarea
Los LIF remotos manejan el tráfico a los LUN SAN durante el procedimiento de actualización. No es necesario mover los LIF de SAN por el estado del clúster o del servicio durante la actualización. Los LIF de SAN no se mueven a menos que sea necesario asignarlos a nuevos puertos.

Verifica que los LIF estén en buen estado y ubicados en los puertos correctos después de poner en línea el nodo 4.


NOTE: Si está cambiando la velocidad de puerto de las tarjetas de interfaz de red Ethernet basadas en T6 o los puertos de la placa base, puede que observe que se reciben paquetes con formato incorrecto después de la conversión de velocidad. Consulte https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["ID de error de NetApp Bugs Online: 1570339"^] y el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["Errores de CRC en puertos T6 después de convertir de 40GbE a 100GbE"^] para obtener orientación.

.Pasos
. Reanude la operación de reubicación:
+
[source, cli]
----
system controller replace resume
----
+
El sistema ejecuta las siguientes tareas:

+
** Comprobación de quórum del clúster
** Comprobación del ID del sistema
** Comprobación de la versión de la imagen
** Comprobación de la plataforma de destino
** Comprobación de accesibilidad de red


+
El sistema pausa la operación en esta etapa de la verificación de accesibilidad de la red.

. Reanude la operación de reubicación:
+
[source, cli]
----
system controller replace resume
----
+
El sistema realiza las siguientes comprobaciones:

+
** Comprobación del estado del clúster
** Comprobación del estado de LIF de clúster


+
Después de ejecutar estas comprobaciones, el sistema reubica los agregados que no son raíz y los LIF de datos NAS que pertenecen al nodo 2 en la nueva controladora, el nodo 4. La operación de reemplazo de la controladora se coloca en pausa una vez que se completa la reubicación de recursos.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
[source, cli]
----
system controller replace show-details
----
+
Si el procedimiento de reemplazo de la controladora está en pausa, compruebe y corrija el error, si corresponde, y luego emita `resume` para continuar la operación.

. Si es necesario, restaure y revierta los LIF desplazados o migre y modifique manualmente los LIF del nodo 2 que no pudieron reubicarse automáticamente en el nodo 4.
+
[role="tabbed-block"]
====
.Restaurar y revertir los LIF desplazados
--
.. Enumere todos los LIF desplazados:
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. Si alguna LIF se ha desplazado, restaure el nodo de inicio al nodo 4:
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.Migrar y modificar manualmente los LIF
--
.. Migre los LIF que no pudieron reubicarse automáticamente al nodo 4:
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. Modifique el nodo de inicio y el puerto de inicio para los LIF migrados:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. Reanude la operación para solicitar que el sistema realice las comprobaciones previas necesarias:
+
[source, cli]
----
system controller replace resume
----
+
El sistema realiza las siguientes comprobaciones posteriores:

+
** Comprobación de quórum del clúster
** Comprobación del estado del clúster
** Comprobación de reconstrucción de los agregados
** Comprobación del estado del agregado
** Comprobación del estado del disco
** Comprobación del estado de LIF de clúster
** Comprobación del volumen



