---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: 'Conozca cómo el procedimiento para actualizar controladoras que ejecutan ONTAP 9.8 o una versión posterior mediante `system controller replace` los comandos funcionan.' 
---
= Descripción general de la actualización de ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de actualizar los nodos mediante ARL, debe comprender cómo funciona el procedimiento. En este contenido, el procedimiento se divide en varias etapas.



== Actualice el par de nodos

Para actualizar la pareja de nodos, debe preparar los nodos originales y realizar una serie de pasos en los nodos original y en los nuevos. A continuación, puede retirar los nodos originales.



== Información general sobre la secuencia de actualizaciones de ARL

Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo, una controladora cada vez, aprovechando la configuración de par de alta disponibilidad para reubicar la propiedad de agregados que no son raíz. Todos los agregados que no son raíz deben pasar por dos reubicaciones para llegar a su destino final, que es el nodo actualizado correcto.

Cada agregado tiene un propietario particular y un propietario actual. El propietario del hogar es el propietario real del agregado, y el propietario actual es el propietario temporal.

La siguiente tabla describe las tareas de alto nivel que realiza durante cada etapa y el estado de propiedad del agregado al final de la etapa. Los pasos detallados se proporcionan más adelante en el procedimiento:

[cols="35,65"]
|===
| Etapa | Descripción 


| link:stage_1_index.html["Etapa 1. Prepare la actualización"]  a| 
Durante la fase 1, realizará comprobaciones previas y, si fuera necesario, corrija la propiedad del agregado. Debe registrar determinada información si gestiona el cifrado del almacenamiento mediante OKM y puede optar por desactivar las relaciones de SnapMirror.

Propiedad del agregado al final de la fase 1:

* El nodo 1 es el propietario raíz y el propietario actual de los agregados del nodo 1.
* El nodo 2 es el propietario particular y el propietario actual de los agregados del nodo 2.




| link:stage_2_index.html["Fase 2. Reubicar y retirar el nodo 1"]  a| 
Durante la fase 2, debe reubicar agregados no raíz y LIF de datos NAS al nodo 1 en el nodo 2. Este proceso está en gran medida automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Si es necesario, reubique los agregados que han fallado o que han vetado. Antes de retirar el nodo 1, registre la información del nodo 1 para su uso más adelante. También es posible preparar el modo de reiniciar el sistema de los nodos 3 y los nodos 4 más adelante en el procedimiento.

Propiedad del agregado al final de la fase 2:

* El nodo 2 es el propietario actual de los agregados del nodo 1.
* El nodo 2 es el propietario particular y el propietario actual de agregados del nodo 2.




| link:stage_3_index.html["Etapa 3. Instale y arranque el nodo 3"]  a| 
Durante la fase 3, instale e inicie node3, compruebe que el clúster y los puertos de gestión de nodos de node1 estén conectados en node3, vuelva a asignar los discos de node1 a node3 y verifique la instalación de node3. Si utiliza el cifrado de volúmenes de NetApp (NVE), debe restaurar la configuración del gestor de claves. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 3. También se deben reubicar los LIF de datos NAS del nodo 1 y los agregados no raíz del nodo 2 al nodo 3, y verificar que las LIF SAN existan en el nodo 3.

Propiedad agregada al final de la etapa 3:

* Node3 es el propietario raíz y el propietario actual de los agregados del nodo 1.
* El nodo 2 es el propietario particular y el propietario actual de agregados del nodo 2.




| link:stage_4_index.html["Etapa 4. Reubicar y retirar el 2"]  a| 
Durante la fase 4, se reubicarán los agregados no raíz y los LIF de datos NAS del nodo 2 al nodo 3. También puede grabar la información del nodo 2 para utilizarla más adelante en el procedimiento antes de retirar el nodo 2.

Propiedad agregada al final de la etapa 4:

* Node3 es el propietario raíz y el propietario actual de los agregados que originalmente pertenecían al nodo 1.
* El nodo 2 es el propietario en casa de los agregados 2.
* El nodo 3 es el propietario actual de agregados de 2 nodos.




| link:stage_5_index.html["Etapa 5. Instale y arranque el nodo 4"]  a| 
Durante la fase 5, instale e inicie node4, compruebe que el clúster y los puertos de gestión de nodos de node2 estén conectados en node4, vuelva a asignar los discos de node2 a node4 y verifique la instalación de node4. Si utiliza NVE, debe restaurar la configuración del gestor de claves. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 4. También se deben reubicar los LIF de datos NAS 2 y los agregados no raíz de nodo 3 a nodo 4, y verificar que las LIF SAN existan en el nodo 4.

Propiedad agregada al final de la etapa 5:

* Nodo 3 es el propietario raíz y el propietario actual de los agregados que originalmente pertenecían al nodo 1.
* Node4 es el propietario nacional y el propietario actual de agregados que pertenecía originalmente al nodo 2.




| link:stage_6_index.html["Etapa 6. Complete la actualización"]  a| 
Durante la fase 6, confirme que los nodos nuevos están configurados correctamente y, si los nodos nuevos tienen la función de cifrado habilitada, debe configurar y configurar el cifrado de almacenamiento o NVE. También debe retirar los nodos antiguos y reanudar las operaciones de SnapMirror.

|===