---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/reassign-node1-disks-to-node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'Debe reasignar los discos que pertenecían a node1 a node3 al actualizar las controladoras con ONTAP 9,8 o una versión posterior mediante `system controller replace` comandos.' 
---
= Reasigne discos de node1 GB a node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe reasignar los discos que pertenecían a node1 a node3 antes de verificar la instalación de node3.

.Acerca de esta tarea
Siga los pasos de esta sección en node3.

.Pasos
. [[reassign-node1-node3-app-step1]]Vaya al menú de inicio y, con 22/7, seleccione la opción oculta `boot_after_controller_replacement` . En el aviso, introduzca el nodo 1 para reasignar los discos del nodo 1 al nodo 3, según el ejemplo siguiente.
+
.Expanda el ejemplo de salida de consola
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: En el ejemplo de resultado de la consola anterior, ONTAP le solicitará el nombre del nodo asociado si el sistema utiliza discos de partición avanzada de disco (ADP).

. Si el sistema entra en un bucle de reinicio con el mensaje `no disks found`, indica que el sistema ha restablecido los puertos FC o UTA/UTA2 de nuevo al modo de destino y, por lo tanto, no puede ver ningún disco. Para resolver esto, continúe con <<reassign-node1-node3-app-step3,Paso 3>> Para <<reassign-node1-node3-app-step8,Paso 8>>o vaya a la sección link:verify_node3_installation.html["Verifique la instalación del nodo 3"].
. [[reassign-node1-node3-app-step3]]Pulse Ctrl-C durante el ARRANQUE AUTOMÁTICO para detener el nodo en el indicador Loader>.
. En el aviso del CARGADOR, introduzca el modo de mantenimiento:
+
`boot_ontap maint`

. En el modo de mantenimiento, muestre todos los puertos iniciadores previamente establecidos que ahora se encuentran en modo de destino:
+
`ucadmin show`

+
Cambie los puertos de nuevo al modo iniciador:

+
`ucadmin modify -m fc -t initiator -f _adapter name_`

. Compruebe que los puertos se han cambiado al modo iniciador:
+
`ucadmin show`

. Salga del modo de mantenimiento:
+
`halt`

+
[NOTE]
====
Si va a actualizar desde un sistema que admite discos externos a un sistema que también admite discos externos, vaya a <<reassign-node1-node3-app-step8,Paso 8>>.

Si va a actualizar desde un sistema que admite discos externos a un sistema que admita discos internos y externos, por ejemplo, un sistema AFF A800, vaya a <<reassign-node1-node3-app-step9,Paso 9>>.

====
. [[reassign-node1-node3-app-step8]]En el indicador de Loader, inicie:
+
`boot_ontap menu`

+
Ahora, en el arranque, el nodo puede detectar todos los discos que se le habían asignado previamente y puede arrancar según se esperaba.

+
Cuando los nodos de clúster que desea reemplazar utilizan cifrado de volumen raíz, ONTAP no puede leer la información de los volúmenes desde los discos. Restaure las claves del volumen raíz.

+

NOTE: Esto solo se aplica cuando el volumen raíz utiliza el cifrado de volúmenes de NetApp.

+
.. Vuelva al menú de inicio especial:
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. Seleccione *(10) establecer secretos de recuperación de Onboard Key Manager*
.. Introduzca `y` en el siguiente símbolo del sistema:
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. En la solicitud de, introduzca la frase de contraseña del gestor de claves.
.. Introduzca los datos de copia de seguridad cuando se le solicite.
+

NOTE: Debe haber obtenido la clave de acceso y los datos de backup en la link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"] sección de este procedimiento.

.. Después de que el sistema se inicie de nuevo en el menú de inicio especial, ejecute la opción *(1) Inicio normal*
+

NOTE: Es posible que se encuentre un error en este momento. Si se produce un error, repita los subpasos de <<reassign-node1-node3-app-step8,Paso 8>> hasta que el sistema arranque normalmente.



. [[reassign-node1-node3-app-step9]]Si está actualizando desde un sistema con discos externos a un sistema que admita discos internos y externos (sistemas AFF A800, por ejemplo), defina el agregado node1 como agregado raíz para confirmar que node3 se inicia desde el agregado raíz de node1. Para establecer el agregado raíz, vaya al menú de arranque y seleccione la opción `5` para entrar en modo de mantenimiento.
+

CAUTION: *Debe realizar los siguientes subpasos en el orden exacto que se muestra; de lo contrario, podría causar una interrupción o incluso pérdida de datos.*

+
El siguiente procedimiento establece el nodo 3 para arrancar desde el agregado raíz del nodo 1:

+
.. Entrar en el modo de mantenimiento:
+
`boot_ontap maint`

.. Compruebe la información de RAID, plex y suma de comprobación para el agregado 1-1:
+
`aggr status -r`

.. Compruebe el estado del agregado 1-1:
+
`aggr status`

.. Si es necesario, active el agregado de los nodos:
+
`aggr_online root_aggr_from___node1__`

.. Impida que el nodo 3 arranque desde su agregado raíz original:
+
`aggr offline _root_aggr_on_node3_`

.. Establezca el agregado raíz del nodo 1 como el nuevo agregado raíz del nodo 3:
+
`aggr options aggr_from___node1__ root`

.. Compruebe que el agregado raíz del nodo 3 esté sin conexión y que el agregado raíz de los discos extraídos del nodo 1 esté en línea y establecido en raíz:
+
`aggr status`

+

NOTE: Si no se pudo realizar el subpaso anterior, el nodo 3 se puede arrancar desde el agregado raíz interno, o bien es posible que el sistema asuma que existe una nueva configuración de clúster o que se le solicite identificar una.

+
El siguiente muestra un ejemplo de resultado del comando:

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



