---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'Configure los puertos FC integrados de nodo 4, los puertos UTA/UTA2 o la tarjeta UTA/UTA2 cuando actualice las controladoras que ejecutan ONTAP 9.8 o posterior mediante `system controller replace` comandos.' 
---
= Establezca la configuración de FC o UTA/UTA2 en el nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si el nodo 4 tiene puertos FC integrados, puertos de adaptador de objetivo unificado (UTA/UTA2) integrados o una tarjeta UTA/UTA2, debe configurar los ajustes antes de completar el resto del procedimiento.

.Acerca de esta tarea
Es posible que necesites completar<<Configure los puertos FC en el nodo 4>> o<<Comprobar y configurar los puertos UTA/UTA2 en el nodo 4>> , o ambas secciones.

[NOTE]
====
Si el nodo 4 no tiene puertos FC integrados, puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2 (por ejemplo, sistemas AFF y FAS introducidos a partir de ONTAP 9.15.1) y está actualizando un sistema con discos de almacenamiento, puede saltar alink:reassign-node2-disks-to-node4.html["Reasigne discos de node2 GB a node4"] .

Asegúrese de que el nodo 4 tenga suficiente espacio en rack. Si el nodo 4 se encuentra en un chasis separado del nodo 2, es posible colocar el nodo 4 en la misma ubicación que el nodo 3. Si el nodo 2 y el nodo 4 están en el mismo chasis, el nodo 4 ya se encuentra en la ubicación de rack adecuada.

====


== Configure los puertos FC en el nodo 4

Si el nodo 4 tiene puertos FC, ya sea integrados o en un adaptador FC complementario, debe establecer las configuraciones de los puertos en el nodo antes de ponerlo en servicio porque los puertos no están preconfigurados cuando se envían los sistemas.  Si no configura los puertos según lo requerido, podría experimentar una interrupción en el servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto de FC en el nodo 2 que haya guardado en la sección link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puede omitir esta sección si el sistema no tiene configuraciones de FC. Si su sistema tiene puertos UTA/UTA2 integrados o un adaptador UTA/UTA2, debe configurarlos en <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 4>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.

.Pasos
. Mostrar información sobre todos los adaptadores de red convergentes y FC en el sistema:
+
`system node hardware unified-connect show`

. Compare la configuración de FC del nodo 4 con la de los ajustes capturados anteriormente del nodo 1.
. Modifique los puertos FC en el nodo 4 según sea necesario:
+
** Para programar como puertos de destino:
+
`ucadmin modify -m fc -t target _adapter_`

+
Por ejemplo: `ucadmin modify -m fc -t target 2a`

** Para programar puertos iniciadores:
+
`ucadmin modify -m fc -t initiator _adapter_`

+
`-t` Es el tipo FC4: Objetivo o iniciador.

+
Por ejemplo: `ucadmin modify -m fc -t initator 2b`



. Detenga el nodo:
+
`halt`

. Arranque el sistema desde el símbolo del sistema del CARGADOR:
+
`boot_ontap menu`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Seleccione opción `5` desde el menú de arranque para el modo de mantenimiento.


. [[paso8]]realice una de las siguientes acciones:
+
** Vaya a. <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 4>> Si el nodo 4 tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados.
** Si el nodo 4 no tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, omita _Verificar y configurar puertos UTA/UTA2 en el nodo 4_ y vaya alink:reassign-node2-disks-to-node4.html["Reasigne discos de node2 GB a node4"] .






== Comprobar y configurar los puertos UTA/UTA2 en el nodo 4

Si el nodo 4 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA 2, debe comprobar la configuración de los puertos y configurarlos, según cómo se desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA 2. El modo FC admite iniciador FC y objetivo FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y admite destino FC.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Los puertos UTA/UTA2 pueden estar en un adaptador o en la controladora con las siguientes configuraciones:

* Las tarjetas UTA/UTA2 solicitadas al mismo tiempo que la controladora están configuradas antes del envío para tener la personalidad solicitada.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras están configurados (antes del envío) para tener la personalidad solicitada.


Sin embargo, debe comprobar la configuración de los puertos UTA/UTA2 del nodo 4 y cambiarlo, si es necesario.


WARNING: Introduzca los comandos de esta sección en el indicador de shell del modo de mantenimiento.

.Pasos
. Compruebe cómo están configurados actualmente los puertos en el nodo 4:
+
`system node hardware unified-connect show`

+
El sistema muestra un resultado similar al siguiente ejemplo:

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. Compruebe la configuración:
+
`ucadmin show`

+
Examine el resultado del `ucadmin show` Command y determine si los puertos UTA/UTA2 tienen la personalidad que desea.

+
La salida de los siguientes ejemplos muestra que el tipo FC4 del adaptador "1b" está cambiando a. `initiator` y que el modo de los adaptadores "2a" y "2b" está cambiando a. `cna`:

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. Realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si los puertos CNA... | Entonces… 


| No tenga la personalidad que usted desea | Vaya a. <<auto_check_4_step5,Paso 5>>. 


| Tenga la personalidad que usted desea | Omita los pasos 5 a 9 y vaya a<<auto_check_4_step10,Paso 10>> . 
|===
. [[auto_check_4_step5]]realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si va a configurar... | Entonces… 


| Puertos en una tarjeta UTA/UTA2 | Ir a<<auto_check_4_step6,Paso 6>> 


| Puertos UTA/UTA2 integrados | Omite el paso 6 y ve a<<auto_check_4_step7,Paso 7>> . 
|===
. [[auto_check_4_step6]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está en línea, desconecte el puerto UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[auto_check_4_step7]]Si la configuración actual no coincide con el uso deseado, cambie la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** `-m` Es el modo personalidad, FC o 10 GbE UTA.
** `-t` Es el tipo FC4, `target` o. `initiator`.
+

NOTE: Debe utilizar el iniciador FC para unidades de cinta y configuraciones de MetroCluster .  Debe utilizar el destino FC para los clientes SAN.



. Coloque cualquier puerto de destino en línea ingresando el siguiente comando, una vez para cada puerto:
+
`storage enable adapter <adapter_name>`

. Conecte el cable del puerto.


. [[auto_check_4_step10]]Salir del modo de mantenimiento:
+
`halt`

. [[step14]]Inicie el nodo en el menú de inicio:
+
`boot_ontap menu`



.El futuro
* Si va a actualizar a un sistema AFF A800, vaya a link:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["Reasigne los discos del nodo 2 al nodo 4, Paso 9"].
* Para todas las demás actualizaciones del sistema, vaya alink:reassign-node2-disks-to-node4.html["Reasigne los discos node2 a node4, paso 1"] .

