---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_5_index.html 
keywords: install, boot, node4, node2, node-management, stage 5 
summary: 'Secuencia de procesos en la fase 5 de una actualización de ARL mediante `system controller replace` Comandos en controladoras que ejecutan ONTAP 9.8 o una versión posterior.' 
---
= Etapa 5. Instale y arranque el nodo 4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 5, debe instalar y arrancar el nodo 4, compruebe que los puertos de gestión del clúster y de los nodos del nodo 2 estén en línea en el nodo 4 y verifique la instalación del nodo 4. Si utiliza NVE, debe restaurar la configuración del gestor de claves. Si es necesario, debe configurar FC o UTA/UTA2 en el nodo 4. También se deben reubicar los LIF de datos NAS 2 y los agregados no raíz de nodo 3 a nodo 4, y verificar que las LIF SAN existan en el nodo 4.

.Pasos
. link:install_boot_node4.html["Instale y arranque el nodo 4"]
. link:set_fc_or_uta_uta2_config_node4.html["Establezca la configuración de FC o UTA/UTA2 en el nodo 4"]
. link:verify_node4_installation.html["Verifique la instalación del nodo 4"]
. link:restore_key-manager_config_node4.html["Restaure la configuración de gestor de claves en el nodo 4"]
. link:move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html["Mueva agregados no raíz y LIF de datos NAS que pertenecen al nodo 2 desde el nodo 3 al nodo 4"]

