---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/boot_node1_with_a900_controller_and_nvs.html 
keywords: boot, NVRAM, controller, module, node1, aff, a700, a900 
summary: Nodo de arranque con el módulo de controlador AFF A900 y el módulo NVRAM. 
---
= Nodo de arranque con los controladores AFF A900 o FAS9500 y módulos NVRAM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El nodo 1 con el controlador AFF A900 o FAS9500 y los módulos NVRAM están ahora listos para el arranque. Una actualización de A700 de AFF a AFF A900 o de FAS9000 a FAS9500 intercambiando la controladora y los módulos NVRAM implica mover únicamente las conexiones de consola y de gestión. Esta sección proporciona los pasos necesarios para arrancar el nodo 1 con el controlador AFF A900 o FAS9500 y los módulos NVRAM.

.Pasos
. Ajuste la `bootarg.storageencryption.support` y.. `kmip.init.maxwait` variables para evitar un bucle de arranque después de cargar la configuración del nodo 1.
+
Si aún no lo ha hecho anteriormente en el procedimiento, consulte el artículo de la base de conocimientos https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["Cómo indicar que tengo unidades FIPS instaladas"^] para determinar el tipo de unidades de autocifrado que están en uso.

+
[cols="35,65"]
|===
| Si están en uso las siguientes unidades... | Entonces… 


| Unidades de cifrado en almacenamiento de NetApp (NSE) que cumplen con los requisitos de cifrado automático de nivel 2 de FIPS 140-2-2  a| 
** `setenv bootarg.storageencryption.support *true*`
** `setenv kmip.init.maxwait off`




| SED de NetApp no con FIPS  a| 
** `setenv bootarg.storageencryption.support *false*`
** `setenv kmip.init.maxwait off`


|===
+
[NOTE]
====
** No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad.
** Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.
** Si se produce una interrupción del suministro eléctrico después de configurar el `kmip.init.maxwait` variable a. `off`, póngase en contacto con el soporte técnico para obtener ayuda para evitar la posible pérdida de datos.
** Tan pronto como se complete la actualización de la controladora en el par de alta disponibilidad, debe anular la definición del `kmip.init.maxwait` variable. Consulte link:ensure_new_controllers_are_set_up_correctly.html["Confirmar que las nuevas controladoras están configuradas correctamente"].


====
. Arranque el nodo en el menú de arranque:
+
`boot_ontap menu`

. Reasigne los discos 1-1 del A700 de AFF al nodo 1 del AFF A900 introduciendo "22/7" y seleccionando la opción oculta `boot_after_controller_replacement` cuando el nodo se detiene en el menú de arranque.
+
Tras un breve retraso, se le pedirá que introduzca el nombre del nodo que se va a reemplazar. Si hay discos compartidos (también llamados Advanced Disk Partitioning (ADP) o discos con particiones), se le pedirá que introduzca el nombre del nodo del compañero de alta disponibilidad.

+
Estos mensajes pueden aparecer ocultos en los mensajes de la consola. Si no introduce un nombre de nodo o introduce un nombre incorrecto, se le pedirá que vuelva a introducir el nombre.

+
[NOTE]
====
Si `[localhost:disk.encryptNoSupport:ALERT]: Detected FIPS-certified encrypting drive` y, o `[localhost:diskown.errorDuringIO:error]: error 3 (disk failed) on disk` se producen errores, realice los pasos siguientes:

.. Detenga el nodo en el símbolo del sistema del CARGADOR.
.. Compruebe y restablezca los bootargs de cifrado de almacenamiento mencionados en <<A900_boot_node1,Paso 1>>.
.. En el símbolo del sistema del cargador, arranque:
+
`boot_ontap`



====
+
Puede utilizar el siguiente ejemplo como referencia:

+
.Expanda el ejemplo de salida de consola
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7

(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.



The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement

This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes

.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>

System rebooting...

.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
====
+
[NOTE]
====
Los ID del sistema que se muestran en el ejemplo anterior son ID de ejemplo. Los ID reales del sistema de los nodos que va a actualizar serán diferentes.

Entre introducir nombres de nodo en la solicitud de entrada y la solicitud de inicio de sesión, el nodo se reinicia unas cuantas veces para restaurar las variables de entorno, actualizar el firmware en las tarjetas del sistema y para otras actualizaciones de ONTAP.

====

