---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html 
keywords: cluster, ha, aff, a800, shared, storage, data, management 
summary: Conecte el clúster, la alta disponibilidad, el almacenamiento y las conexiones de datos que se habían conectado anteriormente al AFF A800 node1 al AFF A90 o AFF A70 node1 recién instalado 
---
= Cable node1 para cluster-HA compartido y almacenamiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si realiza una de las siguientes actualizaciones, debe conectar el clúster, la alta disponibilidad, el almacenamiento, los datos y las conexiones de gestión que se habían conectado previamente a la node1 en el sistema existente a la node1 recién instalada en el sistema de reemplazo.

[cols="35,65"]
|===
| Sistema existente | Sistema de sustitución 


| AFF A250 | AFF A30 y AFF A50 


| AFF C250 | AFF C30 y AFF C60 


| AFF A800 | AFF A70 y AFF A90 


| AFF C800 | C80 
|===


== Conecte los puertos e0M y BMC

Si el sistema existente tiene un puerto de gestión (e0M) y un puerto BMC, los puertos e0M y BMC se combinan y se accede a ellos a través del puerto «llave» del sistema de reemplazo. Antes de conectarse al sistema de reemplazo, debe asegurarse de que los puertos e0M y BMC estén conectados al mismo switch y a la misma subred del sistema existente.

[cols="35,65"]
|===
| Si... | Realice lo siguiente... 


| Las direcciones IP e0M y BMC están en la misma subred IP | Conecte el puerto e0M o BMC del sistema existente al puerto de llave del sistema de sustitución. 


| Las direcciones IP de e0M y BMC se encuentran en subredes diferentes  a| 
. Combine las direcciones IP e0M y BMC en una subred IP.
. Conecte el puerto e0M o BMC del sistema existente al puerto de llave del sistema de sustitución.


|===


== Conéctese a un clúster de dos nodos sin switches

En las siguientes tablas se muestra el uso de puertos del switch para configuraciones de clústeres sin switch de dos nodos.

|===
| Puerto | AFF A800 y AFF C800 | AFF A90 | AFF A70 y AFF C80 


| Clúster | e0a | e1a | e1a 


| Clúster | e1a | e7a (use e1b si no hay e7a) | e1b 


| HA | e0b | No conectar | No conectar 


| HA | e1b | No conectar | No conectar 


| Puertos de almacenamiento SAS (si existen y se utilizan) | Cualquier puerto disponible | Cualquier puerto disponible | Cualquier puerto disponible 


| Puertos de almacenamiento Ethernet para bandejas NS224 | Cualquier puerto disponible | Consulte Asignación de conectividad de almacenamiento Ethernet | Consulte Asignación de conectividad de almacenamiento Ethernet 
|===
|===
| Puerto | AFF A250 y AFF C250 | AFF A30, AFF C30, AFF C60 | AFF A50 


| Clúster y alta disponibilidad | e0c | e4a | e4a 


| Clúster y alta disponibilidad | e0d | e2a (use e4b si no hay e2a) | e2a (use e4b si no hay e2a) 


| Puertos de almacenamiento Ethernet | Cualquier puerto disponible | e3a, e3b | e3a, e3b 


| Puertos de almacenamiento SAS | Cualquier puerto disponible | 3a, 3b | 3a, 3b 
|===


== Conéctese a un clúster conectado a switches

Para un clúster con switch, compruebe que cumple con los siguientes requisitos para el nodo AFF A30, AFF A50, AFF A70, AFF A90, AFF C30, AFF C60 o AFF C80 (reemplazo):

* Los puertos de clúster idénticos en el nodo de reemplazo se encuentran en el mismo switch. Por ejemplo, al finalizar la actualización, se deben conectar e1a en node1 y e1a en node2 a un switch de clúster. De igual forma, el segundo puerto de clúster de ambos nodos debe conectarse al segundo switch de clúster. La conexión cruzada de puertos compartidos cluster-HA, donde e1a desde node1 está conectado a Switcha y e1a desde node2 está conectado al switch B, provoca fallos de comunicación de alta disponibilidad.
* El nodo de reemplazo utiliza puertos Ethernet compartidos de clúster-alta disponibilidad. Comprobar que los switches del clúster están instalados con un archivo de configuración de referencia (RCF) que sea compatible con los puertos compartidos de cluster-HA.

