---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: Decidir si utilizar el procedimiento ARL que actualiza los modelos de controladora en el mismo chasis. 
---
= Decida si desea utilizar el procedimiento de reubicación de agregados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este contenido describe cómo actualizar las controladoras de almacenamiento en un par de alta disponibilidad y mantener todos los datos y discos existentes. Se trata de un procedimiento complejo que sólo deben ser utilizados por administradores con experiencia.

Puede utilizar este procedimiento en las siguientes circunstancias:

* Está realizando una de las siguientes actualizaciones de la controladora:
+
[cols="50,50"]
|===
| La controladora anterior | Controladora de reemplazo 


| AFF A800 | AFF A70 y AFF A90 


| AFF A220 configurado como ASA | ASA A150 


| AFF A220, AFF A200 o AFF C190 | AFF A150 


| FAS2620 o FAS2720 | FAS2820 


| AFF A700 configurado como ASA | ASA A900 


| AFF A700 | AFF A900 


| FAS9000 | FAS9500 
|===
* Verificó con su representante de ventas de NetApp que recibió el hardware para actualizar su controladora:
+
** Dos o dos controladoras AFF A90 o dos AFF A70 y todos los módulos de I/O necesarios para la actualización. La longitud requerida de 100GbE cables.
** Controladoras ASA A150, AFF A150 o FAS2820
** Controladoras ASA A900, AFF A900 o FAS9500 y módulos NVRAM y las piezas necesarias para la actualización


* Está ejecutando la versión mínima de ONTAP para la actualización. Para obtener más información, consulte link:index.html["Descripción general"].
* No desea añadir las nuevas controladoras como una nueva pareja de alta disponibilidad al clúster y migrar los datos mediante movimientos de volúmenes.
* Tiene experiencia en la administración de ONTAP y se siente cómodo con los riesgos de trabajar en modo de privilegios de diagnóstico.


No puede utilizar este procedimiento en las siguientes circunstancias:

* Utiliza el software de virtualización FlexArray en los sistemas AFF A800, AFF A700 o FAS9000.
* En este caso, utiliza un switch compartido para la interconexión del clúster y almacenamiento conectado a Ethernet.


Para actualizar las configuraciones IP de MetroCluster en sistemas AFF A800, AFF A700 o FAS9000, consulte link:other_references.html["Referencias"] para vincular al contenido _Actualización y expansión de MetroCluster_.


NOTE: Puede usar el cifrado de almacenamiento de NetApp (NSE), el cifrado de volúmenes de NetApp (NVE) y el cifrado de agregados de NetApp (NAE) con este procedimiento.

Si prefiere un método diferente de actualización del hardware de la controladora y desea realizar movimientos de volúmenes, consulte link:other_references.html["Referencias"] Para enlazar con _Upgrade moviendo volúmenes o Storage_.

Consulte link:other_references.html["Referencias"] Para establecer un enlace al centro de documentación de _ONTAP 9_, donde puede acceder a la documentación de producto de ONTAP 9.
