---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: Comprenda si puede utilizar ARL para actualizar un A700 de AFF a un AFF A900. 
---
= Directrices para actualizar controladoras
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizar ARL para actualizar un par de controladoras que ejecuten ONTAP 9.10.1P10, 9.11.1P6 o una versión posterior en las siguientes configuraciones del sistema:

* Controladoras A700 de AFF a un sistema AFF A900
* Controladoras FAS9000 a un sistema FAS9500




== Actualizaciones compatibles de ARL

Actualización de la controladora de un A700 de AFF a un AFF A900 o de un FAS9000 a un FAS9500 con ARL, y el módulo NVRAM es la combinación compatible. Si ha recibido un nuevo sistema AFF A900 o FAS9500 como un sistema completo, incluido un nuevo chasis, consulte link:other_references.html["Referencias"] Para establecer un enlace con los comandos _use "system Controller replace" para actualizar el hardware de la controladora que ejecuta contenido de ONTAP 9.8 o posterior_.


WARNING: Este procedimiento se aplica estrictamente a una actualización de AFF A700 a AFF A900 o de FAS9000 a FAS9500 que ejecute ONTAP 9.10.1P10, 9.11.1P6 o una versión posterior. NO utilice este procedimiento para realizar una actualización entre otras combinaciones del sistema.

La actualización de la controladora mediante ARL es compatible en sistemas configurados con volúmenes de SnapLock Enterprise y SnapLock Compliance.



== Clústeres de dos nodos sin switches

Si va a actualizar nodos en un clúster sin switches de dos nodos, puede dejar los nodos en el clúster sin switches mientras realiza la actualización. No es necesario convertirlos en un clúster con switches.



== Solucionar problemas

Si ocurre algún problema mientras se actualizan las controladoras, consulte link:troubleshoot_index.html["Solucionar problemas"] sección al final del procedimiento para obtener más información y soluciones posibles.

Si no encuentra ninguna solución al problema que encontró, póngase en contacto con el soporte técnico.
