---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: Sepa si puede utilizar ARL, manteniendo el chasis y los discos del sistema antiguos, para la configuración de actualización. 
---
= Directrices para actualizar controladoras
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para comprender si puede utilizar la reubicación de agregados (ARL), que mantiene el antiguo chasis y los discos del sistema, depende de la configuración de actualización del sistema y de la versión de ONTAP.



== Actualizaciones compatibles de ARL

Las actualizaciones de controladoras son compatibles con ciertas configuraciones del sistema. Para ver la lista de sistemas compatibles y versiones mínimas de ONTAP, consulte link:index.html["Descripción general"].

Si ha recibido un nuevo AFF A30, AFF A50, AFF A70, AFF A90, AFF A150, AFF A900, AFF C30, AFF C60, AFF C80, FAS2820 o FAS9500 como sistema completo, incluyendo un nuevo chasis, consulte link:other_references.html["Referencias"]el enlace con los comandos _Use «system controller replace» para actualizar el hardware de la controladora con ONTAP 9,8 o posterior_.

La actualización de la controladora mediante ARL es compatible en sistemas configurados con volúmenes de SnapLock Enterprise y SnapLock Compliance.



== Clústeres de dos nodos sin switches

Si va a actualizar nodos en un clúster sin switches de dos nodos, puede dejar los nodos en el clúster sin switches mientras realiza la actualización. No es necesario convertirlos en un clúster con switches.



== Cambiar clústeres conectados

Si va a actualizar nodos en un clúster conectado a un switch de clúster, debe comprobar que la marca, el modelo, la versión de firmware, RCF y la versión de ONTAP que se ejecutan en el switch serán las mismas que las que se ejecutan en la controladora de reemplazo después de la actualización. Si es necesario, debe realizar la actualización del switch antes de actualizar las controladoras mediante ARL.

Para obtener más información, consulte link:upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["Conéctese a un clúster conectado a switches"].



== Solucionar problemas

Si ocurre algún problema mientras se actualizan las controladoras, consulte link:troubleshoot_index.html["Solucionar problemas"] sección al final del procedimiento para obtener más información y soluciones posibles.

Si no encuentra ninguna solución al problema que encontró, póngase en contacto con el soporte técnico.
