---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, aff, a700, a900 
summary: Puede actualizar el hardware de la controladora en un A700 de AFF a un AFF A900 intercambiando el módulo de la controladora y el NVS. 
---
= Descripción general
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Este procedimiento describe cómo actualizar el hardware de la controladora mediante la reubicación de agregados (ARL) para las siguientes configuraciones del sistema:

[cols="30,20,20,30"]
|===
| Método | Versión de ONTAP | Sistemas compatibles | Descripción 


| Uso `system controller replace` comandos | 9.10.1P10, 9.11.1P6 o una versión posterior | AFF A700 a AFF A900 | Convierte un sistema A700 de AFF en un sistema AFF A900, manteniendo el chasis A700 


| Uso `system controller replace` comandos | 9.10.1P10, 9.11.1P6 o una versión posterior | FAS9000 hasta FAS9500 | Convierte un sistema FAS9000 en un sistema FAS9500, manteniendo el chasis FAS9000. 
|===
Puede actualizar el hardware de una controladora de forma no disruptiva en un par de alta disponibilidad (ha) intercambiando la controladora y los módulos de NVRAM. Primero, debe migrar los agregados no raíz entre los nodos de la controladora antiguos. Después de la instalación, debe migrar los agregados no raíz de los nodos de la controladora antiguos a los nodos de la controladora de reemplazo. Durante el procedimiento de actualización, se puede acceder a los datos alojados en los nodos que se van a actualizar.

.Acerca de esta tarea
Durante este procedimiento de actualización de controladoras, solo puede cambiar las dos unidades reemplazables de campo (FRU) de cada nodo del sistema A700 o FAS9000 de AFF por las nuevas FRU.


NOTE: No es necesario mover, desconectar o volver a conectar las tarjetas de I/o, los cables de datos, las bandejas de discos y los discos.

Este procedimiento usa un método llamado reubicación de agregados (ARL), que aprovecha la configuración de alta disponibilidad para permitirle mover la propiedad de agregados que no son raíz de un nodo a otro si comparten almacenamiento dentro del mismo clúster.

Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo y, de este modo, reubicar la propiedad de agregados que no son raíz. Puede migrar agregados varias veces de nodo a nodo para confirmar que al menos un nodo está sirviendo datos desde los agregados a través del procedimiento de actualización. También migra LIF de datos entre nodos del clúster a medida que continúa.


NOTE: Los términos *1* y *2* sólo se utilizan como referencia a los nombres de nodo de este documento. Cuando siga el procedimiento, deberá sustituir los nombres reales de los nodos.

.Información adicional
* Este procedimiento es complejo y asume que tiene habilidades avanzadas de administración de ONTAP. Usted también debe leer y entender el link:guidelines_for_upgrading_controllers_with_arl.html["Directrices para actualizar controladoras"] y la link:overview_of_the_arl_upgrade.html["Descripción general de la actualización de ARL"] secciones antes de comenzar la actualización.
* En este procedimiento se asume que el hardware de la controladora de reemplazo es nuevo y no se ha usado en otro sistema. Los pasos necesarios para preparar las controladoras usadas con el `wipeconfig` el comando no se incluye en este procedimiento. Debe ponerse en contacto con el soporte técnico si el hardware de la controladora de reemplazo se utilizó anteriormente como parte de otro clúster de ONTAP o como sistema de un único nodo independiente.
* Puede usar este procedimiento para actualizar el hardware de la controladora en clústeres con más de dos nodos; sin embargo, debe realizar el procedimiento por separado para cada pareja de alta disponibilidad del clúster.
* Este procedimiento solo se aplica a sistemas A700 y FAS9000 de AFF. Para todos los demás modelos de controlador que necesiten actualizar a un sistema AFF A900 o FAS9500, consulte la link:other_references.html["Referencias"] Para enlazar con los comandos _use "system Controller replace" para actualizar el hardware de la controladora que ejecuta ONTAP 9.8 o posterior_ y el _Using aggregate Relocation para actualizar manualmente el hardware de la controladora que ejecuta contenido de ONTAP 9.8 o posterior_.
* Los sistemas AFF A900 y FAS9500 solo admiten alimentación de gama alta (de 200 V a 240 V). Si su sistema A700 o FAS9000 de AFF se ejecuta con una alimentación de línea baja (de 100 V a 120 V), debe convertir la alimentación de entrada de AFF A700 o FAS9000 antes de utilizar este procedimiento.
* Si va a actualizar desde un sistema A700 o FAS9000 de AFF con tiempos de inactividad, puede actualizar el hardware de la controladora moviendo almacenamiento o poniéndose en contacto con el soporte técnico. Consulte link:other_references.html["Referencias"] Para enlazar con _Upgrade moviendo volúmenes o Storage_.

