---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: Puede actualizar el hardware de la controladora convirtiendo un sistema antiguo en un sistema de reemplazo y manteniendo los discos y chasis del sistema antiguos. 
---
= Conozca este procedimiento de actualización de ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varios métodos de reubicación agregada (ARL) para actualizar el hardware de las controladoras. Este procedimiento describe cómo actualizar las controladoras de almacenamiento en un par de alta disponibilidad (HA) convirtiendo el sistema existente en el sistema de reemplazo, conservando el chasis y los discos del sistema existente.

ARL se beneficia de la configuración de alta disponibilidad y la comunicación entre clústeres. Esto le permite mover la propiedad de agregados no raíz de un nodo a otro si comparten almacenamiento dentro del mismo clúster.

Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo y, de este modo, reubicar la propiedad de agregados que no son raíz. Debe migrar los agregados no raíz entre los nodos de la controladora antiguos. Después de instalar los nodos de reemplazo, se deben migrar los agregados no raíz desde los nodos de la controladora antiguos a los nodos de la controladora de reemplazo. Durante el procedimiento de actualización, se puede acceder a los datos alojados en los nodos que se van a actualizar. También migra LIF de datos entre nodos del clúster a medida que continúa.

El hardware de la controladora que sustituye depende del tipo de modelo de sistema existente:

[cols="30,70"]
|===
| Si su sistema existente es... | Realice lo siguiente... 


| AFF A250 y AFF C250 | Intercambie las dos controladoras AFF A250 o AFF C250 con las nuevas controladoras y los módulos I/O. 


| AFF A800 y AFF C800 | Intercambie las dos controladoras AFF A800 o AFF C800 con las nuevas controladoras y los módulos I/O. 


| AFF A220, AFF A200, AFF C190, FAS2620 o FAS2720 | Intercambie el módulo del controlador en cada nodo de la controladora antigua por el módulo nuevo. 


| AFF A700 o FAS9000 | Intercambie la controladora y los módulos NVRAM de cada nodo de la controladora antigua con los módulos nuevos. *Nota*: No es necesario mover, desconectar o volver a conectar las tarjetas de E/S, los cables de datos, los estantes de discos y los discos. 
|===

NOTE: Los términos *1* y *2* sólo se utilizan como referencia a los nombres de nodo de este documento. Al seguir el procedimiento, debe sustituir los nombres reales de los nodos.



== Requisitos y limitaciones

Debe tener en cuenta factores importantes antes de comenzar el procedimiento de actualización.


NOTE: Debe revisar toda la siguiente información importante antes de comenzar el procedimiento de actualización.

* Este procedimiento es complejo y asume que tiene habilidades avanzadas de administración de ONTAP. También debe leer y comprender el link:guidelines_for_upgrading_controllers_with_arl.html["Pautas para actualizar los controladores"] y link:overview_of_the_arl_upgrade.html["Secuencia de actualización de ARL"] antes de comenzar la actualización.
* En este procedimiento se asume que el hardware de la controladora de reemplazo es nuevo y no se ha usado en otro sistema. Los pasos necesarios para preparar las controladoras usadas con el `wipeconfig` el comando no se incluye en este procedimiento. Debe ponerse en contacto con el soporte técnico si el hardware de la controladora de reemplazo se utilizó anteriormente como parte de otro clúster de ONTAP o como sistema de un único nodo independiente.
* Puede usar este procedimiento para actualizar el hardware de la controladora en clústeres con más de dos nodos; sin embargo, debe realizar el procedimiento por separado para cada pareja de alta disponibilidad del clúster.
* Si tiene un switch que no es compatible con la versión de ONTAP y el sistema de sustitución al que está actualizando, consulte link:other_references.html["Referencias"] Para enlazar con _Hardware Universe_.
* Los sistemas AFF A250 y AFF C250 utilizan puertos integrados de 10/25 GbE para la interconexión de clústeres. Para actualizar clústeres sin conmutador de dos nodos de un sistema AFF A250 o AFF C250 a un sistema AFF A50, AFF A30, AFF C60 o AFF C30, debe usar una tarjeta X60132A de 4 puertos de 10/25 GbE en la ranura 1 de ambos nodos. Esto proporciona interconexión de clústeres para los LIF de clúster a un puerto temporal en la plataforma de destino.
* Los sistemas AFF A30, AFF A50, AFF A70, AFF A90, AFF A1K, AFF C30, AFF C60, AFF C80, FAS70 y FAS90 comparten 100GbE puertos de red para conexiones de clúster y de alta disponibilidad. Estos sistemas pueden admitir conexiones de clúster 10GbE o 25GbE a switches de clúster heredados; sin embargo, NetApp recomienda actualizar a las velocidades de clúster de 100GbE GbE cuando los switches 10GbE y 25GbE ya no sean necesarios. Para obtener más información, consulte los siguientes artículos de la base de conocimientos:
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["Cómo configurar los puertos de clúster 10G o 25G en una nueva configuración de clúster"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["Cómo convertir los puertos de clúster 10G o 25G existentes a puertos de clúster 40G o 100g"^]


--
+
Si no puede conectar los puertos de clúster e0a o e0b del nodo existente a los puertos de clúster del nodo nuevo, consulte lo siguiente para obtener más información:

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["ID de error de NetApp Bugs Online CONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["ID de error de NetApp Bugs Online: 1127315"^]


* Los sistemas ASA A900, AFF A900 y FAS9500 solo admiten energía de línea alta (de 200V V a 240V V CA). Si su sistema A700 o FAS9000 de AFF se ejecuta con una alimentación de línea baja (de 100 V a 120 V), debe convertir la alimentación de entrada de AFF A700 o FAS9000 antes de utilizar este procedimiento.
* Si va a actualizar desde un sistema existente con un tiempo de inactividad incluido en los <<supported-systems-in-chassis,matriz de sistemas compatibles>>, puede actualizar el hardware de la controladora moviendo almacenamiento o ponerse en contacto con el soporte técnico. Consulte link:other_references.html["Referencias"] el enlace _Actualizar moviendo volúmenes o almacenamiento_.




== Automatice el proceso de actualización de la controladora

Este procedimiento proporciona los pasos para el procedimiento automatizado, que utiliza la asignación de disco automática y comprobaciones de accesibilidad de puertos de red para simplificar la experiencia de actualización de controladora.
