---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: Instale los módulos del sistema de reemplazo en node2 durante una actualización ARL de los modelos de controladora en el mismo chasis. 
---
= Instale el módulo AFF A30, AFF A50, AFF C30 o AFF C60 en node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Instale el módulo de controlador de reemplazo que recibió para la actualización en node2. El nodo 2 es el controlador B ubicado en la mitad inferior del chasis cuando se miran los controladores desde la parte trasera del sistema.

.Pasos
. Coloque el sistema de almacenamiento en los rieles situados en el centro del armario o rack de telecomunicaciones, y luego apoye el sistema de almacenamiento desde la parte inferior y deslícelo en su lugar.
+

NOTE: No inserte por completo el módulo de la controladora en el chasis hasta que se le indique hacerlo más adelante en el procedimiento.

. Conecte los puertos de consola y de gestión al módulo de controladora 2.
+

NOTE: Debido a que el chasis ya está encendido, el nodo 2 inicia la inicialización del BIOS seguida del AUTOBOOT tan pronto como está completamente instalado.  Para interrumpir el arranque del nodo 2, antes de insertar completamente el módulo controlador en la ranura, se recomienda conectar los cables de administración y de consola serial al módulo controlador del nodo 2.

. Con el mango de leva en la posición abierta, empuje firmemente el módulo del controlador hasta que se encuentre con el plano medio y quede completamente asentado. El pestillo de bloqueo se eleva cuando el módulo del controlador está completamente asentado. Cierre la palanca de leva a la posición de bloqueo.
+

NOTE: Para evitar dañar los conectores, no ejerza demasiada fuerza al deslizar el módulo del controlador en el chasis.

. Conecte la consola serial tan pronto como el módulo esté instalado y prepárese para interrumpir el AUTOBOOT del nodo2.
. Después de interrumpir EL ARRANQUE AUTOMÁTICO, el nodo 2 se detiene en el símbolo del sistema del CARGADOR. Si no interrumpe el AUTOARRANQUE a tiempo y node2 comienza el arranque, espere a que se le indique el prompt y pulse Ctrl-C para ir al menú de arranque. Cuando el nodo se detenga en el menú de arranque, utilice la opción `8` para reiniciar el nodo e interrumpir EL AUTOARRANQUE durante el reinicio.
. En el símbolo del SISTEMA LOADER> 2, establezca las variables de entorno predeterminadas:
+
`set-defaults`

. Guarde la configuración predeterminada de las variables de entorno:
+
`saveenv`

. Para configuraciones sin conmutador de dos nodos, verifique que tenga una tarjeta X60132A de 4 puertos 10/25 GbE en la ranura 1 del nodo 2. La tarjeta X60132A es necesaria para la interconexión del clúster durante la actualización.

