---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/manage-authentication-using-kmip-servers.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configure y gestione el cifrado de almacenamiento, gestione las claves de autenticación y ponga en modo inactivo las relaciones de SnapMirror durante una actualización de AFF A700 a AFF A900. 
---
= Gestionar la autenticación mediante servidores KMIP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir de ONTAP 9.10.1, se pueden usar servidores de protocolo de interoperabilidad de gestión de claves (KMIP) para gestionar las claves de autenticación.

.Pasos
. Añadir una nueva controladora:
+
`security key-manager external enable`

. Añada el gestor de claves:
+
`security key-manager external add-servers -key-servers _key_management_server_ip_address_`

. Verifique que los servidores de gestión de claves estén configurados y disponibles para todos los nodos del clúster:
+
`security key-manager external show-status`

. Restaure las claves de autenticación de todos los servidores de gestión de claves vinculados al nuevo nodo:
+
`security key-manager external restore -node _new_controller_name_`


