---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_and_nas_data_lifs_back_to_node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: Compruebe que los LIF de datos NAS de node2 en node1 se reubican de node1 a node2 cuando utiliza ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Vuelva a colocar los agregados que no son raíz y las LIF de datos NAS en el nodo 2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Después de verificar la configuración de red en node2 y antes de reubicar agregados de node1 a node2, debe verificar que los LIF de datos NAS que pertenecen a node2 y que están actualmente en node1 se reubiquen de node1 a node2. También debe verificar si las LIF DE SAN existen en el nodo 2.

.Acerca de esta tarea
Las LIF remotas gestionan el tráfico a LUN DE SAN durante el procedimiento de actualización. No es necesario mover LIF DE SAN durante la actualización para el estado del clúster o del servicio. Los LIF SAN no se mueven a menos que tengan que asignarse a nuevos puertos. Después de conectar el nodo 2 en línea, debe verificar que las LIF están en buen estado y estén ubicadas en los puertos adecuados.

.Pasos
. Reanude la operación de reubicación:
+
`system controller replace resume`

+
El sistema ejecuta las siguientes tareas:

+
--
** Comprobación de quórum del clúster
** Comprobación del ID del sistema
** Comprobación de la versión de la imagen
** Comprobación de la plataforma de destino
** Comprobación de accesibilidad de red


--
+
La operación se detiene en esta fase de la comprobación de accesibilidad de red.

. Reanude la operación de reubicación:
+
`system controller replace resume`

+
El sistema realiza las siguientes comprobaciones:

+
--
** Comprobación del estado del clúster
** Comprobación del estado de LIF de clúster


--
+
Después de realizar estas comprobaciones, el sistema reubica los agregados no raíz y las LIF de datos NAS en node2, que ahora se está ejecutando en la controladora de reemplazo.

+
La operación de reemplazo de la controladora se coloca en pausa una vez que se completa la reubicación de recursos.

. Comprobar el estado de las operaciones de reubicación de agregados y movimiento de LIF de datos de NAS:
+
`system controller replace show-details`

+
Si el procedimiento de reemplazo de la controladora está en pausa, compruebe y corrija el error, si corresponde, y luego emita `resume` para continuar la operación.

. Si es necesario, restaure y devuelva los LIF desplazados. Enumerar las LIF desplazadas:
+
`cluster controller-replacement network displaced-interface show`

+
Si hay alguna LIF desplazada, restaurar el nodo inicial a 2:

+
`cluster controller-replacement network displaced-interface restore-home-node`

. Reanude la operación para solicitar que el sistema realice las comprobaciones previas necesarias:
+
`system controller replace resume`

+
El sistema realiza las siguientes comprobaciones posteriores:

+
** Comprobación de quórum del clúster
** Comprobación del estado del clúster
** Comprobación de reconstrucción de los agregados
** Comprobación del estado del agregado
** Comprobación del estado del disco
** Comprobación del estado de LIF de clúster
** Comprobación del volumen



