---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/prepare_nodes_for_upgrade.html 
keywords: preparing, prepare, nodes, upgrade, stage 1, prechecks, old, system, chassis, disk, disks 
summary: Prepare los nodos y ejecute una serie de comprobaciones previas cuando utilice ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Prepare los nodos para la actualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El proceso de reemplazo de la controladora comienza con una serie de comprobaciones previas. También se recopila información sobre los nodos originales para usar más adelante del procedimiento y, si es necesario, determinar el tipo de unidades de cifrado automático que se están usando.

.Pasos
. Enumere la versión del firmware del Service Processor (SP) o de la controladora de gestión de la placa base (BMC) que se ejecuta en la controladora anterior:
+
`service-processor show`

+
Compruebe que tiene una versión de firmware de SP o BMC compatible:

+
[cols="30,35,35"]
|===
| La controladora anterior | SP o BMC | Versión de firmware mínima 


| AFF A800 | BMC | 10,9 


| AFF A220 | BMC | 11.9P1 


| AFF A200 | SP | 5.11P1 


| C190 de AFF | BMC | 11.9P1 


| FAS2620 | SP | 5.11P1 


| FAS2720 | BMC | 11.9P1 
|===
. Para iniciar el proceso de sustitución de la controladora, introduzca el siguiente comando en el modo de privilegio avanzado de la línea de comandos de ONTAP:
+
`set -privilege advanced`

+
`system controller replace start -nodes _node_names_`

+
Verá un resultado similar al siguiente ejemplo. La salida muestra la versión de ONTAP que se ejecuta en el clúster:

+
....
Warning:
1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedures.

Do you want to continue? {y|n}: y
....
. Seleccione `y`. Verá la siguiente salida:
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
Durante la fase de comprobaciones previas, el sistema ejecuta la siguiente lista de comprobaciones en segundo plano.

+
[cols="35,65"]
|===
| Comprobación previa | Descripción 


| Comprobación del estado del clúster | Comprueba todos los nodos del clúster para confirmar que están en buen estado. 


| Comprobación del estado de reubicación de agregados | Comprueba si ya hay una reubicación de agregados en curso. Si hay otra reubicación de agregado en curso, la comprobación falla. 


| Comprobación del nombre del modelo | Comprueba si los modelos de controlador son compatibles con este procedimiento. Si los modelos no son compatibles, la tarea falla. 


| Comprobación de quórum de clúster | Comprueba que los nodos que se van a sustituir tengan quórum. Si los nodos no están en quórum, la tarea falla. 


| Comprobación de la versión de la imagen | Comprueba que los nodos que se reemplazan ejecuten la misma versión de ONTAP. Si las versiones de la imagen ONTAP son diferentes, la tarea fallará. Los nodos nuevos deben tener la misma versión de ONTAP 9.x instalada en ellos que se haya instalado en los nodos originales. Si los nodos nuevos tienen instalada una versión diferente de ONTAP, debe reiniciar el sistema las controladoras nuevas después de instalarlas. Para obtener instrucciones sobre cómo actualizar ONTAP, consulte link:other_references.html["Referencias"] Para enlazar a _Upgrade ONTAP_. 


| Comprobación de estado de HA | Comprueba si los dos nodos que se van a reemplazar se encuentran en una configuración de parejas de alta disponibilidad (ha). Si no está habilitada la conmutación por error del almacenamiento para las controladoras, la tarea falla. 


| Comprobación del estado del agregado | Si los nodos que se van a sustituir tienen agregados propios para los que no son el propietario principal, la tarea fallará. Los nodos no deben tener ningún agregado que no sea local. 


| Comprobación del estado del disco | Si alguno de los nodos que se van a reemplazar tiene discos ausentes o con errores, la tarea falla. Si falta algún disco, consulte link:other_references.html["Referencias"] Para establecer un vínculo a la gestión de discos y agregados con la CLI_, _administración de almacenamiento lógico con la CLI_ y _Administración de alta disponibilidad_ para configurar el almacenamiento para el par de alta disponibilidad. 


| Comprobación del estado de LIF de datos | Comprueba si alguno de los nodos que se van a sustituir tiene LIF de datos no locales. Los nodos no deben contener ninguna LIF de datos para la cual no sean el propietario principal. Si uno de los nodos contiene LIF de datos no locales, la tarea falla. 


| Estado de LIF del clúster | Comprueba si los LIF del clúster están activos para ambos nodos. Si las LIF del clúster están inadas, la tarea falla. 


| Comprobación del estado de ASUP | Si no se configuran las notificaciones de AutoSupport, la tarea falla. Debe habilitar AutoSupport antes de iniciar el procedimiento de reemplazo de la controladora. 


| Comprobación del uso de CPU | Comprueba si el uso de CPU es superior al 50 % en el caso de cualquiera de los nodos que se van a sustituir. Si el uso de CPU es superior al 50 % durante un período de tiempo considerable, la tarea falla. 


| Comprobación de reconstrucción de agregados | Comprueba si la reconstrucción se está produciendo en algún agregado de datos. Si la reconstrucción del agregado está en curso, la tarea falla. 


| Comprobación de trabajo de afinidad de nodo | Comprueba si se están ejecutando trabajos de afinidad de nodos. Si se están ejecutando trabajos de afinidad de nodo, la comprobación falla. 
|===
. Una vez iniciada la operación de sustitución de las controladoras y que se completen las comprobaciones previas, la operación se coloca en pausa, lo que permite recopilar información de salida que se pueda necesitar más adelante en el proceso de actualización de las controladoras.
. Ejecute el siguiente conjunto de comandos según lo indicado por el procedimiento de reemplazo de la controladora en la consola del sistema.
+
Ejecute los comandos desde el puerto serie conectado a cada nodo, ejecute y guarde la salida de los comandos individualmente:

+
** `vserver services name-service dns show`
** `network interface show -curr-node _local_ -role cluster,intercluster,node-mgmt,cluster-mgmt,data`
** `network port show -node _local_ -type physical`
** `service-processor show -node _local_ -instance`
** `network fcp adapter show -node _local_`
** `network port ifgrp show -node _local_`
** `system node show -instance -node _local_`
** `run -node _local_ sysconfig`
** `run -node local sysconfig -ac`
** `run -node local aggr status -r`
** `vol show -fields type`
** `run local aggr options _data_aggregate_name_`
** `vol show -fields type , space-guarantee`
** `storage aggregate show -node _local_`
** `volume show -node _local_`
** `storage array config show -switch _switch_name_`
** `system license show -owner _local_`
** `storage encryption disk show`
** `security key-manager onboard show-backup`
** `security key-manager external show`
** `security key-manager external show-status`
** `network port reachability show -detail -node _local_`
+

NOTE: Si el cifrado de volúmenes de NetApp (NVE) o el cifrado de agregado de NetApp (NAE) con el gestor de claves integrado están en uso, mantenga la frase de acceso del gestor de claves preparada para completar el administrador de claves de nuevo a sincronizar más adelante en el procedimiento.



. Si su sistema utiliza unidades de autocifrado, consulte el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["Cómo saber si una unidad tiene la certificación FIPS"^] Para determinar el tipo de unidades de autocifrado que se están utilizando en la pareja de alta disponibilidad que se está actualizando. El software ONTAP admite dos tipos de unidades de autocifrado:
+
--
** Unidades SAS o NVMe con cifrado en almacenamiento de NetApp (NSE) certificado FIPS
** Unidades NVMe (SED) con autocifrado no FIPS


[NOTE]
====
No es posible mezclar unidades FIPS con otros tipos de unidades en el mismo nodo o la pareja de alta disponibilidad.

Puede mezclar unidades de cifrado distinto de SED en el mismo nodo o par de alta disponibilidad.

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["Obtenga más información sobre las unidades de autocifrado compatibles"^].

--




== Corrija la propiedad del agregado si fallan las comprobaciones previas de ARL

Si falla la comprobación del estado del agregado, debe devolver los agregados propiedad del nodo asociado al nodo propietario principal e iniciar de nuevo el proceso de comprobaciones previas.

.Pasos
. Devolver los agregados que actualmente pertenecen al nodo asociado al nodo propietario principal:
+
`storage aggregate relocation start -node _source_node_ -destination _destination-node_ -aggregate-list *`

. Compruebe que ni el nodo 1 ni el nodo 2 siguen teniendo agregados cuyos propietarios son actualmente (pero no el propietario del hogar):
+
`storage aggregate show -nodes _node_name_ -is-home false -fields owner-name, home-name, state`

+
En el ejemplo siguiente se muestra el resultado del comando cuando un nodo es al mismo tiempo el propietario actual y el propietario principal de los agregados:

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== Después de terminar

Debe reiniciar el proceso de sustitución de la controladora:

`system controller replace start -nodes _node_names_`



== Licencia

Cada nodo del clúster debe tener su propio archivo de licencia de NetApp (NLF).

Si no dispone de un NLF, las funciones con licencia actualmente en el clúster están disponibles para la nueva controladora. Sin embargo, el uso de funciones sin licencia en la controladora puede provocar que no cumpla el contrato de licencia, por lo que debe instalar NLF en la nueva controladora una vez completada la actualización.

Consulte link:other_references.html["Referencias"] Para establecer un enlace al sitio de soporte de _NetApp_, donde puede obtener su NLF. Los NLF están disponibles en la sección _My Support_ en _Software licenses_. Si el sitio no tiene el NLF que necesita, póngase en contacto con su representante de ventas de NetApp.

Para obtener información detallada sobre las licencias, consulte link:other_references.html["Referencias"] Para vincular a _System Administration Reference_.
