---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1, NVRAM, controller, module, modules 
summary: Reubique los agregados no raíz de node2 a node1 cuando utilice ARL para actualizar los modelos de controladoras en el mismo chasis. 
---
= Reubique los agregados que no son raíz y los LIF de datos NAS del nodo 2 al nodo 1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de poder sustituir node2 con el módulo del sistema de reemplazo, primero debe reubicar los agregados no raíz que pertenecen a node2 a node1.

.Antes de empezar
Una vez completadas las comprobaciones posteriores a la fase anterior, la versión de recursos para el nodo 2 se iniciará automáticamente. Los agregados que no son raíz y los LIF de datos que no son SAN se migran del nodo 2 al nuevo nodo 1.

.Acerca de esta tarea
Una vez migrados los agregados y las LIF, la operación se coloca en pausa con fines de verificación. En este momento, debe comprobar que todos los agregados que no son raíz y los LIF de datos no SAN se han migrado al nodo 1 nuevo.

El propietario raíz de los agregados y las LIF no se modifica; solo se modifica el propietario actual.

.Pasos
. Compruebe que todos los agregados que no son raíz están en línea y su estado en el nodo 1:
+
`storage aggregate show -node node1 -state online -root false`

+
El ejemplo siguiente muestra que los agregados no raíz del nodo 1 están en línea:

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	  #Vols	 Nodes	 RAID	  Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB     744.8GB	  0%	  online	  5	 node1   raid_dp  normal
aggr_2	      825.0GB	  825.0GB	  0%	  online	  1	 node1   raid_dp  normal
2 entries were displayed.
----
+
Si los agregados se han desconectado o quedan extranjeros en el nodo 1, conectarlos utilizando el siguiente comando del nuevo nodo 1, una vez para cada agregado:

+
`storage aggregate online -aggregate _aggr_name_`

. Verifique que todos los volúmenes estén conectados en el nodo 1 usando el siguiente comando del nodo 1 y examinando su resultado:
+
`volume show -node node1 -state offline`

+
Si alguno de los volúmenes está sin conexión en el nodo 1, conectarlos utilizando el siguiente comando del nodo 1, una vez para cada volumen:

+
`volume online -vserver _vserver-name_ -volume _volume-name_`

+
La `_vserver-name_` para utilizarlo con este comando se encuentra en el resultado del anterior `volume show` comando.

. Compruebe que las LIF se han movido a los puertos correctos y que tienen el estado de `up`. Si alguna LIF está inactiva, establezca el estado administrativo de las LIF en `up` Con el siguiente comando, una vez para cada LIF:
+
`network interface modify -vserver _vserver_name_ -lif _LIF_name_ -home-node _nodename_ - status-admin up`

. Compruebe que no haya ninguna LIF de datos en el nodo 2 mediante el siguiente comando y examinar el resultado:
+
`network interface show -curr-node _node2_ -role data`


