---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/stage_2_index.html 
keywords: upgrade, preparing, preparation, prepare, overview, stage 1 
summary: 'Secuencia de fase 2 de procesos para una actualización de ARL mediante `system controller replace` Comandos en controladoras que ejecutan ONTAP 9.8 o una versión posterior.' 
---
= Fase 2. Reubique los recursos del nodo 1 y retire el nodo 1 del A700 o el FAS9000 de AFF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durante la fase 2, debe reubicar agregados no raíz y LIF de datos NAS al nodo 1 en el nodo 2. Este proceso está en gran medida automatizado; la operación se pausa para permitir comprobar su estado. Debe reanudar manualmente la operación. Si es necesario, reubique los agregados que han fallado o que han vetado. Debe registrar la información del nodo 1 para su uso posterior en el procedimiento y, a continuación, cambiar el controlador del nodo 1 y los módulos NVRAM correspondientes, retirar el nodo 1 y reiniciar el sistema con el nodo 1 actualizado.

.Pasos
. link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["Reubique los agregados que no son raíz y los LIF de datos NAS que pertenecen al nodo 1 al nodo 2"]
. link:relocate_failed_or_vetoed_aggr.html["Se han producido fallos en la reubicación o los agregados vetados"]
. link:retire_node1.html["Retire el nodo 1"]
. link:netboot_node1.html["Reiniciar el sistema"]

