---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Antes de iniciar la actualización, verifique que disponga del hardware correcto para actualizar los modelos de controladora en el mismo chasis. 
---
= Verifique la actualización de hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de iniciar la actualización, compruebe que tiene los módulos correctos para el sistema de sustitución. Si faltan piezas, póngase en contacto con el soporte técnico o con su representante de ventas de NetApp para obtener ayuda.

[cols="50,50"]
|===
| Si va a actualizar desde... | El sistema de sustitución debe tener... 


| AFF A250 y AFF C250 | Dos módulos de controladora y nuevos módulos I/O. 


| AFF A800 y AFF C800 | Dos módulos de controladora, dos NVRAMs y nuevos módulos I/O. 


 a| 
* AFF A220 configurado como ASA
* AFF A220, AFF A200, AFF C190
* FAS2620, FAS2720

 a| 
Dos módulos de controladora

Si va a convertir el sistema existente en una bandeja de almacenamiento para poder conectarlo a otro sistema, el sistema de sustitución también debe tener dos módulos de I/O.



 a| 
* AFF A700 configurado como ASA
* AFF A700
* FAS9000

| Dos controladoras y dos módulos NVRAM 
|===