---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_upgrade_hardware.html 
keywords: nodes, upgrade, verify, hardware 
summary: Antes de iniciar la actualización, verifique que disponga del hardware correcto para actualizar los modelos de controladora en el mismo chasis. 
---
= Verifique la actualización de hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de iniciar la actualización, compruebe que dispone del hardware correcto para la actualización. En función de la actualización, para cada par de alta disponibilidad que vaya a actualizar, debe tener dos módulos de controladora o dos módulos de controladora y dos módulos NVRAM para el sistema de reemplazo. Si faltan piezas, póngase en contacto con el soporte técnico o con su representante de ventas de NetApp para obtener ayuda.

[cols="50,50"]
|===
| Si está actualizando... | El sistema de sustitución debe tener... 


| AFF A800 | Dos módulos de controladora, dos NVRAMs y nuevos módulos I/O. 


| AFF A220 configurado como ASA para ASA A150 | Dos módulos de controladora 


| AFF A220, AFF A200 o AFF C190 a AFF A150 | Dos módulos de controladora 


| FAS2620 o FAS2720 a FAS2820 | Dos módulos de controladora 


| AFF A700 configurado como ASA para ASA A900 | Dos controladoras y dos módulos NVRAM 


| AFF A700 a AFF A900 | Dos controladoras y dos módulos NVRAM 


| FAS9000 hasta FAS9500 | Dos controladoras y dos módulos NVRAM 
|===