---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: Decida si desea utilizar el procedimiento ARL manual para actualizar los controladores de almacenamiento en un par HA con nuevos controladores que ejecutan ONTAP 9.8 o posterior. 
---
= Decidir si se utilizará este procedimiento de reubicación agregada
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este procedimiento describe cómo actualizar el hardware del controlador mediante la reubicación manual de agregados (ARL) en sistemas con ONTAP 9.8 o posterior. Solo debe usar este procedimiento complejo si es un administrador de ONTAP con experiencia.

Utilice este contenido en las siguientes circunstancias:

* No quiere añadir las nuevas controladoras como una nueva pareja de alta disponibilidad al clúster y migrar los datos mediante los movimientos de volúmenes.
* Tiene experiencia en la administración de ONTAP y se siente cómodo con los riesgos de trabajar en el modo de privilegios de diagnóstico.
* Sus controladores ejecutan ONTAP 9.8 o posterior.
* Tiene un sistema que utiliza configuraciones de 4 y 8 nodos de Fabric MetroCluster que ejecutan ONTAP 9.8 o una versión posterior.
* Tiene agregados híbridos en el sistema.


[NOTE]
====
* Si vas a actualizar un sistema intercambiando módulos de controladora en el mismo chasis, como AFF A800 o AFF C800, NetApp recomienda encarecidamente usar el procedimiento de actualización que link:../upgrade-arl-auto-in-chassis/index.html["actualiza los modelos de controladores usando ARL, manteniendo el chasis del sistema, los discos y los datos existentes"]. Este procedimiento ARL incluye los pasos que aseguran que los discos internos permanezcan seguros en el chasis cuando quites e instales las controladoras durante el procedimiento de actualización.
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["Conoce las combinaciones de actualización de sistemas compatibles usando ARL, manteniendo el chasis, los discos y los datos del sistema existente"].

* Puede usar el cifrado de almacenamiento de NetApp (NSE), el cifrado de volúmenes de NetApp (NVE) y el cifrado de agregados de NetApp (NAE) con este procedimiento.


====
Si prefiere un método diferente de actualización del hardware de la controladora y desea realizar movimientos de volúmenes, consulte link:other_references.html["Referencias"] Para enlazar con _Upgrade moviendo volúmenes o Storage_.

Consulte link:other_references.html["Referencias"] Para establecer un enlace al centro de documentación de _ONTAP 9_, donde puede acceder a la documentación de producto de ONTAP 9.



== Elija un procedimiento de actualización de hardware diferente

* link:../upgrade-arl/index.html["Revise los métodos ARL alternativos disponibles para actualizar el hardware del controlador"].
* Si prefiere un método diferente de actualización del hardware de la controladora y desea realizar movimientos de volúmenes, consulte link:other_references.html["Referencias"] Para enlazar con _Upgrade moviendo volúmenes o Storage_.


.Información relacionada
Referirse a link:other_references.html["Referencias"] para vincular a la _Documentación de ONTAP 9_.

.El futuro
Después de decidir si utilizar este procedimiento ARL, link:arl_upgrade_workflow.html["revisar el flujo de trabajo de actualización de ARL"].
