---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/get_address_key_management_server_encryption.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: Configure el cifrado del almacenamiento durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.8 o posterior. 
---
= Obtenga la dirección IP de un servidor de gestión de claves externo para el cifrado de almacenamiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Después de la actualización, debe configurar de inmediato el cifrado del almacenamiento y establecer una clave de autenticación en todo el clúster para reemplazar las claves de autenticación en el nivel de nodo anteriores.

.Pasos
. Instale los certificados de capa de sockets seguros (SSL) de cliente y servidor necesarios para comunicarse con los servidores de gestión de claves:
+
`security certificate install`

. Configure el cifrado del almacenamiento en todos los nodos mediante el siguiente comando en cada nodo:
+
`security key-manager setup`

. Añada la dirección IP para cada servidor de gestión de claves:
+
`security key-manager add`

. Compruebe que los mismos servidores de gestión de claves estén configurados y disponibles en todos los nodos del clúster:
+
`security key-manager show -status`

. Cree una nueva clave de autenticación para todo el clúster:
+
`security key-manager create-key`

. Anote el nuevo ID de clave de autenticación.
. ReKey todas las unidades de autocifrado con la nueva clave de autenticación:
+
`storage encryption disk modify -disk * -data-key-id _authentication_key_id_`


