---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: Utilice el procedimiento de actualización manual de ARL para actualizar el hardware de la controladora que ejecute ONTAP 9.8 o una versión posterior y reubicar la propiedad de agregados no raíz. 
---
= Conozca este procedimiento de actualización de ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este procedimiento describe cómo actualizar el hardware del controlador mediante la reubicación manual de agregados (ARL) en sistemas que ejecutan ONTAP 9.8 o posterior.

Puede utilizar este procedimiento ARL si está realizando una de las siguientes actualizaciones:

* Desde el sistema FAS hasta el sistema FAS
* Desde el sistema AFF hasta el sistema AFF
+
Sólo puede actualizar a un sistema de sustitución de la misma serie:

+
** El sistema A-Series de AFF para el sistema AFF A-Series
** Del sistema C-Series de AFF al sistema AFF C-Series


* Desde el sistema ASA hasta el sistema ASA
+
No se admiten las actualizaciones de ASA a un sistema de sustitución de ASA R2. Para obtener más información sobre la migración de datos de ASA a ASA R2, consulte link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["Habilite el acceso a datos desde hosts SAN a su sistema de almacenamiento ASA R2"^].

+
Sólo puede actualizar a un sistema de sustitución de la misma serie:

+
** El sistema A-Series de ASA para el sistema ASA A-Series
** Del sistema C-Series de ASA al sistema ASA C-Series




Durante el procedimiento, debe actualizar el hardware de la controladora original con el hardware de la controladora de reemplazo y, de este modo, reubicar la propiedad de agregados que no son raíz. Puede migrar agregados varias veces de nodo a nodo para confirmar que al menos un nodo está sirviendo datos desde los agregados a través del procedimiento de actualización. También puede migrar las interfaces lógicas de datos (LIF) y asignar los puertos de red de la nueva controladora a los grupos de interfaces a medida que continúa.


NOTE: En este documento, los nodos originales se denominan _nodo1_ y _nodo2_, y los nuevos nodos se denominan _nodo3_ y _nodo4_.  Durante el procedimiento descrito, el nodo1 se reemplaza por el nodo3 y el nodo2 se reemplaza por el nodo4.  Los términos _nodo1_, _nodo2_, _nodo3_ y _nodo4_ se utilizan únicamente para distinguir entre los nodos originales y los nuevos.  Al seguir el procedimiento, debes sustituir los nombres reales de tus nodos originales y nuevos.  Sin embargo, en realidad, los nombres de los nodos no cambian: el nodo3 tiene el nombre nodo1 y el nodo4 tiene el nombre nodo2 después de que se actualiza el hardware del controlador.

.Información importante:
* Este procedimiento es complejo y asume que tiene habilidades avanzadas de administración de ONTAP. También debe leer y comprender el link:guidelines_upgrade_with_arl.html["Pautas para actualizar controladores con ARL"] y el link:arl_upgrade_workflow.html["Flujo de trabajo de actualización de ARL"] antes de comenzar la actualización.
* En este procedimiento se asume que el hardware de la controladora de reemplazo es nuevo y no se ha usado. Los pasos necesarios para preparar las controladoras usadas con el `wipeconfig` el comando no se incluye en este procedimiento. Debe ponerse en contacto con el soporte técnico si se utilizó anteriormente el hardware de la controladora de reemplazo, especialmente si las controladoras ejecutaban Data ONTAP en 7-Mode.
* Puede usar este procedimiento para actualizar el hardware de la controladora en clústeres con más de dos nodos; sin embargo, debe realizar el procedimiento por separado para cada pareja de alta disponibilidad (ha) del clúster.


* Además de configuraciones que no sean de MetroCluster, este procedimiento se aplica a configuraciones de cuatro y ocho nodos de Fabric MetroCluster que ejecuten ONTAP 9.8 y versiones posteriores.
+
** Para configuraciones de MetroCluster que ejecuten ONTAP 9.7 y versiones anteriores, vaya a. link:other_references.html["Referencias"] Para enlazar con _Using aggregate Relocation a Upgrade manualmente hardware de controladora que ejecuta ONTAP 9.7 o anterior_.
** Para configuraciones de IP de MetroCluster y opciones de actualización adicionales para configuraciones de Fabric MetroCluster, vaya a. link:other_references.html["Referencias"] Para vincular al contenido de _MetroCluster Upgrade y Expansion_.



