---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/manage_authentication_okm.html 
keywords: manage, authentication, onboard key manager, okm, key, passphrase, fips 
summary: Use el administrador de claves incorporado para gestionar claves de autenticación durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9,8 o posterior. 
---
= Gestione claves de autenticación mediante el gestor de claves incorporado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede utilizar el Administrador de claves integrado (OKM) para gestionar las claves de autenticación. Si tiene configurado OKM, debe registrar la frase de acceso y el material de copia de seguridad antes de iniciar la actualización.

.Pasos
. Registre la clave de acceso para todo el clúster.
+
Esta es la frase de acceso que se introdujo cuando se configuró o actualizó OKM con la CLI o la API REST.

. Verifica la frase de contraseña y la operación del key-manager:
+
`security key-manager onboard sync`

+
Cuando te lo pidan, introduce la frase de contraseña OKM para todo el clúster que registraste en el paso anterior.

. Verifica que cc-mode está activado revisando la salida del siguiente comando:
+
`security key-manager config show`

. Haz una copia de seguridad de la información del key-manager:
+
`security key-manager onboard show-backup`



.El futuro
Después de gestionar las claves de autenticación mediante Onboard Key Manager, link:quiesce_snapmirror_relationships.html["pausa las relaciones SnapMirror"].
