---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: Verifique que los puertos físicos del nodo 1 se asignen correctamente al nodo 3 durante una actualización manual de ARL en controladoras que ejecuten ONTAP 9.8 o una versión posterior. 
---
= Asigne puertos del nodo 1 al nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe asegurarse de que los puertos físicos del nodo 1 se asignen correctamente a los puertos físicos del nodo 3, lo que permitirá que el nodo 3 se comunique con otros nodos del clúster y con la red después de la actualización.

.Antes de empezar
Ya debe tener información acerca de los puertos en los nodos nuevos del _Hardware Universe_. (Vaya a. link:other_references.html["Referencias"] Para establecer un enlace con el _Hardware Universe_). Utilice la información posteriormente en esta sección y en link:map_ports_node2_node4.html["Asigne puertos del nodo 2 al nodo 4"].

La configuración de software del nodo 3 debe coincidir con la conectividad física del nodo 3, y es necesario restaurar la conectividad IP para poder continuar con la actualización.

.Acerca de esta tarea
La configuración del puerto puede variar en función del modelo de los nodos.

.Pasos
. [[step1]]realice los siguientes pasos para verificar si la configuración es un clúster sin switch de dos nodos:
+
.. Configure el nivel de privilegio en Advanced:
+
`set -privilege advanced`

.. Compruebe si la configuración es un clúster sin switches de dos nodos:
+
`network options switchless-cluster show`

+
Por ejemplo:

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
El valor de este comando debe coincidir con el estado físico del sistema.

.. Volver al nivel de privilegio de administración:
+
`set -privilege admin`



. [[step2]]realice los siguientes cambios:
+
.. Modifique los puertos que forman parte del dominio de retransmisión del clúster:
+
`network port modify -node _node_name_ -port _port_name_ -mtu 9000 -ipspace Cluster`

+
En este ejemplo, se añade el puerto de clúster e1b en la opción "1-1":

+
[listing]
----
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000
----
.. Migre las LIF del clúster a los nuevos puertos, una vez por cada LIF:
+
`network interface migrate -vserver _Vserver_name_ -lif _lif_name_ -source-node _node1_ -destination-node _node1_ -destination-port _port_name_`

+
Cuando se migran todas las LIF del clúster y se establece la comunicación del clúster, el clúster debe entrar en quórum.

.. Modifique el puerto de inicio de las LIF de clúster:
+
`network interface modify -vserver Cluster -lif _lif_name_ –home-port _port_name_`

.. Quite los puertos antiguos del dominio de retransmisión de clúster:
+
`network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports _node1:port_`

.. Muestra el estado del nodo 1 y del nodo 3:
+
`cluster show -node _node1_ -fields health`

.. Según la versión de ONTAP que se ejecute en el par de alta disponibilidad que se va a actualizar, realice una de las siguientes acciones:
+
[cols="30,70"]
|===
| Si la versión de ONTAP es... | Realice lo siguiente... 


| 9,8 a 9.11.1 | Compruebe que las LIF del clúster están escuchando en el puerto 7700:

`::> network connections listening show -vserver Cluster` 


| 9.12.1 o posterior | Omita este paso y vaya a. <<man_map_1_step3,Paso 3>>. 
|===
+
El resultado esperado de la escucha del puerto 7700 en los puertos del clúster tal y como se muestra en el siguiente ejemplo de un clúster de dos nodos:

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. Para cada LIF de clúster que no esté escuchando en el puerto 7700, establezca el estado administrativo de la LIF en `down` y después `up`:
+
`::> net int modify -vserver Cluster -lif _cluster-lif_ -status-admin down; net int modify -vserver Cluster -lif _cluster-lif_ -status-admin up`

+
Repita el paso secundario (f) para comprobar que la LIF del clúster ahora está escuchando en el puerto 7700.



. [[man_map_1_step3]]modifique las membresías de dominio de difusión de puertos físicos que alojan LIF de datos.
+
.. Enumerar el estado de accesibilidad de todos los puertos:
+
`network port reachability show`

.. Repare la accesibilidad de los puertos físicos, seguidos de los puertos VLAN, ejecutando el siguiente comando en cada puerto, un puerto cada vez:
+
`reachability repair -node _node_name_ -port _port_name_`

+
Se espera una advertencia como la siguiente. Revise e introduzca `y` o. `n` según corresponda:

+
[listing]
----
WARNING: Repairing port "node_name:port" might cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
.. Para que ONTAP complete la reparación, espere un minuto aproximadamente después de ejecutar el `reachability repair` en el último puerto.
.. Enumere todos los dominios de retransmisión del clúster:
+
`network port broadcast-domain show`

.. A medida que se realiza la reparación de accesibilidad, ONTAP intenta colocar los puertos en los dominios de retransmisión correctos. Sin embargo, si la accesibilidad de un puerto no se puede determinar y no corresponde con ninguno de los dominios de difusión existentes, ONTAP creará nuevos dominios de difusión para estos puertos. Según sea necesario, puede eliminar los dominios de retransmisión recientemente creados si todos sus puertos miembro se convertirán en puertos miembros de los grupos de interfaces. Eliminar dominios de retransmisión:
+
`broadcast-domain delete -broadcast-domain _broadcast_domain_`

.. Revise la configuración del grupo de interfaces y, según sea necesario, añada o elimine puertos miembro.
+
Añada puertos miembro a los puertos del grupo de interfaces:

+
`ifgrp add-port -node _node_name_ -ifgrp _ifgrp_port_ -port _port_name_`

+
Quite puertos miembro de los puertos del grupo de interfaces:

+
`ifgrp remove-port -node _node_name_ -ifgrp _ifgrp_port_ -port _port_name_`

.. Elimine y vuelva a crear puertos VLAN según sea necesario. Eliminar puertos VLAN:
+
`vlan delete -node _node_name_ -vlan-name _vlan_port_`

+
Crear puertos VLAN:

+
`vlan create -node _node_name_ -vlan-name _vlan_port_`

+

NOTE: En función de la complejidad de la configuración de red del sistema que se está actualizando, puede que sea necesario repetir los subpasos (a) a (g) hasta que todos los puertos estén colocados correctamente cuando sea necesario.



. [[step4]]Si no hay ninguna VLAN configurada en el sistema, vaya a. <<man_map_1_step5,Paso 5>>. Si hay VLAN configuradas, restaure las VLAN desplazadas configuradas previamente en puertos que ya no existen o que se configuraron en puertos que se movieron a otro dominio de difusión.
+
.. Mostrar las VLAN desplazadas:
+
`cluster controller-replacement network displaced-vlans show`

.. Restaure las VLAN desplazadas al puerto de destino deseado:
+
`displaced-vlans restore -node _node_name_ -port _port_name_ -destination-port _destination_port_`

.. Compruebe que se han restaurado todas las VLAN desplazadas:
+
`cluster controller-replacement network displaced-vlans show`

.. Las VLAN se colocan automáticamente en los dominios de retransmisión correspondientes un minuto después de su creación. Compruebe que las VLAN restauradas se hayan colocado en los dominios de retransmisión correspondientes:
+
`network port reachability show`



. [[man_map_1_step5]]a partir de ONTAP 9.8, ONTAP modificará automáticamente los puertos de inicio de las LIF si los puertos se mueven entre dominios de difusión durante el procedimiento de reparación de accesibilidad del puerto de red. Si el puerto principal de una LIF se trasladó a otro nodo, o si no está asignado, esa LIF se presentará como LIF desplazada. Restaure los puertos de inicio de LIF desplazadas cuyos puertos de inicio ya no existen o se reubicaron en otro nodo.
+
.. Muestre las LIF cuyos puertos iniciales podrían haberse movido a otro nodo o ya no existen:
+
`displaced-interface show`

.. Restaure el puerto de inicio de cada LIF:
+
`displaced-interface restore -vserver _Vserver_name_ -lif-name _LIF_name_`

.. Compruebe que se han restaurado todos los puertos iniciales de LIF:
+
`displaced-interface show`



+
Cuando todos los puertos se configuran y se añaden correctamente a los dominios de retransmisión correctos, el `network port reachability show` el comando debería informar el estado de accesibilidad como "ok" para todos los puertos conectados y el estado como "no-accesibilidad" para puertos sin conectividad física. Si alguno de los puertos informa de un estado distinto de estos dos, repare la accesibilidad tal como se describe en <<man_map_1_step3,Paso 3>>.

. [[man_map_1_step6]]Compruebe que todas las LIF están administrativamente activas en puertos que pertenecen a los dominios de difusión correctos.
+
.. Compruebe si existen LIF administrativamente inactivos:
+
`network interface show -vserver _Vserver_name_ -status-admin down`

.. Compruebe si existen LIF operativos inactivos:
+
`network interface show -vserver _Vserver_name_ -status-oper down`

.. Modifique los LIF que deban modificarse para que tengan un puerto de inicio diferente:
+
`network interface modify -vserver _Vserver_name_ -lif _LIF_name_ -home-port _home_port_`

+

NOTE: Para los LIF iSCSI, la modificación del puerto inicial requiere que la LIF esté administrativamente inactiva.

.. Revertir las LIF que no son home con sus respectivos puertos:
+
`network interface revert *`




