---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: Configure los puertos FC integrados de nodo 3, los puertos UTA/UTA2 o la tarjeta UTA/UTA2 durante una actualización manual ARL en controladoras que ejecutan ONTAP 9.8 o posterior. 
---
= Establezca la configuración de FC o UTA/UTA2 en el nodo 3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si el nodo 3 tiene puertos FC integrados, puertos de adaptador de objetivo unificado (UTA/UTA2) integrados o una tarjeta UTA/UTA2, debe configurar los ajustes antes de completar el resto del procedimiento.

.Acerca de esta tarea
Es posible que necesites completar<<Configure los puertos FC en el nodo 3>> o<<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>> , o ambas secciones.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término «UTA2» para referirse a adaptadores y puertos de CNA. Sin embargo, la CLI utiliza el término "CNA".

Si el nodo 3 no tiene puertos FC integrados, puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2 (por ejemplo, sistemas AFF y FAS introducidos a partir de ONTAP 9.15.1) y está actualizando un sistema con discos de almacenamiento, puede saltar al siguiente paso.link:map_ports_node1_node3.html["Asigne puertos del nodo 1 al nodo 3"] .



== Configure los puertos FC en el nodo 3

Si el nodo 3 tiene puertos FC, ya sea integrados o en un adaptador FC complementario, debe establecer las configuraciones de los puertos en el nodo antes de ponerlo en servicio porque los puertos no están preconfigurados cuando se envían los sistemas.  Si no configura los puertos, podría experimentar una interrupción en el servicio.

.Antes de empezar
Debe tener los valores de configuración del puerto FC del nodo 1 donde haya guardado link:prepare_nodes_for_upgrade.html["Prepare los nodos para la actualización"].

.Acerca de esta tarea
Puede omitir esta sección si el sistema no tiene configuraciones de FC. Si su sistema tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe configurarlos en <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.


IMPORTANT: Introduzca los comandos de esta sección en el indicador del clúster.

.Pasos
. Muestra información sobre todos los adaptadores de red convergentes y FC en el sistema.
+
`system node hardware unified-connect show`

. Compare la configuración FC del nodo3 con la configuración que capturó anteriormente del nodo1.
. [[man_config_3_step3]]Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si la configuración de FC predeterminada en los nodos nuevos es... | Realice lo siguiente... 


| Igual que los que capturó en el nodo 1 | Vaya a <<man_config_3_step9,Paso 9>>. 


| Diferente de las que capturó en el nodo 1 | Vaya a <<man_config_3_step4,Paso 4>>. 
|===
. [[man_config_3_step4]]Modifique los puertos FC en el nodo 3 según sea necesario ingresando uno de los siguientes comandos:
+
** Para programar puertos de destino:
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** Para programar puertos iniciadores:
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` Es el tipo FC4: Objetivo o iniciador.



. Verifique la nueva configuración ingresando el siguiente comando y examinando el resultado:
+
`system node hardware unified-connect show`

. Salir del modo de mantenimiento:
+
`halt`

. Tras introducir el comando, espere hasta que el sistema se detenga en el símbolo del sistema del entorno de arranque.
. Arranque el nodo 3 en el indicador del entorno de arranque:
+
`boot_ontap`

. [[man_config_3_step9]]Realice una de las siguientes acciones:
+
** Si el nodo 3 tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, vaya a. <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>>.
** Si el nodo 3 no tiene una tarjeta UTA/UTA2 o puertos UTA/UTA2 integrados, omita <<Comprobar y configurar los puertos UTA/UTA2 en el nodo 3>> y vaya a. link:map_ports_node1_node3.html["Asigne puertos del nodo 1 al nodo 3"].






== Comprobar y configurar los puertos UTA/UTA2 en el nodo 3

Si el nodo 3 tiene puertos UTA/UTA2 integrados o una tarjeta UTA/UTA2, debe comprobar la configuración de los puertos y es posible que los vuelva a configurar, según cómo desee usar el sistema actualizado.

.Antes de empezar
Debe tener los módulos SFP+ correctos para los puertos UTA/UTA2.

.Acerca de esta tarea
Si desea utilizar un puerto adaptador de objetivo unificado (UTA/UTA2) para FC, primero debe verificar cómo se ha configurado el puerto.


NOTE: Los materiales de marketing de NetApp podrían utilizar el término UTA2 para consultar los puertos y adaptadores de CNA. Sin embargo, la CLI utiliza el término CNA.

Puede utilizar el `ucadmin show` comando para verificar la configuración actual del puerto:

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
Los puertos UTA/UTA2 se pueden configurar en modo FC nativo o modo UTA/UTA2. El modo FC admite el iniciador FC y el destino FC; el modo UTA/UTA2 permite que el tráfico FCoE y NIC simultáneas comparta la misma interfaz SFP+ 10 GbE y sea compatible con destinos FC.

Se pueden encontrar los puertos UTA/UTA2 en un adaptador o en la controladora, y tienen las siguientes configuraciones, pero debe comprobar la configuración de los puertos UTA/UTA2 en el nodo 3 y cambiarlo, si es necesario:

* LAS tarjetas UTA/UTA2 solicitadas cuando se solicita la controladora se configuran antes del envío para tener la personalidad que solicita.
* Las tarjetas UTA/UTA2 solicitadas por separado desde la controladora se envían con la personalidad de destino FC predeterminada.
* Los puertos UTA/UTA2 integrados en las nuevas controladoras se configuran antes del envío para que tengan la personalidad que solicita.
+

NOTE: Ingrese los comandos de esta sección en el indicador del clúster, a menos que se le indique que ingrese al modo de mantenimiento.



.Pasos
. Verifique la configuración actual del puerto ingresando el siguiente comando en el nodo3:
+
`system node hardware unified-connect show`

+
El sistema muestra un resultado similar al siguiente ejemplo:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[step2]]Si el módulo SFP+ actual no coincide con el uso deseado, sustitúyalo por el módulo SFP+ correcto.
+
Póngase en contacto con su representante de NetApp para obtener el módulo SFP+ correcto.

. [[paso3]]examine la salida del `system node hardware unified-connect show` o. `ucadmin show` Comando para determinar si los puertos UTA/UTA2 tienen la personalidad que desea.
. [[step4]]realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si los puertos UTA/UTA2... | Realice lo siguiente... 


| No tenga la personalidad que usted desea | Vaya a. <<man_check_3_step5,Paso 5>>. 


| Tenga la personalidad que usted desea | Omita los pasos 5 a 13 y vaya a<<man_check_3_step14,Paso 14>> . 
|===
. [[man_check_3_step5]]Si el sistema tiene discos de almacenamiento y está ejecutando Clustered Data ONTAP 8.3, inicie el nodo 3 e ingrese al modo de mantenimiento:
+
`boot_ontap maint`

. Compruebe la configuración:
+
`ucadmin show`

. Realice una de las siguientes acciones:
+
[cols="35,65"]
|===
| Si va a configurar... | Realice lo siguiente... 


| Puertos en una tarjeta UTA/UTA2 | Vaya a <<man_check_3_step8,Paso 8>>. 


| Puertos UTA/UTA2 integrados | Omite el paso 8 y ve a<<man_check_3_step9,Paso 9>> . 
|===
. [[man_check_3_step8]]Si el adaptador está en modo iniciador y el puerto UTA/UTA2 está en línea, desconecte el puerto UTA/UTA2:
+
`storage disable adapter _adapter_name_`

+
Los adaptadores del modo de destino se desconectan automáticamente en modo de mantenimiento.

. [[man_check_3_step9]]Si la configuración actual no coincide con el uso deseado, cambie la configuración según sea necesario:
+
`ucadmin modify -m fc|cna -t initiator|target _adapter_name_`

+
** `-m` es el modo de personalidad, `fc` o. `cna`.
** `-t` Es el tipo FC4, `target` o. `initiator`.
+

NOTE: Debe utilizar el iniciador FC para unidades de cinta y configuraciones de MetroCluster .  Debe utilizar el destino FC para los clientes SAN.



. Detenga el sistema:
+
`halt`

+
El sistema se detiene en el aviso del entorno de arranque.

. Introduzca el siguiente comando:
+
`boot_ontap`

. [[step11]]Compruebe los ajustes:
+
`system node hardware unified-connect show`

+
La salida de los siguientes ejemplos muestra que el tipo FC4 del adaptador "1b" está cambiando a. `initiator` y que el modo de los adaptadores "2a" y "2b" está cambiando a. `cna`:

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[paso 12a]]Coloque todos los puertos de destino en línea ingresando el siguiente comando, una vez para cada puerto:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -state up`

. [[man_check_3_step14]]Conecte el puerto.

