---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: Si es necesario, configure el nuevo módulo de controladoras para NVE o NAE durante una actualización manual ARL en controladoras que ejecuten ONTAP 9.8 o una versión posterior. 
---
= Configure el cifrado de volumen de NetApp o el cifrado agregante en el nuevo módulo del controlador
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si la controladora reemplazada o el partner de alta disponibilidad (ha) de la nueva controladora utilizan el cifrado de volúmenes de NetApp (NVE) o el cifrado de agregados de NetApp (NAE), debe configurar el nuevo módulo de controladoras para NVE o NAE.

.Acerca de esta tarea
Este procedimiento incluye los pasos que se realizan en el nuevo módulo del controlador. Debe introducir el comando en el nodo correcto.

.Pasos
. Compruebe que los servidores de gestión de claves aún estén disponibles, su estado y la información de la clave de autenticación:
+
`security key-manager key query -node node`

. Añada los servidores de gestión de claves que se enumeran en el paso anterior a la lista del servidor de gestión de claves de la nueva controladora:
+
.. Añada el servidor de gestión de claves mediante el siguiente comando:
+
`security key-manager -add _key_management_server_ip_address_`

.. Repita el paso anterior para cada servidor de gestión de claves enumerado. Puede vincular hasta cuatro servidores de gestión de claves.
.. Compruebe que los servidores de gestión de claves se han añadido correctamente mediante el siguiente comando:
+
`security key-manager show`



. En el nuevo módulo de controlador, ejecute el asistente de configuración de gestión de claves para configurar e instalar los servidores de gestión de claves.
+
Debe instalar los mismos servidores de gestión de claves que se instalan en el módulo de controladora existente.

+
.. Inicie el asistente de configuración del servidor de gestión de claves en el nuevo nodo mediante el siguiente comando:
+
`security key-manager setup -node _new_controller_name_`

.. Complete los pasos del asistente para configurar los servidores de gestión de claves.


. Restaure las claves de autenticación de todos los servidores de gestión de claves vinculados al nuevo nodo:
+
[cols="35,65"]
|===
| Durante... | Se usa este comando... 


| Gestor de claves externas | `security key-manager external restore`Este comando necesita la clave de acceso de OKM 


| Gestión de claves incorporada (OKM) | `security key-manager onboard sync` 
|===
+
Para obtener más información, vea el artículo de la base de conocimientos https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["Cómo restaurar la configuración del servidor del administrador de claves externo desde el menú de arranque de ONTAP"^].



.Después de terminar
Compruebe si alguno de los volúmenes se desconectó debido a que no existían claves de autenticación o porque no se pudo acceder a los servidores de gestión de claves externos. Vuelva a poner en línea esos volúmenes mediante el uso de  `volume online` dominio.
