---
sidebar: sidebar 
permalink: upgrade-arl/index.html 
keywords: aggregate, relocation, moving, manual, upgrade, relocate, hardware 
summary: Use la reubicación de agregados para actualizar el hardware de la controladora 
---
= Comience aquí: Elija el procedimiento de actualización de ARL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede actualizar el hardware de la controladora sin interrupciones mediante la reubicación de agregados (ARL). Para conocer otros métodos de actualización del hardware del controlador, consulte link:../upgrade/upgrade-decide-to-use-this-guide.html["Actualice trasladando volúmenes o almacenamiento"].

El uso de ARL permite actualizar de forma no disruptiva el hardware de la controladora en un par de nodos que ejecutan ONTAP mediante la migración de agregados no raíz de los nodos originales a los nodos nuevos del mismo clúster. Durante la actualización, se puede acceder a los datos alojados en los nodos que se están actualizando.

ARL aprovecha la configuración de alta disponibilidad para ofrecerle la posibilidad de mover la propiedad de agregados no raíz de un nodo a otro si comparten almacenamiento dentro del mismo clúster.

Existen varios métodos ARL para actualizar el hardware del controlador. Para seleccionar el procedimiento adecuado, revise la siguiente información sobre los sistemas y las versiones de ONTAP compatibles con cada opción de actualización de ARL.



== Utilice comandos para reemplazar la controladora del sistema con ONTAP 9.15,1 o posterior

Si el escenario de actualización aparece en la siguiente matriz de sistemas compatibles, vaya a link:../upgrade-arl-auto-app-9151/index.html["Utilice comandos para sustituir la controladora del sistema para actualizar el hardware de la controladora introducido en ONTAP 9.15.1 y versiones posteriores"] para iniciar el procedimiento de actualización.

.Muestra los sistemas admitidos
[%collapsible]
====
|===
| Controladora existente | Controladora de reemplazo | Compatible empezando con ONTAP... 


| AFF A400 | AFF A50 | 9.16.1 


| AFF A300 | AFF A50 | 9.16.1 


| AFF A220 y AFF A150 | AFF A20 | 9.16.1 


| FAS8200, FAS8300, FAS8700 Y FAS9000 | FAS70, FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300, AFF A400, AFF A700 | AFF A70, AFF A90, AFF A1K | 9.15.1 


| AFF A900 | AFF A90 y AFF A1K | 9.15.1 
|===
====


== Actualice los modelos de controladoras en el mismo chasis

Si el escenario de actualización aparece en la siguiente matriz de sistemas compatibles, vaya a link:../upgrade-arl-auto-affa900/index.html["Utilice los comandos para sustituir la controladora del sistema para actualizar los modelos de controladora en el mismo chasis"] para iniciar el procedimiento de actualización.

.Muestra los sistemas admitidos
[%collapsible]
====
[cols="20,20,40"]
|===
| Sistema antiguo | Sistema de sustitución | Versiones de ONTAP compatibles 


| AFF C250 | AFF C30 y AFF C60 | 9.16.1 y posterior 


| AFF A250 | AFF A50 y AFF A30 | 9.16.1 y posterior 


| AFF C800 | AFF C80 | 9.16.1 y posterior 


| AFF A800 | AFF A70 o AFF A90 | 9.15.1 y posterior 


| AFF A220 configurado como cabina All SAN (ASA) | ASA A150 | 9.13.1P1 y posterior 


| AFF A220 | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 y posteriores 


| AFF A200 | AFF A150  a| 
9.10.1P15, 9.11.1P11 y posterior

*Nota*: AFF A200 no admite versiones de ONTAP posteriores a 9.11.1.



| C190 de AFF | AFF A150 | 9.10.1P15, 9.11.1P11, 9.12.1P5 y posteriores 


| FAS2620 | FAS2820  a| 
9.11.1P7 o versiones de revisión posteriores (FAS2620)

*Nota*: FAS2620 no admite versiones de ONTAP posteriores a 9.11.1.

9.13.1 y posterior (FAS2820)



| FAS2720 | FAS2820 | 9.13.1 y posterior 


| AFF A700 configurado como ASA | ASA A900 | 9.13.1P1 y posterior 


| AFF A700 | AFF A900 | 9.10.1P10, 9.11.1P6 y posterior 


| FAS9000 | FAS9500 | 9.10.1P10, 9.11.1P6 y posterior 
|===
====


== Utilice comandos para reemplazar la controladora del sistema con ONTAP 9.8 o posterior

Si el escenario de actualización aparece en la siguiente matriz de sistemas compatibles, vaya a link:../upgrade-arl-auto-app/index.html["Utilice comandos para sustituir la controladora del sistema para actualizar el hardware de la controladora que ejecute ONTAP 9.8 o una versión posterior"] para iniciar el procedimiento de actualización.

.Muestra los sistemas admitidos
[%collapsible]
====
|===
| La controladora anterior | Controladora de reemplazo 


| FAS8020, FAS8040, FAS8060 Y FAS8080 | FAS8200, FAS8300, FAS8700 Y FAS9000 


| FAS8060, FAS8080 | FAS9500 


| AFF8020, AFF8040, AFF8060 Y AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800 


| AFF8060, AFF8080 | AFF A900 


| FAS8200 | FAS8300 DE FEBRERO DE FAS8700, FAS9000 FAS9500 


| FAS8300, FAS8700 Y FAS9000 | FAS9500 


| AFF A300 | AFF A400, AFF A700, AFF A800, AFF A900 


| AFF A320 | AFF A400 


| AFF A400, AFF A700 | AFF A900 
|===
====


== Utilice los comandos para reemplazar la controladora del sistema con ONTAP 9.5 a 9,7

Si el escenario de actualización aparece en la siguiente matriz de sistemas compatibles, vaya a link:../upgrade-arl-auto/index.html["Utilice los comandos para sustituir la controladora del sistema para actualizar el hardware de la controladora que ejecuta ONTAP 9.5 a 9.7"] para iniciar el procedimiento de actualización.

.Muestra los sistemas admitidos
[%collapsible]
====
[cols="50,50"]
|===
| La controladora anterior | Controladora de reemplazo 


| FAS8020, FAS8040, FAS8060 Y FAS8080 | FAS8200, FAS8300, FAS8700 Y FAS9000 


| AFF8020, AFF8040, AFF8060 Y AFF8080 | AFF A300, AFF A400, AFF A700, AFF A800 


| FAS8200 | FAS8700, FAS9000, FAS8300 


| AFF A300 | AFF A700, AFF A800, AFF A400 
|===
====


== Utilice comandos ARL manuales

Si el escenario de actualización no es compatible con comandos del sistema, puede realizar una actualización de ARL mediante comandos manuales.

Elija el procedimiento para su versión de ONTAP para iniciar la actualización:

* link:../upgrade-arl-manual-app/index.html["Actualizar manualmente el hardware de la controladora que ejecute ONTAP 9.8 o una versión posterior"]
* link:../upgrade-arl-manual/index.html["Actualizar manualmente el hardware de la controladora que ejecute ONTAP 9.7 o una versión anterior"]

